### ISSUE TITLE
React first page

### ISSUE THREAD

**Issue by scholar6admin** [Scholar-6/brillder#10]
Add some styling and make sure the button 'create' goes to Pro forma page.

**Comment by scholar6admin** [comment]
![](https://user-images.githubusercontent.com/58778078/72424471-f9d2c180-377d-11ea-94ee-e90e92932886.png)

**Comment by ivanromakh** [comment]
@scholar6admin View for Phone make button 90% of width with big texts.
![image](https://user-images.githubusercontent.com/18567511/72890997-e2ff1280-3d1b-11ea-88ca-8bde7ae81df4.png)
View for pc. Buttons with 240px. They look big.
![image](https://user-images.githubusercontent.com/18567511/72891389-cd3e1d00-3d1c-11ea-9824-15f35098f3d3.png)
Pull request: https://github.com/Scholar-6/brillder/pull/17
