### ISSUE TITLE
Image Component

### ISSUE THREAD

**Issue by scholar6admin** [Scholar-6/brillder#100]
I would like drag and drop functionality similar to Wordpress etc.

**Comment by ivanromakh** [comment]
@SashaScholar6 I find one. Need design for dropzone
![image](https://user-images.githubusercontent.com/18567511/75340680-94eda980-589b-11ea-8f13-018a0002c1ac.png)

there are some examples
https://react-dropzone.js.org/

**Comment by ivanromakh** [comment]
@SashaScholar6 Also design for preview now it shows the name of file in the bottom.
![image](https://user-images.githubusercontent.com/18567511/75340779-ca929280-589b-11ea-84d7-ef73ccfe5890.png)
