### ISSUE TITLE
Remove pre-login page

### ISSUE THREAD

**Issue by SashaScholar6** [Scholar-6/brillder#1016]
Branch NewLogin

- [x] replace with this:

<img width="958" alt="Screenshot 2020-06-30 at 13 38 14" src="https://user-images.githubusercontent.com/59654112/86121793-f4242a80-bad6-11ea-8212-a3b8d97fc257.png">

**Comment by scholar6admin** [comment]
@ivanromakh this is now a critical blocker because it is blocking @farman9849 from completing mobile work. Please prioritise this tomorrow and let Farman know as soon as it is on Dev

**Comment by ivanromakh** [comment]
@scholar6admin ok
