### ISSUE TITLE
Add checkbox on profile to make name private and not searchable

### ISSUE THREAD

**Issue by SashaScholar6** [Scholar-6/brillder#1018]
<img width="776" alt="Screenshot 2020-07-02 at 10 37 57" src="https://user-images.githubusercontent.com/59654112/86336500-3a50c980-bc50-11ea-9bac-3818c2f02330.png">

- [x] Change text to 'Keep me secret: I don't want to be searchable'

- [x] Font should be Brandon Reg Dark Blue

- [x] Checkbox should be below Name field

**Comment by ivanromakh** [comment]
@aromakh for this task you need update searching and add new field to user.
