### ISSUE TITLE
Delete button user mgmt

### ISSUE THREAD

**Issue by SashaScholar6** [Scholar-6/brillder#1040]
<img width="105" alt="Screenshot 2020-07-01 at 12 23 56" src="https://user-images.githubusercontent.com/59654112/86233571-e5507d00-bb95-11ea-8930-d1b13953f746.png">

- [x] need before 7 July

- [x] dark blue feather icon trash-2 https://feathericons.com/?query=trash

- [x] Popup: 'Permanently delete this user?' - Yes, delete / No, keep

**Comment by aromakh** [comment]
@SashaScholar6  @lindsaymacvean 
What does delete means?

Should we remove all the related info of the user including bricks/questions?

Or just mark user as deleted, and do not should him in user list, and do not allow to login etc?

**Comment by SashaScholar6** [comment]
No, not associated bricks - only not in user list and no login.  It is unlikely we will delete any user with content, but deletions should be separate.  This is mostly to make sure user management page is clean and representative of serious users

**Comment by aromakh** [comment]
@SashaScholar6  got it.
Thanks!

**Comment by aromakh** [comment]
@ivanromakh  
Here is api:
http://swagger.scholar6.org/docs/#!/user/userDeleteUserIdDELETE

**Comment by aromakh** [comment]
@ivanromakh 
migration is fixed
