### ISSUE TITLE
Show Back to Work bricks in three columns in 'All Projects' view

### ISSUE THREAD

**Issue by SashaScholar6** [Scholar-6/brillder#1042]
- [x] A bit like Github, from left to right: Draft (Red), Review (Amber), Published (Green)

<img width="1461" alt="Screenshot 2020-07-01 at 12 36 31" src="https://user-images.githubusercontent.com/59654112/86234847-d2d74300-bb97-11ea-81f3-6e664a99c2fe.png">

**Comment by ivanromakh** [comment]
@SashaScholar6

**Comment by ivanromakh** [comment]
@SashaScholar6 I need more desciption about this.what is there is only draft bricks should I show always one column?

**Comment by ivanromakh** [comment]
@SashaScholar6 What about build in process. Should I remove it from  that or we will implement it later?
![image](https://user-images.githubusercontent.com/18567511/87047719-85944a80-c203-11ea-88c6-b362f5b7d737.png)

**Comment by SashaScholar6** [comment]
We can remove

**Comment by SashaScholar6** [comment]
For back to work home: red draft on left, review in the middle, published on the right
