### ISSUE TITLE
Implement publisher subscriber pattern for brick autosave.

### ISSUE THREAD

**Issue by aromakh** [Scholar-6/brillder#1074]
Currently we do PUT every time, when model is changed. I cause issue as when new brick is created there are few similar PUT call in the same moment.

There is no need to create multiple PUT with same info.

Create some AutoSave service, which will be looking to "Saved" property, and send PUT only when Saved === false.

"Saved" should be set to true, when PUT is sent.

**Comment by ivanromakh** [comment]
@lindsaymacvean I setup delay in .env.production REACT_APP_BUILD_AUTO_SAVE_DELAY=500. And also hardcoded 500 miliseconds if there is no env varialbe
