### ISSUE TITLE
Proforma Create

### ISSUE THREAD

**Issue by scholar6admin** [Scholar-6/brillder#11]
Add 'create' button and make that go to the first version of the brick builder page.

**Comment by scholar6admin** [comment]
This looks good. Just add a save/update button that progresses to the brick builder page.

![](https://user-images.githubusercontent.com/18567511/72629794-b03ece00-3959-11ea-8052-d258c1bcd027.png)

**Comment by ivanromakh** [comment]
Final Style
Phone:
![image](https://user-images.githubusercontent.com/18567511/72898462-cd461900-3d2c-11ea-8e3e-68deb40c8d37.png)
Tablet
![image](https://user-images.githubusercontent.com/18567511/72898529-f6ff4000-3d2c-11ea-9bb6-cd2740ce1c3e.png)

All fields are required.
Maximym length for input boxes 30.
And 140 and 150 letters for text boxes.

**Comment by ivanromakh** [comment]
https://github.com/Scholar-6/brillder/pull/18
