### ISSUE TITLE
Moving tabs in build does not save changes in play preview

### ISSUE THREAD

**Issue by SashaScholar6** [Scholar-6/brillder#1119]
eg. if I decide want QP3 to be QP1, I expect that the change I have made will be carried forward in the play preview.

**Comment by ivanromakh** [comment]
@aromakh I added login in front but it not saving in backend. Order of questions is not switching. Order in question in response is good. but after refreshing page backend give me old order. always the same.
![image](https://user-images.githubusercontent.com/18567511/86612597-10353980-bfb9-11ea-8c73-e64346a4eda7.png)

**Comment by ivanromakh** [comment]
@aromakh seems like order now is by id no matter how I tried  to switch questions.
