### ISSUE TITLE
Add clear and clear all to notifications

### ISSUE THREAD

**Issue by SashaScholar6** [Scholar-6/brillder#1133]
- [ ] removes items from dropdown, no need to store for now or notifications centre needed

<img width="1437" alt="Screenshot 2020-07-06 at 16 44 40" src="https://user-images.githubusercontent.com/59654112/86606468-5635d180-bfa8-11ea-8317-f8513ebdb6c7.png">

- [ ] when this and #1132 done, pass task on to Farman to style
 slide 26
https://xd.adobe.com/view/b926b24c-3e0b-4238-6035-ef34d9c333c7-cf17/screen/c8894899-453d-4faa-ab67-389d29916f11/Back-To-Work-Default-V2

**Comment by william-gooch** [comment]
Are we still including this in this build? The other day you said to remove it for now to prevent people from accidentally removing important notifications.
