### ISSUE TITLE
Mobile: Intro - Prep Expanded

### ISSUE THREAD

**Issue by SashaScholar6** [Scholar-6/brillder#1147]
https://xd.adobe.com/view/1e39452a-5837-49db-6dfd-dfd6cfcd93d9-6808/
<img width="372" alt="Screenshot 2020-07-07 at 15 59 55" src="https://user-images.githubusercontent.com/59654112/86793358-aaee5080-c06b-11ea-9a6b-abbc1896a8c8.png">

**Comment by ivanromakh** [comment]
@farmanahmed2007 I  added class to header when prep is expanded
