### ISSUE TITLE
Change answer component panel: Add Click + Correct button and scrollbar on right hand side (see note for details)

### ISSUE THREAD

**Issue by SashaScholar6** [Scholar-6/brillder#118]
- Click + Correct button should be the same size as short answer
- All buttons should be 10% narrower (keeping gaps between each button as they are) to accommodate scrollbar
- Scrollbar should be thin, short and brick red

**Comment by ivanromakh** [comment]
@SashaScholar6 What do you mean by 'brick red' in 'Scrollbar should be thin, short and brick red'
