### ISSUE TITLE
Ensure there is more spacing (not touching edges) and that question type dropdown is centred.  This is an issue for the longer options

### ISSUE THREAD

**Issue by SashaScholar6** [Scholar-6/brillder#119]
<img width="560" alt="Screenshot 2020-02-27 at 16 12 54" src="https://user-images.githubusercontent.com/59654112/75462366-10bf2300-597c-11ea-898a-16bd835101c8.png">

**Comment by ivanromakh** [comment]
@SashaScholar6 done
