### ISSUE TITLE
Published bricks are editable

### ISSUE THREAD

**Issue by ivanromakh** [Scholar-6/brillder#1228]
Not sure if this is still happening?

When someone published brick and other guy will add something. Other guy which will try to play this brick most likely will have this error. (If published brick is not valid what should we do?)
![image](https://user-images.githubusercontent.com/18567511/87676663-8daf3580-c781-11ea-8bb6-bb8db8969c70.png)

**Comment by scholar6admin** [comment]
@ivanromakh is this still happening or can this be closed?

**Comment by ivanromakh** [comment]
@scholar6admin shouldn`t happen.

**Comment by scholar6admin** [comment]
Great thanks.
