### ISSUE TITLE
Different types of users have different access: builders, editors, administrators

### ISSUE THREAD

**Issue by scholar6admin** [Scholar-6/brillder#124]
![image](https://user-images.githubusercontent.com/58778078/75670195-38f89b80-5c74-11ea-955f-13b6910a8c7a.png)

**Comment by aromakh** [comment]
@ivanromakh 
I added new login method **/auth/login/:userType**, it is the same as previous one, but with additional userType param which is 1,2,3,4 enum value.

Also, you can do:
get "/user/current" to get current logged in user object.
