### ISSUE TITLE
Mobile: Intro page: Unexpanded grey play icon should not pulse and should not move onto next page

### ISSUE THREAD

**Issue by SashaScholar6** [Scholar-6/brillder#1253]
<img width="322" alt="Screenshot 2020-07-22 at 13 02 32" src="https://user-images.githubusercontent.com/59654112/88169018-9e492b00-cc1b-11ea-935e-a76f8fe6b7ee.png">

**Comment by ivanromakh** [comment]
dublicated close https://github.com/Scholar-6/brillder/issues/1248
