### ISSUE TITLE
View  Profile tweaks

### ISSUE THREAD

**Issue by SashaScholar6** [Scholar-6/brillder#1274]
<img width="1058" alt="Screenshot 2020-07-23 at 11 15 37" src="https://user-images.githubusercontent.com/59654112/88270738-66eb8480-ccd6-11ea-9f79-608fe00163ef.png">

- [x] top of Name Surname boxes should be level with top of roles box

- [x] Reduce height of Name Surname, email, password and Subjects boxes by 20%

- [x] Reduce gap between Name Surname boxes and email so that 'keep me secret..' tickbox is equidistant from bottom of name surname to top of email box

- [x] once above done, move up subjects and bio panels

**Comment by ivanromakh** [comment]
@farmanahmed2007  almost need to make it in the same line. Make padding in Name Surname width based vw.
![image](https://user-images.githubusercontent.com/18567511/88525103-db8a3000-d002-11ea-9488-e2c6343028c3.png)
