### ISSUE TITLE
Ability to upload and save picture to Profile Page

### ISSUE THREAD

**Issue by SashaScholar6** [Scholar-6/brillder#1353]
<img width="250" alt="Screenshot 2020-07-30 at 11 35 24" src="https://user-images.githubusercontent.com/59654112/88907385-d9211380-d258-11ea-9d87-dd518771a9dc.png">

**Comment by ivanromakh** [comment]
Done images are uploading but data isn`t saving in backend waiting for: https://github.com/Scholar-6/brillder-backend/issues/190
![image](https://user-images.githubusercontent.com/18567511/88944551-8ade3580-d295-11ea-86b1-f325665f4d4b.png)
