### ISSUE TITLE
As admin, can't seem to save changes to another user's subjects

### ISSUE THREAD

**Issue by SashaScholar6** [Scholar-6/brillder#1363]
<img width="713" alt="Screenshot 2020-07-31 at 12 34 00" src="https://user-images.githubusercontent.com/59654112/89027123-3d5fd800-d32a-11ea-9bd3-af1880111f04.png">

**Comment by ivanromakh** [comment]
@aromakh seems problem in backend. Subjects are not saving during this request
![image](https://user-images.githubusercontent.com/18567511/89280374-377f3500-d651-11ea-874d-5c10cb78c5c0.png)

**Comment by ivanromakh** [comment]
@aromakh ops. they are saving.
