### ISSUE TITLE
Update Privacy Policy text

### ISSUE THREAD

**Issue by SashaScholar6** [Scholar-6/brillder#1393]
In order to submit this to Google we need to provide a url link that opens the privacy policy. 

I am thinking that maybe a #fragment at the end of the url that triggers the policy to popup?

![image](https://user-images.githubusercontent.com/58778078/89458853-a5198700-d75f-11ea-8497-bb286129265f.png)

https://docs.google.com/document/d/1ceeWL3wDuU1hfoxgy3Mykj6nT4_iEarplRfKkHtkYPM/edit#heading=h.ia2sg3lxcjn6

- [x] replace existing with text in google doc

**Comment by ivanromakh** [comment]
@scholar6admin updated  https://dev-brillder.scholar6.org/login/privacy-policy
