### ISSUE TITLE
update 'coming soon' popup

### ISSUE THREAD

**Issue by SashaScholar6** [Scholar-6/brillder#1407]
<img width="882" alt="Screenshot 2020-08-05 at 21 22 40" src="https://user-images.githubusercontent.com/59654112/89455351-78b33a00-d762-11ea-8993-9d0085f58e52.png">

(line 1) Coming soon!  If you have any suggestions for this feature,
(line 2) send us a message via the 'Help' ('?') button in the bottom left of this screen

- [x] can be three lines if necessary as popup should be a bit narrower

- [x] annotate

- [x] f (x)

**Comment by ivanromakh** [comment]
![image](https://user-images.githubusercontent.com/18567511/89515182-74793200-d7df-11ea-89ed-7e4fa808dfaa.png)
