### ISSUE TITLE
Move all General Subject bricks out of Core in Back To Work

### ISSUE THREAD

**Issue by SashaScholar6** [Scholar-6/brillder#1413]
<img width="744" alt="Screenshot 2020-08-06 at 11 23 48" src="https://user-images.githubusercontent.com/59654112/89515487-73dc9d80-d7d7-11ea-9d4f-9c5d3b921ac7.png">

Don't want to see student bricks in core in Back to Work as an Admin

- [x] can be a rule for all 'General' Subject bricks

**Comment by ivanromakh** [comment]
@SashaScholar6  if I do so admins will not be able to see them.

**Comment by ivanromakh** [comment]
@SashaScholar6 should I create third button for General subject bricks
