### ISSUE TITLE
Suggestion sidebar width should be fixed relative to tab window  

### ISSUE THREAD

**Issue by SashaScholar6** [Scholar-6/brillder#1414]
<img width="868" alt="Screenshot 2020-08-06 at 11 38 32" src="https://user-images.githubusercontent.com/59654112/89517093-8952c700-d7d9-11ea-8be3-6a60e00ed6c4.png">

- [x] in the unlikely case that a word takes up more than one line, break with a hyphen ('-')

**Comment by ivanromakh** [comment]
@SashaScholar6 it will be hard to add (-) to words

**Comment by ivanromakh** [comment]
library for hyphens https://www.npmjs.com/package/react-hyphen
