### ISSUE TITLE
Make notifications clickable

### ISSUE THREAD

**Issue by SashaScholar6** [Scholar-6/brillder#1441]
![Screenshot 2020-08-10 at 12 47 01](https://user-images.githubusercontent.com/59654112/89779602-ace27e00-db07-11ea-86db-85f20c9b8521.png)

- [x] if brick published, user taken to 'View All'

- [x] if brick submitted for review or assigned a brick to edit, user taken to Back to Work build tab

- [x] If new suggestions on brick, user taken to Question panel where these were made, with sidebar expanded

**Comment by ivanromakh** [comment]
third point require changes in routing. will take some time

**Comment by william-gooch** [comment]
For the time being it's at least possible to route to the correct brick - there is a brick ID stored on the database so that should be possible.

**Comment by ivanromakh** [comment]
@william-gooch @SashaScholar6  now comments lead to investigation build page.
