### ISSUE TITLE
Add Play tab to Back to Work

### ISSUE THREAD

**Issue by SashaScholar6** [Scholar-6/brillder#1444]
<img width="1440" alt="Screenshot 2020-08-10 at 11 28 31" src="https://user-images.githubusercontent.com/59654112/89784158-15cdf400-db10-11ea-9bbd-5986b48a36d8.png">

https://xd.adobe.com/view/38f73641-4f9c-461f-a83b-62fca48ee95c-6da4/

- [ ] Assigned bricks show here, first in red, then amber when attempted

**Comment by ivanromakh** [comment]
@william-gooch what is the name of api call?

**Comment by william-gooch** [comment]
GET /bricks/assigned
