### ISSUE TITLE
Fix difference in proportions of zendesk widget and 'Trouble scrolling...' text and arrows on laptop (2560x1600) and monitor (2K)

### ISSUE THREAD

**Issue by SashaScholar6** [Scholar-6/brillder#1457]
<img width="957" alt="Screenshot 2020-08-12 at 14 46 09" src="https://user-images.githubusercontent.com/59654112/90023007-177fef00-dcab-11ea-96cf-410c351d780c.png">

laptop view

![Screenshot 2020-08-12 at 14 46 24](https://user-images.githubusercontent.com/59654112/90023010-18188580-dcab-11ea-99ab-01bd7aac3fdc.png)

monitor view

- [x] text and arrows should be centred and same proportions in both

- [x] text should be narrower than work area width, centred as above and same across different resolutions/fixed relative to work area and tab window

- [x] zendesk size

**Comment by ivanromakh** [comment]
as I know iframe is imposible to style it with css I will style it with code in zendesk init function. for phones it should be the same size as it is I think.
