### ISSUE TITLE
Production BUGS: If I click to delete stephen arscott, I get taken to my own profile page; if I click to delete jonathan arscott gmail account, I get logout popup which actually logs me out if clicked

### ISSUE THREAD

**Issue by SashaScholar6** [Scholar-6/brillder#1458]
![Screenshot 2020-08-12 at 14 55 49](https://user-images.githubusercontent.com/59654112/90023933-3632b580-dcac-11ea-8eb0-60a393833daf.png)

- [x] I should get 'Permanently delete this user?' popup in both (indeed all) cases

- [x] DON'T delete either

**Comment by ivanromakh** [comment]
@SashaScholar6  I think problem is with menu dropdown which is clickable but invinsible.
![image](https://user-images.githubusercontent.com/18567511/90029462-91bc6d80-dcc3-11ea-977e-0b552ed96a72.png)

**Comment by ivanromakh** [comment]
Fixed by unmounting menu.
