### ISSUE TITLE
Dynamic averages for submitted bricks by Students in Teach tab

### ISSUE THREAD

**Issue by SashaScholar6** [Scholar-6/brillder#1483]
![Screenshot 2020-08-17 at 09 51 43](https://user-images.githubusercontent.com/59654112/90378107-dacc4300-e070-11ea-979a-57e13bde46c8.png)

**Comment by ivanromakh** [comment]
@william-gooch I need dynamic avarages for each assigned brick in GET: /classrooms
Move stats from class to each assignment
![image](https://user-images.githubusercontent.com/18567511/92093032-826ca380-eddb-11ea-80c4-48935bdc555a.png)

![image](https://user-images.githubusercontent.com/18567511/92092931-649f3e80-eddb-11ea-9416-3b67d209ebd8.png)
