### ISSUE TITLE
Set Breakpoints

### ISSUE THREAD

**Issue by scholar6admin** [Scholar-6/brillder#15]
@ivanromakh
Can we set the break points to
max-width: 599px
min-width: 600px
min-width: 900px
min-width: 1200px
min-width: 1800px

As per this article.
https://www.freecodecamp.org/news/the-100-correct-way-to-do-css-breakpoints-88d6a5ba1862/

**Comment by ivanromakh** [comment]
@scholar6admin pull request has breakpoints for second page (Proforma).
https://github.com/Scholar-6/brillder/pull/16

**Comment by ivanromakh** [comment]
Proforma breakpoints https://github.com/Scholar-6/brillder/pull/16/commits/e09f0f30614c47a69ad207a3176c210d521692bc

**Comment by ivanromakh** [comment]
Checked breakpoints on Phone and PC.

**Comment by ivanromakh** [comment]
First page breaks only  for Phone and pc. https://github.com/Scholar-6/brillder/pull/17
