### ISSUE TITLE
Add next button in play mobile view for last question of investigation and review

### ISSUE THREAD

**Issue by scholar6admin** [Scholar-6/brillder#1512]
![image](https://user-images.githubusercontent.com/58778078/91026833-378ca800-e5f3-11ea-9705-c7aa951d5d0b.png)

- [x] when clicked, popup: 'Submit answers?', Options: 'Yes'/'Not yet!'

**Comment by ivanromakh** [comment]
@scholar6admin sasha asked to remove it now you can swap it

**Comment by ivanromakh** [comment]
@scholar6admin https://github.com/Scholar-6/brillder/issues/1402
