### ISSUE TITLE
Mobile Intro page: remove 'Expand to start timer...' text, make chevron same size as the one next to brief

### ISSUE THREAD

**Issue by SashaScholar6** [Scholar-6/brillder#1516]
- [x] remove small text next to chevron

- [x] increas chevron size to match brief chevron above

**Comment by ivanromakh** [comment]
@SashaScholar6 As I see chevron size increasing only for mobile. Am I right?

**Comment by ivanromakh** [comment]
@SashaScholar6 Should I remove text for mobile and desktop or only for mobile?

**Comment by SashaScholar6** [comment]
yes only mobile
