### ISSUE TITLE
Change all reds to #C43C30

### ISSUE THREAD

**Issue by SashaScholar6** [Scholar-6/brillder#153]
<img width="300" alt="Screenshot 2020-03-19 at 12 29 00" src="https://user-images.githubusercontent.com/59654112/77063472-0b368500-69de-11ea-9494-f6be70256ae4.png">

**Comment by ivanromakh** [comment]
@SashaScholar6 Its image. I can`t change it. Need brighter one.

**Comment by ivanromakh** [comment]
it has color #A74B3E
