### ISSUE TITLE
BUG: create new user bugs

### ISSUE THREAD

**Issue by SashaScholar6** [Scholar-6/brillder#1533]
- [x] When i create new new user and fill out fields, general subject is not assigned

- [x] When fields are filled and I click green save button first time, profile saved popup should appear

**Comment by ivanromakh** [comment]
we don`t have backend for this created task for this https://github.com/Scholar-6/brillder-backend/issues/263

**Comment by william-gooch** [comment]
@ivanromakh Backend now ready for this task.
