### ISSUE TITLE
Standard user should not be able to add teacher role to themselves

### ISSUE THREAD

**Issue by SashaScholar6** [Scholar-6/brillder#1534]
Only admin should be able to add AND REMOVE (this is new) roles 

However, everyone can see which roles they have

**Comment by william-gooch** [comment]
This already happens on the server - there just needs to be a mirror for this on the frontend so that it doesn't try to send role information if the user isn't an admin - also if the user tries it should display a meaningful popup rather than 'Sorry, we've ran into a brick wall...'
