### ISSUE TITLE
Student should have Back to Work in dropdown

### ISSUE THREAD

**Issue by SashaScholar6** [Scholar-6/brillder#1538]
![Screenshot 2020-08-26 at 13 05 27](https://user-images.githubusercontent.com/59654112/91301464-e1f3ff00-e79c-11ea-88bc-0c8ad42a8282.png)

**Comment by ivanromakh** [comment]
@SashaScholar6 so every one should be able to see it right?

**Comment by SashaScholar6** [comment]
Yes
