### ISSUE TITLE
Mobile: Synthesis, add timer and 'Aim to spend X minutes on this section'

### ISSUE THREAD

**Issue by SashaScholar6** [Scholar-6/brillder#1542]
- [x] synthesis on mobile page 

![86b76314-23b3-4abc-a290-ffdbe5788520](https://user-images.githubusercontent.com/59654112/93485465-6270d000-f903-11ea-8901-4815f891e68d.jpg)

![b6c2d8e1-9345-49aa-8eb8-ffaab04ee9ce]
(https://user-images.githubusercontent.com/59654112/93485473-643a9380-f903-11ea-87ed-0912c33ab50b.jpg)

- [x] format synthesis to be like prep (font size and weight to reg, subject colour)

**Comment by ivanromakh** [comment]
@SashaScholar6  what is this about. I should show popup? only for mobile in Play?
