### ISSUE TITLE
Synthesis cut off at bottom

### ISSUE THREAD

**Issue by SashaScholar6** [Scholar-6/brillder#1547]
<img width="1196" alt="Screenshot 2020-08-27 at 11 05 13" src="https://user-images.githubusercontent.com/59654112/91427347-ac5f1c80-e855-11ea-83b8-7017724ccd29.png">

<img width="937" alt="Screenshot 2020-08-27 at 17 12 14" src="https://user-images.githubusercontent.com/59654112/91467444-7c7d3c80-e888-11ea-8895-2b868794f0d4.png">

- [x] add padding at the bottom

- [ ] text should be dark blue - is it just because it is an old brick?

**Comment by ivanromakh** [comment]
@SashaScholar6 seems like old. Color should be dark blue there.
