### ISSUE TITLE
Minimised zendesk in sidebar should be bigger and centred (more to the right)

### ISSUE THREAD

**Issue by SashaScholar6** [Scholar-6/brillder#1556]
<img width="246" alt="Screenshot 2020-08-27 at 17 23 48" src="https://user-images.githubusercontent.com/59654112/91468645-2c06de80-e88a-11ea-95dc-cf5d4bab5a9d.png">

**Comment by ivanromakh** [comment]
@SashaScholar6 if I do it here it will become bigger everywhere. In view profile it will overlap text field.
![image](https://user-images.githubusercontent.com/18567511/92002197-40465200-ed48-11ea-81df-755bdb087649.png)
