### ISSUE TITLE
Bug: Popup timeout?

### ISSUE THREAD

**Issue by SashaScholar6** [Scholar-6/brillder#1560]
If I do not click any popup options from Profile page after a little time it exits the page completely.

This should not happen

- [ ] same happens if link popup is not clicked

**Comment by ivanromakh** [comment]
@SashaScholar6  there is no timeouts. In final step page there is no link which can move to introduction page. It can happen only in page refresh. I couldn`t detect it.

**Comment by ivanromakh** [comment]
there could be some error which requires page refresh we need logger to detect it. can`t reproduce
