### ISSUE TITLE
Add Core/Private toggle to Play and move down a bit. (brick should have status if user is invited or not)

### ISSUE THREAD

**Issue by SashaScholar6** [Scholar-6/brillder#1566]
- [x] - add multiple user icon for bricks I have been invited to

**Comment by ivanromakh** [comment]
@william-gooch For this I need new api get call. Similar to GET: https://dev-api.scholar6.org/bricks

**Comment by william-gooch** [comment]
Invitations have been added. They use the /bricks endpoint, and are in the same section as assignments.
An assignment will have a `isInvitation` flag set if it is an invitation rather than an assignment. They both use the same kind of object, though.
@ivanromakh

**Comment by ivanromakh** [comment]
@william-gooch I just invited someone but that person can`t see that brick in back to work page in build or play tab.

**Comment by ivanromakh** [comment]
@william-gooch I forgot. /bricks only for admins. In back-to-work for builders and editors we use /currentUser.

**Comment by william-gooch** [comment]
@ivanromakh I thought we were using /bricks/assigned for Play tab in Back to Work, which is where invited bricks should appear? They already are returned from that request.
/bricks/currentUser is only used for Build, right?

I did realize there's no flag for whether a brick in Build is their own brick or if they are instead the editor, so I did add that.
