### ISSUE TITLE
Add marker for assigned bricks in View All

### ISSUE THREAD

**Issue by william-gooch** [Scholar-6/brillder#1568]
![Screenshot 2020-09-01 at 14 27 21](https://user-images.githubusercontent.com/59654112/91857089-53c9be00-ec5f-11ea-9dd4-6be8e1fd7463.png)

- [X] fileplus icon

<img width="687" alt="Screenshot 2020-09-03 at 11 59 52" src="https://user-images.githubusercontent.com/59654112/92107008-07a48800-eddd-11ea-96b0-543859a3393c.png">

- [x] in left column circle seems a bit decentred to the left?

- [x] also add for hover state

![Uploading Screenshot 2020-09-03 at 11.59.59.png…]()

**Comment by ivanromakh** [comment]
@william-gooch which Api call I should use for this?

**Comment by ivanromakh** [comment]
@william-gooch for view all I use  GET: /bricks/byStatus/4. I only get published bricks.
