### ISSUE TITLE
Fix fonts in build and popup

### ISSUE THREAD

**Issue by SashaScholar6** [Scholar-6/brillder#1581]
- [x] Text default now italic in work area and serif in phone preview?

- [x] serif in popup? All should be brandon reg

<img width="560" alt="Screenshot 2020-09-02 at 10 00 36" src="https://user-images.githubusercontent.com/59654112/91961958-ce4c1980-ed03-11ea-97cc-9f7bb560e975.png">
<img width="1033" alt="Screenshot 2020-09-02 at 10 01 21" src="https://user-images.githubusercontent.com/59654112/91961962-d1470a00-ed03-11ea-94b9-12aa18c85455.png">

<img width="140" alt="Screenshot 2020-09-02 at 10 17 22" src="https://user-images.githubusercontent.com/59654112/91963276-8f1ec800-ed05-11ea-9e0f-1957adde4917.png">

- [x] T icon should be bigger, f(x) should be italic

<img width="352" alt="Screenshot 2020-09-02 at 10 25 21" src="https://user-images.githubusercontent.com/59654112/91964100-a316f980-ed06-11ea-9df7-9b038972ae79.png">

- [x] View all font under brick title should be Reg not Light

**Comment by ivanromakh** [comment]
![image](https://user-images.githubusercontent.com/18567511/92227586-26734f00-eeaf-11ea-8c32-d8484e375b2c.png)
