### ISSUE TITLE
Teach: Remove amber column, all submitted bricks green

### ISSUE THREAD

**Issue by SashaScholar6** [Scholar-6/brillder#1621]
<img width="716" alt="Screenshot 2020-09-07 at 12 28 39" src="https://user-images.githubusercontent.com/59654112/92383410-2d47cf00-f106-11ea-9bc4-a3225c888bd5.png">

- [x] readjust alignment to be like screenshot

**Comment by ivanromakh** [comment]
@SashaScholar6  Should I remove yellow from sidebar too?
![image](https://user-images.githubusercontent.com/18567511/92402772-d1e30480-f138-11ea-9406-b8f14093d091.png)
