### ISSUE TITLE
Update brick fields shown in Teach tab: only title (bold caps), date set as shown

### ISSUE THREAD

**Issue by SashaScholar6** [Scholar-6/brillder#1622]
<img width="716" alt="Screenshot 2020-09-07 at 12 28 39" src="https://user-images.githubusercontent.com/59654112/92383516-63854e80-f106-11ea-99b9-1224247d410c.png">

- [x] large title

- [x] 'date set' (date assigned) formatted as above (we'll do deadline later)

**Comment by ivanromakh** [comment]
@william-gooch can you add new fields to assignment like DeadLine and DateSet
![image](https://user-images.githubusercontent.com/18567511/92395403-f4baec00-f12b-11ea-8d26-959ef7a0cfb6.png)
