### ISSUE TITLE
Teach tab updates

### ISSUE THREAD

**Issue by SashaScholar6** [Scholar-6/brillder#1640]
- [x] display class average score on right (white text in green circle) - is this definitely working? can you send a screenshot?

- [x] remove submitted line in overview area

- [x] if no bricks have been completed, do not show anything in green column (ie. show nothing at all in the whole column, no circle, number of user, icons, nothing - just blank space)

- [x] do not show any date in deadline area yet

**Comment by ivanromakh** [comment]
@SashaScholar6 it is working but color was wrong. Changed color from blue to white
![image](https://user-images.githubusercontent.com/18567511/92474244-3313e200-f1e4-11ea-9714-9dc01e4c1d39.png)
