### ISSUE TITLE
When I select RAG filters on build, all three columns should be used

### ISSUE THREAD

**Issue by SashaScholar6** [Scholar-6/brillder#1652]
<img width="1440" alt="Screenshot 2020-09-08 at 13 01 56" src="https://user-images.githubusercontent.com/59654112/92474412-b11bbd00-f1d3-11ea-9226-f3a9c0a22acd.png">

- [ ] if more than one filter selected, show red first, then amber then green

**Comment by ivanromakh** [comment]
@farmanahmed2007 can you fix it seems css issue
