### ISSUE TITLE
Toby Ticket #59: text input output bug from build

### ISSUE THREAD

**Issue by SashaScholar6** [Scholar-6/brillder#1684]
Ticket #59
Hi - I've made a provisional brick for maths (chai...
Requester: Toby Peres
Assignee: Support
Hi - I've made a provisional brick for maths (chain rule), but when I play through it, a lot of the formatting is not as it should be. For instance, in the first page of the investigation, only the question I asked shows up and everything else is at the bottom of the page, but below the furthest point you can scroll to. Also I don't know how to access the slack workspace since it asks for a work email - maybe the workspace hasn't been set up (I've never used slack before so I'm unfamiliar with it).
Thanks very much,
Toby
------------------
Submitted from: https://brillder.scholar6.org/build/brick/251/build/investigation/question-component/30100

**Comment by ivanromakh** [comment]
@SashaScholar6 just checked it works good in production in that component
