### ISSUE TITLE
Fix blank row bug in Manage Classes

### ISSUE THREAD

**Issue by SashaScholar6** [Scholar-6/brillder#1697]
<img width="1217" alt="Screenshot 2020-09-15 at 12 08 47" src="https://user-images.githubusercontent.com/59654112/93197759-52fb5680-f74c-11ea-9de7-25d952451c42.png">
<img width="1137" alt="Screenshot 2020-09-15 at 12 08 53" src="https://user-images.githubusercontent.com/59654112/93197764-55f64700-f74c-11ea-8f92-f4c25f46f2a0.png">
![Uploading Screenshot 2020-09-15 at 12.09.01.png…]()

**Comment by ivanromakh** [comment]
@william-gooch this is easier to fix from backend side. you need to filter students. give me only the ones with first or last name.
![image](https://user-images.githubusercontent.com/18567511/93349495-35a7b480-f840-11ea-9cc2-cd232d22922a.png)
