### ISSUE TITLE
Change to 5 mins ago and move 'X' on right in line with other 'x's

### ISSUE THREAD

**Issue by SashaScholar6** [Scholar-6/brillder#1707]
<img width="132" alt="Screenshot 2020-09-15 at 18 27 17" src="https://user-images.githubusercontent.com/59654112/93238060-362d4600-f781-11ea-9dfb-127130b56f56.png">

- [x] text change

- [x] 'x' placement

**Comment by ivanromakh** [comment]
@SashaScholar6 we will need to change library to do so moment js have these. if we need to change we will need to write our own thing
![image](https://user-images.githubusercontent.com/18567511/93886220-d2110180-fced-11ea-98f4-fe989d8720ba.png)

**Comment by ivanromakh** [comment]
@william-gooch do you have any ideas how to make minutes to mins?

**Comment by william-gooch** [comment]
I can do that, I think.
Using this feature of the library: https://momentjs.com/docs/#/customization/relative-time/
