### ISSUE TITLE
When I have published a brick and notification appears, brick should be at the top of brick list (in first row green icon column) 

### ISSUE THREAD

**Issue by SashaScholar6** [Scholar-6/brillder#1713]
<img width="1345" alt="Screenshot 2020-09-21 at 11 19 45" src="https://user-images.githubusercontent.com/59654112/93750812-63a04680-fbfc-11ea-8f34-7510c1eca42a.png">

- [x] make icon in circle same thickness as core/private toggle, notifications (a bit thicker)

**Comment by william-gooch** [comment]
Should this be cleared when the notification is cleared? I.e. when the user marks the notification as read, should it go back to its normal place in the list?

**Comment by ivanromakh** [comment]
@william-gooch what do you think. Could you add publisher to brick?

**Comment by ivanromakh** [comment]
@william-gooch need a request to get bricks which I have published
