### ISSUE TITLE
Autosuggest usernames on invite

### ISSUE THREAD

**Issue by SashaScholar6** [Scholar-6/brillder#1718]
<img width="297" alt="Screenshot 2020-09-17 at 12 31 20" src="https://user-images.githubusercontent.com/59654112/93459226-b23e9f80-f8e1-11ea-9033-4ed30aaa5b9c.png">

- [x] if I type in matching email or Name and Surname, show Username in dropdown (William has enables this)

**Comment by william-gooch** [comment]
@SashaScholar6 what does this actually entail?
@ivanromakh do you need anything from me for this?
