### ISSUE TITLE
When I click edit notification, I should be taken to Back to work Build Tab

### ISSUE THREAD

**Issue by SashaScholar6** [Scholar-6/brillder#1731]
![Kapture 2020-09-17 at 12 24 26](https://user-images.githubusercontent.com/59654112/93464285-3c3e3680-f8e9-11ea-98c8-a70e2073525b.gif)

- [x] circles in notification panel should also be clickable

- [x] build core toggle if 'educate the world' was clicked by builder

- [x] build private toggle if 'educate the world' was clicked by builder

**Comment by ivanromakh** [comment]
@aromakh you need to add variable to notification isPrivate or isCore which will mean oposite.
![image](https://user-images.githubusercontent.com/18567511/93468094-233c8200-f8f7-11ea-8760-3e5eddd64a21.png)

**Comment by ivanromakh** [comment]
@aromakh its for the second and third point in the task
