### ISSUE TITLE
If user is Brick Author, Admin or Assigned Editor, Exit button redirects to Back to Work Build tab (Core or Private depending on brick following #1727 and #1728)

### ISSUE THREAD

**Issue by SashaScholar6** [Scholar-6/brillder#1733]
<img width="1069" alt="Screenshot 2020-09-17 at 13 44 54" src="https://user-images.githubusercontent.com/59654112/93466532-ae644a80-f8ec-11ea-85df-8d55e35ed20b.png">

- [x] if user is just playing, redirect to Back to Work Learn tab (Core or Private depending on Brick following #1727 and #1728)

**Comment by william-gooch** [comment]
@ivanromakh What do you need for this in the backend?
