### ISSUE TITLE
Make filters apply for 'Build' and 'Edit' bricks too, and show 'View All' 'Build' or 'Edit as selected when filters applied

### ISSUE THREAD

**Issue by SashaScholar6** [Scholar-6/brillder#1737]
<img width="368" alt="Screenshot 2020-09-17 at 14 45 49" src="https://user-images.githubusercontent.com/59654112/93472198-a4dee080-f8f4-11ea-9b0b-7cff449fab3c.png">

- [x] selector red as in #1736

**Comment by ivanromakh** [comment]
waiting for https://github.com/Scholar-6/brillder-backend/issues/288
