### ISSUE TITLE
Clean up errors in build

### ISSUE THREAD

**Issue by scholar6admin** [Scholar-6/brillder#1742]
https://jenkins.scholar6.org/jenkins/job/Deploy%20Dev%20Frontend/1883/console

looks like we can remove storybook to stop the icanuse-lite error 

and there are a bunch of react errors.

**Comment by ivanromakh** [comment]
@william-gooch I fixed obvious ones rest leave to you in graph components. almost all of them related to useEffect hooks you can include dependencies of just include
