### ISSUE TITLE
When a certain length is exceed in Brief input of Proposal phase (PP3), user is redirected to home screen (text attempted in notes below)

### ISSUE THREAD

**Issue by SashaScholar6** [Scholar-6/brillder#176]
Merkle Trees have been used in many technologies such as Bitcoin and Git version Control. In this brick we will be using 'square root' as a contrived hashing function in order to emulate more complex hash functions like SHA-1 or SHA-256, we will then put this into a merkle tree and finally try extending this into a delta compression chain. The goal is to see why we use this technology to detect changes to both decrease storage requirements and quickly detect changes in a file system or version history.

**Comment by aromakh** [comment]
@SashaScholar6  limit is changed from 255 to 65,535 characters (which is max of Text type)

Let me know please if we need more and I will change it to MEDIUMTEXT which is 16,777,215 or LONGTEXT  which is 4,294,967,295 characters.

I would suggest to not use LONGTEXT  from the begining as it could produce performance issues in the future.
