### ISSUE TITLE
Teach View when book shape is expanded

### ISSUE THREAD

**Issue by SashaScholar6** [Scholar-6/brillder#1766]
<img width="721" alt="Screenshot 2020-09-22 at 20 40 49" src="https://user-images.githubusercontent.com/59654112/93923634-f089f380-fd13-11ea-826c-3eae4fc5c555.png">

- [x] top row is same as in #1795 

- [x] ticks and crosses from final score page

- [x] 24 is maximum number of questions

- [x] only show number of questions in brick (not 24 every time) and space accordingly (further rules may be need if spaces look off)

- [x] even spacing between ticks and crosses, centred with numbers above

- [x] chevron down (below book, above yellow circle) sorts students by highest score

**Comment by william-gooch** [comment]
@ivanromakh I added some more data to the /stats/assignment/{assignmentId} endpoint that should help with this. However to change it, it requires that both the live and review answers are send to the /play/attempt separately. Final answers should be in "answers" field and live answers should be send in "liveAnswers" field.

**Comment by ivanromakh** [comment]
@william-gooch for this task need update for api call. 
![image](https://user-images.githubusercontent.com/18567511/95081976-0986a180-0723-11eb-87cd-2ba7d14dc7c7.png)
GET: /stats/assignment/85
it looks like this
![image](https://user-images.githubusercontent.com/18567511/95082071-31760500-0723-11eb-9629-fd6f1017a8a9.png)
I don`t need also liveAnswers.
