### ISSUE TITLE
BUG: links not becoming hyperlinks in brief and prep etc

### ISSUE THREAD

**Issue by SashaScholar6** [Scholar-6/brillder#1779]
https://brillder.scholar6.org/build/new-brick/proposal

- [x] see khan academy link in proposal brief/prep

<img width="411" alt="Screenshot 2020-09-23 at 12 12 18" src="https://user-images.githubusercontent.com/59654112/93999405-0f30ce80-fd96-11ea-981f-2476ed34e148.png">

- [x] nice :) when entered into proposal dark blue phones, set hyperlink colour to light blue

**Comment by ivanromakh** [comment]
https://ckeditor.com/docs/ckeditor5/latest/features/link.html

**Comment by ivanromakh** [comment]
To add this need to upgrade ckeditor from v19 to v21. It will take time.
![image](https://user-images.githubusercontent.com/18567511/93987477-47351300-fd90-11ea-969a-145c05af43ed.png)
