### ISSUE TITLE
Begin book design post play (accessible via a notification)

### ISSUE THREAD

**Issue by SashaScholar6** [Scholar-6/brillder#1790]
<img width="956" alt="Screenshot 2020-09-22 at 15 11 04" src="https://user-images.githubusercontent.com/59654112/93886767-1b5d5300-fce6-11ea-8983-e8ed9854e3a3.png">

- [x] Purple on book is an example of a subject colour - should change accordingly

**Comment by ivanromakh** [comment]
http://local-brillder.scholar6.org:3000/post-play/637

**Comment by ivanromakh** [comment]
https://dev-brillder.scholar6.org/post-play/637
