### ISSUE TITLE
Question display in play results book

### ISSUE THREAD

**Issue by SashaScholar6** [Scholar-6/brillder#1792]
<img width="957" alt="Screenshot 2020-09-22 at 15 20 50" src="https://user-images.githubusercontent.com/59654112/93887702-5318ca80-fce7-11ea-95ac-8bab15c6814e.png">

- [x] move mouse out to close book as in proposal.  

- [x] At the moment because the notification panel is over the hover area the book opens automatically, so you can't see the text or cover. Any easy fix?  If not, we could make give the B on the cover a hover colour and pulse and tell users to 'Click the B' to open it'.

- [x] question displays on left (scrollable if necessary)

<img width="957" alt="Screenshot 2020-09-22 at 15 21 00" src="https://user-images.githubusercontent.com/59654112/93887711-557b2480-fce7-11ea-8677-ee6fe5e4cf5b.png">

- [x] content page at the front for different attempts

- [x] clicking the eye next to ticks or crosses shows answer from either investigation or review

- [x] new attempt registers in row below on right

- [x] something like this click and animation to move between pages: https://archive.org/details/goodytwoshoes00newyiala/page/n11/mode/2up

**Comment by ivanromakh** [comment]
@william-gooch need a way to get investigation and review answers.

**Comment by ivanromakh** [comment]
https://github.com/Scholar-6/brillder-backend/issues/301
