### ISSUE TITLE
Only include 'Drag Component here' panel below question text component on QP1 - do not show on subsequent panels

### ISSUE THREAD

**Issue by SashaScholar6** [Scholar-6/brillder#1806]
<img width="745" alt="Screenshot 2020-09-23 at 13 13 29" src="https://user-images.githubusercontent.com/59654112/94005709-f0830580-fd9e-11ea-9f10-6831c8808c36.png">

**Comment by ivanromakh** [comment]
this fix will apply for new questions. Old ones will be the same.
