### ISSUE TITLE
Ticket #67 Synthesis has gone missing

### ISSUE THREAD

**Issue by SashaScholar6** [Scholar-6/brillder#1820]
https://brillder.scholar6.org/build/brick/257/investigation/synthesis

A lot of my content has seemingly disappeared from...
Requester: Sophie
Assignee: Support
A lot of my content has seemingly disappeared from the editor. It's still present in the mobile-screen-preview, but it seems to be missing in the editor itself.
------------------
Submitted from: https://brillder.scholar6.org/build/brick/257/investigation/question-component/30403

![](https://scholar6.zendesk.com/attachments/token/fpcUMJhoYkSxt2LjMCFe54urg/?name=Screenshot+2020-09-24+at+09.17.20.png)

![](https://scholar6.zendesk.com/attachments/token/3ZQ5HLw9KIifyrWssZnNDMxl7/?name=Screenshot+2020-09-24+at+09.17.07.png)

![](https://scholar6.zendesk.com/attachments/token/HE4itSLEj1vFtrpSEjheBlF8H/?name=Screenshot+2020-09-24+at+09.17.42.png)

- [x] seems Wiris related as pure text components still showing and editable

- [x] could it also be because of new fixed question text component?

**Comment by ivanromakh** [comment]
@SashaScholar6 @lindsaymacvean I removed route so some users can have this issue

**Comment by ivanromakh** [comment]
they should use route path without /build/ inside

**Comment by ivanromakh** [comment]
https://brillder.scholar6.org/build/brick/261/investigation/question-component/30671

**Comment by ivanromakh** [comment]
@SashaScholar6 where did she/he get this link? I need to replace it if it is somewhere still.
