### ISSUE TITLE
Turn on Latex input on Wiris

### ISSUE THREAD

**Issue by SashaScholar6** [Scholar-6/brillder#1821]
http://www.wiris.com/news/wiris-editor-latex-support-insight#:~:text=LaTeX%20is%20manipulated%20as%20MathML&text=Upon%20submit%20the%20HTML%20editor,the%20MathML%20mechanism%20takes%20place.
wiris.comwiris.com
LaTeX support in WIRIS plugins: Insights. | WIRIS | math & science (3 kB)
http://www.wiris.com/themes/wiris_com/icons/logoW.png

10:29
for turning on latex

**Comment by ivanromakh** [comment]
It works from version 7.24.0. There was issues with previous versions. Now it works as copy and paste.
