### ISSUE TITLE
When writing LaTeX in CK Editor, equation goes to centre and breaks lines of text

### ISSUE THREAD

**Issue by SashaScholar6** [Scholar-6/brillder#1826]
<img width="1027" alt="Screenshot 2020-09-24 at 15 21 00" src="https://user-images.githubusercontent.com/59654112/94150796-e124ba80-fe79-11ea-952f-5e06dd1149a3.png">

**Comment by ivanromakh** [comment]
@SashaScholar6  can`t reproduce it can you give me a link for question?
