### ISSUE TITLE
Add notification for learner to access Play Results Book

### ISSUE THREAD

**Issue by SashaScholar6** [Scholar-6/brillder#1834]
- [x] Will say something like l1: 'Your Brick Summary is Ready | l2: View your copy of 'Brick Title', 

- [x] green circle, open-book icon

**Comment by william-gooch** [comment]
Added this notification. Notification type is `6` for adding custom icon and routing code.

**Comment by ivanromakh** [comment]
![image](https://user-images.githubusercontent.com/18567511/94566383-eff0e000-0272-11eb-8b0a-ed1d9f7a860f.png)
