### ISSUE TITLE
Ticket #71 Harry can't submit his brick to editors

### ISSUE THREAD

**Issue by SashaScholar6** [Scholar-6/brillder#1837]
Ticket #71
Hi. I'm still getting the error where I can't send...
Requester: Harry Vinall-Smeeth
Assignee: Support
Hi. I'm still getting the error where I can't send my brick to an editor (see screenshot). Thanks!
------------------
Submitted from: https://brillder.scholar6.org/play-preview/brick/252/build-complete
Status: New | Today at 11:48 AM

**Comment by ivanromakh** [comment]
I checked it works fine now
