### ISSUE TITLE
End of publisher process

### ISSUE THREAD

**Issue by scholar6admin** [Scholar-6/brillder#1852]
<img width="1428" alt="Screenshot 2020-09-29 at 13 53 00" src="https://user-images.githubusercontent.com/59654112/94554981-2de20a00-025b-11eb-8112-b3916a1755b4.png">

Rename editor role in profile to publisher and give permissions for the subject areas they have selected on their profile. 

The publisher has publish button and send back to editor/author.

**Comment by ivanromakh** [comment]
something blocked by https://github.com/Scholar-6/brillder-backend/issues/300
