### ISSUE TITLE
Add New Design for 'Your Proposal Phase' (see notes)

### ISSUE THREAD

**Issue by SashaScholar6** [Scholar-6/brillder#186]
- Coloured background #E5E8ED
- new back and forward arrows
- book animation/hover https://www.pinterest.fr/pin/818810775990226821/

<img width="960" alt="Screenshot 2020-03-30 at 11 46 38" src="https://user-images.githubusercontent.com/59654112/77902280-36905e00-7281-11ea-9caa-ee483b343a69.png">

<img width="1440" alt="Screenshot 2020-04-01 at 13 28 57" src="https://user-images.githubusercontent.com/59654112/78132352-e0f0b880-741c-11ea-9f8e-7ce2c203b01e.png">

**Comment by ivanromakh** [comment]
Hm. need to use transformation for this one. It will take some time
