### ISSUE TITLE
VIEW ALL: Update Sidebar shape and styling (see notes+link)

### ISSUE THREAD

**Issue by SashaScholar6** [Scholar-6/brillder#187]
- Padding, Radius 39
- Sort By/Filter All Caps
- HIde/Show Arrow and Cross
- Highlight over Filter
<img width="300" alt="Screenshot 2020-03-30 at 12 25 02" src="https://user-images.githubusercontent.com/59654112/77902733-f67dab00-7281-11ea-8cb1-4d0da219879c.png">

**Comment by aromakh** [comment]
Sasha  2:02 PM
If I were to be really fussy - which I have to be, but not necessarily all for tomorrow - I would say:
1. the centre of the X should be aligned with the centre of the circles below
2. the X and the arrow should be the same thickness
3. English Literature should be in Purple
4. Rest of the Subjects should be there
5. The 'X' should only show up once a subject is selected, perhaps with an animation
But none of those are particularly important except for 4., helpful for testers to know what we intend to offer, 5. would be nice (or at least for X to disappear when filters hidden) - and may as well do 3. as it's Joe's subject and a quick fix.
