### ISSUE TITLE
How does a student enter superscript/subscript into short answer?

### ISSUE THREAD

**Issue by scholar6admin** [Scholar-6/brillder#1895]
![image](https://user-images.githubusercontent.com/58778078/94805942-1767ba00-03e5-11eb-9e5f-ffb354a3a184.png)

![image](https://user-images.githubusercontent.com/58778078/94805959-1df63180-03e5-11eb-92be-bc1c11e09f14.png)

**Comment by ivanromakh** [comment]
By ckeditor.
![image](https://user-images.githubusercontent.com/18567511/103086087-4ceb0080-45ec-11eb-8196-c80dd4b58a92.png)
