### ISSUE TITLE
Clicking x on notification activates the notification instead of clearing it.

### ISSUE THREAD

**Issue by scholar6admin** [Scholar-6/brillder#1898]
![image](https://user-images.githubusercontent.com/58778078/94806509-f6ec2f80-03e5-11eb-90cc-432e3394adf2.png)

**Comment by utk0730** [comment]
Hi @scholar6admin  I would like to work on this issue, but need some help in setting up.
I am getting an error when starting server , attaching screenshot below[](url)
<img width="1348" alt="desmos-error" src="https://user-images.githubusercontent.com/28000030/94913699-55d5a580-04c7-11eb-8835-a3f59263e83f.png">

Is adding an entry to the hosts file on mac in mandatory ? (referring to this, that i skipped ->  add an entry to the hosts file ** linux /etc/hosts ** windows C:\Windows\System32\Drivers\etc\hosts 127.0.0.1 local-brillder.scholar6.org)

**Comment by william-gooch** [comment]
Sorry, this wasn't in the README - I've updated it now.
You also need to add this line:
`REACT_APP_DESMOS_API_KEY=dcb31709b452b1cf9dc26972add0fda6`
to your .env file

**Comment by utk0730** [comment]
thanks @william-gooch. It's working for me now.
I want to work on this issue, please assign it to me

**Comment by utk0730** [comment]
@william-gooch @scholar6admin need some help with login. 
locally app is running on localhost:3000, but during sing in locally I am getting connection problem

### attaching etc/hosts config below
<img width="567" alt="Screenshot 2020-10-03 at 5 59 16 AM" src="https://user-images.githubusercontent.com/28000030/94978940-9839c980-053d-11eb-909f-fe0ed28e63f8.png">

### api endpoint that it is hitting
https://dev-api.scholar6.org/auth/login/3

**Comment by utk0730** [comment]
@william-gooch @scholar6admin Please help me with this initial setup.

**Comment by william-gooch** [comment]
@utk0730 What are you doing to sign in? Have you made an account before trying to?
If the API endpoint isn't working, please send a screenshot of the response body so I know what the error is.

**Comment by utk0730** [comment]
<img width="604" alt="Screenshot 2020-10-07 at 2 48 06 AM" src="https://user-images.githubusercontent.com/28000030/95261304-ca9e3c00-0847-11eb-9bc5-5fd60f287723.png">
with these same credentials I am able to login on https://dev-brillder.scholar6.org/login
but it is not working on my local i.e http://localhost:3001/login
