### ISSUE TITLE
Ticket # 81 Synthesis does not appear 760px-1280px screen width

### ISSUE THREAD

**Issue by SashaScholar6** [Scholar-6/brillder#1903]
Ticket #81
Synthesis does not appear 760px-1280px screen width
![image](https://user-images.githubusercontent.com/58778078/95246118-fdc2da00-080b-11eb-92fc-25f253c49fd5.png)

When I play through my bricks, the formatting of t...
Requester: Toby Peres
Assignee: Support
When I play through my bricks, the formatting of the synthesis is wrong - it basically shows a blank page, with just the first line squeezed in at the top.
------------------
Submitted from: https://brillder.scholar6.org/play-preview/brick/258/synthesis

**Comment by ivanromakh** [comment]
@SashaScholar6 maybe it is related to device and browser.

**Comment by scholar6admin** [comment]
This is to do with the window sizing. We need to make sure the synthesis compresses when the window is smaller. (or else display the message about needing a bigger boat etc).

**Comment by scholar6admin** [comment]
https://scholar6.zendesk.com/agent/tickets/81
