### ISSUE TITLE
Ticket #80 Maya Editing userflow double-check

### ISSUE THREAD

**Issue by SashaScholar6** [Scholar-6/brillder#1904]
I am just editing Lois's brick and at the end this screen appeared which is the same as when I make a brick so I was wondering if that is how you want it to look? Also when I first opened the brick I could edit it completely...

------------------
Submitted from: https://brillder.scholar6.org/play-preview/brick/255/build-complete

Attachment(s)
Screenshot 2020-10-01 at 10.38.21.png

**Comment by ivanromakh** [comment]
@SashaScholar6 it is not possible only admin and author can unlock or edit bricks
