### ISSUE TITLE
Assigning editor should refresh bricks for editor in back to work.

### ISSUE THREAD

**Issue by scholar6admin** [Scholar-6/brillder#1906]
As an editor 
When I get a notification for a brick assigned to me
And I click on the notification
Then I should see the new brick in my back to work etc. 

The brick does not show up because it needs to make a fresh call to the api to get the latest bricks for the user.

**Comment by william-gooch** [comment]
@ivanromakh can you do this by making another call to the API endpoint whenever the notification is clicked?
I feel as though otherwise this would require socket.io which I think is a little overkill.
