### ISSUE TITLE
Ticket #75 MSUP Error in Wiris

### ISSUE THREAD

**Issue by SashaScholar6** [Scholar-6/brillder#1910]
Have submitted a ticket to Wiris

As a builder
When I use wiris to enter 
![image](https://user-images.githubusercontent.com/58778078/95231518-268ea380-07fb-11eb-9fa6-c82011e420b2.png)

![image](https://user-images.githubusercontent.com/58778078/95231856-9e5cce00-07fb-11eb-96c5-a176ecbc6739.png)
And I go to a different question panel and then come back
I should not see the function displaying 
![image](https://user-images.githubusercontent.com/58778078/95231951-c4826e00-07fb-11eb-80c2-4943dcc02542.png)

https://brillder.scholar6.org/build/brick/251/investigation/question-component/30100

![Screenshot 2020-10-02 at 11 37 56](https://user-images.githubusercontent.com/59654112/94909710-df737c00-04a3-11eb-89b8-6c7a323cbc63.png)

I'm doing a pair match question and I keep getting "Invalid <msup> element" in the right hand box in the seventh question pair box - so when I play through the brick, it doesn't come out as I've typed it.

------------------
Submitted from: https://brillder.scholar6.org/build/brick/251/investigation/question-component/30719

Screenshot 2020-09-26 at 13.00.02.png
Screenshot 2020-09-26 at 13.00.02
PNG

**Comment by ivanromakh** [comment]
@SashaScholar6 All I can do is post issue in wiris plugin.

**Comment by scholar6admin** [comment]
I will contact Wiris account manager.

**Comment by ivanromakh** [comment]
@scholar6admin seems <msup> is not supported as latex yet. I tried by my self.

**Comment by ivanromakh** [comment]
example: <msup> base superscript </msup>
The MathML <msup> element is used to attach a superscript to an expression.
![image](https://user-images.githubusercontent.com/18567511/94911518-f1a6e780-04ae-11eb-83fe-397e5e5e2e9b.png)

**Comment by ivanromakh** [comment]
@scholar6admin $$x^2$$ works fine for me.

**Comment by scholar6admin** [comment]
I have contacted Toby to find out if he knows about that way of doing superscript and where he got msup from.

**Comment by tobyperes** [comment]
Hi - I don't know where msup came from. I had been trying to type -2x/(x^2 +1)^2 into wiris but it turned it into what I showed in the screenshot. I've just tried to write it again and the same thing has happened.
