### ISSUE TITLE
Clicking 'View Brick Summary' notification leads to blank screen

### ISSUE THREAD

**Issue by SashaScholar6** [Scholar-6/brillder#1915]
<img width="1025" alt="Screenshot 2020-10-02 at 11 49 50" src="https://user-images.githubusercontent.com/59654112/94910782-7856c700-04a5-11eb-8136-1739971dd8a8.png">

**Comment by ivanromakh** [comment]
@lindsaymacvean which brick is it?

**Comment by scholar6admin** [comment]
Redirecting to @SashaScholar6 as he created this ticket?
