### ISSUE TITLE
Make Subject Colour appear on book cover, B and circle (inside page)

### ISSUE THREAD

**Issue by SashaScholar6** [Scholar-6/brillder#1930]
Subject colour is not showing on book and B however

- [x] side of cover and B

- [x] circle in inside

<img width="1499" alt="Screenshot 2020-10-05 at 12 16 42" src="https://user-images.githubusercontent.com/59654112/95067934-d2a19300-0704-11eb-9b6e-8e7bbac2cd94.png">

<img width="1432" alt="Screenshot 2020-10-05 at 12 17 50" src="https://user-images.githubusercontent.com/59654112/95067903-cb7a8500-0704-11eb-8b8b-8ec34b5f10a7.png">

**Comment by ivanromakh** [comment]
@william-gooch this needs backend fix
