### ISSUE TITLE
Pointing left is with editor, pointing right is with publisher

### ISSUE THREAD

**Issue by SashaScholar6** [Scholar-6/brillder#1934]
<img width="703" alt="Screenshot 2020-10-05 at 15 14 08" src="https://user-images.githubusercontent.com/59654112/95084371-12c13f80-071e-11eb-969e-11874dbefcd5.png">

**Comment by ivanromakh** [comment]
Hi @william-gooch.
Need update in api calls for back to work page for list of bricks.
bricks with status 2 should have some bool variable which can tell me is it is currently assigned editor or publisher.

Api call which need to be updated:
GET: https://dev-api.scholar6.org/bricks/currentUser
GET: https://dev-api.scholar6.org/bricks
