### ISSUE TITLE
Safari: Notification circle colours showing as black rather than red or yellow like other browsers

### ISSUE THREAD

**Issue by SashaScholar6** [Scholar-6/brillder#1949]
![Screenshot 2020-10-06 at 13 34 44](https://user-images.githubusercontent.com/59654112/95196763-d272c780-07d8-11eb-8243-0afbb822b2df.png)

- [x] see tab 1 (should be like screenshot below)

<img width="395" alt="Screenshot 2020-10-06 at 13 36 56" src="https://user-images.githubusercontent.com/59654112/95196896-09e17400-07d9-11eb-9860-a33cce723b52.png">

**Comment by farman9849** [comment]
SVG is not adding dynamic color to safari browser, need to add css based circles

**Comment by SashaScholar6** [comment]
@farman9849 ok, let's forget about this task for now and focus on Mobile and other tasks in the queue
