### ISSUE TITLE
Desmos Graph improvements

### ISSUE THREAD

**Issue by scholar6admin** [Scholar-6/brillder#1969]
- [x] Should not count towards word count
![image](https://user-images.githubusercontent.com/58778078/121693568-2e58c300-cac1-11eb-831e-081ed1ef45bf.png)

- [x] Add desmos to synthesis
![image](https://user-images.githubusercontent.com/58778078/117670901-38289700-b1a0-11eb-92a1-8fdb7e1231ab.png)

- [x] Desmos graph popup needs 'insert' button and 'x' to close popup
![image](https://user-images.githubusercontent.com/58778078/117670954-424a9580-b1a0-11eb-81aa-64f2f28851cf.png)

**Comment by william-gooch** [comment]
@SashaScholar6 what do you mean by 'get rid of display tools option'?

**Comment by scholar6admin** [comment]
Its this button
![image](https://user-images.githubusercontent.com/58778078/121329321-058fcc80-c90d-11eb-8280-dbed3f479641.png)

That enables this option in the play
![image](https://user-images.githubusercontent.com/58778078/121329363-0de80780-c90d-11eb-918d-0b9f5957e2f8.png)

**Comment by william-gooch** [comment]
Why are we getting rid of that, just out of curiosity?

**Comment by scholar6admin** [comment]
@william-gooch I cant seem to see the quill option in dev-app on synthesis

![image](https://user-images.githubusercontent.com/58778078/121535077-b83d5900-c9f9-11eb-8b08-af9d38c46b2a.png)

That's also a good why question Ill double check with Toby and see what he wants.

**Comment by william-gooch** [comment]
My bad, I forgot to add an icon lol. Fixed.

**Comment by william-gooch** [comment]
@scholar6admin what should this 'insert' button do? the graph automatically updates so there's no need for a button for it?
