### ISSUE TITLE
Author end of brick buttons

### ISSUE THREAD

**Issue by SashaScholar6** [Scholar-6/brillder#1974]
As an author

If brick status 1 and no editor assigned the no return to editor button
If brick status 1 and editor assigned then return to editor button
If brick status 2 and editor assigned then NO return to editor button

**Comment by ivanromakh** [comment]
@william-gooch after I removed editor the list with editors is empty. to add return to editor I need that editor id somewhere in brick.

**Comment by william-gooch** [comment]
Should be fixed now @ivanromakh
