### ISSUE TITLE
Investigation Build: Update Tab Styling to No Borders, Light Blue Grey and Brandon Reg/Black (hover+tab headings) 

### ISSUE THREAD

**Issue by SashaScholar6** [Scholar-6/brillder#198]
<img width="633" alt="Screenshot 2020-03-30 at 12 56 44" src="https://user-images.githubusercontent.com/59654112/77906163-c802ce80-7287-11ea-986a-1947b028e6b2.png">

**Comment by ivanromakh** [comment]
@SashaScholar6 Provide link to adobe, please
