### ISSUE TITLE
Search UI improvements

### ISSUE THREAD

**Issue by SashaScholar6** [Scholar-6/brillder#1997]
<img width="1444" alt="Screenshot 2020-10-12 at 12 55 51" src="https://user-images.githubusercontent.com/59654112/95738957-5837bc80-0c8a-11eb-87f8-8fa022ac555b.png">

- [x] highlight matches (like Google books)

<img width="1372" alt="Screenshot 2020-10-08 at 16 03 59" src="https://user-images.githubusercontent.com/59654112/95469419-ea388000-097f-11eb-872f-866e3650a3db.png">

- [x] also highlight in hover area

**Comment by ivanromakh** [comment]
@aromakh by which fields search is working now?

**Comment by aromakh** [comment]
Hi @ivanromakh 
Currently we do search over following fields:
["author", "editors", "openQuestion", "subTopic", "title", "alternativeTopics"]

**Comment by aromakh** [comment]
authorId
