### ISSUE TITLE
Back to work - build - Personal: set colors of bricks

### ISSUE THREAD

**Issue by scholar6admin** [Scholar-6/brillder#2002]
As an author 
When I select 'keep control'
I should only see the option to 'publish' the brick
When I look at my back to work -> build -> personal area the bricks should show with the following colours.
Bricks should be tiled (not columns) with status=1 first and then status=4 after.

Red - unpublished (status=1)
Amber ring - published (status=4 but isCore=false)

<img width="720" alt="Screenshot 2020-10-12 at 17 00 31" src="https://user-images.githubusercontent.com/59654112/95761390-88905280-0cac-11eb-82af-9ae4d21c97af.png">

When I select 'view all'->personal toggle
Then I should see published and isCore=false and only my own authored bricks. 

When I search in view all 
I should NEVER see personal bricks

- [x] update filter bars

- [x] for build personal, display draft and self-published by date, like View All Bricks page (no need for columns - then filters clickable to separate)

**Comment by ivanromakh** [comment]
@william-gooch now publish should be available for personal bricks where isCore = false.  This mean author should be able to do self publish for personal bricks.

POST: /brick/publish/brickId

**Comment by ivanromakh** [comment]
@william-gooch GET: /bricks/byStatus should not return self publish bricks of other users.

**Comment by ivanromakh** [comment]
@aromakh search should not return personal bricks where isCore = false
