### ISSUE TITLE
Ticket #96 lost the whole of a synthesis on the kalam cosmological argument

### ISSUE THREAD

**Issue by SashaScholar6** [Scholar-6/brillder#2014]
Ticket #96
https://scholar6.zendesk.com/agent/tickets/96
hi i just lost the whole of a synthesis on the kal...
Requester: stephen arscott
Assignee: Support
hi i just lost the whole of a synthesis on the kalam cosmological argument
i was pressing the final button after read through and it disappeared.
can we get it back? i had read it through so it had been on my screen for sometime?
it was saved to word half way so it is not a complete disaster  but at 4.00 am here a bit annoying!
yours hoping
stephen
------------------
Отправлено с https://brillder.scholar6.org/build/brick/295/investigation/synthesis
Show less

**Comment by scholar6admin** [comment]
Still not clear what caused this. But suspicion is that a blank synthesis was cached either locally or remotely and then overrode the changes that Stephen was making. 

We are adding diff functionality to brick saving to improve the step by step saving of changes. https://github.com/Scholar-6/brillder-backend/issues/311
