### ISSUE TITLE
User Preference: Change home screen for student

### ISSUE THREAD

**Issue by scholar6admin** [Scholar-6/brillder#2020]
<img width="957" alt="Screenshot 2020-10-09 at 14 33 45" src="https://user-images.githubusercontent.com/59654112/95583481-7b6d2c80-0a3c-11eb-99d3-e690cb67361a.png">

As a new user
When I select 'student' as a preference
Then my profile should only show 'student' role
But I should still be able to access brick building routes etc.
And I should not see a 'Bio' field
And on the home page I should see only 'view and play' icon highlighted. 

When I have a brick assigned to me to play
Or I have started building a brick
Then I should also see 'back to work' highlighted.

When I have finished playing at least one brick
Then I should see 'My Library' highlighted.

FIXES:

- [x] don't change text on hover for unavailable icons

- [x] don't allow try building unless red (ie. after a brick has been played)

- [x] Popups Back to Work: 'To unlock this, a brick needs to have been assigned to you' (white, thick text like link copied - feather lock icon in red circle)

- [x] Popup for My Library icon: 'Play a brick to unlock this' (white, thick text like link copied - feather lock icon in red circle)

- [x] Popup for Try Building if still blue: 'Play a brick to unlock this' (white, thick text like link copied - feather lock icon in red circle)

- [x] Make Back to Work icon a bit smaller

- [x] Update new icons in dropdown menus (in white)

**Comment by ivanromakh** [comment]
@william-gooch need request to check if current logged in user played any brick

**Comment by william-gooch** [comment]
@ivanromakh done. It's just a `hasPlayedBrick` attribute of the user object now so you can just use /user/current to get it.
It automatically is set to true when a user attempts a brick.
