### ISSUE TITLE
BUG: Editor should be able to see status=1 bricks

### ISSUE THREAD

**Issue by scholar6admin** [Scholar-6/brillder#2031]
As an editor
When I send a brick 'back to author'
Then I should still be able to see the brick in back to work -> public toggle
![image](https://user-images.githubusercontent.com/58778078/95753940-3c3c1700-0c9a-11eb-870e-decf91bfa5af.png)

**Comment by ivanromakh** [comment]
@scholar6admin this is backend problem. I checked it seems to be fixed now.

**Comment by ivanromakh** [comment]
@scholar6admin if brick is private it will be in private toggle
