### ISSUE TITLE
Teach View from sidebar

### ISSUE THREAD

**Issue by SashaScholar6** [Scholar-6/brillder#2035]
- [x] Clicking on a class shows me bricks from that class only (not names unless expanded)

- [x] If i click on an individual name from sidebar, I see bricks for that person - expanded view shows only their results.

**Comment by ivanromakh** [comment]
@william-gooch need request to get bricks assigned to student by current logged in teacher by that student Id.

**Comment by william-gooch** [comment]
@ivanromakh should be done.
The endpoint is /bricks/assignedTo/{studentId}
It returns an array of Assignment objects from which you can get the brick.
