### ISSUE TITLE
Create basic library

### ISSUE THREAD

**Issue by scholar6admin** [Scholar-6/brillder#2050]
As an authenticated user
When I click on 'library' or whatever button is called
Then I should see the following

<img width="1812" alt="Screenshot 2020-10-23 at 12 24 38" src="https://user-images.githubusercontent.com/59654112/96992877-c9992a00-152a-11eb-9808-bc1773261cf7.png">

- [x] make sure click goes to book (not endless loading)

- [x] add 'FILTER BY CLASS' above current filter bar

- [x] rename current filter bar 'FILTER BY SUBJECT'

**Comment by william-gooch** [comment]
@ivanromakh I've added this endpoint, it's POST /play/library
There are two possible parameters in the body, classroomId for filtering by classroom and subjectId for filtering by subject. Neither of them are required, though.
As per Sasha's request this doesn't only show attempts that were from assignments.

**Comment by ivanromakh** [comment]
@william-gooch I need assignment id in this list

**Comment by william-gooch** [comment]
@ivanromakh  I can add that but it won't be present on every item. Some of them won't be from bricks that were assigned, so you need to make sure you add checks for it.

**Comment by ivanromakh** [comment]
@william-gooch I need only brick for which I can show book. then remove them from list

**Comment by william-gooch** [comment]
@ivanromakh You can show a book for every brick. You get the book based on brick ID, not assignment ID right?

**Comment by ivanromakh** [comment]
@william-gooch I see I don`t need.

**Comment by ivanromakh** [comment]
@william-gooch its userId 
![image](https://user-images.githubusercontent.com/18567511/98360001-c37a7180-2031-11eb-894f-ea31f51662d4.png)

**Comment by ivanromakh** [comment]
@william-gooch can you add check if they have live answers?

**Comment by william-gooch** [comment]
@ivanromakh not sure what you mean by that. At the moment it returns it if there is at least one attempt on it by that user. So if they have an attempt on it they should have answers for it, yeah.

**Comment by ivanromakh** [comment]
@william-gooch now there is old attempts which are invalid. They don`t have liveAttempts
![image](https://user-images.githubusercontent.com/18567511/98360553-aeeaa900-2032-11eb-82cc-3ef00370fa72.png)

**Comment by ivanromakh** [comment]
@william-gooch I will add some filter in front end as well but if all attempts then I don`t need it in current request

**Comment by ivanromakh** [comment]
@william-gooch if at least on attempt is valid then it should be present in list

**Comment by william-gooch** [comment]
Done.

**Comment by ivanromakh** [comment]
@william-gooch GET: /classrooms not working for students. need list of assigned classes to students.

**Comment by william-gooch** [comment]
Done. Endpoint is /classrooms/me
/classrooms should only be used for teacher or admin.

**Comment by ivanromakh** [comment]
@william-gooch need this for student

**Comment by william-gooch** [comment]
@ivanromakh The endpoint for students is /classrooms/me. This returns the classrooms that student is in.
