### ISSUE TITLE
Make transition between expanded and contracted notification panel smoother

### ISSUE THREAD

**Issue by SashaScholar6** [Scholar-6/brillder#2061]
![Kapture 2020-10-14 at 21 22 59](https://user-images.githubusercontent.com/59654112/96035738-bff52f80-0e63-11eb-8bf1-dacd96c024e3.gif)

- [ ] when notifications cleared, leave text for one second then roll up smoothly

**Comment by farman9849** [comment]
this cannot be included in the top-right area because the dropdown is made with dialog, Its HTML should be added into the same area where the action buttons are
