### ISSUE TITLE
Fix user preferences

### ISSUE THREAD

**Issue by scholar6admin** [Scholar-6/brillder#2107]
Specific problem: user 84 cannot remove publisher (even as admin)

In general

https://lucid.app/lucidchart/e65bec83-908d-459c-b639-e06fe24ca82b/edit?page=0_0#

https://home.scholar6.org/2020/06/30/permissions/

As a general user I should be able to select **one of**: student, builder or teacher **preference** in my profile. 

As an admin I should be able to set any role for a user including publisher role. Publisher role should be in addition to one of student/builder/teacher preferences. (Ivan - this one is for backend)

As a publisher I should not be able to unselect publisher role.

**Comment by ivanromakh** [comment]
@aromakh general student user can`t change role.
every user should be able to set student builder or teacher role.
![image](https://user-images.githubusercontent.com/18567511/102874857-b1228e80-444b-11eb-9589-3348074dd34f.png)
![image](https://user-images.githubusercontent.com/18567511/102874913-c8fa1280-444b-11eb-82ba-68ec2618e35f.png)
