### ISSUE TITLE
Link subject choice to rest of proposal

### ISSUE THREAD

**Issue by scholar6admin** [Scholar-6/brillder#2111]
<img width="882" alt="Screenshot 2021-01-20 at 12 57 53" src="https://user-images.githubusercontent.com/59654112/105171909-1d61e200-5b1f-11eb-9bc5-f2441104aeaa.png">

- [x] Add red Edit Icon next to 'This will be a SUBJECT brick', similar height and thickness as text

- [x] When clicked, redirects to choose subject panel if user has more than one subject

<img width="480" alt="Screenshot 2021-01-20 at 13 00 12" src="https://user-images.githubusercontent.com/59654112/105172296-b264db00-5b1f-11eb-9c3e-d26b15c2eda0.png">

- [x] Add Brillder logo to default choose subject phone

- [x] Add 'Next' text before arrow (same size as title page (what is it about?)

- [x] In Brick Title page, replace Next text with back arrow IF user has more than one subject

**POPUP**
- [x] If user has only one subject, clicking icon provokes popup: 'Only "SUBJECT" is listed on your profile.   Add another subject?  

- [x] Add Dropdown of subjects like William did for classes

- [x] Selecting new subject should save in profile

**Comment by ivanromakh** [comment]
Hi @SashaScholar6. Not sure about Next text before arrow there is already that label there.
