### ISSUE TITLE
Mobile: student preference home page should match options on desktop version

### ISSUE THREAD

**Issue by scholar6admin** [Scholar-6/brillder#2117]
<img width="279" alt="Screenshot 2020-10-28 at 18 28 24" src="https://user-images.githubusercontent.com/59654112/97473555-686abf80-194b-11eb-8b41-135f24639f89.png">

- [x] add bell and three dots menu

- [x] remove BETA (at the moment it means I can't click on three dots

**Comment by farman9849** [comment]
Not clear
