### ISSUE TITLE
Mobile: update user preference sizing

### ISSUE THREAD

**Issue by scholar6admin** [Scholar-6/brillder#2120]
<img width="367" alt="Screenshot 2020-10-30 at 14 00 35" src="https://user-images.githubusercontent.com/59654112/97707955-535f6f00-1ab8-11eb-8116-3d171029ff5e.png">

https://xd.adobe.com/view/30331e87-c1e7-4b03-9500-f91d835be8ee-6560/

**Comment by ivanromakh** [comment]
@SashaScholar6 it looks different. I updated sizing to make it look like in image but content there is different
![image](https://user-images.githubusercontent.com/18567511/97867888-5d32dd80-1d17-11eb-8c19-b23465f99806.png)

**Comment by SashaScholar6** [comment]
@ivanromakh which content is different - the text?  Think we can stretch to overlay zendesk and beta text on this page

**Comment by ivanromakh** [comment]
@SashaScholar6 Title. text under radio buttons. and zendesk button and beta text

**Comment by ivanromakh** [comment]
@SashaScholar6 title is shorter in image

**Comment by SashaScholar6** [comment]
@ivanromakh what have we currently got on desktop?/ What's the URL?
