### ISSUE TITLE
255 limit on suggestions (see proposal): Rosie #106 & Caroline #118 & Stephen #131: Comments of a certain length are being cut off or not posting at all

### ISSUE THREAD

**Issue by scholar6admin** [Scholar-6/brillder#2130]
As an editor
When I add a suggestion on the proposal
There is a character limit of 255 

Make this character unlimited (63,206 POST limit) or else limit to the recommended for socket.io etc.

TICKETS #106 & #118
Rosie Castle  Oct 16 14:05
To: scholar6 Show all
Here's some examples: I can't scroll any further up or down to see the whole comment, and there doesn't seem to be a way to click into the suggestion to read the whole thing/ or to edit it- only possible to delete. 

<img width="609" alt="Screenshot 2020-10-26 at 20 56 35" src="https://user-images.githubusercontent.com/59654112/97222172-3a13a580-17ce-11eb-95f6-5894ce46e2aa.png">

- [ ] see cut off

Caroline Greenaway  Thursday 11:58
To: scholar6 Show all
Hi Sasha,

In addition, I am also having issues with longer suggestions in Rosie's synthesis. I think it is the length that was also the problem in the plan part as I wrote 'test' and it took it (I have since deleted the comment) and on the synthesis I have been able to successfully write a shorter suggestion which has saved and stayed there.

Thanks
Caroline

**Comment by ivanromakh** [comment]
@aromakh 
http://local-brillder.scholar6.org:3000/build/new-brick/proposal
![image](https://user-images.githubusercontent.com/18567511/97289181-8521cd00-184f-11eb-989f-1836252161e2.png)

**Comment by ivanromakh** [comment]
@aromakh 
![image](https://user-images.githubusercontent.com/18567511/97289237-98349d00-184f-11eb-86b4-56449d2c04e3.png)

**Comment by scholar6admin** [comment]
This should now be resolved
