### ISSUE TITLE
Unauthenticated user - text tweaks

### ISSUE THREAD

**Issue by scholar6admin** [Scholar-6/brillder#2155]
<img width="1179" alt="Screenshot 2020-10-27 at 11 19 40" src="https://user-images.githubusercontent.com/59654112/97288583-52bfa200-1846-11eb-9fb5-dabbf93ff92c.png">

- [x] Cool :) some small tweaks:

increase space between 'Welcome to Brillder' and first paragraph, and between first paragraph and second paragraph

- [x] let's add a typewriter animation to this :)

**Comment by ivanromakh** [comment]
@SashaScholar6 
![image](https://user-images.githubusercontent.com/18567511/97295213-abe40180-1857-11eb-80da-7c2622c37091.png)

**Comment by SashaScholar6** [comment]
Cool :) some small tweaks:

1. increase space between 'Welcome to Brillder' and first paragraph, and between first paragraph and second paragraph
2. let's add a typewriter animation to this :)
