### ISSUE TITLE
Mobile font size and cutoffs

### ISSUE THREAD

**Issue by SashaScholar6** [Scholar-6/brillder#2188]
- [x] Pair Match - answers tiny, should be same as regular text

- [x] categorise font bigger, like reg text

- [x] cut off at bottom of screen not before, and enough margin so that next previous buttons don't overlap text

**Comment by farman9849** [comment]
@SashaScholar6 can you send me a particular account where I can see this brick and fix issues

**Comment by SashaScholar6** [comment]
@farman9849 https://brillder.scholar6.org/play/brick/132/intro

**Comment by SashaScholar6** [comment]
@farman9849 seems a general problem for the above answer types, particular 
brick link above

**Comment by farman9849** [comment]
I need access to this brick, it's just showing a loading screen, please provide credentials
