### ISSUE TITLE
Make comment notifications clickable

### ISSUE THREAD

**Issue by SashaScholar6** [Scholar-6/brillder#2189]
<img width="526" alt="Screenshot 2020-10-24 at 15 56 28" src="https://user-images.githubusercontent.com/59654112/97084023-5cfa5a00-1614-11eb-875c-fb433fb6b6eb.png">

- [x] Take user to appropriate question panel, with comment panel already OPEN

**Comment by ivanromakh** [comment]
@SashaScholar6 oval comments are clickable
![image](https://user-images.githubusercontent.com/18567511/97296192-003bb100-1859-11eb-9f6a-40a4cd7cab05.png)

**Comment by SashaScholar6** [comment]
@ivanromakh Thank you - but should all be circles (not stretched) and clickable
