### ISSUE TITLE
Create open question on proforma page

### ISSUE THREAD

**Issue by scholar6admin** [Scholar-6/brillder#22]
We need to create another field on the proforma page. 

Backend
Field called: 'Open Question'

- [x] Brick Table
- [x] Swagger
- [x] Backend API 
- [ ] Front end

![image](https://user-images.githubusercontent.com/58778078/73271170-01f81b80-41d8-11ea-964d-f1a123a7e787.png)

**Comment by ivanromakh** [comment]
@scholar6admin need default text for this field (which is grey)
![image](https://user-images.githubusercontent.com/18567511/74165257-88c3e400-4c2d-11ea-9d27-944d894ca3ac.png)
