### ISSUE TITLE
Isaac Ticket #140: Image from text component stretching on phone - should be fixed width, same padding right and left

### ISSUE THREAD

**Issue by SashaScholar6** [Scholar-6/brillder#2246]
<img width="1059" alt="Screenshot 2020-10-28 at 15 45 21" src="https://user-images.githubusercontent.com/59654112/97452282-dce63400-1934-11eb-8636-3efd148c0fa0.png">

**Comment by ivanromakh** [comment]
@SashaScholar6 how did you added image there?
