### ISSUE TITLE
Comment panel tweaks 2

### ISSUE THREAD

**Issue by SashaScholar6** [Scholar-6/brillder#2251]
- [x] add grey border/overlay when suggestion box is expanding so the below doesn't happen

<img width="319" alt="Screenshot 2020-10-28 at 17 40 27" src="https://user-images.githubusercontent.com/59654112/97467666-b8925380-1944-11eb-969d-0c9cd78c7639.png">

**Comment by ivanromakh** [comment]
@SashaScholar6 I need example is it present anywhere in current site or image?

**Comment by SashaScholar6** [comment]
@ivanromakh everywhere in build and plan book
