### ISSUE TITLE
Disable Landscape/rotating on phone

### ISSUE THREAD

**Issue by SashaScholar6** [Scholar-6/brillder#2269]
<img width="373" alt="Screenshot 2020-11-03 at 12 12 30" src="https://user-images.githubusercontent.com/59654112/97978470-e3a9f680-1dcd-11eb-9c2c-60520d8a54be.png">

- [x] Brandon BOLD: We think it will be easier to take in information with your device upright.

- [x] feather rotate-ccw and smartphone

**Comment by ivanromakh** [comment]
Screen can be locked only when window is full screen. And fullscreen can be made only by user.
![image](https://user-images.githubusercontent.com/18567511/97976631-9cbeff80-1dd3-11eb-9ce3-34b3498eb231.png)
