### ISSUE TITLE
Animate tab expansion when clicking between tabs so transition is smoother

### ISSUE THREAD

**Issue by SashaScholar6** [Scholar-6/brillder#2272]
![Kapture 2020-10-29 at 16 08 17](https://user-images.githubusercontent.com/59654112/97592546-0f5d6300-1a01-11eb-8eb1-ce90606e8c63.gif)

**Comment by ivanromakh** [comment]
@SashaScholar6 this will be hard for CPU we will need to show more ck-editors. its already slow. need some refactoring before doing this.
