### ISSUE TITLE
Mobile: show teachers teacheer options in homepage and dropdowns

### ISSUE THREAD

**Issue by SashaScholar6** [Scholar-6/brillder#2298]
- [x] not seeing Manage Classes in homepage?

**Comment by ivanromakh** [comment]
@SashaScholar6 maybe you are admin
![image](https://user-images.githubusercontent.com/18567511/98021906-9483b600-1e0d-11eb-8921-9206b850c3c1.png)

**Comment by SashaScholar6** [comment]
@ivanromakh ah, I am, yes, ok - would still like to see manage classes as admin as I do on desktop (am teacher and admin atm)
