### ISSUE TITLE
Block/Hide start building in Mobile dropdown

### ISSUE THREAD

**Issue by SashaScholar6** [Scholar-6/brillder#2299]

**Comment by ivanromakh** [comment]
@william-gooch I think the best way to add me something to user object to detect if user can go to build page or not. becouse it is used each page.

**Comment by william-gooch** [comment]
@scholar6admin @ivanromakh Do you think it's a good idea to use the unused Student and Builder roles for this maybe?
I.E. the student role is assigned when you play a brick for the first time, allowing you to Start Building. Then once you finish building a brick, the builder role is assigned, allowing you to access Back to Work?
