### ISSUE TITLE
Mobile: Back to Work updates

### ISSUE THREAD

**Issue by SashaScholar6** [Scholar-6/brillder#2300]
- [x] make LEARN bold all caps

- [x] pending publication in Learn?

![Screenshot 2020-11-03 at 17 54 42](https://user-images.githubusercontent.com/59654112/98015946-a9584d80-1dfd-11eb-9b1d-33d2da2a99c9.png)

**Comment by ivanromakh** [comment]
@SashaScholar6 not sure where teacher tab should be.

**Comment by ivanromakh** [comment]
@SashaScholar6  in mobile

**Comment by ivanromakh** [comment]
![image](https://user-images.githubusercontent.com/18567511/98010934-f3423300-1dff-11eb-8cb0-9da1741b6926.png)

**Comment by SashaScholar6** [comment]
@ivanromakh nice work - but how come pending publication circles in Learn?

**Comment by ivanromakh** [comment]
@SashaScholar6 its not pending publication its submited to teacher. but colors changed not sure why will fix it.
