### ISSUE TITLE
Mobile: if I click on icon either side of the one in the middle, bring that icon to the middle

### ISSUE THREAD

**Issue by SashaScholar6** [Scholar-6/brillder#2302]

**Comment by ivanromakh** [comment]
@SashaScholar6 need more description

**Comment by SashaScholar6** [comment]
@ivanromakh at the moment if I click on an icon not in the middle (eg View All, Back to Work) nothing happens because of scroll wheel. Want to keep scroll wheel, just make it so clicking brings them to the middle of the screen and therefore then clickable a second time to get to where you wanted.
