### ISSUE TITLE
Add User Preference Indicator to profile page

### ISSUE THREAD

**Issue by SashaScholar6** [Scholar-6/brillder#2309]
<img width="720" alt="Screenshot 2020-11-05 at 15 30 49" src="https://user-images.githubusercontent.com/59654112/98253907-e9ddd580-1f7b-11eb-985d-58691c0870df.png">

- [ ] should work the same way as onboarding user pref page

<img width="305" alt="Screenshot 2020-11-05 at 15 31 45" src="https://user-images.githubusercontent.com/59654112/98253990-0548e080-1f7c-11eb-8a67-1586efb81a62.png">

**Comment by ivanromakh** [comment]
@william-gooch it is security issue better to fix it in backend. Request name is https://dev-api.scholar6.org/classrooms/students.
