### ISSUE TITLE
Hover Areas 

### ISSUE THREAD

**Issue by SashaScholar6** [Scholar-6/brillder#2323]
- [ ] move transparent circle slightly so opaque circle is centred

<img width="270" alt="Screenshot 2020-11-09 at 15 54 07" src="https://user-images.githubusercontent.com/59654112/98556860-ced4d380-22a3-11eb-9648-5e217178d5e5.png">

**Comment by ivanromakh** [comment]
@SashaScholar6 they are complete circles.
