### ISSUE TITLE
When brick is valid, Admin should have all four options in build as clickable

### ISSUE THREAD

**Issue by SashaScholar6** [Scholar-6/brillder#2333]
<img width="1313" alt="Screenshot 2020-11-05 at 18 08 59" src="https://user-images.githubusercontent.com/59654112/98273402-83b07d00-1f92-11eb-9d80-a0b181db81c8.png">

**Comment by ivanromakh** [comment]
@SashaScholar6 what do you mean by this? It depends on status of brick. if status is draft you can`t return brick to author as it is already on author
