### ISSUE TITLE
Search display bug

### ISSUE THREAD

**Issue by SashaScholar6** [Scholar-6/brillder#2339]
<img width="1780" alt="Screenshot 2020-11-06 at 23 35 53" src="https://user-images.githubusercontent.com/59654112/98421099-e421e600-2088-11eb-8c1d-8e168c6bce16.png">

**Comment by ivanromakh** [comment]
@SashaScholar6  need more details can`t reporoduce it 
![image](https://user-images.githubusercontent.com/18567511/98527125-4c3c1c00-2283-11eb-8992-2e453b736c40.png)
