### ISSUE TITLE
Campbell #180 Issues saving with unicode greek characters.

### ISSUE THREAD

**Issue by SashaScholar6** [Scholar-6/brillder#2340]
![image](https://user-images.githubusercontent.com/40644139/99239061-6ed5b400-27f2-11eb-8c35-128e1b97c22d.png)

**Comment by william-gooch** [comment]
@aromakh needs to add 
```TYPEORM_DRIVER_EXTRA='{"charset":"utf8mb4_unicode_ci"}'```
to environment variables.
