### ISSUE TITLE
Make filters work for user management screen

### ISSUE THREAD

**Issue by SashaScholar6** [Scholar-6/brillder#2347]
<img width="1574" alt="Screenshot 2020-11-09 at 15 32 22" src="https://user-images.githubusercontent.com/59654112/98554441-ffffd480-22a0-11eb-9d67-2f27e349c8ae.png">

- [x] role

- [x] subject

- [x] role and subject

- [x] numbers in sidebar should be numbers of users per subject/role (not number of bricks)

**Comment by ivanromakh** [comment]
@william-gooch need amount of users assigned to brick. maybe different method like /subjects/byUser
Don`t need bricksCount or publishedBricksCount here.
![image](https://user-images.githubusercontent.com/18567511/99258938-f25ac980-2821-11eb-91d5-774030c1d788.png)

**Comment by ivanromakh** [comment]
@SashaScholar6 should I remove these numbers. they don`t make any sense now.
![image](https://user-images.githubusercontent.com/18567511/99259240-61d0b900-2822-11eb-89cd-45599ac7a48f.png)

**Comment by ivanromakh** [comment]
@SashaScholar6 filters should work. why this task was moved back in front end?
