### ISSUE TITLE
Send to Publisher notification should have send icon in circle (not message)

### ISSUE THREAD

**Issue by SashaScholar6** [Scholar-6/brillder#2351]
- [x] change icon

- [x] icon should be same thickness as others (thicker)

<img width="551" alt="Screenshot 2020-11-11 at 17 41 10" src="https://user-images.githubusercontent.com/59654112/98838843-1777c280-2445-11eb-8193-521b70db5805.png">

**Comment by ivanromakh** [comment]
@SashaScholar6 I have send icon in circle
![image](https://user-images.githubusercontent.com/18567511/98669089-88da4700-2359-11eb-83e3-cf7423f47c7f.png)
in which page is it?
