### ISSUE TITLE
Intro page updates

### ISSUE THREAD

**Issue by SashaScholar6** [Scholar-6/brillder#2352]
<img width="709" alt="Screenshot 2020-11-10 at 12 50 40" src="https://user-images.githubusercontent.com/59654112/98670773-7e1cb380-2353-11eb-9084-2b39feaae626.png">

- [x] keep subject circle fixed

- [x] make brick title black not bold

- [x] change 'Brief' and 'Prep' to 2.4 vw (smaller)

**Comment by ivanromakh** [comment]
@SashaScholar6 what do you mean by fixed subject circle?
