### ISSUE TITLE
Desktop Pair Match: if image input, output in play should limit sizing (much smaller than screenshot)

### ISSUE THREAD

**Issue by SashaScholar6** [Scholar-6/brillder#2355]
<img width="833" alt="Screenshot 2020-11-10 at 16 33 34" src="https://user-images.githubusercontent.com/59654112/98695201-a9fb6180-2372-11eb-9898-ccbb3e2e9f7a.png">

**Comment by ivanromakh** [comment]
@SashaScholar6 you mean I need to limit height for desktop?

**Comment by ivanromakh** [comment]
@SashaScholar6 max height for images are now 30% of screen height
