### ISSUE TITLE
Add Submit/Publish button at end of Play Preview (see notes for link and details)

### ISSUE THREAD

**Issue by SashaScholar6** [Scholar-6/brillder#236]
Something like animation below, but with Brandon Grotesque Black - same specs as 'Review and Submit' button

https://www.pinterest.fr/pin/818810775989897410/

<img width="957" alt="Screenshot 2020-04-05 at 13 35 04" src="https://user-images.githubusercontent.com/59654112/78473610-4ce75f80-7742-11ea-8268-08dde4a8f70d.png">

**Comment by ivanromakh** [comment]
@SashaScholar6. In which page this button should show up?
