### ISSUE TITLE
When I search in personal tab, hover areas do not match so can't access brick I'd like to access

### ISSUE THREAD

**Issue by SashaScholar6** [Scholar-6/brillder#2361]
![Kapture 2020-11-10 at 18 25 40](https://user-images.githubusercontent.com/59654112/98709258-71638400-2382-11eb-95d3-69ddf0df18d0.gif)

- [x] stay on same screen while searching (not blue loading)

**Comment by ivanromakh** [comment]
@SashaScholar6 can`t reproduce it
