### ISSUE TITLE
Microinteractions and titles

### ISSUE THREAD

**Issue by SashaScholar6** [Scholar-6/brillder#2371]
**BUILD TABS**

- [x] change colour of tabs of hover

- [x] make numbers a bit thicker on hover (simultaneous with colour change)

- [x] make '+' and synthesis icons a bit thicker on hover (simultaneous with colour change)

- [x] make 'x' red and a bit thicker thicker on hover

- [x] make undo redo rotation smoother

- [x] when hover over comment circle, add 50 % circle behind (like for bricks) in same colour as circle - either e5e8ed, amber or red

- [x] if comment present in circle, show title 'View Comment' or 'View Comments' if more than one

**Comment by ivanromakh** [comment]
@SashaScholar6 I don`t have colors.

**Comment by SashaScholar6** [comment]
You mean for tabs? Was thinking something a bit lighter. Try F5F6F7 as we are already using it elsewhere
