### ISSUE TITLE
Book fixes

### ISSUE THREAD

**Issue by SashaScholar6** [Scholar-6/brillder#2383]
- [x] restore hover out to close book

<img width="1498" alt="Screenshot 2020-11-13 at 11 02 45" src="https://user-images.githubusercontent.com/59654112/99060889-03e16e80-25a1-11eb-8b08-237ae467fd95.png">

- [x] add margin on right-hand side of prep

- [x] Open Question should be in Italics and smaller

<img width="802" alt="Screenshot 2020-11-13 at 11 06 26" src="https://user-images.githubusercontent.com/59654112/99060957-1c518900-25a1-11eb-8545-f46118ef88e5.png">

<img width="803" alt="Screenshot 2020-11-13 at 11 06 35" src="https://user-images.githubusercontent.com/59654112/99060962-1fe51000-25a1-11eb-9374-fa221fd01641.png">

- [x] make word and line highlighting smaller in book, same as reg text

<img width="816" alt="Screenshot 2020-11-13 at 11 06 56" src="https://user-images.githubusercontent.com/59654112/99061017-34290d00-25a1-11eb-8065-d792a6ed682a.png">

- [x] blockquote grey vertical line should also show in book

- [x] make 'Synthesis' title text bigger (same size as 'My Answers')

<img width="765" alt="Screenshot 2020-11-13 at 11 07 47" src="https://user-images.githubusercontent.com/59654112/99061054-430fbf80-25a1-11eb-8ae7-755801596b00.png">

- [x] increase spacing a little bit between green play button and play again

- [x] make play again text a tiny bit smaller

- [x] add green 0.5 transparent circle on hover (like with subject circles)

**Comment by ivanromakh** [comment]
@SashaScholar6 Synthesis and My Answers have same size
