### ISSUE TITLE
Drag and drop of component onto panel

### ISSUE THREAD

**Issue by scholar6admin** [Scholar-6/brillder#24]
![image](https://user-images.githubusercontent.com/58778078/73440875-ff1d3800-4349-11ea-9c46-16affa3494d0.png)

Something like that.

**Comment by ivanromakh** [comment]
![image](https://user-images.githubusercontent.com/18567511/73463282-a9668100-4385-11ea-9c32-324eb127ddbd.png)

**Comment by ivanromakh** [comment]
![image](https://user-images.githubusercontent.com/18567511/73463347-c8651300-4385-11ea-96ae-de0ce8c7eeec.png)
