### ISSUE TITLE
Create page for legal text

### ISSUE THREAD

**Issue by scholar6admin** [Scholar-6/brillder#2418]
Replace 'Privacy' button at bottom with
Terms & Conditions

Create a single public route 
/terms

This route uses the following template and parses a markdown file (not included in the repository) using a library such as 
https://github.com/markedjs/marked to parse the markdown. 

The headers in the markdown file become options on the left sidebar

<img width="1797" alt="Screenshot 2020-11-17 at 17 10 49" src="https://user-images.githubusercontent.com/59654112/99415287-efcaa380-28f7-11eb-80b6-7a84032ba689.png">

<img width="1689" alt="Screenshot 2020-12-01 at 14 26 05" src="https://user-images.githubusercontent.com/59654112/100746740-67f99480-33e1-11eb-9f0f-29da2a4814a9.png">

- [x] error message

<img width="1413" alt="Screenshot 2020-12-01 at 14 26 17" src="https://user-images.githubusercontent.com/59654112/100746753-6b8d1b80-33e1-11eb-9ef1-7f4ad6d2a911.png">

- [x] bullets mismatching

<img width="1394" alt="Screenshot 2020-12-01 at 14 26 26" src="https://user-images.githubusercontent.com/59654112/100746756-6c25b200-33e1-11eb-8a0b-0ab018c1a72b.png">

- [x] numbers mismatching and duplicating

<img width="1598" alt="Screenshot 2020-12-01 at 14 27 01" src="https://user-images.githubusercontent.com/59654112/100746758-6cbe4880-33e1-11eb-94b7-03bd1118b2c6.png">

- [x] font strange and forces horizontal scroll (should only scroll vertically, font in Brandon

- [x] Sizing and weights of titles should be more consistent

- [x] More titles in sidebar

- [x] Should be white circles not radio buttons

- [x] clicking titles in sidebar ideally takes user to that part of text

**Comment by ivanromakh** [comment]
@scholar6admin what search button in this page do?

**Comment by SashaScholar6** [comment]
@ivanromakh can search within text and redirect to first match

**Comment by scholar6admin** [comment]
@ivanromakh go with that but if its a challenge then we can simply revert to searching isCore:true published bricks.

**Comment by ivanromakh** [comment]
@scholar6admin  I tried the file you give me but there is some warnings in that file.
![image](https://user-images.githubusercontent.com/18567511/100607347-809b7900-3313-11eb-9abf-bb46c969de26.png)

**Comment by ivanromakh** [comment]
@scholar6admin url http://local-brillder.scholar6.org:3000/terms
