### ISSUE TITLE
View all, Back to Work and My library: when subject selected, make heading smaller

### ISSUE THREAD

**Issue by SashaScholar6** [Scholar-6/brillder#2422]
<img width="1334" alt="Screenshot 2020-11-17 at 19 31 35" src="https://user-images.githubusercontent.com/59654112/99432057-f06d3500-290b-11eb-88e5-099deb4e4ef9.png">

- [x] size of 'All Bricks' and 'My Library' should stay the same

- [x] something like screenshot (basically the longest subject should not be cut off by toggle)

- [x] should remain centred heightwise with toggle in view all

- [x] first letter (R), 3 Bricks founnd and circle of first brick should be perfectly aligned

- [x] When Classes clicked, class name should become title

- [x] Add My Library to dropdown options (before View Profile and Logout)

**Comment by ivanromakh** [comment]
@SashaScholar6 what do you mean by 'first letter (R), 3 Bricks founnd and circle of first brick should be perfectly aligned'?
