### ISSUE TITLE
Publish isCore:false bricks to personal library

### ISSUE THREAD

**Issue by scholar6admin** [Scholar-6/brillder#2423]
As a teacher I want to publish my personal bricks to my personal archive without going through the review process. 
In order to share and assign my bricks with my own class and colleagues etc. 

The button should say 'Self Publish'
The brick should then have status=4 but still isCore=false

It should still appear in back to work -> build -> persona tab. 
It should now be accessible as a public route so that it can be shared. 

![image](https://user-images.githubusercontent.com/58778078/99469366-77d19d00-293a-11eb-866d-ecbfc6b11a34.png)
This is what I see at the moment when I try to publish.

**Comment by ivanromakh** [comment]
@SashaScholar6 what should I write here. I removed 'to Core Library' as it doesn`t make sense. Maybe 'to Archive'?

**Comment by ivanromakh** [comment]
@william-gooch as I admin I can self publish but as build can`t make self publish. need backend update
