### ISSUE TITLE
Adapt Brick

### ISSUE THREAD

**Issue by SashaScholar6** [Scholar-6/brillder#2426]
- [x] shouldn't have repeat icon in back to work

- [x] adapt brick button:

dark blue not red, white text

- [x] on hover, make text blue, button e5e8ed

- [x] copy icon a bit thicker to match assign

- [x] assign brick button on hover, red text and white button

**Comment by ivanromakh** [comment]
@william-gooch for copy icon I need some field in brick. can you add it like isCopy. Not sure if we need to save original brickId. Maybe better not bollean but integer like copyBrickId.

**Comment by ivanromakh** [comment]
@SashaScholar6 who should be the author of copied brick?
