### ISSUE TITLE
Glasses icon animation

### ISSUE THREAD

**Issue by SashaScholar6** [Scholar-6/brillder#2434]
<img width="668" alt="Screenshot 2020-11-18 at 15 48 52" src="https://user-images.githubusercontent.com/59654112/99686740-2cc3a100-2a84-11eb-97f2-a9ca59fbeaa2.png">

- [x] on hover, eye appears (feather eye icon filled in white, dark blue circle in the middle

- [x] dark blue circle fade to feather-aperture and aperture icon spins

**Comment by ivanromakh** [comment]
@SashaScholar6 main page layout is hard for me there is a lot of css. hard to comprehend.  there are 4 different layouts. for tablets, laptops, ex wide laptops and apple macbook. apple-macbook seems the biggest of them.

**Comment by ivanromakh** [comment]
@SashaScholar6 can you give me the newest design of main page with classes button for me to not break glasses button.

**Comment by SashaScholar6** [comment]
@ivanromakh let's meet and discuss. mr1
