### ISSUE TITLE
Homepage restructuring

### ISSUE THREAD

**Issue by SashaScholar6** [Scholar-6/brillder#2435]
- [x] current start building becomes 'Build Bricks'

- [x] change route to Back to Work build screen

- [x] rename 'Back to Work' to 'Assignments', point to just learn tab

- [x] after that, split public personal toggle into two tabs for both build and learn

- [x] Pagination bug in Build Personal (second page onwards)

<img width="297" alt="Screenshot 2020-11-26 at 12 07 00" src="https://user-images.githubusercontent.com/59654112/100343620-e5876400-2fdf-11eb-8a80-0233007a846f.png">

**Comment by ivanromakh** [comment]
@SashaScholar6 need design for this. not sure where to place Assignments button
