### ISSUE TITLE
Add basic image interface to all answer types that support images

### ISSUE THREAD

**Issue by SashaScholar6** [Scholar-6/brillder#2458]
- [x] no preview or slider

- [x] all other fields

- [ ] short answer

- [x] choose one, choose several and categorise should have same image input and interface

- [x] add image support for horizontal and vertical shuffle

- [x] pair match

**Comment by ivanromakh** [comment]
@SashaScholar6 how is it going to work with short answer?

**Comment by SashaScholar6** [comment]
Not for short answer - unless you can integrate Google assistant or Alexa!

**Comment by ivanromakh** [comment]
@SashaScholar6 Alexa is for recording sound not images right?
