### ISSUE TITLE
Desktop Play UI

### ISSUE THREAD

**Issue by SashaScholar6** [Scholar-6/brillder#2460]
- [x] make numbers in hvoer go 193366

- [ ] Categorise answers too small (should be same as reg text)

- [x] add margin underneath text component

- [ ] pair match answers on left should be same as reg text

- [x] remove move button from vertical shuffle

**Comment by ivanromakh** [comment]
@SashaScholar6 for me categorise look good
![image](https://user-images.githubusercontent.com/18567511/100243992-22e7e500-2f3f-11eb-9385-1a0cd3deed21.png)

**Comment by SashaScholar6** [comment]
@ivanromakh maybe because it's on 4k monitor? Will check other screens

**Comment by SashaScholar6** [comment]
@ivanromakh so, looks like categorise font fixed rather than responsive

24px reg/16 px categorise in HD monitor and 4K monitor
18px reg/16 px categorise in 2560x1600 mac laptop
