### ISSUE TITLE
Editor Popup

### ISSUE THREAD

**Issue by SashaScholar6** [Scholar-6/brillder#2465]
- [x] when editor invited (after send invite clicked and white popup), screen should update to show chip with new editor

<img width="638" alt="Screenshot 2020-12-17 at 19 41 44" src="https://user-images.githubusercontent.com/59654112/102502048-f8053280-409f-11eb-8a95-72b7c64685d5.png">

- [x] instead of adding new editor to existing, new one has replaced old one (should remain possible to have multiple editors and chips, and the page should reflect what is in editor popup

**Comment by ivanromakh** [comment]
@SashaScholar6 for me editors are updating. maybe it is related to specific role?

**Comment by SashaScholar6** [comment]
Possibly w admin then (pretty sure that's when I saw it). And perhaps publisher and teacher too need checking

**Comment by ivanromakh** [comment]
@SashaScholar6 I detect same issue if I try to invite my self. Seems self invite forbidden.
Seems I need to add validation if invitation failed.

**Comment by ivanromakh** [comment]
@SashaScholar6 if new one will be adding to existing there will be no way to remove editors.

**Comment by ivanromakh** [comment]
@SashaScholar6 I don`t see any problem with adding editors. they are replacing but they are also autofilling in popup too.
![image](https://user-images.githubusercontent.com/18567511/102612221-05223000-4139-11eb-80e4-b43a376f029c.png)
![image](https://user-images.githubusercontent.com/18567511/102612228-081d2080-4139-11eb-98e0-14c29140b2fc.png)
![image](https://user-images.githubusercontent.com/18567511/102612247-0c493e00-4139-11eb-927d-e9df042ce785.png)

**Comment by SashaScholar6** [comment]
@ivanromakh at the moment if Ivan is editor and I invite Sasha, I would expect to see Ivan and Sasha are editing this brick (not just Sasha is editing this brick). This is after invite sent and popup exited, on white screen under submit for review
