### ISSUE TITLE
Sound component in Choose One and Several

### ISSUE THREAD

**Issue by SashaScholar6** [Scholar-6/brillder#2473]
<img width="476" alt="Screenshot 2020-11-27 at 12 06 11" src="https://user-images.githubusercontent.com/59654112/100747463-6086bb00-33e2-11eb-96d8-6b812cc5f93a.png">

SOUND

- [x] make choose one and several taller

- [x] increase margin between each answer

- [x] in popup, make popup e5e8ed and add upload button

- [x] when sound or image inserted, only show sound or image with trash icon - popop 'Delete image?' or 'Delete sound?' - Yes/No

**Comment by ivanromakh** [comment]
@SashaScholar6 need design for this.

**Comment by SashaScholar6** [comment]
![Uploading Screenshot 2020-11-27 at 12.06.11.png…]()

**Comment by SashaScholar6** [comment]
![Uploading Screenshot 2020-11-27 at 12.06.11.png…]()
