### ISSUE TITLE
Glasses in Home and assignment tab

### ISSUE THREAD

**Issue by SashaScholar6** [Scholar-6/brillder#2490]
<img width="528" alt="Screenshot 2020-12-01 at 11 56 12" src="https://user-images.githubusercontent.com/59654112/100731870-40e49800-33cc-11eb-9b8b-2a35b012ec86.png">

- [x] move eyes a bit higher, so like in home screen

<img width="392" alt="Screenshot 2020-12-01 at 11 57 40" src="https://user-images.githubusercontent.com/59654112/100731995-7093a000-33cc-11eb-950b-7b3a60a578ee.png">

- [x] right eye should be slightly more to the right to be centred in glass width

**Comment by ivanromakh** [comment]
@SashaScholar6 probably becouse of forbidden request.

**Comment by ivanromakh** [comment]
@SashaScholar6 some request takes around 4seconds. so delay should be around  4 seconds
![image](https://user-images.githubusercontent.com/18567511/100628254-b00cae80-3330-11eb-9f62-5d0541a8838a.png)

**Comment by ivanromakh** [comment]
@SashaScholar6 request to get subjects in backend side executing too slow not sure why.
