### ISSUE TITLE
Home page icons - basic hover/animation

### ISSUE THREAD

**Issue by SashaScholar6** [Scholar-6/brillder#2495]
BUILD BRICKS

<img width="465" alt="Screenshot 2020-12-01 at 12 02 28" src="https://user-images.githubusercontent.com/59654112/100732867-a5542700-33cd-11eb-83d5-00f36c20c712.png">

- [x] move text a bit lower so same spacing as manage classess and view all bricks

- [x] rotate on hover like elsewhere (10 degress CC I think?)

ASSIGNMENTS

- [x] animate on hover so it seems bricks are stacking from bottom

**Comment by ivanromakh** [comment]
I will try to do it with html tabs as blocks hard to move rect tags inside svg. Animation in svg is too simple for this.
