### ISSUE TITLE
Play Preview: Clicking Prep from Investigation removes answers and causes timer to reset

### ISSUE THREAD

**Issue by SashaScholar6** [Scholar-6/brillder#2505]
- [x] answers should be saved

- [x] timer of investigation should keep going not reset (and include time spent back in Prep section)

**Comment by ivanromakh** [comment]
@SashaScholar6 for me timer is going forward and not reseting

**Comment by ivanromakh** [comment]
@SashaScholar6 answers are also saving

**Comment by SashaScholar6** [comment]
@ivanromakh so I thought, which is why it surprised me.  Must have been play preview - think it would be nice there as well - or was there a reason we opted against?
