### ISSUE TITLE
Add smile to manage classes icon on hover

### ISSUE THREAD

**Issue by SashaScholar6** [Scholar-6/brillder#2519]
<img width="357" alt="Screenshot 2020-12-03 at 14 51 53" src="https://user-images.githubusercontent.com/59654112/101026465-3a465400-3577-11eb-9451-1fa56b6d4712.png">

- [x] move a bit lower

- [x] make left smile 193366 (not dark blue, вибачте)

**Comment by ivanromakh** [comment]
@SashaScholar6 need svg with smile

**Comment by SashaScholar6** [comment]
Sure - but will you still be able to animate from left to right? (Like progress circle essentially)

**Comment by ivanromakh** [comment]
@SashaScholar6 which progress circle?

**Comment by SashaScholar6** [comment]
Provisional and final score

**Comment by ivanromakh** [comment]
@SashaScholar6 I will try.

**Comment by SashaScholar6** [comment]
Better with or without SVG? Thought it might be more feasible without but lmk

**Comment by ivanromakh** [comment]
@SashaScholar6 its just if I have final svg and start svg it will be easier to animate.

**Comment by SashaScholar6** [comment]
Well start will be nothing really. Will send in 10 mins or so when by computer
