### ISSUE TITLE
Work Area Colours

### ISSUE THREAD

**Issue by SashaScholar6** [Scholar-6/brillder#2526]
- [x] Enter question text here, enter answer and enter hint placeholders should be ACACAC

- [x] Sound Icon should be ACACAC default, red on hover

**Comment by ivanromakh** [comment]
@SashaScholar6 sound icon is png can`t animate will change to another png with different color on hover.

**Comment by SashaScholar6** [comment]
@ivanromakh ok will send as svg 1 min
