### ISSUE TITLE
Add superscript and subscript buttons to short answer in play

### ISSUE THREAD

**Issue by SashaScholar6** [Scholar-6/brillder#2527]
- [x] style like in work area, entry panel f5f6f7, button background e5e8ed

![Screenshot 2020-12-04 at 15 46 40](https://user-images.githubusercontent.com/59654112/101177327-fa9b6d00-3647-11eb-8acf-6ad7e553b01b.png)

- [x] fix three dots because of overflow

**Comment by ivanromakh** [comment]
@SashaScholar6 we will need to update validation for this to check superscript and subscript.

**Comment by SashaScholar6** [comment]
@ivanromakh yep, maybe one for @william-gooch
