### ISSUE TITLE
Change black text to dark blue in Assignment tab

### ISSUE THREAD

**Issue by SashaScholar6** [Scholar-6/brillder#2544]
**Change black text to dark blue in Assignment tab**

<img width="1029" alt="Screenshot 2020-12-07 at 11 39 03" src="https://user-images.githubusercontent.com/59654112/101341295-281f2b00-3881-11eb-82a0-2ffeab30b9b3.png">

- [x] class title

- [x] length and assigned date

- [x] number of students

- [x] avg score

red 'X's 

- [ ] should be thicker and a bit smaller in play sidebar and expanded brick (so same thickness and ticks)

**Comment by ivanromakh** [comment]
@SashaScholar6 cant find `red Xs`.
