### ISSUE TITLE
Image and Sound text and style updates

### ISSUE THREAD

**Issue by SashaScholar6** [Scholar-6/brillder#2548]
<img width="411" alt="Screenshot 2020-12-10 at 23 09 52" src="https://user-images.githubusercontent.com/59654112/101836089-0e117100-3b3d-11eb-8c0d-5d45419594a7.png">

- [x] make image component background e5e8ed (not f5f6f7)

- [x] update text to 'Click to Select Image (jpg, png or gif)'

- [x] Can we drag sounds in? If not, update text to just 'Click to Select Sound (_x, y, z_)' - x, y, z = whichever file types we support? (in regular, not italics

**Comment by ivanromakh** [comment]
drag and drop works fine. It should work for all audio types. I checked with (.m4a) format

**Comment by ivanromakh** [comment]
Not sure about which formats we should use. it depends on browser.
![image](https://user-images.githubusercontent.com/18567511/102221778-3b6a7000-3eeb-11eb-96b7-e0deeaa63ad2.png)
