### ISSUE TITLE
Grey text (l2 and timestamp) should be reg not bold

### ISSUE THREAD

**Issue by SashaScholar6** [Scholar-6/brillder#2549]
<img width="423" alt="Screenshot 2020-12-17 at 19 31 49" src="https://user-images.githubusercontent.com/59654112/102500892-9db7a200-409e-11eb-850a-636acf333d9e.png">

- [x] line 2 of notification

- [x] timestamp reg not bold

**Comment by ivanromakh** [comment]
@william-gooch I leave this to you. This text come to me as one sentence. Can you add <span class="date">25th november</span> for date in backend so I can change font based on it.
