### ISSUE TITLE
Can't progress from end of brick in production play

### ISSUE THREAD

**Issue by SashaScholar6** [Scholar-6/brillder#2553]
<img width="1440" alt="Screenshot 2020-12-22 at 14 59 09" src="https://user-images.githubusercontent.com/59654112/102875953-56e2f700-4466-11eb-8d74-5d9c82223eda.png">

**Comment by ivanromakh** [comment]
@aromakh this is backend issue 
https://brillder.scholar6.org/play/brick/256/live
![image](https://user-images.githubusercontent.com/18567511/102989781-e350f080-451e-11eb-8fdc-6654bed56552.png)

![image](https://user-images.githubusercontent.com/18567511/102989758-d6cc9800-451e-11eb-9c68-39a6e32362ae.png)

**Comment by aromakh** [comment]
@lindsaymacvean  issue is related to lack of space on Elasticsearch EC2 instance.
It will be fixed after migration to new VPC.

**Comment by ivanromakh** [comment]
![image](https://user-images.githubusercontent.com/18567511/103358585-9640c180-4abe-11eb-9713-498afdc39bfa.png)

**Comment by aromakh** [comment]
@ivanromakh works fine on new vpc

**Comment by aromakh** [comment]
@SashaScholar6 could you please validate it?)
