### ISSUE TITLE
If I add bio in profile, show profile pic in phone with bio text underneath

### ISSUE THREAD

**Issue by SashaScholar6** [Scholar-6/brillder#2555]
<img width="1420" alt="Screenshot 2020-12-22 at 15 10 36" src="https://user-images.githubusercontent.com/59654112/102877302-55b2c980-4468-11eb-83bd-854dff03e48e.png">

**Comment by ivanromakh** [comment]
@SashaScholar6. You reopened this issue. I don`t see any problem with it. could you add more details.
