### ISSUE TITLE
Add new student button should be only thing on page if there are no existing students.

### ISSUE THREAD

**Issue by SashaScholar6** [Scholar-6/brillder#2564]
<img width="1916" alt="Screenshot 2021-01-05 at 12 10 20" src="https://user-images.githubusercontent.com/59654112/103639713-16e43f80-4f4f-11eb-8c1a-8e7cde5a6fee.png">

- [x] should be same size as previous page, but 'users' icon rather than 'user' - text underneath is 'Invite Students

**Comment by william-gooch** [comment]
@SashaScholar6 which button should show up if there is no classroom selected on the side? For now I have the Invite Tutee button, but if you think that should change let me know.
