### ISSUE TITLE
Password reset option on login

### ISSUE THREAD

**Issue by scholar6admin** [Scholar-6/brillder#2592]
- [x] make the mobile password reset page work (should look as close as possible to mobile email login page)
- [x] Email reset template: 
- [x] <img width="450" alt="Screenshot 2021-07-13 at 13 03 16" src="https://user-images.githubusercontent.com/59654112/125448404-4993e29c-9760-4d68-89c6-1de330088129.png">

- [x] If email is not recognised then show same popup as if the email was recognised.

- [x] If user clicks forgot password without email show popup 'You need to enter an email before clicking this.'
- [x] After user clicks forgot password show popup 'Now check your email for a password reset link.'

- [x] (Backend) After user clicks link in email and enters new password. they should see a popup that says "Your password has been changed successfully."
- [x] Then the user should be logged in immediately
- [x] Popups should look good on mobile

###

Small white text between username and password on email login.

"Forgot password?"

![image](https://user-images.githubusercontent.com/58778078/117147645-5dd32c00-adad-11eb-9712-cc9e5efa8188.png)

**Comment by ivanromakh** [comment]
@aromakh could you update this request so it will return token to resetPassword?http://swagger.scholar6.org/docs/#!/auth/authResetPasswordEmailPOST

**Comment by aromakh** [comment]
@ivanromakh  sure

**Comment by scholar6admin** [comment]
@ivanromakh link is there but not clickable in dev-app

**Comment by ivanromakh** [comment]
@scholar6admin its clickable. it send you email with link to reset password

**Comment by ivanromakh** [comment]
@scholar6admin or I need design for this page.
![image](https://user-images.githubusercontent.com/18567511/117322624-d5c95100-ae96-11eb-85f2-57441fd816bc.png)

**Comment by ivanromakh** [comment]
@scholar6admin I got it. its after he finished reseting password

**Comment by ivanromakh** [comment]
@scholar6admin what if email is not present in database? it is doing nothing currently.
![image](https://user-images.githubusercontent.com/18567511/118805536-b119a400-b8ae-11eb-95fb-68ce8c91010d.png)

**Comment by ivanromakh** [comment]
@aromakh @william-gooch last point if for backend.

After this request you need to log in user or return email.
/auth/changePassword

right now all I got is OK
![image](https://user-images.githubusercontent.com/18567511/118806982-6862ea80-b8b0-11eb-9044-8e3ceb724247.png)

**Comment by ivanromakh** [comment]
@scholar6admin reset password page isn`t working in phones. should we do something about it?
![image](https://user-images.githubusercontent.com/18567511/118807769-63526b00-b8b1-11eb-88fb-1f8f7848b376.png)
