### ISSUE TITLE
Display subjects in order of most bricks first

### ISSUE THREAD

**Issue by SashaScholar6** [Scholar-6/brillder#2594]
<img width="387" alt="Screenshot 2021-01-13 at 17 48 00" src="https://user-images.githubusercontent.com/59654112/104482766-9618e980-55c7-11eb-91ee-d2b184a6cb70.png">

- [x] if a subject has no bricks, do not show '0'

<img width="736" alt="Screenshot 2021-01-13 at 17 51 01" src="https://user-images.githubusercontent.com/59654112/104483008-e85a0a80-55c7-11eb-8abc-c516cd2f8be9.png">

**Comment by ivanromakh** [comment]
@SashaScholar6  what should this button do? Show filters?
![image](https://user-images.githubusercontent.com/18567511/105019101-65fd9a80-5a4e-11eb-8dbc-31e5fee12214.png)

**Comment by SashaScholar6** [comment]
Sorry that's now not needed as we'll show the new subject page there
