### ISSUE TITLE
At end of play - make share one button

### ISSUE THREAD

**Issue by scholar6admin** [Scholar-6/brillder#2596]
Make the language friendlier.

Instead of external/internal

- [x] Final Step page change text to  'Share with a friend or colleague'
- [x] Text should also be clickable
- [x] Icon thicker on hover

![Screenshot 2021-01-19 at 17 56 39](https://user-images.githubusercontent.com/59654112/105067114-afb2a900-5a7f-11eb-92d0-fa5c5f82a0e0.png)

- [x] add tooltips here (same styling as in build) - 'Copy Link' and 'Invite an existing user'

![Screenshot 2021-01-19 at 17 56 58](https://user-images.githubusercontent.com/59654112/105067162-ba6d3e00-5a7f-11eb-8ccf-0bff6496c6a4.png)

- [x] nice :) move icons and tooltips a little bit higher so more space between edge and tooltip

<img width="441" alt="Screenshot 2021-01-21 at 12 20 59" src="https://user-images.githubusercontent.com/59654112/105344441-3c29ac80-5be3-11eb-81e2-2a0f45e0a539.png">

<img width="207" alt="Screenshot 2021-01-21 at 12 22 08" src="https://user-images.githubusercontent.com/59654112/105344482-49469b80-5be3-11eb-8763-192154fc3adc.png">

- [x] change Share Brick hover to avoid confusion - grey e5e8ed background, dark blue text or icon

**Comment by ivanromakh** [comment]
@SashaScholar6 not sure about fourth point in this task

**Comment by SashaScholar6** [comment]
@ivanromakh when hovering over link or user plus icon, tooltip should appear
