### ISSUE TITLE
Add arrows for if classes overflow on Manage Classrooms page.

### ISSUE THREAD

**Issue by william-gooch** [Scholar-6/brillder#2599]
- [x] make buttons width of text (with just enough padding on either side of Class Name)

<img width="1392" alt="Screenshot 2021-02-08 at 15 06 25" src="https://user-images.githubusercontent.com/59654112/107230324-39bab580-6a1f-11eb-941c-7ce83c458b80.png">

<img width="1294" alt="Screenshot 2021-02-10 at 14 38 17" src="https://user-images.githubusercontent.com/59654112/107517162-aa8fd800-6bad-11eb-9db7-6d750ca1bd02.png">

- [x] only show left chevron if applicable and always have first subject in line with other row (more left, so directly above art & design) - nevermind if it goes into namefield- it's unlikely to overlap to 

- [x] make chevrons red on hover
- [x] can we have the last buttons fading opacity rather than being cut off?

<img width="299" alt="Screenshot 2021-02-10 at 17 11 37" src="https://user-images.githubusercontent.com/59654112/107537401-1af52400-6bc3-11eb-8271-f5ca6f184153.png">

- [x] move 'CLASSES' text right so in line with class name shapes

**Comment by ivanromakh** [comment]
@SashaScholar6 I will think about it you should make it in separate task. I don`t have any idea how to do it right now.
![image](https://user-images.githubusercontent.com/18567511/107531953-0a927880-6bc6-11eb-8b9d-ab0fef2a2707.png)

**Comment by ivanromakh** [comment]
Done 8 gradients of colors for last part like bellow hover no hove even not even selected hovered etc:

![image](https://user-images.githubusercontent.com/18567511/107538243-6eb83b00-6bcc-11eb-9ff3-1db06acc60fa.png)
![image](https://user-images.githubusercontent.com/18567511/107538292-7972d000-6bcc-11eb-9ae2-d36bdfa12224.png)
