### ISSUE TITLE
Update play dashboard home

### ISSUE THREAD

**Issue by SashaScholar6** [Scholar-6/brillder#2605]
<img width="1806" alt="Screenshot 2021-01-18 at 14 01 14" src="https://user-images.githubusercontent.com/59654112/104919246-37bc8400-5996-11eb-8119-3cf214f6605b.png">

- [x] shapes get a bit bigger on hover

- [x] hide all sidebar text and buttons for this page for auth user

- [x] keep discover bricks text for unauth but change 'topic' to 'subject'

- [x] hide 'general' and 'current affairs'

**Comment by ivanromakh** [comment]
the number of subjects is not the same as in image. Maybe few new was created
![image](https://user-images.githubusercontent.com/18567511/105051424-68281f00-5a77-11eb-891e-5710de51d935.png)

**Comment by SashaScholar6** [comment]
Yes that's probably right, do they not fit?

**Comment by ivanromakh** [comment]
@aromakh I can`t get subjects for unauthorized user. Can you make this request public?
![image](https://user-images.githubusercontent.com/18567511/105152013-598d4680-5b0f-11eb-8160-5ab9f3d6d72c.png)

**Comment by aromakh** [comment]
@ivanromakh subject are public now.
