### ISSUE TITLE
Reduce hover area so it doesn't overlap

### ISSUE THREAD

**Issue by SashaScholar6** [Scholar-6/brillder#2607]
- [x] grey rounded rectangle background, all pages with hover area

**Comment by ivanromakh** [comment]
![image](https://user-images.githubusercontent.com/18567511/105014848-955dd880-5a49-11eb-9e52-b2e44bc6be23.png)

**Comment by SashaScholar6** [comment]
Morning Ivan, size looks good.

- Round all 4 corners
- Keep subject circle on left
- Remove play icon (instead whole area is clickable)
