### ISSUE TITLE
BUG: tex rendering too large for mobile preview

### ISSUE THREAD

**Issue by scholar6admin** [Scholar-6/brillder#2609]
See this brick question here

![image](https://user-images.githubusercontent.com/58778078/105035718-5e8cc000-5a53-11eb-8220-c5a8e063f411.png)

https://app.brillder.com/build/brick/210/investigation/question-component/28993

**Comment by ivanromakh** [comment]
@SashaScholar6 Should I add scrolling here? from left to right?

**Comment by SashaScholar6** [comment]
@ivanromakh Might not be the best experience for the user, but can try it.  If text was shrunk would user be able to zoom in?

**Comment by SashaScholar6** [comment]
On an actual phone I mean

**Comment by ivanromakh** [comment]
It will zoom whole page not text in box

**Comment by SashaScholar6** [comment]
ok promising, will need to do a few tests on mobile
