### ISSUE TITLE
Filtering and Navigation

### ISSUE THREAD

**Issue by SashaScholar6** [Scholar-6/brillder#2615]
<img width="599" alt="Screenshot 2021-01-21 at 12 30 43" src="https://user-images.githubusercontent.com/59654112/105345373-7c3d5f00-5be4-11eb-94fb-501a8bb6192b.png">

- [x] if **all subjects uselected** (when previously one or more was selected), show all subjects panel, and keep showing sidebar

<img width="1437" alt="Screenshot 2021-01-21 at 12 16 08" src="https://user-images.githubusercontent.com/59654112/105343845-747cbb00-5be2-11eb-885a-8dd8dbe42eca.png">

- [x] If View All clicked, just stack filters of all subjects with bricks, with subject with most bricks at the top

**Comment by ivanromakh** [comment]
@SashaScholar6 I don`t understand first point of task. `if no subject selected, show all subjects panel` isn`t it how it works now?

**Comment by SashaScholar6** [comment]
@ivanromakh not for me at least

I get a jumbled up page with ALL BRICKS as title (like screenshot)

**Comment by ivanromakh** [comment]
I see I need to change Title

**Comment by ivanromakh** [comment]
@SashaScholar6 new functionality will require at least one subject to be selected. and sort by can`t sort filtered bricks by subjects

**Comment by ivanromakh** [comment]
I will need to check it

**Comment by ivanromakh** [comment]
but clicking that radio buttons will do noting, or it should do something?

**Comment by SashaScholar6** [comment]
If it's showing newest first per subject then we can remove that section as popularity is meaningless at the moment (not even sure it works properly?)
