### ISSUE TITLE
student - assignment fixes

### ISSUE THREAD

**Issue by SashaScholar6** [Scholar-6/brillder#2618]
<img width="915" alt="Screenshot 2021-01-28 at 12 36 17" src="https://user-images.githubusercontent.com/59654112/106133384-7952e900-6165-11eb-8609-9faf680a45ab.png">

- [x] Show numbers of bricks assigned per class in sidebar

<img width="925" alt="Screenshot 2021-01-28 at 12 36 23" src="https://user-images.githubusercontent.com/59654112/106133389-7a841600-6165-11eb-9a99-3f68805c7772.png">

- [x] View All should remain the same at the top, being the sum of everything below

- [x] Add hover selector for each class

**Comment by ivanromakh** [comment]
@SashaScholar6 view all can`t be the sum because brick can be assigned to class directly. so number of bricks assigned to class !== view all count
