### ISSUE TITLE
Add academic levels to bricks (and denote on view all bricks)

### ISSUE THREAD

**Issue by scholar6admin** [Scholar-6/brillder#2621]
@aromakh 
- [x] modify /brick/{id} GET POST PUT to handle brick level as an extra field.

@ivanromakh 
- [x] This will be underneath keywords field

<img width="706" alt="Screenshot 2021-01-22 at 16 48 05" src="https://user-images.githubusercontent.com/59654112/105512608-9b65ea80-5cd1-11eb-802c-d27894ea3aeb.png">

- [x] bricks (I, II, III, IV)

<img width="207" alt="Screenshot 2021-01-22 at 16 47 54" src="https://user-images.githubusercontent.com/59654112/105512630-a3258f00-5cd1-11eb-8a24-d4af10bb9e6f.png">

- [x] books: 1-4 bands (lines) at top and bottom

**Comment by ivanromakh** [comment]
@scholar6admin should we add it in proposal as step during brick creation?

**Comment by scholar6admin** [comment]
Lets replace 'sub topic' with a drop down.

**Comment by aromakh** [comment]
@ivanromakh 
done
http://swagger.scholar6.org/docs/#!/brick/bricksGET

**Comment by ivanromakh** [comment]
@SashaScholar6 As I understand it will be select with dropdown. what will be labels for levels (I, II, III, IV)?

**Comment by SashaScholar6** [comment]
Yes, dropdown:

I: Foundation (GCSE equiv.)
II: Core 1 (AS equiv.)
III: Core 2 (A-Level / IB equiv.)
IV: Extension (Oxbridge equiv.)
