### ISSUE TITLE
Sizing and spacing in Play

### ISSUE THREAD

**Issue by SashaScholar6** [Scholar-6/brillder#2622]
<img width="1104" alt="Screenshot 2021-01-21 at 00 23 08" src="https://user-images.githubusercontent.com/59654112/105339950-8c057500-5bdd-11eb-964f-093b1631af99.png">

- [x] bullets and numbering small in work area, phone and play(preview) - should be same size as reg text

- [x] spacing in phone should be same as work area (less)
![Uploading Screenshot 2021-01-21 at 11.46.28.png…]()

**Comment by ivanromakh** [comment]
@SashaScholar6 I just checked it and font size is almost the same. maybe that text was copy pasted from somewhere where font size style was applied. Could you give me link to brick

**Comment by ivanromakh** [comment]
![image](https://user-images.githubusercontent.com/18567511/105374564-883f1600-5c10-11eb-9fc5-ddf2f2535259.png)

**Comment by SashaScholar6** [comment]
@ivanromakh 👌
