### ISSUE TITLE
My Library Update

### ISSUE THREAD

**Issue by SashaScholar6** [Scholar-6/brillder#2623]
<img width="727" alt="Screenshot 2021-01-21 at 11 47 28" src="https://user-images.githubusercontent.com/59654112/105340673-7cd2f700-5bde-11eb-9624-c19414296cb3.png">

- [x] height is last attempt score

- [x] width is dependent on brick length (like first shelf), 20, 40 and 60 mins

- [x] empty grey spaces in shelf are number of published bricks not yet played in that subject (when we have levels, it will be per level)

- [x] tooltip with Subject in bold (l1), Brick title (l2) in reg
- [x] make tooltip background 193366, text white

- [x] @ivanromakh  a very short bar for 0, in the subject colour, bit like here but could be slightly shorter

<img width="193" alt="Screenshot 2021-01-26 at 20 18 39" src="https://user-images.githubusercontent.com/59654112/105893683-aee7bd00-6013-11eb-9f6e-8e143fe39723.png">

- [x] a bit less rounding of books and score

**Comment by ivanromakh** [comment]
@aromakh. I need last attempt score for every brick but better to move it out from brick and place where numberOfAttempts located I mean in root object.

Request POST /play/library.
![image](https://user-images.githubusercontent.com/18567511/105375743-a6594600-5c11-11eb-95a5-5b3d57a4ba32.png)

**Comment by ivanromakh** [comment]
@SashaScholar6 I think for start we will show one subject in each row. 
![image](https://user-images.githubusercontent.com/18567511/105482476-17036f80-5cb1-11eb-8324-95a6f025107a.png)

what white lines mean?
![image](https://user-images.githubusercontent.com/18567511/105482596-43b78700-5cb1-11eb-9cf1-146b3bd7f4b7.png)
How many white lines I should show?

**Comment by SashaScholar6** [comment]
1 subject per row ok :)
Don't worry about lines for now - they will represent difficulty level but need to add that field in front and backend first.

**Comment by ivanromakh** [comment]
@SashaScholar6  I am not sure about grey bricks. If they are in library they should have at least one attempt. so they all should be colorfull if score is not zero.

**Comment by SashaScholar6** [comment]
mr1?

**Comment by ivanromakh** [comment]
@aromakh this is task

**Comment by aromakh** [comment]
> @aromakh. I need last attempt score for every brick but better to move it out from brick and place where numberOfAttempts located I mean in root object.
> 
> Request POST /play/library.
> ![image](https://user-images.githubusercontent.com/18567511/105375743-a6594600-5c11-11eb-95a5-5b3d57a4ba32.png)

Created PR with the reuqested changes.

**Comment by ivanromakh** [comment]
@SashaScholar6 general subject has white color. looks weird.
![image](https://user-images.githubusercontent.com/18567511/105855065-54893500-5ff0-11eb-90bd-4ffea36b0ac8.png)

**Comment by SashaScholar6** [comment]
@ivanromakh coloured books should go from bottom to top - just make general subject dark blue for now

**Comment by ivanromakh** [comment]
@SashaScholar6 right now it is without pagination. it is scrolling now when overflow.
