### ISSUE TITLE
Manage Classes - Student Tab, editing class

### ISSUE THREAD

**Issue by SashaScholar6** [Scholar-6/brillder#2633]
<img width="488" alt="Screenshot 2021-01-22 at 13 53 48" src="https://user-images.githubusercontent.com/59654112/105493128-41592b00-5cb9-11eb-9783-cc0bf8b856c1.png">

- [x] make edit icon dark blue default (100% opacity) and bigger (same size as edit icon next to trash)

<img width="1070" alt="Screenshot 2021-01-25 at 11 31 56" src="https://user-images.githubusercontent.com/59654112/105694211-f6315900-5f00-11eb-8995-38d564c0d222.png">

- [x] give both edit icons, trash icon, add new student icon and chevron next to name red hover colour
- [x] make users icon thinner so same as '0' and 'Selected'
- [x] name chevron should sort student alphabetically by last name
- [x] remove chevron next to 'CLASSES'

**Comment by ivanromakh** [comment]
@SashaScholar6 actually circle is good. Its just when current user don`t have subject he will see white dropdown. he can`t select subject which he doesn`t have.

**Comment by ivanromakh** [comment]
@SashaScholar6 it stays if that subject is one of yours.

**Comment by SashaScholar6** [comment]
ah indeed thx :)

**Comment by ivanromakh** [comment]
@SashaScholar6 which trash icon should go red on hover?
