### ISSUE TITLE
View All not showing student(s) in New Class

### ISSUE THREAD

**Issue by SashaScholar6** [Scholar-6/brillder#2651]
This is still an issue, only in students tab it seems

<img width="1035" alt="Screenshot 2021-01-29 at 11 27 53" src="https://user-images.githubusercontent.com/59654112/106263745-1032aa80-6225-11eb-924e-b9f01445d181.png">

**Comment by ivanromakh** [comment]
@SashaScholar6 I am not sure. there should be 136 students in dev now. In view all.

**Comment by ivanromakh** [comment]
@lindsaymacvean @SashaScholar6  I think we need to update this page. We don`t have student role anymore. and new students will not show up here or when you change role they will not appear here again.

**Comment by ivanromakh** [comment]
@SashaScholar6 this is backend issue. We remove student role and new and updated users will not show up in students list. Leave this to @aromakh.

**Comment by ivanromakh** [comment]
@aromakh update this request

GET /classrooms/students - this request should get users where userPreference === student

**Comment by aromakh** [comment]
@ivanromakh  done

**Comment by ivanromakh** [comment]
@SashaScholar6 you probably don`t have some permision to see users...

**Comment by ivanromakh** [comment]
@aromakh  teacher can`t get users. 
![image](https://user-images.githubusercontent.com/18567511/106267297-1e3af800-6232-11eb-97bf-7d45cc022b82.png)

**Comment by aromakh** [comment]
@ivanromakh should work now.
Let me know if you see any issues.
