### ISSUE TITLE
Brillder Partners Programme Landing Page

### ISSUE THREAD

**Issue by SashaScholar6** [Scholar-6/brillder#2657]
https://xd.adobe.com/view/a8dc464b-4f1e-4c2e-b5c7-0c3e01bacd22-fd8f/

- [x] title in brandon bold
- [x] fix CTA panel and logo while scrolling
- [x] hover states and play circle icon
- [x] Dropdown: less than 1000 students / less than 5000 students / less than 10,000 students/ 10,000+ students

<img width="523" alt="Screenshot 2021-01-26 at 18 11 11" src="https://user-images.githubusercontent.com/59654112/105878930-e0578d00-6001-11eb-849e-0fb3ad72bb26.png">

- [x] Link to dashboard from discover bricks button

- [x] nice :) remove H1 thickness so bold weight is standard (ie thinner)

- [x] body copy - It is perhaps harder...rates / Brillder...classroom etc. in Brandon Light, not Regular

- [x] increase the space a bit betweeen brillder logo and 'Partners Programme'

- [x] Number of students should not be an option, only dropdown placeholder

- [x] move dropdown arrrow more left so not touching the edge of the panel

<img width="478" alt="Screenshot 2021-01-27 at 11 29 48" src="https://user-images.githubusercontent.com/59654112/105978608-06793d80-6093-11eb-805a-34071bd33e03.png">

<img width="491" alt="Screenshot 2021-01-27 at 11 29 36" src="https://user-images.githubusercontent.com/59654112/105978605-05481080-6093-11eb-8169-6622f493d91b.png">

- [x] is background image 10% opacity? If not, should be

- [x] remove three dots from 'Your School Email'
- [x] Validation: if book consultation button clicked and either field is empty, make panel red

<img width="226" alt="Screenshot 2021-01-27 at 18 15 14" src="https://user-images.githubusercontent.com/59654112/106027945-a6eb5400-60cb-11eb-9f65-c1302b4d8c70.png">

- [x] make tab header 'Brillder Bespoke'

<img width="803" alt="Screenshot 2021-01-29 at 16 42 47" src="https://user-images.githubusercontent.com/59654112/106295726-15a5ea00-6251-11eb-9123-6e9bf0e415de.png">

- [x] text below these headings should be smaller, like for What is Brillder paragraph

**Comment by ivanromakh** [comment]
@lindsaymacvean could you create repos for this and brillder.com landing pages.

**Comment by ivanromakh** [comment]
@SashaScholar6 need two icons
![image](https://user-images.githubusercontent.com/18567511/105842741-55fe3180-5fdf-11eb-8140-640600db0ea3.png)

**Comment by SashaScholar6** [comment]
top left 6 shape sent, don't you already have Brillder B shape?

**Comment by ivanromakh** [comment]
@SashaScholar6 done but @aromakh needs to refresh cash in amason service for brillder.com
