### ISSUE TITLE
If no subjects selected / all subjects unselected in 'My Subjects' show me my subjects on the right

### ISSUE THREAD

**Issue by SashaScholar6** [Scholar-6/brillder#2661]
<img width="1916" alt="Screenshot 2021-01-27 at 11 46 03" src="https://user-images.githubusercontent.com/59654112/105980610-5c4ee500-6095-11eb-9df0-39a531219a0e.png">

- [x] ie, like subjects panel, but only showing my subjects

<img width="1060" alt="Screenshot 2021-01-27 at 11 48 24" src="https://user-images.githubusercontent.com/59654112/105980779-9324fb00-6095-11eb-873a-2f761f6f4815.png">

- [x] if I have not selected any subjects in all subjects, I should still be able to click on my subjects tab 

- [x] when I click on a subject, is there a way not to show blue loading page? A smooth transition would be nicer if possible

**Comment by ivanromakh** [comment]
@SashaScholar6 last point will take a lot of time. I can cash data but it could make some bugs later. so it will take time. will do it later.

**Comment by SashaScholar6** [comment]
ok
