### ISSUE TITLE
Notification Panel updates

### ISSUE THREAD

**Issue by SashaScholar6** [Scholar-6/brillder#2663]
- [x] After clicking 'You have X notifications' to show notification panel, I should be able to click again to hide
- [x] Add selector on hover so user knows whole notification is clickable
- [x] make icons in circles 10% bigger on hover
- [x] make up down white scroll arrows dark blue on hover
- [x] same for clear all text and icon (dark blue on hover

- [x] great :) Clear All and x icon should be like one button and hover together

- [x] make x in circle icon bigger

- [x] remove selector when no notifications
- [x] remove bold on hover of no notifications text

**Comment by ivanromakh** [comment]
@SashaScholar6 What do you mean by selector in second point?

**Comment by SashaScholar6** [comment]
@ivanromakh like for sidebar subjects.  I know, but it wasn't obvious enough for Joe as there was no more evident visual change

**Comment by ivanromakh** [comment]
@SashaScholar6  you mean change background color?

**Comment by SashaScholar6** [comment]
<img width="215" alt="Screenshot 2021-01-27 at 15 31 50" src="https://user-images.githubusercontent.com/59654112/106005722-c7f47a80-60b4-11eb-8fec-7defa4b12027.png">

like this

**Comment by ivanromakh** [comment]
ok

**Comment by SashaScholar6** [comment]
:) thank you
