### ISSUE TITLE
Unauthenticated / Authenticated Flow

### ISSUE THREAD

**Issue by SashaScholar6** [Scholar-6/brillder#2665]
- [x] Discover bricks text on on subjects page, then normal sidebar without tabs

- [x] Try one of the following underneath no bricks found options, showing only available subjectss

<img width="1450" alt="Screenshot 2021-01-27 at 15 11 43" src="https://user-images.githubusercontent.com/59654112/106002968-03da1080-60b2-11eb-9747-00df30b281ac.png">

- [x] Cool :) Move subjects lower

- [x] Add ':', so 'Try one of the following:' and move to the centre of the page

<img width="715" alt="Screenshot 2021-01-27 at 15 14 50" src="https://user-images.githubusercontent.com/59654112/106003365-6d5a1f00-60b2-11eb-8905-39e12a94561d.png">

- [x] should show subject panel here

- [x] great :) change 'Try one of the following:' to Regular Italic (not Bold) and move text and subject panels a bit lower still
- [x] When I click one of the other subjects, deselect the one I was one. Eg. I click Chinese and see there are no bricks, so I click on French as suggested.  Heading should then be just French and sidebar should have only French selected

**Comment by ivanromakh** [comment]
@SashaScholar6 don`t understand last screenshot.

**Comment by ivanromakh** [comment]
@SashaScholar6 give me url of last screenshot page.

**Comment by SashaScholar6** [comment]
@ivanromakh neither do I, that's why I'd like it to be subject panel page. maybe has been updated now, one sec

**Comment by SashaScholar6** [comment]
https://dev-app.brillder.com/play/dashboard

ah, that would be why - do we need to clear this maybe, and link subjects to website?

**Comment by ivanromakh** [comment]
@SashaScholar6 Ok I will just make it move to /all-subjects page
