### ISSUE TITLE
Dropdown updates

### ISSUE THREAD

**Issue by SashaScholar6** [Scholar-6/brillder#2666]
<img width="977" alt="Screenshot 2021-01-27 at 13 02 24" src="https://user-images.githubusercontent.com/59654112/105989211-14ce5600-60a1-11eb-97ab-aef8732da51f.png">

- [x] never dropup - instead fix height below to show top three subjects, which is scrollable

- [x] remove 'x' which clears all subjects as easy for users to shoot themselves in the foot

- [x] dropdown arrow should either always work or be hidden - best if it just shows subjects alphabetically below (three visible, scrollable to see more)

- [x] if 'No Options', make text bigger (same as normal size, and change text to 'Sorry, try typing something else'

- [x] font in dropdown should be Brandon regular
<img width="1273" alt="Screenshot 2021-01-27 at 15 16 02" src="https://user-images.githubusercontent.com/59654112/106003558-9b3f6380-60b2-11eb-9ba0-47e5b531015d.png">

**Comment by ivanromakh** [comment]
@SashaScholar6  can`t remove shadow its probably something embeded.
