### ISSUE TITLE
New onboarding screen for all users

### ISSUE THREAD

**Issue by SashaScholar6** [Scholar-6/brillder#2667]
- [x] This screen comes after user preference screen for all new users

<img width="1438" alt="Screenshot 2021-01-27 at 16 41 16" src="https://user-images.githubusercontent.com/59654112/106015224-8c5eae00-60be-11eb-8942-25d1c7d63b82.png">

- [x] Use PP1 (What is it about?) as guideline, and change colours - placement and size of phone and red shape should be exactly the same, only different colours, same for entry panels and rounded lines below

- [x] Red chevron starts 193366, only goes red after first name and last name filled

- [x] get started text also clickable

- [x] if either text or chevron clicked before fields field, make entry panels red

- [x] default phone is just bigger user icon, then shows username once fields filled, like in plan panels

- [x]  add typewriter animation to username

- [x] Get started goes straight to homepage for Students

- [x] generate button before get started, and get started text default bold

**Comment by ivanromakh** [comment]
@SashaScholar6  what will be url of this page? `/user/set-username` ?

**Comment by SashaScholar6** [comment]
What's the URL of the previous page (User Pref)?

**Comment by ivanromakh** [comment]
@SashaScholar6 /user/preference

**Comment by SashaScholar6** [comment]
set-username
