### ISSUE TITLE
Book fixes and library shortcut

### ISSUE THREAD

**Issue by SashaScholar6** [Scholar-6/brillder#2672]
<img width="1450" alt="Screenshot 2021-01-28 at 15 38 46" src="https://user-images.githubusercontent.com/59654112/106153975-677e3f80-617f-11eb-87a7-1cd05d814a51.png">

- [x] superscript subscript should not show on cover

<img width="1913" alt="Screenshot 2021-01-28 at 15 40 31" src="https://user-images.githubusercontent.com/59654112/106155884-4c143400-6181-11eb-99ac-382b778b5d2c.png">

- [x] Allow book to close when hovering out as before

<img width="719" alt="Screenshot 2021-01-28 at 15 54 08" src="https://user-images.githubusercontent.com/59654112/106155532-12432d80-6181-11eb-99f5-53130f7e59c4.png">

- [x] Add blue button on left of open book, Brandon bold text - takes user to Library

- [x] hover is opposite colours

<img width="704" alt="Screenshot 2021-01-28 at 16 06 00" src="https://user-images.githubusercontent.com/59654112/106157220-c2656600-6182-11eb-9239-6dc2f2f76bbe.png">

- [x] add hove on attempt text - 50% dark blue

**Comment by ivanromakh** [comment]
@SashaScholar6  what do you mean by `hover is oposite colors`?

**Comment by SashaScholar6** [comment]
@ivanromakh ie. View in my library button background goes white and text blue
