### ISSUE TITLE
Correct Incorrect in book

### ISSUE THREAD

**Issue by SashaScholar6** [Scholar-6/brillder#2675]
<img width="1148" alt="Screenshot 2021-01-28 at 16 30 44" src="https://user-images.githubusercontent.com/59654112/106160926-a794f080-6186-11eb-85af-ce24f62dff41.png">

- [x] incorrect answer marked correct 

<img width="1472" alt="Screenshot 2021-01-28 at 16 31 20" src="https://user-images.githubusercontent.com/59654112/106161012-bf6c7480-6186-11eb-8e9f-e1b16793bb42.png">

- [x] correct showing yellow hint (should be f5f6f7)

<img width="821" alt="Screenshot 2021-01-28 at 16 32 46" src="https://user-images.githubusercontent.com/59654112/106160941-abc10e00-6186-11eb-835d-2e2c3364a38a.png">

- [x] make missing word text smaller in box, same as reg text

- [x] **BUG: If I select eye to view investigation or review in one question, all next questions keep that - I should start every page by not seeing my answers, and then the choice to view either**

**Comment by ivanromakh** [comment]
@SashaScholar6 book is grey. Hint boxes will be invincible.
![image](https://user-images.githubusercontent.com/18567511/106266195-d1a2ed00-6230-11eb-9c45-3e6734385508.png)
