### ISSUE TITLE
Tessa Ticket: Line breaks for highlighting

### ISSUE THREAD

**Issue by SashaScholar6** [Scholar-6/brillder#2680]
- [x] make text for word and line highlighting smaller in phone preview (same as reg text)

- [x] prevent hyphens ('-') from causing line breaks in phone preview

<img width="1361" alt="Screenshot 2021-01-29 at 13 12 43" src="https://user-images.githubusercontent.com/59654112/106274022-e765e180-6233-11eb-885e-5e5509ad4af7.png">
<img width="400" alt="Screenshot 2021-01-29 at 13 16 17" src="https://user-images.githubusercontent.com/59654112/106274194-2e53d700-6234-11eb-9cd4-3456fa38fcc2.png">

Line breaks should be as follows

Fillet of a fenny snake,   
In the cauldron boil and bake;   
Eye of newt, and toe of frog,   
Wool of bat, and tongue of dog,   
Adder’s fork, and blind-worm’s sting,   
Lizard’s leg, and howlet’s wing,   
For a charm of powerful trouble, 
Like a hell-broth boil and bubble.   

<img width="532" alt="Screenshot 2021-01-29 at 13 28 33" src="https://user-images.githubusercontent.com/59654112/106275336-edf55880-6235-11eb-8f73-1757f8418aba.png">

- [x] place highlighter closer to text and remove outer circle, make default highlighter now dark blue

- [x] when I hover on default highlighter, circle appears so hover makes it looks like default currently does - dark blue outer circle, grey/no fill inside

- [x] In popup when when clicked, pink selector should be dark blue

<img width="208" alt="Screenshot 2021-01-29 at 13 34 15" src="https://user-images.githubusercontent.com/59654112/106275775-b044ff80-6236-11eb-9094-62fb5b2a2cc3.png">

- [x] Add a circle to the right of highlighter with 'br' inside

- [x] Default is off - colours: f5f6f7 circle, acacac text

- [x] background of circle goes white on hover

- [x] if 'yes' clicked for line break, circle goes green, text white

- [x] cool make 'br' text bigger, so same as text on left (click the highlighter.....)

**Comment by ivanromakh** [comment]
@SashaScholar6 is it in production or dev? give me a link

**Comment by SashaScholar6** [comment]
@ivanromakh  https://app.brillder.com/build/brick/417/investigation/question-component/81488

**Comment by SashaScholar6** [comment]
Question 3

**Comment by ivanromakh** [comment]
@SashaScholar6 I don`t understand last 4 points in task. about colors.
