### ISSUE TITLE
Brick should only be able to be assigned to any one class once, not multiple times

### ISSUE THREAD

**Issue by SashaScholar6** [Scholar-6/brillder#2687]

**Comment by aromakh** [comment]
@ivanromakh 
Currently when teacher assign brick to stuned/classroom which is already assigned, existing assignment will be returned in response.

@SashaScholar6  
If brick has assignements to student and classroom of that student, brick will be displayed twice when View All option is selected. Please ask Ivan to remove  duplicates at FrontEnd if needed.

**Comment by aromakh** [comment]
@ivanromakh 
Could you please display message for the existing assignments?

'You have already assigned "Brick Title" to "Student Name"

**Comment by ivanromakh** [comment]
@aromakh this is not working yet I was able to invite the same student by teacher to class few times.

**Comment by ivanromakh** [comment]
![image](https://user-images.githubusercontent.com/18567511/106877656-ae20ec00-66e1-11eb-8459-c42b110780b3.png)

**Comment by ivanromakh** [comment]
@aromakh its working for view all bricks.
