### ISSUE TITLE
Library - what to show and how

### ISSUE THREAD

**Issue by SashaScholar6** [Scholar-6/brillder#2688]
- [x] Assigned - public - completed (100% opacity, height from score)
- [x] Assigned - adapted - completed (100% opacity, height from score)
- [x] Assigned - created from scratch by teacher completed (100% opacity, height from score)

- [x] Assigned - not yet completed (grey space)

- [x] Not assigned - public - completed completed (100% opacity, height from score)

**Comment by scholar6admin** [comment]
I cannot test this while I am being blocked from accessing the library. I think changes being made by @aromakh will resolve this.
