### ISSUE TITLE
Fix homepage display bug

### ISSUE THREAD

**Issue by SashaScholar6** [Scholar-6/brillder#2692]
<img width="674" alt="Screenshot 2021-02-02 at 12 31 50" src="https://user-images.githubusercontent.com/59654112/106594640-ac74ee00-6552-11eb-9bb8-8d328dc7b3c2.png">

- [ ] picture error
- [ ] text error

**Comment by ivanromakh** [comment]
@SashaScholar6 Andriy was working on images can you check it now?
