### ISSUE TITLE
Expanded bookshelf with brick titles

### ISSUE THREAD

**Issue by SashaScholar6** [Scholar-6/brillder#2695]
<img width="1089" alt="Screenshot 2021-07-06 at 14 39 11" src="https://user-images.githubusercontent.com/59654112/124609977-05311580-de68-11eb-8a06-6decd4be6342.png">
<img width="1346" alt="Screenshot 2021-07-06 at 14 39 24" src="https://user-images.githubusercontent.com/59654112/124609984-07936f80-de68-11eb-977c-2d0a3820c25d.png">

- [x] @aromakh forget about above. You give me live score. I also need review score to calculate percentages. in example above it is 30.

- [x] Books stay grey unless 50% score
- [x] Grey books with a score <50% have score in text in circle underneath
- [x] Second two bricks here should have bands?
- [x] all bricks should have bands in main library
- [x] @ivanromakh  if brick is adapted by user (has adaptedFromId), then show initials of user who adapted brick

![image](https://user-images.githubusercontent.com/58778078/118290209-11cf6800-b4ce-11eb-9ff0-9f964230bd2a.png)

![image](https://user-images.githubusercontent.com/58778078/118289881-b309ee80-b4cd-11eb-9ce5-2ad9510d5efc.png)

- [x] Font should be centered height and width along spine of book
- [x] Font should be brandon-grotesque-bold
- [x] Greyed out brick should have grey text 
- [x] Book with bands should be same height as others

- [x] Restore library styling from xd design

<img width="1805" alt="Screenshot 2021-02-02 at 15 35 30" src="https://user-images.githubusercontent.com/59654112/106615102-63319800-656c-11eb-9cd8-bd265c057c19.png">

- [x] Title should be very small in white along spine across the colour and the grey background of each book

- [x] @SashaScholar6 please confirm this new spec

- [x] put the titles back, should not overflow the book.
<img width="757" alt="Screenshot 2021-02-03 at 16 08 05" src="https://user-images.githubusercontent.com/59654112/106766312-0e5c5300-663a-11eb-8eb4-47915a91e028.png">

![image](https://user-images.githubusercontent.com/58778078/116681277-ad2bed80-a9a4-11eb-8cb0-f9548014de1d.png)

- [x] this happens when subject is clicked in Sidebar

- [x] @aromakh please add adaptedFromId to brick response

- [x] @ivanromakh In expanded view, subject is pretty obvious, so we can remove it from tooltip

**Comment by ivanromakh** [comment]
@aromakh need teacher name in this request
/play/library

**Comment by ivanromakh** [comment]
@aromakh the best if it will be in root object as there could be multiple assignments.
![image](https://user-images.githubusercontent.com/18567511/106735580-1bb71480-661d-11eb-8ad0-e0173661a028.png)

**Comment by ivanromakh** [comment]
@SashaScholar6 what if few teachers assigned the same brick?

**Comment by SashaScholar6** [comment]
@ivanromakh Initials should be from whichever teacher has created or adapted a brick. Do you mean to the same student?

**Comment by ivanromakh** [comment]
@SashaScholar6 somehow finished text rotations. 
![image](https://user-images.githubusercontent.com/18567511/106758603-5ed3b080-663a-11eb-8ca6-cc645300455e.png)

**Comment by SashaScholar6** [comment]
@ivanromakh great thank you. For grey uncompleted, can we have text starting from the bottom, with some padding, like design rather than centred?

**Comment by aromakh** [comment]
@ivanromakh 
Added techers to assignments.

![image](https://user-images.githubusercontent.com/7169477/109671705-fca89580-7b7c-11eb-9f94-27c99473ee79.png)

**Comment by ivanromakh** [comment]
I don`t have teacher here.
![image](https://user-images.githubusercontent.com/18567511/116695384-39500c00-a9c9-11eb-9d68-b05d678607f7.png)

**Comment by ivanromakh** [comment]
@scholar6admin I don`t understand this.
![image](https://user-images.githubusercontent.com/18567511/117444734-893b4f80-af42-11eb-8ef4-2905e06945b2.png)

**Comment by aromakh** [comment]
@ivanromakh  I added adaptedFrom object to the response, if brick was adapted.

**Comment by ivanromakh** [comment]
@aromakh backend error maybe user is too old.  email: lindsaymacvean+student2@scholar6.org password password.
url: /my-library
![image](https://user-images.githubusercontent.com/18567511/118831724-aec44380-b8c8-11eb-98da-799db636c0b5.png)

**Comment by ivanromakh** [comment]
@SashaScholar6 do you see level 4 bangs it is imposible to show them everywhere. they should have at least 40% result to show them.
![image](https://user-images.githubusercontent.com/18567511/118833852-76be0000-b8ca-11eb-8d03-9ad4544fd2b0.png)

**Comment by ivanromakh** [comment]
@SashaScholar6 this is how level2 look like when it is score is 28%.
![image](https://user-images.githubusercontent.com/18567511/118834166-b08f0680-b8ca-11eb-806c-e8be21b177b6.png)

**Comment by ivanromakh** [comment]
@aromakh there is something wrong with this. It should be 34%. but in response it gives me 28%.
![image](https://user-images.githubusercontent.com/18567511/118835086-5c385680-b8cb-11eb-830b-68d1497962d4.png)


As I understand there is review live and max score. I need third one like here which is 30. 
![image](https://user-images.githubusercontent.com/18567511/118835469-b3d6c200-b8cb-11eb-9d74-b6e709aa679e.png)

**Comment by ivanromakh** [comment]
@aromakh forget about above. You give me live score. I also need review score to calculate percentages. 
![image](https://user-images.githubusercontent.com/18567511/118835948-1def6700-b8cc-11eb-937a-63a18eaa808b.png)

**Comment by william-gooch** [comment]
@ivanromakh endpoint now returns the total percent score, and the live score in case that needs to be used as well.

**Comment by ivanromakh** [comment]
@SashaScholar6 I need some more info about this. Where exactly score it should be? In popup on hover?
![image](https://user-images.githubusercontent.com/18567511/124599326-3876a300-de6e-11eb-9a8f-cbf1f3599760.png)
