### ISSUE TITLE
When I invite new users to a class, show pending users

### ISSUE THREAD

**Issue by SashaScholar6** [Scholar-6/brillder#2697]
Otherwise it looks like invitation process hasn't worked

<img width="1462" alt="Screenshot 2021-02-02 at 16 16 21" src="https://user-images.githubusercontent.com/59654112/106620800-37191580-6572-11eb-8ea0-0ad82a438d4c.png">

- [x] Show pending users in alternating 100% yellow and 50% yellow bars (instead of grey and white) - write 'Pending' in Classes column

**Comment by aromakh** [comment]
@ivanromakh 
I added studentsInvitations array to responce.
