### ISSUE TITLE
#Ticket 220  (Toby) suggested time does not change when changing the duration of the brick

### ISSUE THREAD

**Issue by scholar6admin** [Scholar-6/brillder#2698]
https://app.brillder.com/play-preview/brick/374/review

This brick was changed from 20 to 40 minutes
The suggested time for review is not updated in the text (but it is updated in the timer when you click to review)
![image](https://user-images.githubusercontent.com/58778078/106622636-b2c39400-656b-11eb-8926-e07db970ddb0.png)

**Comment by ivanromakh** [comment]
@SashaScholar6 3 minutes are same for every brick. Its just part of text. What should be there?

**Comment by ivanromakh** [comment]
@SashaScholar6 Aim to spend `8` minutes on this section. here 8 could be 4, 8 and 12 depends on the length of brick.
