### ISSUE TITLE
Style Onboarding Terms more like Privacy Policy lightbox

### ISSUE THREAD

**Issue by SashaScholar6** [Scholar-6/brillder#2700]
Onboarding terms page - after user preferences on signup - is not very user friendly.

<img width="1911" alt="Screenshot 2021-02-03 at 10 57 43" src="https://user-images.githubusercontent.com/59654112/106730244-a6444780-660e-11eb-8ba1-432bf4bd8ce7.png">

- [x] Mirror the User preferences white dialogue box, and style text like Privacy Policy - bold red heading, dark blue regular text (all same size)

<img width="1410" alt="Screenshot 2021-02-03 at 10 52 41" src="https://user-images.githubusercontent.com/59654112/106730161-9167b400-660e-11eb-8f70-a20bf6f5697c.png">

- [x] Not a lightbox, so user cannot exit - Agree checkbox is outside box and must be clicked for user to proceed

- [x] Fixed green bar at the bottom of window to agree (like notifications clear all)

**Comment by ivanromakh** [comment]
@SashaScholar6 I am not sure about the second point. I need to add checkbox in Privacy Policy popup?
