### ISSUE TITLE
Subjects onboarding page if Builder preference selected

### ISSUE THREAD

**Issue by SashaScholar6** [Scholar-6/brillder#2701]
<img width="1438" alt="Screenshot 2021-02-03 at 12 59 40" src="https://user-images.githubusercontent.com/59654112/106745119-f4624680-6620-11eb-999a-70c6f7637d75.png">

This screen is after set-username

- [x] white if subject selected, next button to proceed.  

- [x] For teachers, text in title becomes 'teach' instead of 'build'

**Comment by ivanromakh** [comment]
@SashaScholar6 no home button, menu or sidebars right?

**Comment by ivanromakh** [comment]
@SashaScholar6 what should be the url of page. /dashboard/select-subject ?
