### ISSUE TITLE
Profile page updates

### ISSUE THREAD

**Issue by SashaScholar6** [Scholar-6/brillder#2704]
- [x] make save button bigger and fixed so it floats
- [x] Add Intro js popup saying 'Click here to save changes'

**Comment by ivanromakh** [comment]
@SashaScholar6 button start pulsing after all fields filled. it should be always pulsing?
![image](https://user-images.githubusercontent.com/18567511/106770654-dc052280-6646-11eb-8c24-d44d72bea55f.png)
