### ISSUE TITLE
My Highlight or unhighlight as teacher appearing on all bricks

### ISSUE THREAD

**Issue by SashaScholar6** [Scholar-6/brillder#2705]
<img width="937" alt="Screenshot 2021-02-04 at 10 14 19" src="https://user-images.githubusercontent.com/59654112/106871054-1798fe80-66d2-11eb-8e7b-ce9490612d3a.png">

**Comment by william-gooch** [comment]
@SashaScholar6 do you have a consistent way to reproduce this? I can't seem to get it to happen.
