### ISSUE TITLE
Toby Ticket #244: Correct answer marked wrong in review (choose several question)

### ISSUE THREAD

**Issue by SashaScholar6** [Scholar-6/brillder#2706]
https://app.brillder.com/play-preview/brick/407/review

Panel 6 of this brick is not marking as correct even when I select all of the solutions (I've checked repeatedly that I am actually selecting the answers that I've put down as the solutions) - in case the panels shift around, I'm referring to the panel that begins "We can now consider how to solve more complicated equations."
Thanks

https://app.brillder.com/build/brick/407/investigation/question-component/76700

Correct answers 296.6, 180 and 116.6 should be marked correct in review

**Comment by ivanromakh** [comment]
@SashaScholar6 could you activate account ivan@scholar6.org in production and assign me to review that brick

**Comment by SashaScholar6** [comment]
ok, have done that @ivanromakh

**Comment by ivanromakh** [comment]
@william-gooch. Test created and problem detected.
Boolean variable `checked` missing. aditional check added.
![image](https://user-images.githubusercontent.com/18567511/107207436-f9503d00-6a08-11eb-9ae9-8a00d0371673.png)
