### ISSUE TITLE
Profile Page updates

### ISSUE THREAD

**Issue by SashaScholar6** [Scholar-6/brillder#2709]
PASSWORD
- [x] Add Edit icon to password field and tick and cross to confirm or cancel changes

- [ ] if tick clicked, popup is 'Password changed' with green circle and white tick

INTRO JS
- [x] Intro.js: change font to Brandon Regular dark blue
- [x] remove black outline for highlighted area

- [x] first message is 'Hi 'Name', Welcome to your Profile Page!', 'Start Tutorial'

- [x] second: 'Add a picture so that your interactions on the platform are more personal'

Two Options: OK or 'Skip this step'

- [x] third message: 'You have selected your preference to be a 'Student/Teacher/Builder'.  You change your preferences by clicking on the other two radio buttons.'

Next button

- [x] fourth message: 'You can add subjects to your profile in this panel'
- [x] fifth message: 'Add an academic bio in the third person so that the Brillder community can know more about your intellectual background'

- [x] second last message is Click here to save changes

- [x] last message: That's it for this page!  Explore Brillder

BIO IN PHONE

- [x] still show bio even if picture not yet added, grey circle with grey icon

SAVE ICON

- [x] make a bit bigger so level with bottom of username text

**Comment by ivanromakh** [comment]
@SashaScholar6 its better to move reset password to separate task. I can`t do it now.

**Comment by SashaScholar6** [comment]
@ivanromakh ok.  You can't remove the black outline on intro.js?
