### ISSUE TITLE
Builder merge topic fields into keyword

### ISSUE THREAD

**Issue by scholar6admin** [Scholar-6/brillder#2713]
@aromakh 
- [x] The existing topic/sub-topic fields should probably return 200 empty response to stop any glitches in the front end. 
- [x] Migrate all subtopics and topics should be migrated to new field and the old fields removed from database.

@ivanromakh 

- [x] There also needs to be a delete x

Should be like chips

**Comment by ivanromakh** [comment]
@scholar6admin there is no requests for fields only for total brick. we are saving hole brick in the end of proposal.

**Comment by ivanromakh** [comment]
@aromakh you can remove topic field completely I don`t use it in front-end. 
Here we have 
1. Title
2. alternativeTopics
3. Subtopic
![image](https://user-images.githubusercontent.com/18567511/107526088-26931b80-6bc0-11eb-8752-780547aa94c4.png)

**Comment by aromakh** [comment]
@aromakh changes are in **keywords** branch until they are reviewed and merged to dev.

**Comment by ivanromakh** [comment]
key words almost finished
![image](https://user-images.githubusercontent.com/18567511/107945599-8a3e8f80-6f98-11eb-87fe-46d9803565b8.png)

**Comment by ivanromakh** [comment]
bottom buttons are now not fixed. page is scrolling if overflow heightwise.
![image](https://user-images.githubusercontent.com/18567511/107945820-d984c000-6f98-11eb-8672-07356f42f8f9.png)

**Comment by aromakh** [comment]
@ivanromakh should be fixed now.
