### ISSUE TITLE
Library fixes

### ISSUE THREAD

**Issue by SashaScholar6** [Scholar-6/brillder#2715]
<img width="1164" alt="Screenshot 2021-02-04 at 20 24 34" src="https://user-images.githubusercontent.com/59654112/106944547-00d0c700-6727-11eb-975d-fcb2a778a8d8.png">

- [x] make view it in my library button much bigger
- [x] *make view it in my library button red default not blue**

- [x] **latest brick should be first on the left**

- [x] can we animate latest brick score height from bottom?

ADMIN
- [x] If Admin has student preference, he sees two 'My Library icons in homepage

<img width="1681" alt="Screenshot 2021-02-04 at 20 27 12" src="https://user-images.githubusercontent.com/59654112/106944843-602ed700-6727-11eb-911f-2df791aa2715.png">

EXPANDED BOOK SHELF
<img width="405" alt="Screenshot 2021-02-04 at 20 28 24" src="https://user-images.githubusercontent.com/59654112/106944966-894f6780-6727-11eb-9cea-c47c38491292.png">

- [x] Don't show subject in tooltip of expanded shelf view
- [x] Title should not be cut off at the bottom
- [x] Add padding from bottom of book (eg. When I consider...)
- [x] For grey assigned incomplete, start text at bottom with same padding so left align rather than centred
- [x] reduce rounding on all book shapes

**Comment by ivanromakh** [comment]
@SashaScholar6 I can`t detect it. It works fine for me.
![image](https://user-images.githubusercontent.com/18567511/107218705-a7afae80-6a18-11eb-98ab-8cb0a4d9ac35.png)

**Comment by SashaScholar6** [comment]
Yes think it's done now, wasn't working at some point last week

**Comment by SashaScholar6** [comment]
actually no - takes user to zoomed out view, not subject specific expanded shelf

**Comment by ivanromakh** [comment]
@SashaScholar6 could you show it to me?
