### ISSUE TITLE
Iphone cant click from /play/dashboard to intro page

### ISSUE THREAD

**Issue by scholar6admin** [Scholar-6/brillder#2721]
This means all iphone users (including potential investors and customers) cannot play a second brick if they come to the app from social media. 

![image](https://user-images.githubusercontent.com/58778078/107026578-cd338280-67a2-11eb-9d79-21dab22fe338.png)
That play icon does not appear to be clickable

https://app.brillder.com/play/dashboard?subjectId=8

**Comment by ivanromakh** [comment]
problem with full screen in ios. Its imposible to make it by javascript there. 
![image](https://user-images.githubusercontent.com/18567511/107061357-c0ce1a80-67e0-11eb-8692-811a57bdff70.png)
