### ISSUE TITLE
Students cannot see personal bricks assigned to them

### ISSUE THREAD

**Issue by scholar6admin** [Scholar-6/brillder#2725]
As a student I want to see the bricks assigned to me from the teachers personal catalogue.

![image](https://user-images.githubusercontent.com/58778078/107101197-7794bf80-680e-11eb-89b3-245ecc88de8a.png)

Test
user: student@scholar6.org
Should have a brick assigned called 'Brick Props'

**Comment by ivanromakh** [comment]
@scholar6admin I have not problem with assigning personal bricks.

**Comment by ivanromakh** [comment]
@scholar6admin student@test.com now have personal assignments and they are shown there
![image](https://user-images.githubusercontent.com/18567511/107240136-3d0b6c80-6a32-11eb-9e42-e1ee03a82a3c.png)
