### ISSUE TITLE
Ipad Portrait error screen

### ISSUE THREAD

**Issue by SashaScholar6** [Scholar-6/brillder#2726]
Same styling as phone error 

- [x] if screen rotated to portrait, error screen: red background,same icon as phone error screen (phone with rotate-ccw inside), text is 'We think you will enjoy Brillder more with your device in landscape mode' 

- [x] text of error screen is white in Brandon bold

**Comment by ivanromakh** [comment]
@SashaScholar6 this one correct?
![image](https://user-images.githubusercontent.com/18567511/108224757-e98cd300-7143-11eb-9835-3e77056ea2c0.png)

**Comment by SashaScholar6** [comment]
yep nice :)
