### ISSUE TITLE
Phone: Text size fixes

### ISSUE THREAD

**Issue by SashaScholar6** [Scholar-6/brillder#2731]
<img width="539" alt="Screenshot 2021-02-08 at 13 39 06" src="https://user-images.githubusercontent.com/59654112/107220763-04a86600-6a13-11eb-908e-ca58bab88fe4.png">

Font small, needs to be bigger, like reg text

- [x] answer options for popups: Yes / No, skip
- [x] Yes / No (Submit Your Answers?)
- [x] Review 'Not quite-try again', 'Correct!'

**Comment by scholar6admin** [comment]
![image](https://user-images.githubusercontent.com/58778078/109221868-7e7d7500-77b1-11eb-8d0d-234e0aed056d.png)
