### ISSUE TITLE
Phone Summary

### ISSUE THREAD

**Issue by SashaScholar6** [Scholar-6/brillder#2732]
- [ ] like review but in a rounded card shape, with margin to show blue background
- [ ] each answer is swipable (so like flicking through photos)
- [ ] add margin at bottom so enough space for 'View it in my library button

**Comment by farmanahmed2007** [comment]
Let's discuss, as the play process is completed on a desktop view, and resolve its mobile issues

**Comment by farmanahmed2007** [comment]
![image](https://user-images.githubusercontent.com/36436724/109501431-619ab780-7ab9-11eb-9b5e-36fdba354f5c.png)

Please remove this task as it is not developed yet for mobile version
