### ISSUE TITLE
Library on Phone

### ISSUE THREAD

**Issue by SashaScholar6** [Scholar-6/brillder#2733]
<img width="515" alt="Screenshot 2021-02-08 at 13 15 00" src="https://user-images.githubusercontent.com/59654112/107221468-fa3a9c00-6a13-11eb-84f5-ada6c94b3801.png">

- [x] title should be 'MY LIBRARY' or 'SUBJECT' like desktop (not 'New' - remove chevron)
- [x] increase width of books
- [x] Remove glasses icon and 'All' label at top

**Comment by ivanromakh** [comment]
@SashaScholar6  I am not sure about width.
![image](https://user-images.githubusercontent.com/18567511/108843752-d070a000-75e3-11eb-88f4-5effdd1bfc36.png)
