### ISSUE TITLE
Show email in NAME field for pending users

### ISSUE THREAD

**Issue by SashaScholar6** [Scholar-6/brillder#2736]
<img width="728" alt="Screenshot 2021-02-08 at 17 58 42" src="https://user-images.githubusercontent.com/59654112/107254235-68dd2100-6a37-11eb-851c-dd686282603f.png">

- [x] also increase padding on left and right of 'Pending'

**Comment by ivanromakh** [comment]
@SashaScholar6 I can show email for all users if names are empty
