### ISSUE TITLE
Long comment cut off in notification panel

### ISSUE THREAD

**Issue by SashaScholar6** [Scholar-6/brillder#2737]
<img width="469" alt="Screenshot 2021-02-08 at 18 03 54" src="https://user-images.githubusercontent.com/59654112/107254956-16e8cb00-6a38-11eb-9a48-a963d52d1900.png">

- [x] also means circle is squashes
- [x] and 'x' and timestamp disappear

**Comment by ivanromakh** [comment]
@SashaScholar6 its fine for me in investigetion and synthesis suggestions.
![image](https://user-images.githubusercontent.com/18567511/107351012-c83c3f00-6ad2-11eb-99d5-d3ed9deea1f0.png)
