### ISSUE TITLE
Manage Classes Dragging like GMail & UX

### ISSUE THREAD

**Issue by SashaScholar6** [Scholar-6/brillder#2739]
<img width="1912" alt="Screenshot 2021-02-09 at 11 58 33" src="https://user-images.githubusercontent.com/59654112/107354180-23b7fe00-6ace-11eb-9457-93e4f67099b9.png">

<img width="1742" alt="Screenshot 2021-02-09 at 11 58 43" src="https://user-images.githubusercontent.com/59654112/107354200-29addf00-6ace-11eb-840a-903bcf298e91.png">

- [x] remove radio buttons on right and 'SC' heading
- [x] add checkboxes on left, sc replaced by select all
- [x] add tooltips for checkboxes - 'Select' for normal ones, 'Select All' for top one
- [x] enable dragging
- [x] When dragging, have similar style popup/blue button as gmail

- [x] add same animation for individual student
- [x] add same animation for student tab

**Comment by ivanromakh** [comment]
Existing libraries not working for this. I will try new one.https://github.com/atlassian/react-beautiful-dnd/blob/master/docs/patterns/multi-drag.md

**Comment by ivanromakh** [comment]
they don`t have what we need. Will do with html and some events.
https://developer.mozilla.org/en-US/docs/Web/API/DataTransfer/setData
![image](https://user-images.githubusercontent.com/18567511/107367017-76ea7a80-6ae7-11eb-9d9f-8b8ca1eefb94.png)

**Comment by ivanromakh** [comment]
@SashaScholar6 what for is this edit icon?
![image](https://user-images.githubusercontent.com/18567511/107376139-36dcc500-6af2-11eb-9327-5a9e8d4d73a9.png)
