### ISSUE TITLE
Profile Intro.Js - allow users to do things in tutorial

### ISSUE THREAD

**Issue by SashaScholar6** [Scholar-6/brillder#2740]
- [x] USer should be able to add picture - upload interface becomes step if clicked

- [x] Change preference

- [x] Add subjects - dropdown in highlighted area

- [x] Write bio

- [x] Save changes

**Comment by ivanromakh** [comment]
@SashaScholar6 this one is imposible with intro js. dropdown is completely different html component.
![image](https://user-images.githubusercontent.com/18567511/107507058-b082ba80-6ba7-11eb-9f80-6ea2b46dcb2c.png)

**Comment by ivanromakh** [comment]
@SashaScholar6 I have no problem with writing bio its just some keyboard key move to next step.

**Comment by ivanromakh** [comment]
@SashaScholar6 I hide intro js when you click on buttons.

**Comment by SashaScholar6** [comment]
But then can you continue tutorial? @ivanromakh

**Comment by ivanromakh** [comment]
@SashaScholar6 no right now. I can try to do it for popups but not sure about subjects autocomplete or bio.
