### ISSUE TITLE
Manage Classes Updates

### ISSUE THREAD

**Issue by SashaScholar6** [Scholar-6/brillder#2742]
<img width="1294" alt="Screenshot 2021-02-10 at 14 38 17" src="https://user-images.githubusercontent.com/59654112/107517708-60f3bd00-6bae-11eb-91f6-6cff15d2cddb.png">

- [x] if I click on band of student, tick checkbox and show as selected
- [x] if I try dragging a band I have checked, check it (at the moment it doesn't count it and says Move 0 students) - see Gmail if unsure

- [x] have 14 rows (instead of 12) for students tab

<img width="349" alt="Screenshot 2021-02-10 at 14 50 06" src="https://user-images.githubusercontent.com/59654112/107518498-5c7bd400-6baf-11eb-8f69-17792467c78c.png">

- [x] can we try this as a 50% overlay so we can see different students more clearly (from different colours underneath)

- [x] make round hover selector for checkbox dark/less transparent so more visible

**Comment by ivanromakh** [comment]
@SashaScholar6 there is some problem. we can invite members of class. And then if you click on one of them the first one will be selected. admin@test.com and Admin123 admin321 are the same user.
![image](https://user-images.githubusercontent.com/18567511/107392317-39dfb180-6b02-11eb-8b8c-4743cb2b21d7.png)
