### ISSUE TITLE
Terms updates

### ISSUE THREAD

**Issue by SashaScholar6** [Scholar-6/brillder#2752]
- [x] make font size of 'I am over 13...' bigger

- [x] make band e5e8ed by default, green on hover, whole band is clickable
<img width="366" alt="Screenshot 2021-02-11 at 12 20 04" src="https://user-images.githubusercontent.com/59654112/107630180-7aa30c00-6c63-11eb-836d-6b477efde3c7.png">

<img width="1328" alt="Screenshot 2021-02-11 at 12 19 05" src="https://user-images.githubusercontent.com/59654112/107630073-56dfc600-6c63-11eb-9b73-1b21486c4807.png">

- [x] Fix for mobile view

**Comment by ivanromakh** [comment]
@SashaScholar6 should I remove invite pupil from this page?

**Comment by SashaScholar6** [comment]
@ivanromakh ask Lindsay about this today
