### ISSUE TITLE
After playing brick, take user straight away to book page and remove popup notification

### ISSUE THREAD

**Issue by SashaScholar6** [Scholar-6/brillder#2753]
<img width="1692" alt="Screenshot 2021-02-11 at 12 21 04" src="https://user-images.githubusercontent.com/59654112/107630375-b50ca900-6c63-11eb-86f8-ffa261a59488.png">

- [x] route directly
- [x] remove popup notification

**Comment by ivanromakh** [comment]
@william-gooch I think this notification should be removed from backend side.
