### ISSUE TITLE
Manage Classes: Invite pupil should show same popup as invite students

### ISSUE THREAD

**Issue by SashaScholar6** [Scholar-6/brillder#2756]
- [ ] if necessary, then add select a class dropdown

- [x] Students tab -> replace record with 'individuals'

- [x] On the assignment tab -> individuals

Then you should see the list of individuals you have invited.

Backend
- [x] Create api call to add individual students.
- [x] Api to get individuals

As a teacher 
When invite a new student via email
Then the student is added into the 'individuals' classroom associated with the teacher

**Comment by ivanromakh** [comment]
@aromakh Can I invite student to teacher. not to classroom?
![image](https://user-images.githubusercontent.com/18567511/107645629-96b5a600-6c81-11eb-8140-a86ca2441ccd.png)

**Comment by aromakh** [comment]
@ivanromakh 
I added default class to all the existing and new users. 
Also there is *type* fiels in classroom object. 0 - means default, 1- means individual.
Each user can have only 1 individual classroom.

Please manage student in that classroom as individual students of a teacher.
