### ISSUE TITLE
Create Account Popup: update text and continue to review

### ISSUE THREAD

**Issue by SashaScholar6** [Scholar-6/brillder#2757]
- [x] update text:

Before you can review your answers and learn how to improve your score, you need to create an account.

Creating an account is free, no obligations.

- [x] continue to review

Entering the email should create an email invite to signup and create an account.

**Comment by ivanromakh** [comment]
@scholar6admin  is it signUp popup?
![image](https://user-images.githubusercontent.com/18567511/107664165-cc17bf00-6c94-11eb-9345-360f76953cc9.png)

**Comment by ivanromakh** [comment]
@scholar6admin sorry. I get it. it is in the end of play before review.

**Comment by ivanromakh** [comment]
@scholar6admin I need more details on how user will continue to review and how whom he wanna to invite. Should I added third button in that popup `contuniue to review`... need more details.
