### ISSUE TITLE
Play Preview Button and return to editor button should not be active when starting a brick

### ISSUE THREAD

**Issue by SashaScholar6** [Scholar-6/brillder#2766]
<img width="1919" alt="Screenshot 2021-02-12 at 12 58 54" src="https://user-images.githubusercontent.com/59654112/107765478-3599db00-6d32-11eb-9e14-d92445819ba2.png">

**Comment by ivanromakh** [comment]
@SashaScholar6 play preview button should not be active. which user you used to create brick?

**Comment by SashaScholar6** [comment]
Started from scratch as admin on production I believe
