### ISSUE TITLE
IPad: Optimise View and Play

### ISSUE THREAD

**Issue by SashaScholar6** [Scholar-6/brillder#2774]
- [x] after #2781 - new desktop play design
- [x] new interface
- [x] restore home button
- [x] zendesk should not be huge
- [x] fix cut off
- [ ] @ivanromakh template conversion

ALL SUBJECTS

- [x] can't see shapes because everything is white

**Comment by farmanahmed2007** [comment]
is the iPad view been activated yet?
if yes please specify which iPad view is to be in the process vertical or horizontal

**Comment by scholar6admin** [comment]
@SashaScholar6 Im going to say we should focus on landscape mode in ipad. Please correct me if I am wrong. I also want to activate ipad on dev-mobile starting from now.
