### ISSUE TITLE
Brick backgrounds and hover colours

### ISSUE THREAD

**Issue by SashaScholar6** [Scholar-6/brillder#2776]
Hi Ivan, because of grey background in any subject or filtered view, hover no longer visible.  Can we:

- [x] make the grey f5f67f7

- [x] add white rounded rectangle background (so like all-subjects panel)

- [x] background goes e5e8ed on hover

<img width="1110" alt="Screenshot 2021-02-16 at 14 09 01" src="https://user-images.githubusercontent.com/59654112/108067095-9130d500-7060-11eb-96e7-ccee23b26c6a.png">

- [x] Nice :) move left column a bit closer to middle column (so level with text above)and right column more left do that horizontal spaces between brick same as spaces above and below

If need be to make this work, width can be increased slightly

- [x] make button 10% bigger (all sides) on hover

**Comment by ivanromakh** [comment]
@SashaScholar6 what do you mean by white rounded rectangle?

**Comment by SashaScholar6** [comment]
like on all subjects page
