### ISSUE TITLE
Keyword and Level designation and styling

### ISSUE THREAD

**Issue by SashaScholar6** [Scholar-6/brillder#2780]
KEYWORDS
Hashtags in same size font as regular text, with spaces between each hasthags

- [x] hashtag in phone preview (not chip)
- [x] hashtags in plan double page (not chips) 
- [x] hashtags in  brick catalogue/build/search results (@aromakh )

- [x] ellipsiss when overflowing

- [x] autosuggest (@aromakh )

LEVEL DESIGNATION

- [x] level shown in circle by default, smaller by default, bigger on hover

- [x] if icon shown icon, then level bigger font on hover

- [x] don't show duplicates in dropdown
<img width="520" alt="Screenshot 2021-03-04 at 13 39 39" src="https://user-images.githubusercontent.com/59654112/109965346-2386d900-7cef-11eb-840d-40cf7ade7d95.png">

<img width="1437" alt="Screenshot 2021-03-04 at 13 41 20" src="https://user-images.githubusercontent.com/59654112/109965507-56c96800-7cef-11eb-9e8d-cc9bdffcfaef.png">

- [x] title input should be higher and fixed
- [x] maximum of two lines plus panel for keywords
- [x] next and chevron should be fixed to screen not keep moving down

**Comment by ivanromakh** [comment]
@SashaScholar6 About this one. `hashtags in plan double page`. you mean like this?
![image](https://user-images.githubusercontent.com/18567511/108068693-15885580-706b-11eb-9c37-cf3e691b587b.png)

**Comment by ivanromakh** [comment]
@SashaScholar6 how user will be removing hashtags then?

**Comment by aromakh** [comment]
@ivanromakh  http://swagger.scholar6.org/docs/#/keywords
