### ISSUE TITLE
Desktop Play Update

### ISSUE THREAD

**Issue by SashaScholar6** [Scholar-6/brillder#2781]
<img width="1440" alt="Screenshot 2021-02-16 at 12 10 41" src="https://user-images.githubusercontent.com/59654112/108055238-ff20d080-704f-11eb-8ee7-19ba8ab6b687.png">

- [x] progress bar replaces timer
- [x] bar goes red inn last 30 seconds
- [x] chevrons by 'Next' or 'Back' move right and left on hover

- [x] remove 'Investigation text'
- [x] For review, circles around numbers are red or green

**Comment by ivanromakh** [comment]
@SashaScholar6 next button means next question or to synthesis?

**Comment by SashaScholar6** [comment]
Next question
