### ISSUE TITLE
Phone Play Update

### ISSUE THREAD

**Issue by SashaScholar6** [Scholar-6/brillder#2782]
<img width="377" alt="Screenshot 2021-02-16 at 12 51 32" src="https://user-images.githubusercontent.com/59654112/108059372-b4a25280-7055-11eb-89bd-7f12bc00ab49.png">

- [x] help button bottom left
- [x] arrow in circle to exit

**Comment by ivanromakh** [comment]
@SashaScholar6 this red circle is zendesk?
![image](https://user-images.githubusercontent.com/18567511/108719259-03555e00-7528-11eb-9886-d2661231b554.png)

**Comment by SashaScholar6** [comment]
@ivanromakh yes red circle is zendesk

**Comment by ivanromakh** [comment]
@SashaScholar6 ok I will try to make it smaller
![image](https://user-images.githubusercontent.com/18567511/108721830-1fa6ca00-752b-11eb-8d4f-8e1465cae61d.png)

**Comment by ivanromakh** [comment]
@SashaScholar6 should I remove this button from provisional score? and move it to bottom?
![image](https://user-images.githubusercontent.com/18567511/108733377-20ddf400-7537-11eb-9a12-86216ce72609.png)
