### ISSUE TITLE
Published in build public should only show currently published bricks

### ISSUE THREAD

**Issue by SashaScholar6** [Scholar-6/brillder#2784]
<img width="1910" alt="Screenshot 2021-02-16 at 17 28 15" src="https://user-images.githubusercontent.com/59654112/108091883-6ce2f180-707c-11eb-83a6-871f4667c1fa.png">

**Comment by ivanromakh** [comment]
@SashaScholar6 I can`t reproduce it. can you describe steps which you do to see this?

**Comment by SashaScholar6** [comment]
reassuring - must be because I am admin

**Comment by SashaScholar6** [comment]
will have a look now

**Comment by SashaScholar6** [comment]
huh, doesn't seem to be happening anymore - closing issue
