### ISSUE TITLE
Email Templates

### ISSUE THREAD

**Issue by SashaScholar6** [Scholar-6/brillder#2791]
- [x] @farmanahmed2007 speak with William and Lindsay to complete implementation

https://xd.adobe.com/view/fe274b79-68a5-4087-9887-cd5a096ad710-ab74/

- [x] Student invited to class - unauth

- [x] Welcome, new signup

- [x] Individual to bricks by Teacher/Tutor - unauth
- [x] Student to class - auth existing user
- [x] individual to bricks by teacher/tutor

- [x] invitation to edit
- [x] brick returned to author by editor

- [x] brick published

they look great :+1: just two tweaks/questions:

- [x] circles behind top icons not quite right (are they definitely 0.5 opacity #FFFFFF?)

- [x] All the Optional Message fields in Italics should not show if no message added (will that be the case).   At the moment we don't actually have the option to add a message yet, so should just be a bit of space there instead of that placeholder. 

Otherwise great stuff :slightly_smiling_face:

**Comment by william-gooch** [comment]
@SashaScholar6 do we have a design for when a user signs up on their own - i.e. after synthesis during play?

**Comment by william-gooch** [comment]
The templates are now available at api.brillder.com/admin/templates
You need to be logged in as an admin on app.brillder.com (so you might need to get credentials for that)
The templates are written in [Pug](https://pugjs.org/api/getting-started.html), so you'll want to get familiar with that.

**Comment by farmanahmed2007** [comment]
Regarding point 2, they can be dynamic according to the requirement if needed or not

**Comment by farmanahmed2007** [comment]
I have converted them to pug as requested on brillder.com/email_templates
