### ISSUE TITLE
Mobile should show same icons as desktop depending on user-preference

### ISSUE THREAD

**Issue by SashaScholar6** [Scholar-6/brillder#2794]
STUDENT

- [x] from top to bottom:

View & Play (red), Assignments (red), My Library (blue), Build Bricks (blue).  Once we fix library in mobile that will be red and clickable.

- [x] My Library and Build Bricks icons disabled - 193366, error popup with You're going to need a bigger boat

- [x] Remove any other icons

BUILDER

 - [x] from top to bottom:

View All Bricks (red), Build Bricks (blue), Assignments (red)

- [x] Build Bricks and Brick Stats icons disabled - 193366, error popup with You're going to need a bigger boat

- [x] Remove any other icons

TEACHER

  - [x] from top to bottom:
  Assign bricks (red), Manage Classes (blue), Build Bricks (blue), Shared with Me (red)

- [x] Manage Classes and Build Bricks icons disabled - 193366, error popup with You're going to need a bigger boat

- [x] Remove any other icons

**Comment by ivanromakh** [comment]
@SashaScholar6 which page is it?

**Comment by ivanromakh** [comment]
@SashaScholar6 is it home page?
