### ISSUE TITLE
Fix font sizes

### ISSUE THREAD

**Issue by SashaScholar6** [Scholar-6/brillder#2804]
- [x] Missing word tiny in mobile

<img width="721" alt="Screenshot 2021-02-18 at 12 34 03" src="https://user-images.githubusercontent.com/59654112/108351438-d16d9000-71e5-11eb-8696-cd46b6a636a9.png">

- [x] text under keep control etc. should be bigger

<img width="204" alt="Screenshot 2021-02-18 at 12 34 47" src="https://user-images.githubusercontent.com/59654112/108351475-df231580-71e5-11eb-8ca1-311a700c52aa.png">

- [x] text in missing word dropdown should be bigger (same as reg text)

<img width="248" alt="Screenshot 2021-02-18 at 12 34 59" src="https://user-images.githubusercontent.com/59654112/108351521-eea25e80-71e5-11eb-86bd-8402066e0416.png">

- [x] word and line highlighting text should be bigger

<img width="789" alt="Screenshot 2021-02-18 at 13 17 16" src="https://user-images.githubusercontent.com/59654112/108363753-907d7780-71f5-11eb-8dc5-84031b75c26b.png">

- [x] bullet point text should be same size as reg text (bigger)

BOOK

<img width="615" alt="Screenshot 2021-02-18 at 12 37 51" src="https://user-images.githubusercontent.com/59654112/108351698-27423800-71e6-11eb-8f16-3ac6821cecc6.png">

- [x] make reg text same size as ansswer/prep text (bigger)

<img width="632" alt="Screenshot 2021-02-18 at 12 38 33" src="https://user-images.githubusercontent.com/59654112/108351759-3a550800-71e6-11eb-8521-b3a392224220.png">

- [x] make open question same size as prep text (bigger)

<img width="789" alt="Screenshot 2021-02-18 at 13 17 16" src="https://user-images.githubusercontent.com/59654112/108363694-865b7900-71f5-11eb-9d78-13c9621dff37.png">

<img width="607" alt="Screenshot 2021-02-18 at 12 37 40" src="https://user-images.githubusercontent.com/59654112/108363832-a5f2a180-71f5-11eb-84fb-78432529a772.png">

- [x] Synthesis title should be bigger (same as 'My Answer'

- [x] Reg text of Synthesis should be bigger (like elsewhere

- [x] Pair Match, Categorise and Missing Word should be same size as all other answer types, and same as reg text.

**Comment by ivanromakh** [comment]
@SashaScholar6  does line breaks here matter?

**Comment by SashaScholar6** [comment]
Change text to 'Submit for peer review, be considered for our core catalogue and get paid for your work'.

Hopefully that will fit on one line

**Comment by ivanromakh** [comment]
@Sasha should I fix this one first?
![image](https://user-images.githubusercontent.com/18567511/108714440-34cb2b00-7522-11eb-8bb8-356d21587dd3.png)

**Comment by ivanromakh** [comment]
@SashaScholar6 
Prep text is smaller... don`t get it.
![image](https://user-images.githubusercontent.com/18567511/108715534-ace62080-7523-11eb-97b2-8c77516ecb5e.png)
