### ISSUE TITLE
Hover for icons and links on website

### ISSUE THREAD

**Issue by SashaScholar6** [Scholar-6/brillder#2812]
<img width="722" alt="Screenshot 2021-02-18 at 16 42 47" src="https://user-images.githubusercontent.com/59654112/108381861-84e77c00-7208-11eb-92ee-36f9fd7a3b2a.png">

- [x] 1- for hover, I meant 50% circle behind (like on play button in phone)

- [x] 2- let's open twitter and linkedin in a new tab

- [x] 3 - make Contact us send to hello@brillder.com instead

- [x] make contact us text red on hover, and 50% red circle behind mail red button

**Comment by ivanromakh** [comment]
@aromakh  you need to clear cash for https://brillder.com/ to apply changes.
