### ISSUE TITLE
Phone fixes - Assignments

### ISSUE THREAD

**Issue by SashaScholar6** [Scholar-6/brillder#2814]
ASSIGNMENTS

<img width="276" alt="Screenshot 2021-02-19 at 14 47 22" src="https://user-images.githubusercontent.com/59654112/108512654-d43db300-72c1-11eb-98c9-3419e40a0100.png">

- [x] remove whit rectangle shape in top half - should be just grey background

- [x] Only show most recent assignment at the top - same position as screenshot below

- [x] assigned circles should be red

- [x] level text ('I') should be bigger in circle
- [x] completed circles should be green and go to the bottom of list

- [x] Remove Glasses, New label, and public personal toggle

- [x] change 'Learn' to 'ASSIGNMENTS'

- [x] add thin grey lines and more space between each assignment (like grey liine below 'Learn' currently)

<img width="276" alt="Screenshot 2021-02-19 at 14 49 01" src="https://user-images.githubusercontent.com/59654112/108512898-22eb4d00-72c2-11eb-97e5-b9bf563cac81.png">

- [x] scroll cut off fix

**Comment by ivanromakh** [comment]
@SashaScholar6 for me this page scrolling seems broken isn`t it?
![image](https://user-images.githubusercontent.com/18567511/108833489-926c7f80-75d5-11eb-9df0-d6da5b6665c4.png)
