### ISSUE TITLE
Make react buttons href links so that Google can follow them

### ISSUE THREAD

**Issue by scholar6admin** [Scholar-6/brillder#2823]
This may be a redundant task
First try adding sitemap to Google of published bricks then look at this.

At the moment react buttons do not show an href value so even if Google renders the HTML it does not necessarily know that a button is a link that renders a new page. 

So make sure that all buttons render a proper link but it should still use the react router
<a href={window.location.hostname + map.TermsPage} onClick={(e) => {e.preventDefault(); moveToTerms();}}>

This should be for all categories on /play/dashboard/all-subjects and for all bricks in the individual subjects.

**Comment by william-gooch** [comment]
Realizing now that (without the sitemap) this task is actually kind of useless, since there's no way to get to the catalogue page from the index page if you're not logged in!
I'm still doing it but we might want to consider adding in a button like "explore our catalogue" from the login page.
