### ISSUE TITLE
Text getting cut off in new play/pay preview

### ISSUE THREAD

**Issue by SashaScholar6** [Scholar-6/brillder#2825]
<img width="1645" alt="Screenshot 2021-02-22 at 10 43 48" src="https://user-images.githubusercontent.com/59654112/108690661-e6eefc80-74fa-11eb-890c-aed3f8f276c2.png">

**Comment by ivanromakh** [comment]
@SashaScholar6 fixed cut off from right side.
![image](https://user-images.githubusercontent.com/18567511/108703844-db5bff80-7513-11eb-948d-13ddab855b28.png)
