### ISSUE TITLE
White screen on dev when clicking on a brick to see build

### ISSUE THREAD

**Issue by SashaScholar6** [Scholar-6/brillder#2830]
<img width="1369" alt="Screenshot 2021-02-23 at 13 24 54" src="https://user-images.githubusercontent.com/59654112/108843141-964ed080-75da-11eb-850c-5e4730d431d4.png">

**Comment by ivanromakh** [comment]
@william-gooch this seems related to sockets. I leave it to you
![image](https://user-images.githubusercontent.com/18567511/108848958-4e37aa00-75ea-11eb-81c2-ae839c6022e1.png)

**Comment by ivanromakh** [comment]
@william-gooch for me this happen only in dev-brillder. can`t detect it locally.

**Comment by ivanromakh** [comment]
@william-gooch probably related to that env variable you give me but not sure.

**Comment by ivanromakh** [comment]
Previous fix is bad. Need to move that env variable to where REACT_APP_BACKEND_HOST is.

**Comment by ivanromakh** [comment]
@SashaScholar6  it works in dev now.

**Comment by SashaScholar6** [comment]
:) thank you

**Comment by aromakh** [comment]
@ivanromakh env variables for web scoket are added now.
