### ISSUE TITLE
When I click play brick on intro page, go to maximum view

### ISSUE THREAD

**Issue by SashaScholar6** [Scholar-6/brillder#2833]
<img width="1263" alt="Screenshot 2021-02-23 at 14 40 25" src="https://user-images.githubusercontent.com/59654112/108851760-12e6ac80-75e5-11eb-9aae-4f1271c82ca8.png">

- [x] move prep up (ie scroll) when play button clicked, otherwis it could be missed

<img width="184" alt="Screenshot 2021-02-23 at 14 40 10" src="https://user-images.githubusercontent.com/59654112/108851822-2560e600-75e5-11eb-8228-3205505c3fc8.png">

- [x] fix circle cutoff

**Comment by ivanromakh** [comment]
@SashaScholar6 I can`t reproduce those bugs.
