### ISSUE TITLE
Sound and Graph not dragging into work area

### ISSUE THREAD

**Issue by SashaScholar6** [Scholar-6/brillder#2836]
- [x] quote
- [x] image
- [x] sound
- [x] graph

<img width="1532" alt="Screenshot 2021-02-24 at 15 45 52" src="https://user-images.githubusercontent.com/59654112/109017414-72ad8800-76b7-11eb-962e-ebe04380928b.png">

- [x] sound component glitchy and does not seem to appear in phone

**Comment by ivanromakh** [comment]
@SashaScholar6 Could I try this one.

**Comment by ivanromakh** [comment]
@william-gooch  As I see drag and drop only supported for text components.
![image](https://user-images.githubusercontent.com/18567511/108990286-4dad1b00-769f-11eb-8980-ce7d7681514e.png)

**Comment by william-gooch** [comment]
@ivanromakh Yeah, that's my bad - I may have kind of forgotten the other components existed.
Apologies, should have done that before the merge.
However, might it be useful for you to have a go of this so you get the hang of writing Yjs stuff? Or do you still want me to tackle it?

**Comment by ivanromakh** [comment]
@william-gooch ok sure. Need to get familiar with it I will make pull request when finish for you to review.
