### ISSUE TITLE
Play improvements

### ISSUE THREAD

**Issue by SashaScholar6** [Scholar-6/brillder#2841]
ALL QUESTIONS

- [x] fix hover shape to be same as reg grey answer shape and don't increase size on hover (UX can get irritating, especially with things like vertical shuffle)

PLAY PREVIEW

- [x] don't move on to next screens automatically at the ned of investigation and review (i should still be able to click back and forth

 - [x] show levels in circle of introduction desktop and mobile

word line highlight

- [x] 50% hover
- [x] rounded shape with some padding
- [x] hover over words/lines only

categorise

- [x] 50%light blue hover
- [x] option gets bigger on hover

missing word

- [x] try to replace triangle of dropdown with feather-chevron
- [ ] try to replace line with rounded thicker line
- [x] make font in dropdwon bigger

horizontal shuffle

- [x] light blue hover

**Comment by ivanromakh** [comment]
@SashaScholar6 you said don`t make them bigger yesterday.
![image](https://user-images.githubusercontent.com/18567511/109784489-cc600600-7c13-11eb-8c3f-369857b75ac2.png)

**Comment by SashaScholar6** [comment]
Yes correct, sorry didn't spot that was an older task - don't make bigger indeed
