### ISSUE TITLE
Image Interface and captions

### ISSUE THREAD

**Issue by SashaScholar6** [Scholar-6/brillder#2843]
- [x] image component
- [x] prep image input
- [x] synthesis image input

- [x] caption not visible in prep because of blue phone
- [x] should be able to click on image and have interface appear to make changes - prep and synthesis
- [x] Add captions for answer type images

**Comment by ivanromakh** [comment]
@SashaScholar6 I checked quill has image input.

**Comment by SashaScholar6** [comment]
But does it have the interface with attribution requirement?

**Comment by ivanromakh** [comment]
@SashaScholar6 attribution requirement?

**Comment by ivanromakh** [comment]
@SashaScholar6 you mean like in question workspace?

**Comment by SashaScholar6** [comment]
Like image component in build work area, yes.  We need to attribute any image we put into a brick

**Comment by ivanromakh** [comment]
It will take a lot of time for me I leave it for you @william-gooch. you are more familiar with quill. you need to add this popup after image upload.
![image](https://user-images.githubusercontent.com/18567511/109641062-f0f7a780-7b59-11eb-83c1-3102c0929a3f.png)

**Comment by SashaScholar6** [comment]
ok
