### ISSUE TITLE
Phone: when no bricks in a subject, show same message as desktop

### ISSUE THREAD

**Issue by SashaScholar6** [Scholar-6/brillder#2845]
<img width="389" alt="Screenshot 2021-02-24 at 13 30 32" src="https://user-images.githubusercontent.com/59654112/109001046-bb0f7a80-76a4-11eb-9659-1e7c2cc54636.png">

- [x] in top grey area 'Sorry, no bricks found' in brandon bold
- [x] in bottom white area, 'Try one of the following:' in Brandon Regular Italic
- [x] with list of available subjects underneath

**Comment by scholar6admin** [comment]
@SashaScholar6 
![image](https://user-images.githubusercontent.com/58778078/109202712-32273a80-779b-11eb-9711-8646bd310d11.png)

**Comment by SashaScholar6** [comment]
@scholar6admin @lindsaymacvean What am I looking for?
