### ISSUE TITLE
Phone fixes

### ISSUE THREAD

**Issue by SashaScholar6** [Scholar-6/brillder#2846]
<img width="476" alt="Screenshot 2021-02-24 at 13 34 58" src="https://user-images.githubusercontent.com/59654112/109001367-25c0b600-76a5-11eb-9650-033e8db98c6e.png">

- [x] move 'SUbject brick of the week lower
- [x] stop circles squashing

<img width="241" alt="Screenshot 2021-02-24 at 13 36 53" src="https://user-images.githubusercontent.com/59654112/109001548-5c96cc00-76a5-11eb-94a2-e0382c2d2b65.png">

- [x] change icon to 'corner-up-left (feather)

<img width="398" alt="Screenshot 2021-02-24 at 13 38 06" src="https://user-images.githubusercontent.com/59654112/109001707-894ae380-76a5-11eb-8ec7-bc42b8debbe6.png">

- [x] move grey box down (add margin below brick title

<img width="440" alt="Screenshot 2021-02-24 at 13 39 32" src="https://user-images.githubusercontent.com/59654112/109001854-bd260900-76a5-11eb-8980-335135c1da1f.png">

- [x] fix cutoff in expanded prep view

<img width="375" alt="Screenshot 2021-02-24 at 13 42 02" src="https://user-images.githubusercontent.com/59654112/109002141-1a21bf00-76a6-11eb-9c46-faef60691f6e.png">

- [x] remove prep file icon when on prep screen
- [x] replace arrow in circle with corner-up-left and replace next previous chevron with arrow.-left and arrow-right circle

<img width="299" alt="Screenshot 2021-02-24 at 13 45 11" src="https://user-images.githubusercontent.com/59654112/109002466-8997ae80-76a6-11eb-9817-96a90d16f642.png">

- [x] circle getting cut off in number bar
- [x] check zendesk button - if possible just red circle no white border

<img width="489" alt="Screenshot 2021-02-24 at 13 47 42" src="https://user-images.githubusercontent.com/59654112/109002736-e004ed00-76a6-11eb-9d96-28b602e0ce74.png">

- [x] remove synthesis and green button - just arrowrightcircle in bottom sidebar to progress

<img width="475" alt="Screenshot 2021-02-24 at 13 48 27" src="https://user-images.githubusercontent.com/59654112/109002810-fb6ff800-76a6-11eb-9348-d2e121e938b6.png">

- [x] Synthesis title at top should be bold and more to the right

- [x] review button and text replace with arrowrightcircle in toolb ar as above

<img width="377" alt="Screenshot 2021-02-24 at 13 50 29" src="https://user-images.githubusercontent.com/59654112/109003067-4427b100-76a7-11eb-9cef-782c2ae35e25.png">

- [x] add same invite/share w friend colleague as in desktop

- [x] **when three dots clicked, I should see Share Brick, Assign Birck and Adapt Brick buttons in a dropdown (depending on user pref of course - same logic as desktop) - style can be like other mobil dropdown on three dots, but grey background and blue text and icons**

**Comment by ivanromakh** [comment]
![image](https://user-images.githubusercontent.com/18567511/109193427-05762180-77a1-11eb-8588-000290c26eea.png)

**Comment by SashaScholar6** [comment]
Nice 👌💯🙂
