### ISSUE TITLE
In Manage Users, allow admin to sort users by date account created

### ISSUE THREAD

**Issue by SashaScholar6** [Scholar-6/brillder#2853]
<img width="1479" alt="Screenshot 2021-02-25 at 18 44 36" src="https://user-images.githubusercontent.com/59654112/109194500-c2648000-7799-11eb-86a3-5b5fc5a5ea05.png">

- [x] @ivanromakh replace 'SC' with 'Joined' and make colummn wider (name more to the right to make space for date user joined the system)
- [x] add chevron

**Comment by aromakh** [comment]
@ivanromakh just put "created" in orderBy param

**Comment by ivanromakh** [comment]
@aromakh need date here.
https://dev-api.brillder.com/users
![image](https://user-images.githubusercontent.com/18567511/109817766-f37dfe00-7c3a-11eb-93ef-8ec9de05101d.png)

**Comment by aromakh** [comment]
@ivanromakh 
done, field is called "created"

**Comment by ivanromakh** [comment]
not merged yet. probably in pull request.
