### ISSUE TITLE
Tap twice (not three times) to open a brick

### ISSUE THREAD

**Issue by scholar6admin** [Scholar-6/brillder#2855]
On mobile Iphone XS chrome
1st tap selects the brick and shows a play icon
2nd tap should open the brick

But it seems to need third tap on the brick to open 

![image](https://user-images.githubusercontent.com/58778078/109224037-52fb8a00-77b3-11eb-833a-64e9510d1f4f.png)

https://live.browserstack.com/dashboard#os=iOS&os_version=14.0&device_browser=chrome&zoom_to_fit=true&full_screen=true&url=https%3A%2F%2Fdev-app.brillder.com%2Fterms&speed=1

**Comment by farmanahmed2007** [comment]
**Currently on mobile**
the first tap is to view the brick detail
the second tap is for deselecting the brick
**Process:**
you need to first select the brick and then tap on play button to go in play process
there are only 2 actions on that
the third action is to deselect it

**Comment by scholar6admin** [comment]
I think this already resolved. Lets move this to testing column.
