### ISSUE TITLE
Further phone fixes

### ISSUE THREAD

**Issue by SashaScholar6** [Scholar-6/brillder#2857]
- [x] fix non full screen height scrolling issue

- [x] Add blue bar to all subjects page

- [x] user should not be signed out when pressing home button on Chemistry subject page

- [x] make bottom bar shorter, progress bar a bit shorter and bit lower down

INTRODUCTION page phone 

<img width="211" alt="Screenshot 2021-02-26 at 12 46 50" src="https://user-images.githubusercontent.com/59654112/109296541-bf689e80-7830-11eb-86f0-5a00a126710f.png">

- [x] first page has only Brief (NOT Prep) - expanded by default

- [x] bottom bar is shorter and says 'Play Brick' in space where highlighter is (keep exit, three dots and next chevron)

<img width="210" alt="Screenshot 2021-02-26 at 12 46 57" src="https://user-images.githubusercontent.com/59654112/109296690-09ea1b00-7831-11eb-976d-a8cea8eaaa76.png">

- [x] remove number timer in top right

- [x] fix height of youtube videos

- [x] make circle bigger top left and show levels
- [x] title can now take up more spacee at top
- [x] add progress bar at the bottom, but do not switch to next screen when time is up

INVESTIGATION

- [x] when I click to go to next question, I should always see the top of the question (at the moment it seems to show me the scroll height of previous question which meeans when clicking through I have to scroll up again to see the beginning of a question)

- [x] force portrait mode during play

**Comment by ivanromakh** [comment]
@SashaScholar6 how can I transform clock to progress bar?

**Comment by ivanromakh** [comment]
@SashaScholar6 this is probably backend issue. Can`t reproduce it.
![image](https://user-images.githubusercontent.com/18567511/109329209-fa83c580-7862-11eb-8d79-6ceb7d8e737e.png)

**Comment by SashaScholar6** [comment]
ok don't worry - seems to have disappeared for me too :)

**Comment by ivanromakh** [comment]
@SashaScholar6 what do you mean by force portarit in investigation?
![image](https://user-images.githubusercontent.com/18567511/109487457-e7ecd480-7a8c-11eb-81f4-b7cf6541aee7.png)
