### ISSUE TITLE
Mobile End of Investigation and further actions

### ISSUE THREAD

**Issue by SashaScholar6** [Scholar-6/brillder#2859]
PROVISIONAL SCORE

- [x] page should not be scrollable
- [x] move 'Provisional Score' and 'Final Score : Agg' text to centre (width-wise)

SYNTHESIS

- [x] like for Prep, circle is bigger and shows level

FINAL SCORE

- [x] fix hegihts/scrolling issue - score should be in middle of the page

ENDING/FINALSTEP/EXIT SCREEN

<img width="355" alt="Screenshot 2021-02-26 at 13 06 24" src="https://user-images.githubusercontent.com/59654112/109298155-70703880-7833-11eb-87df-80c640b599e4.png">

- [x] add a green circle at the top (same position as intro page, with feather-star icon in it
- [x] remove 'All done!' text
- [x] make 'Well done.. text bigger and put [brick title] on a second line underneath - text should be centred

- [x] Assign brick is an options (underneath resspective feather-icons) for teachers/admins underneath 'Share with a friend ...' - 

- [x] remove highlighter and exit arrow, as well as exit text and button 

- [x] write 'Exit' in grey bar instead, with right chevron

**Comment by ivanromakh** [comment]
@SashaScholar6 is it good?
![image](https://user-images.githubusercontent.com/18567511/109307725-bf28cd00-7849-11eb-9448-7bdf1998c04f.png)

**Comment by SashaScholar6** [comment]
Top half nice yes :) What happens when brick title is longer? Might not need to be quite so big.

Bottom bar to be fixed of course - what does it look like with assign icon underneath?

**Comment by ivanromakh** [comment]
@SashaScholar6 I need design for this. I don`t see play for it in grey bar
![image](https://user-images.githubusercontent.com/18567511/109329055-d0ca9e80-7862-11eb-92b8-188e05e10012.png)

**Comment by SashaScholar6** [comment]
play for it?  It should be in the place of the icons which are no longer necessary on this page in bottom grey bar

**Comment by ivanromakh** [comment]
@SashaScholar6 sorry play for it

**Comment by ivanromakh** [comment]
@SashaScholar6 looks like @lindsaymacvean done some of these.
