### ISSUE TITLE
Bullets tiny in mobile: should be same size as reg text

### ISSUE THREAD

**Issue by SashaScholar6** [Scholar-6/brillder#2875]

**Comment by ivanromakh** [comment]
@SashaScholar6 is it in dev-mobile or dev?

**Comment by SashaScholar6** [comment]
dev-mobile, possibly dev-too

**Comment by SashaScholar6** [comment]
desktop is good, but phone tiny

**Comment by ivanromakh** [comment]
@SashaScholar6 for me they are bigger then regular text. Regular text is 4.5vw and bullets are 6vw.
![image](https://user-images.githubusercontent.com/18567511/109638165-55186c80-7b56-11eb-850c-a55b985c3ad2.png)

**Comment by SashaScholar6** [comment]
think there may be a difference in prep/question (too big) and SYnthesis (wheere really small).  Should always be same as reg text
