### ISSUE TITLE
Check OG tags on brillder.com

### ISSUE THREAD

**Issue by scholar6admin** [Scholar-6/brillder#2878]
![image](https://user-images.githubusercontent.com/58778078/109644927-08309800-7b4e-11eb-8cb9-fdbf2a5c8f63.png)

@SashaScholar6 
Title:
Description: 
Image: (2:1 aspect ratio) blue background with logo

- [x] insert Brillder logo and text I sent on Slack

- [x] Blue background hex is #193366

**Comment by ivanromakh** [comment]
@scholar6admin @SashaScholar6 I need details here not in slack.

**Comment by SashaScholar6** [comment]
can't attach SVGs - was sent to William as thought he was doing it.  It's just Brillder logo with white text underneath

**Comment by ivanromakh** [comment]
@SashaScholar6 I need only description and title

**Comment by ivanromakh** [comment]
@SashaScholar6 should be nice to have a link where it is shown. is it linkedin?

**Comment by SashaScholar6** [comment]
Title: Brillder.com
Description: Brillder® is an online publishing platform for 21st century educators, where high-quality ‘brick’ investigations are created by subject specialists, set by teachers, and explored by students.

Does that sound reasonable @lindsaymacvean ?

**Comment by ivanromakh** [comment]
done. need like to check how it look like.
