### ISSUE TITLE
Vertical shuffle scoring mismatch

### ISSUE THREAD

**Issue by SashaScholar6** [Scholar-6/brillder#2879]
<img width="575" alt="Screenshot 2021-03-02 at 14 13 10" src="https://user-images.githubusercontent.com/59654112/109653542-729f0380-7b61-11eb-8aa2-dd1ff4d19172.png">

- [ ] red cross but 100%

this was on production 470, but should be reproducible elsewhere

**Comment by ivanromakh** [comment]
@william-gooch I could try this.

**Comment by ivanromakh** [comment]
@SashaScholar6 tried to reproduce but maybe its not related to vertical shuffle. how many choices there were in production?

**Comment by ivanromakh** [comment]
@SashaScholar6 for me vertical shuffle works fine if you find brick in dev which have this issue I will fix it.
