### ISSUE TITLE
Mobile Dropdowns

### ISSUE THREAD

**Issue by SashaScholar6** [Scholar-6/brillder#2880]
remember to :

- [x] make 'Share Brick / Assign Brick font smaller and add icons

- [x] Play icon on intro page (not text)
- [x] Exit arrow has popup: 'Exit? Your brick attempt will not be saved. Options: Yes, Exit / No, keep learning

UNAUTH USER

- [x] move brick logo and search to left, then add feather-settings icon and dropdown to 'Stop Tracking', with 'x-octagon' next to it

- [x] Adjust fonts in dropdwons (grey dropdown fonts smaller, blue dropdwon fonts and icons bigger so all the same (width of dropdown can expand if necessary)

- [x] Share and Assign expanded by default on first intro page (also not seeing icons there yet?)

**Comment by ivanromakh** [comment]
@SashaScholar6 icons should be there now. deployed.
