### ISSUE TITLE
POPUPS

### ISSUE THREAD

**Issue by SashaScholar6** [Scholar-6/brillder#2887]
- [x] POPUPS - white hover means text now invisible on hover (should be red if button red)

**CREATE CLASS POPUP**

- [x] dropdown should have subject circle on left and subject in dark blue not black

- [x] dropdwon should have rounded edges and be same height as class name field

- [x] 'Create font should be much bigger

**ASSIGN POPUP**

- [x] text and icon should b e red on hover not white

- [x] hide dropdown arrow

- [x] Change Placeholder to 'Search for students and classes'

- [x] 'Who would you like to assign...? bigger and generalise for all

- [x] Add second line: 'When is it due?'

- [x] Two white radio buttons below 'No deadline' / 'Set date'

- [x] Next to set date - three dropdowns for date - DD. MM. YYYY - 
- [x] for YYYY, start at 2021 end at 2025

**Comment by ivanromakh** [comment]
@SashaScholar6 what if background is white?
![image](https://user-images.githubusercontent.com/18567511/109936901-0fcf7880-7cd7-11eb-96e0-c09f229811fa.png)

![image](https://user-images.githubusercontent.com/18567511/109936884-0b0ac480-7cd7-11eb-9b03-8ccb57560640.png)

**Comment by ivanromakh** [comment]
@SashaScholar6 for deadline It will take sometime to create component for it.

**Comment by SashaScholar6** [comment]
that's ok. nice :) will have a look
