### ISSUE TITLE
PHONE PLAY

### ISSUE THREAD

**Issue by SashaScholar6** [Scholar-6/brillder#2889]
Some already done on call, so do check them off

**PHONE DROPDWONS:**

- [x] blue dropdwon same padding as grey dropdwon

- [x] GREY DROPDWON: text on left and icons on right

- [x] Assign icon (file-plus), not copy

- [ ] Add Enter/Exit full screen to grey dropdown

**PREP PAGE**

- [x] Brief circle cut off

- [x] Add 'Click to expand' _**in Italics**_ next to minimised brief

- [x] subject circle should move down to be centred heightwise

- [x] title move with and 'Set aside text moves up to be closer to title

- [x] chevron instead of play

**INVESTIGATION**

- [x] Short Answer: placeholder and typing centred height and width

- [x] round short answer corners a bit more

- [x] Subject is cut off because of number circles

**PROVISIONAL SCORE**

- [x] ticks and crosses should be aligned with numbers

- [x] 6vw for numbers

- [x] hint width and short answer width should be same margin as reg text

**SYNTHESIS**

- [x] same header as prep

- [x] remove prep button

**FINAL SCORE**

- [x] text is 'Final Score'

- [x] remove prep button

**FINAL STEP**

- [x] move green star button down

- [x] assign brick icon should be thinner (same as hare icon)

- [x] GREY BAR: Add Exit text in bold, quite big

move that red button up a bit so centred heightwise

**Comment by ivanromakh** [comment]
@SashaScholar6  short answer
![image](https://user-images.githubusercontent.com/18567511/109953772-2979bb80-7ce9-11eb-8126-a70712b592ec.png)

**Comment by ivanromakh** [comment]
@SashaScholar6 actually I am not sure about exit full screen button. now if there is ability to enter full screen it enter full screen and lock display for phones.
