### ISSUE TITLE
Can't test in browser's mobile view because full-screen lock isn't supported, throws an error.

### ISSUE THREAD

**Issue by william-gooch** [Scholar-6/brillder#2890]
![image](https://user-images.githubusercontent.com/40644139/109941753-620a9c80-7ccb-11eb-8efb-d18d808d823b.png)

**Comment by ivanromakh** [comment]
@william-gooch which phone is it?

**Comment by william-gooch** [comment]
@ivanromakh all of them. When I press anywhere on the screen after a refresh, the browser first goes full screen, then throws the above error.
Maybe we need a check for user agent? Or just check whether the screen orientation feature is supported before using it?

**Comment by ivanromakh** [comment]
@william-gooch in mine android phone it works good.

**Comment by ivanromakh** [comment]
@william-gooch we need to merge mobile into development

**Comment by william-gooch** [comment]
I've tested it in Chrome, and it still throws the error in the console, it just doesn't crash the application 
![image](https://user-images.githubusercontent.com/40644139/109943380-0b9e5d80-7ccd-11eb-89e3-5c00f23ebfb3.png)
For firefox it actually causes the app to crash.
Either way I think we still need some kind of check to make sure this doesn't crash.
