### ISSUE TITLE
Mobile tweaks

### ISSUE THREAD

**Issue by SashaScholar6** [Scholar-6/brillder#2897]
Screenshot_2021-03-04-15-28-18-961_com.android.chrome.jpg

3:32
Great work on mobile play :)
Small tweaks:

- [x] 1.text and numbers in review should be lower (same as in investigation) - at the moment they are slightly higher

- [ ] 2. Left chevron doesn't do anything on question 1. May as well remove I think.

3:33
Image from Android 
Image from Android

3:35
EXIT SCREEN

- [x] 3. **Assign brick should only be for teacher preference (if not teacher, move share down to be more central)**

- [x] 4. move red exit button slightly more up so centred heightwise

**Comment by ivanromakh** [comment]
@SashaScholar6 it moved to prep no?
![image](https://user-images.githubusercontent.com/18567511/109986061-14fbea00-7d0e-11eb-8725-7d5ffe1cd58e.png)
