### ISSUE TITLE
Investigation Build Page. Sub page for checking question type.

### ISSUE THREAD

**Issue by ivanromakh** [Scholar-6/brillder#29]

**Comment by ivanromakh** [comment]
Draggable
![image](https://user-images.githubusercontent.com/18567511/73257092-d1aa8000-41cb-11ea-8644-266f67458a4c.png)

**Comment by scholar6admin** [comment]
cool

**Comment by scholar6admin** [comment]
Small style thing but could you remove the black border at the bottom on the active tab so the number and the panel look joined up.

Like this on chrome
![image](https://user-images.githubusercontent.com/58778078/73257808-58eff780-41bc-11ea-9213-85bf3f484272.png)

**Comment by ivanromakh** [comment]
@scholar6admin Ok. And need to know about limitation. Like have many questions client can create. And if there should be scroll bar is there is too much questions?
![image](https://user-images.githubusercontent.com/18567511/73259591-c9a10f00-41d0-11ea-976c-12074460f882.png)

**Comment by ivanromakh** [comment]
@scholar6admin  For mobile I don`t know how many numbers I can show.

**Comment by ivanromakh** [comment]
Remove button will be only on active tab. its still raw in the image above

**Comment by ivanromakh** [comment]
![image](https://user-images.githubusercontent.com/18567511/73345779-5e694280-428d-11ea-8154-daa5c4526fb8.png)
