### ISSUE TITLE
Line Highlighting fixes

### ISSUE THREAD

**Issue by scholar6admin** [Scholar-6/brillder#2902]
https://scholar6.zendesk.com/agent/tickets/267

- [x] Line highlighting should have the 'br' icon to force lines to not break
![image](https://user-images.githubusercontent.com/58778078/116243519-eb37d000-a75e-11eb-8dc0-ca89d238a026.png)

- [x] When highlighter is clicked it should ask
![image](https://user-images.githubusercontent.com/58778078/116243562-f8ed5580-a75e-11eb-8fff-1a1617cc001a.png)

- [x] When l click the highlighter then the text should not lose its paragraph breaks between text

https://user-images.githubusercontent.com/58778078/116243705-21754f80-a75f-11eb-85a5-9a0ff607623c.mp4

- [x] On a phone (s9+ chrome) I should still see the empty lines between paragraphs of text

**Comment by ivanromakh** [comment]
@scholar6admin  I am not sure what this means. 
![image](https://user-images.githubusercontent.com/18567511/116257022-5ba11a00-a77c-11eb-8f4e-4cabbb46b4ae.png)

**Comment by ivanromakh** [comment]
@scholar6admin  I see empty lines
