### ISSUE TITLE
Teacher Marking experience

### ISSUE THREAD

**Issue by SashaScholar6** [Scholar-6/brillder#2910]
On Book should not have to click through all the pages to get to question 14 for every student in a class of 30

<img width="1085" alt="Screenshot 2021-03-18 at 13 43 48" src="https://user-images.githubusercontent.com/59654112/111628002-00c8ea00-87f0-11eb-99c0-7d1f402718a6.png">

- [x] style like phone, with 19336 light-blue bars top and bottom, white rings and triangles to show current question

- [x] should go to review by default

- [x] eyes
- [x] numbers from play
- [x] question and answers from book
- [x] investigation/review radio buttons
- [x] back next same as play
- [x] student, subject and title
- [x] 'x' blue by default red on hover

<img width="545" alt="Screenshot 2021-08-25 at 14 17 00" src="https://user-images.githubusercontent.com/59654112/130788954-4dbe45da-e535-47ab-9c29-40f3776d2dc2.png">

nice :) some tweaks:

- [x] move name and title further from top edge and a bit closer to numbers

- [x] add correct/incorrect text and circle with check or cross at top of question

- [x] back and next should have back chevron which animates on hover like desktop play

- [x] should become hand on hover (rather than pointer) for back, next and eye in main area

<img width="628" alt="Screenshot 2021-08-25 at 14 20 30" src="https://user-images.githubusercontent.com/59654112/130789433-c96e7ac2-c924-4262-8c1e-3b41b8a2d82a.png">

- [x] fix hint latex

<img width="598" alt="Screenshot 2021-08-25 at 14 20 59" src="https://user-images.githubusercontent.com/59654112/130789486-f8c18105-f70e-4c46-8d4e-c88a29e83d6c.png">

- [x] default 'x' should be white to close window (can't see it atm)

**Comment by ivanromakh** [comment]
@SashaScholar6 how does that popup upper?

**Comment by ivanromakh** [comment]
@SashaScholar6 there could be multiple attempts I don`t see ability to choose.

**Comment by SashaScholar6** [comment]
It should show the attempt corresponding to the score on the left
