### ISSUE TITLE
Fix websocket handshake

### ISSUE THREAD

**Issue by scholar6admin** [Scholar-6/brillder#2911]
![image](https://user-images.githubusercontent.com/58778078/110341492-4b917780-8022-11eb-9dce-16322527c0b3.png)

UPDATE. 

Closing this task and moving to test trello board for when Quill is deployed. 
https://trello.com/c/HCFO5iQs

**Comment by ivanromakh** [comment]
@scholar6admin It related to backend. Maybe env variable not correct for production it maybe we have another one.
Don`t have this problem with dev-api.
@william-gooch I switch it to you as it is something you were working on.

**Comment by william-gooch** [comment]
@scholar6admin do we have REACT_APP_WEBSOCKET_HOST set on production?
