### ISSUE TITLE
Adapt brick fixes

### ISSUE THREAD

**Issue by scholar6admin** [Scholar-6/brillder#2912]
- [x] After adapting a brick automatically refresh the data in the localcache (so no need to refresh the page)

- [x] When click adapt, automatically self publish brick (so it can be easily assigned)

- [x] Adapt a brick goes to url with :brickid and hangs

![Screenshot 2021-03-10 at 11 42 11](https://user-images.githubusercontent.com/59654112/110617203-b0211380-8195-11eb-8466-d1a6fd90718c.png)

**Comment by ivanromakh** [comment]
@SashaScholar6 there is some backend problems. response takes around 3-6second. I will add something to button to prevent multiple clicking.

**Comment by ivanromakh** [comment]
@SashaScholar6 this one is for backend
![image](https://user-images.githubusercontent.com/18567511/110788936-f3ec4980-8277-11eb-90f7-290a6e2de536.png)
@aromakh this request make it like in upper image. `/brick/adapt/` set isCore = false and status = publish.

**Comment by aromakh** [comment]
@ivanromakh done
