### ISSUE TITLE
Assignments fixes

### ISSUE THREAD

**Issue by SashaScholar6** [Scholar-6/brillder#2916]
SIDEBAR

- [x] long class should have ellipsis and tooltip with full name

- [x] Student Names should be regular size (bigger)

**class header**

- [x] buttons f5f6f7 light grey not white

- [x] assign new birck in regular not bold

- [x] add tooltips 'Edit Class Name or Subject' and 'Add New Student'

- [x] when click edit make background white, animate background to make transition smoother

- [x] keep same spacing in text while editing

**For individual student**

- [x] remove 0/0 and users icon

- [x] replace with 'Completed' or 'Not Attempted'

- [x] Avg: '—' not 0 if not attempted

- [x] circle yellow if not attempted, red if not attempted and past deadline, grey if completed

- [x] if no students, have create class button also in view all

- [x] make tooltips light blue with grey text

- [x] make general colour dark blue so we can see it

**Comment by ivanromakh** [comment]
@aromakh for this one I need status in assignment. https://dev-api.brillder.com/bricks/assignedTo/390
![image](https://user-images.githubusercontent.com/18567511/110484423-4f40ff00-80f3-11eb-82f0-f30ac1e152de.png)
![image](https://user-images.githubusercontent.com/18567511/110484775-a6df6a80-80f3-11eb-9be2-307fd53f5421.png)

**Comment by ivanromakh** [comment]
for this one I need status too
![image](https://user-images.githubusercontent.com/18567511/110484967-d4c4af00-80f3-11eb-875b-04fe60172edf.png)

**Comment by ivanromakh** [comment]
@aromakh I don`t see any changes in that request maybe pull request not merged.

**Comment by aromakh** [comment]
@ivanromakh 
Status will be in studentStatus array. It will contain only one item for the current student.
Not sure, if there is any case when array is empty.
