### ISSUE TITLE
Brillder.com updates

### ISSUE THREAD

**Issue by SashaScholar6** [Scholar-6/brillder#2917]
DESKTOP
https://xd.adobe.com/view/b30db25c-e99b-47da-bc38-99e41ecab830-e65e/

<img width="1802" alt="Screenshot 2021-03-09 at 15 33 37" src="https://user-images.githubusercontent.com/59654112/110487545-fa4eba00-80ed-11eb-9b8b-fdece56d0829.png">

- [ ] 50% light blue circles on hover for linkedin, twitter; 50% white hover for mail

- [x] login register dark blue on hover

- [x] teacher button goes red on hover

- [x] student explore goes grey and red text on hover

- [x] animate second phone like deck of cards

- [x] animate teacher show me how and student explore to fade in after 1 or 2 seconds. 

<img width="1804" alt="Screenshot 2021-03-09 at 15 33 57" src="https://user-images.githubusercontent.com/59654112/110487560-fcb11400-80ed-11eb-90bc-f890f08c2861.png">

- [x] go here from landing teacher show me how button

- [x] sample unit button goes white with red text on hover

- [x] build great content goes red on hover
- [x] login register dark blue on hover

MOBILE
https://xd.adobe.com/view/f8effa94-7afd-42b9-b5bd-f333a2576412-adbc/ 

- [x] <img width="279" alt="Screenshot 2021-03-09 at 15 34 15" src="https://user-images.githubusercontent.com/59654112/110488359-b1e3cc00-80ee-11eb-94d8-60665b87534e.png">

- [x] <img width="279" alt="Screenshot 2021-03-09 at 15 34 26" src="https://user-images.githubusercontent.com/59654112/110488366-b314f900-80ee-11eb-8fb2-7096b72078e0.png">

**Comment by ivanromakh** [comment]
@SashaScholar6 what do you mean by white hover on mail. it is already white.
![image](https://user-images.githubusercontent.com/18567511/110617475-6d176e00-819e-11eb-9e9b-0c143f5aba90.png)
![image](https://user-images.githubusercontent.com/18567511/110617497-730d4f00-819e-11eb-90f2-9772b3dc31f8.png)

**Comment by SashaScholar6** [comment]
I mean 50% bigger circle behind (like play buttons have)

**Comment by ivanromakh** [comment]
@SashaScholar6 what there buttons should do?
![image](https://user-images.githubusercontent.com/18567511/110634365-8a563780-81b2-11eb-995a-9a93a319dfed.png)

**Comment by SashaScholar6** [comment]
- sample a brick goes to select subject page

- build great content will be a popup with an email field

will call you after lunch

**Comment by ivanromakh** [comment]
@SashaScholar6 page published here https://brillder.com/teachers/ buttons not clickable yet.
