### ISSUE TITLE
Cover Page Mobile

### ISSUE THREAD

**Issue by SashaScholar6** [Scholar-6/brillder#2918]
Mobile
https://xd.adobe.com/view/15199ba2-ed28-409c-a0d1-3c4932c0ef51-404a/

- [ ] <img width="374" alt="Screenshot 2021-03-09 at 17 19 03" src="https://user-images.githubusercontent.com/59654112/110502527-8f0be480-80fb-11eb-8632-46ca4914a8ef.png">

**not seeing this on mobile?**

Desktop
https://xd.adobe.com/view/04091e15-ca40-4e07-ba24-7e6dbda01d07-515a/ 

- [x] <img width="1438" alt="Screenshot 2021-03-09 at 17 19 35" src="https://user-images.githubusercontent.com/59654112/110502594-a0ed8780-80fb-11eb-9040-5290143c109e.png">

IMAGE

- [x] publisher can choose any image in the brick, or add a new one

**Comment by ivanromakh** [comment]
@aromakh we need method to add this image to brick. Do you have any idea?

**Comment by ivanromakh** [comment]
@SashaScholar6 only publisher should be able to add image to cover? builder should be restricted?

**Comment by SashaScholar6** [comment]
yes, only publisher or admin

**Comment by ivanromakh** [comment]
@SashaScholar6 its for play preview or play pages?

**Comment by SashaScholar6** [comment]
Hi Ivan, only for play

**Comment by ivanromakh** [comment]
@SashaScholar6 what is this red button?
![image](https://user-images.githubusercontent.com/18567511/111453299-1836a300-871c-11eb-8138-d4adf2c754e1.png)

**Comment by SashaScholar6** [comment]
yeah was worried that lookeed too much like a button.  It should just show brick number (id) as shown

**Comment by ivanromakh** [comment]
@SashaScholar6 what is this?
![image](https://user-images.githubusercontent.com/18567511/111456750-0b1bb300-8720-11eb-9dc8-dd6bc3a6bccf.png)

**Comment by SashaScholar6** [comment]
For those who commission bricks/partnerships. Either don't worry about it, or have Company name be Scholar 6 by default.

**Comment by aromakh** [comment]
@ivanromakh 
Do you need any changes from API?
