### ISSUE TITLE
After backend #453: register interest popup

### ISSUE THREAD

**Issue by SashaScholar6** [Scholar-6/brillder#2922]
LANDING
- [X]  50% light blue bigger circles on hover for linkedin, twitter; 50% white hover for mail

- [x] **mobile and desktop** make video window bigger and darken restof screen
<img width="1416" alt="Screenshot 2021-03-10 at 15 58 33" src="https://user-images.githubusercontent.com/59654112/110648954-78c45e00-81b9-11eb-9e89-99fa1dce61ef.png">

- [x] **mobile and desktop* add red circle with x to exit

BRILLDER FOR TEACHERS
- [X] button hover colour
<img width="1151" alt="Screenshot 2021-03-10 at 15 54 45" src="https://user-images.githubusercontent.com/59654112/110648370-f176ea80-81b8-11eb-922b-6b6f627ebd3d.png">

- [x] Popup says:
We'd love to meet you.  Give us your email and we'll be in touch shortly.
Email panel
create partial account

- [x] add cascade animation to this text

<img width="752" alt="Screenshot 2021-03-10 at 15 56 50" src="https://user-images.githubusercontent.com/59654112/110648700-3b5fd080-81b9-11eb-8305-19286b7dfd95.png">

- [x] for desktop only - remove we call them bricks and button is sample a unit in my subject

MOBILE LANDING
- [x] fix line for red shape

- [x] both buttons should be centred

- [x] move tech shool image left and down

- [x] remove hover circles for mobile

- [x] please align text on left hand side and make sure icons are also aligned and same size

<img width="275" alt="Screenshot 2021-03-11 at 15 16 35" src="https://user-images.githubusercontent.com/59654112/110800720-c81f9280-827c-11eb-82e2-3472681f3b69.png">

- [ ] http://swagger.scholar6.org/docs/#!/marketing/addEmailToMailchimp

- [ ] fix small popup in phone

- [ ] when typing, leave 'I want to build great content button at the bottom'

**Comment by ivanromakh** [comment]
@SashaScholar6  chimney animation is generalized it will be hard to move.
