### ISSUE TITLE
Onboarding updates

### ISSUE THREAD

**Issue by SashaScholar6** [Scholar-6/brillder#2924]
SIGNUP SCREEN
- [x] tsx to show Brandon in wheel

<img width="384" alt="Screenshot 2021-02-24 at 12 06 09" src="https://user-images.githubusercontent.com/59654112/108991762-c65ca900-7698-11eb-9a15-fba71a595605.png">

<img width="462" alt="Screenshot 2021-03-11 at 17 14 53" src="https://user-images.githubusercontent.com/59654112/110818160-4edc6b80-828d-11eb-9456-74f8c0de3580.png">

- [x] 'Click on...experience' smaller and brandon reg not bold

<img width="889" alt="Screenshot 2021-03-11 at 17 14 22" src="https://user-images.githubusercontent.com/59654112/110818240-6156a500-828d-11eb-9c2c-115ccbce1946.png">

- [x] instead of red stop tracking button nest in a popup from a settings/cog icon which is next to help button in maximised view (feather-settings)

- [x] default is white, similar height to button, red on hover

- [x] when clicked, popup triggered.  ‘Cookies are currently enabled.’ buttons: ‘Keep exploring’ / ‘Disable and stop session’    

- [x] If you accept, then change your mind, you can click the settings icon in the bottom left and choose to ‘Disable and stop session’.

<img width="1354" alt="Screenshot 2021-03-11 at 17 26 11" src="https://user-images.githubusercontent.com/59654112/110819859-e1313f00-828e-11eb-8f98-4edb2a3d5660.png">

- [x] when sidebar minimised (eg during play), put cog icon above zendesk circle

<img width="1123" alt="Screenshot 2021-03-11 at 17 27 31" src="https://user-images.githubusercontent.com/59654112/110820131-1b9adc00-828f-11eb-8c9d-7539a4cf7494.png">

- [x] restore placeholder search to left as before (give to @farmanahmed2007 to do this point if you wish)

**Comment by ivanromakh** [comment]
@SashaScholar6 I am not sure about that popup. need more details. Why two buttons. what second button should do, which one is accept button.

**Comment by SashaScholar6** [comment]
Cookies are currently enabled is popup title. Disable is effectively stop tracking button.

**Comment by ivanromakh** [comment]
@SashaScholar6 Lindsay changed popup. Is this task still valid except wheel svg?

**Comment by ivanromakh** [comment]
@SashaScholar6 about wheel svg there is some images inside and svg is very big.

**Comment by SashaScholar6** [comment]
Would image being a PNG work?

**Comment by SashaScholar6** [comment]
Only bit still valid is about putting cog above help button in minimised sidebar (like during investigation)

**Comment by ivanromakh** [comment]
@SashaScholar6 Yep png will work but svg is better. I added @farman9849 here maybe he have some solution. 
@farman9849 branch is wheel if you can add images in svg wheel then good.

**Comment by ivanromakh** [comment]
@SashaScholar6 need png for that svg.
