### ISSUE TITLE
Unauthenticated flow

### ISSUE THREAD

**Issue by SashaScholar6** [Scholar-6/brillder#2927]
- [x] view all on hover glasses should be visible and white

- [x] When I click View All, make title 'All bricks'

- [x] Don't show everything as selected in white

- [x] Instead show bricks stacked by subject with most bricks first - then when subject clicked filter and subject title show as normal (instead of having to deselect everything)

- [x] replace view all with current affairs (which will then become general & topical)

- [x] Subjects 'X' should show in white bar when something is selected.  Blue by default, red on hover.  Remove animation

- [x] suggested subjects should be much higher so close to 'Try one of the following'
<img width="1098" alt="Screenshot 2021-03-23 at 16 49 51" src="https://user-images.githubusercontent.com/59654112/112175844-e0d26580-8bf7-11eb-8eaf-bae36cbcf497.png">

- [x] Same with up down chevrons - blue default, red hover

- [x] should be able to stack subjects like before

- [x] fix cut off of brick scrolling

- [x] **Add All Radio button on left of white bar** that selects and stack all subjects in order of brick number (like View All before)

<img width="272" alt="Screenshot 2021-03-19 at 14 35 58" src="https://user-images.githubusercontent.com/59654112/111788478-6d131e80-88c0-11eb-9a4f-3805fda2fcb9.png">

<img width="211" alt="Screenshot 2021-03-23 at 11 59 47" src="https://user-images.githubusercontent.com/59654112/112136467-452cff00-8bcf-11eb-9aa3-726fa964f2c3.png">

- [x] click on ... font smalller

- [x] cog higher to be level with zendesk and more to the right

- [x] **Add login / register like website with white and red hover**

**Comment by ivanromakh** [comment]
@SashaScholar6 those are hard to understand.

**Comment by SashaScholar6** [comment]
Sorry they were notes from a call. Will show you after lunch. You've got enough to keep you busy for the next 45 mins or so?
