### ISSUE TITLE
Reminder buttons

### ISSUE THREAD

**Issue by SashaScholar6** [Scholar-6/brillder#2932]
- [x] for assignments, notification for now, (there will be a email)

- [x] add yellow 50% hover behind and tooltip saying 'Send Reminder' or 'Send Reminders' (not Archive Brick)

<img width="176" alt="Screenshot 2021-03-16 at 19 54 24" src="https://user-images.githubusercontent.com/59654112/111364413-79fdfb00-8691-11eb-9e5c-df0e2941f8f2.png">

- [x] white popup reminder if one student, reminders if more than one

- [x] same icon not tick 

- [x] fix notification styling, yellow icon if within deadline, red if not

- [x] when notification clicked, take student to intro page

- [x] add 50% red circle and tooltip when reminder button red

- [x] 'Archived' and add numbers to Live Bricks and Archived

<img width="297" alt="Screenshot 2021-03-17 at 12 41 50" src="https://user-images.githubusercontent.com/59654112/111461995-2b4a7280-871e-11eb-8c2d-9ad203e3d449.png">

- [x] light blue tooltip, red hover and white icon for edit class button

**Comment by aromakh** [comment]
Hi @ivanromakh 
what should I implement there?)
