### ISSUE TITLE
Colour dropdown coming up behind text component on dev-app

### ISSUE THREAD

**Issue by scholar6admin** [Scholar-6/brillder#2940]
As a builder
When I click on text color
Then the panel shows up underneath the text area and is not really clickable

![image](https://user-images.githubusercontent.com/58778078/111017689-dcfb4380-83ac-11eb-90b7-fb8b9341400f.png)

**Comment by william-gooch** [comment]
@ivanromakh some weird CSS thing is happening with z-index. Any chance you could take a look at this, I can't seem to figure it out.

**Comment by ivanromakh** [comment]
@william-gooch I will as soon as I can login.
