### ISSUE TITLE
Notification Popup causes issues with View All and Manage Classes pages on Firefox.

### ISSUE THREAD

**Issue by william-gooch** [Scholar-6/brillder#2956]
![image](https://user-images.githubusercontent.com/40644139/111285522-21027880-8639-11eb-9da4-d17119acca4e.png)

As above, entire tab section is shifted downwards and you need to scroll to reach it.

**Comment by ivanromakh** [comment]
@william-gooch I don`t see this issue in firefox.
![image](https://user-images.githubusercontent.com/18567511/111495188-cb68c180-8747-11eb-8e46-075c22a1e4b2.png)

**Comment by ivanromakh** [comment]
@william-gooch try to pull changes yours branch seems old. maybe its fixed.

**Comment by ivanromakh** [comment]
@william-gooch I somehow trigered that notification but have no overflow.
![image](https://user-images.githubusercontent.com/18567511/111501125-5e582a80-874d-11eb-84a4-4acd0511575e.png)
