### ISSUE TITLE
Final brick attempt is storing review score instead of total score

### ISSUE THREAD

**Issue by scholar6admin** [Scholar-6/brillder#2961]
Still happening on brick on preprod 14-05-2021

https://dev-mobile.brillder.com/post-play/brick/804/422

This brick called chemistry test
1. First answer 720 (correct)
2. Second answer not given (incorrect)
Review
3. First answer 720 (correct)
4. Second answer 11.4 (correct
Final score is 75%

Book shows 100%

![image](https://user-images.githubusercontent.com/58778078/111298590-d12aae00-8646-11eb-9bb9-43d8143bcefa.png)

**Comment by ivanromakh** [comment]
@aromakh @william-gooch  what is old score. is it live score or review score?
![image](https://user-images.githubusercontent.com/18567511/118468486-7e847580-b70d-11eb-91c3-89bba8322812.png)
