### ISSUE TITLE
Teacher-Student Onboarding

### ISSUE THREAD

**Issue by SashaScholar6** [Scholar-6/brillder#2962]
GENERAL

- [x] 'Get your username' instead of 'Generate a username'
- [x] select-subjects: if subjects selected, don't show general in profile page / only select general by default on profile if no subjects selected

<img width="678" alt="Screenshot 2021-03-16 at 14 48 47" src="https://user-images.githubusercontent.com/59654112/111319865-ba944f00-8666-11eb-982a-9b34bce8b52c.png">

- [x] name and surname should be lower so closer to lines

- [x] chevron should be further from get started

- [x] edit icons should be higher so slightly above height of lines - with tooltips saying 'Edit First Name' and 'Edit Last Name'

- [x] generate button and get started should be a bit higher

TEACHER

- [x] go to home screen after select-subjects, grey out (well blue out) all other icons except Manage Classes

- [x] clicking reports should not show 'we need a bigger boat' - instead 'Hold tight, we're working on making this feature available to you soon' with red circle and alert triangle

- [x] add intro.js for manage classes icon with text saying 'Click on the Manage Classes icon to begin'

- [x] Teacher gets taken to assignments tab by default, and creates class from there (same buttons and flow as current students)

- [x] Add create class button to Assignments sidebar

STUDENT

- [x] After account activation (from teacher invitation) goes straight to profile page? 

- [x] Flow should be restored, ie: 1. terms, 2. User Pref with student button preselected 

- [x] Flow cont: 3. select-subjects with 'What kind of bricks will you play?' (subject of class or brick pre-selected)

- [x] Then go to homepage

**Comment by ivanromakh** [comment]
@SashaScholar6 about teacher what do you mean by grey out. only change color?
![image](https://user-images.githubusercontent.com/18567511/111311759-4312ef80-8667-11eb-93f8-7e552e019a1b.png)

**Comment by SashaScholar6** [comment]
teacher won't be able to assign without inviting people, so think that's fine.  They will have the option to assign from manage classes.

Yes make other icons 193366

**Comment by ivanromakh** [comment]
@SashaScholar6 I don`t undesrtand. after teacher complete onboarding he goes to home page. If I do as you say I will need to make a long chain to show that intro js message. or I will be showing that intro js message every time.

**Comment by SashaScholar6** [comment]
I'm suggesting the following:

1. Terms
2. User Pref - selects teacher
3. Select-Subjects
4. Homepage with intro-js over manage classes icon (others blue) - maybe just needs a new url?
5. After clicking manage classes gets taken to assignments tab, where option is to create a class

**Comment by ivanromakh** [comment]
@SashaScholar6 its only for desktop?

**Comment by SashaScholar6** [comment]
good point. 1, 2 and 3 should be mobile also. 4 & 5 will have to wait as manage classes not working on mobile yet
