### ISSUE TITLE
Cookie popup not showing on mobile view

### ISSUE THREAD

**Issue by scholar6admin** [Scholar-6/brillder#2976]
Still not showing on Dev-app 15th April 2021
Iphone xs with safari and chrome
![image](https://user-images.githubusercontent.com/58778078/113911381-d3a99f00-97d1-11eb-8ef4-815c8c1eba68.png)
https://live.browserstack.com/dashboard#os=iOS&os_version=14.0&device_browser=safari&zoom_to_fit=true&full_screen=true&url=https%3A%2F%2Fdev-app.brillder.com%2Fplay%2Fbrick%2F409%2Fnew-prep&speed=1

**Comment by ivanromakh** [comment]
I see its not showing only in some pages.
![image](https://user-images.githubusercontent.com/18567511/114061931-9dd2ec00-989f-11eb-8878-7d807dfe4cbc.png)

**Comment by ivanromakh** [comment]
@scholar6admin maybe you tested it in production. I don`t see it only production or once you accepted it. you can only disable it from play.
