### ISSUE TITLE
Preselect subjects based on teacher class

### ISSUE THREAD

**Issue by scholar6admin** [Scholar-6/brillder#2977]
Instead of passing meta data on the subject in the token link. Lets save the subject in the database when the partial user is created. 

As a student 
When I am invited by a teacher
And I click on the activation link
Then I should see the subjects of the classes I have been invited to preselected on the subjects page. 

![image](https://user-images.githubusercontent.com/58778078/111395238-497b8880-86b4-11eb-8ecb-125bf1ed8331.png)

**Comment by ivanromakh** [comment]
@SashaScholar6 I can`t do it. @william-gooch was working on it. I need backend first to do something there.

**Comment by SashaScholar6** [comment]
@ivanromakh ok no problem thank you.

**Comment by scholar6admin** [comment]
Doesn't seem to be working on dev-app
I created 3 teachers in english, french and economics and invited this student to 3 different classes with bricks
But only one subject was preselected when I clicked on the signup link as the student
![image](https://user-images.githubusercontent.com/58778078/115427375-53376500-a1f9-11eb-9e3c-8522d427a75e.png)

**Comment by william-gooch** [comment]
That is as intended. You should be able to select the subject for the class you have clicked on (using the metadata in the token) but when you **accept** an invitation for other classes.
