### ISSUE TITLE
Activated account link does not allow login with Google.

### ISSUE THREAD

**Issue by scholar6admin** [Scholar-6/brillder#2981]
- [x] Add a page to show google login or email login
- [x] prefill email with email for activation

If you arrive at /activateaccount page with a specific email can we restrict Google oauth to only authenticate with that email to make sure that the Google email and the email in our database are consistent. 

It has become apparent that students in school may often forget passwords (perhaps to get out of doing work). So we need to make sure that oauth is just as easy as username and password. 

As a user
When I click the activate account link in an invitation email
And I select Google
Then it redirects to normal login

# Additional test cases
signup with gmail -> login with email
~~signup with gmail -> signup with email~~
signup with gmail -> email password reset
signup with email -> login with gmail
signup with email -> signup with gmail

**Comment by ivanromakh** [comment]
it is impossible to select google in activation account link. you can`t select google you can only type password.

**Comment by ivanromakh** [comment]
@scholar6admin this is backend problem no?

**Comment by ivanromakh** [comment]
@scholar6admin there is no ability to active google account they can only activate email account. for google activation we need update in backend side.
