### ISSUE TITLE
Clicking on notification "user completed your assignment" goes to bluescreen timeout

### ISSUE THREAD

**Issue by scholar6admin** [Scholar-6/brillder#2982]
![image](https://user-images.githubusercontent.com/58778078/111396162-729d1880-86b6-11eb-8681-dff7ae5b8322.png)

Consider limiting the number of 'completed your assignment' notifications to stop flooding of the teacher with notifications.

**Comment by ivanromakh** [comment]
can`t reproduce it. Something could be wrong with attempt or it was removed from database.

**Comment by ivanromakh** [comment]
for me it tells that attempt is not found in dev.
so it probably was removed from database. not a bug.
![image](https://user-images.githubusercontent.com/18567511/128315323-d1b683f9-c10d-43bd-82e8-378714fd7419.png)
