### ISSUE TITLE
Add Material UI to Frontend

### ISSUE THREAD

**Issue by scholar6admin** [Scholar-6/brillder#3]
Add Material UI

https://github.com/mui-org/material-ui

Review 3.x documentation here
https://v3.material-ui.com/demos/app-bar/

**Comment by ivanromakh** [comment]
@lindsaymacvean. There is already v4.8.3 for react.
I added to branch material-ui.
https://material-ui.com/getting-started/installation

**Comment by scholar6admin** [comment]
Brillant thankyou.
