### ISSUE TITLE
Add user preference to user management screen

### ISSUE THREAD

**Issue by scholar6admin** [Scholar-6/brillder#3004]
We have removed teacher, builder, student from roles column but we still need to see it so lets add a user preference column.

![image](https://user-images.githubusercontent.com/58778078/111624801-0caeaf00-87e4-11eb-9dba-3872a1b04d6e.png)

This is useful for marketing to see who has signed up.

**Comment by ivanromakh** [comment]
@scholar6admin maybe I can add them in roles colum like it was before S T or B letter?

**Comment by ivanromakh** [comment]
@aromakh I need rolePreference here.
![image](https://user-images.githubusercontent.com/18567511/113579868-8db3d600-962d-11eb-9a7b-6524b96bf4d2.png)

**Comment by aromakh** [comment]
@ivanromakh  done, rolePreference is added.
