### ISSUE TITLE
New Play experience

### ISSUE THREAD

**Issue by SashaScholar6** [Scholar-6/brillder#3010]
https://xd.adobe.com/view/653d24b5-bb82-4785-acba-3bc7def7904d-306e/

<img width="720" alt="Screenshot 2021-03-19 at 15 05 56" src="https://user-images.githubusercontent.com/59654112/111792504-9c2b8f00-88c4-11eb-8f68-b5091ea432f5.png">

- [x] COVER: **SUBJECT (at the moment all showing as Religion and Philosphy)**

<img width="1440" alt="Screenshot 2021-03-19 at 15 06 25" src="https://user-images.githubusercontent.com/59654112/111792588-ae0d3200-88c4-11eb-938f-ab452dec578c.png">

- [x] SECTIONS

<img width="1440" alt="Screenshot 2021-03-19 at 15 06 52" src="https://user-images.githubusercontent.com/59654112/111792656-be251180-88c4-11eb-8acf-0656df2bc116.png">

- [x] BRIEF: use same cascading animation as on Brillder for teachers landing for text and circles on left

<img width="721" alt="Screenshot 2021-03-19 at 15 08 06" src="https://user-images.githubusercontent.com/59654112/111792820-ea409280-88c4-11eb-8686-ba786c466f8b.png">

- [x] PRE-PREP (static bar)

<img width="1440" alt="Screenshot 2021-03-19 at 15 11 00" src="https://user-images.githubusercontent.com/59654112/111793190-515e4700-88c5-11eb-9a3e-63ef089aad71.png">

- [x] **NEW PREP**. prep button in sidebar should redirect to here

<img width="1440" alt="Screenshot 2021-03-19 at 15 11 39" src="https://user-images.githubusercontent.com/59654112/111793294-69ce6180-88c5-11eb-907c-0ed7be59e16b.png">

- [x] PRE-INVESTIGATION (static bar), animation for text and circle on left

<img width="1439" alt="Screenshot 2021-03-19 at 15 12 37" src="https://user-images.githubusercontent.com/59654112/111793416-8bc7e400-88c5-11eb-9c35-aa9649eb17d0.png">

- [x] investigation countdown

<img width="1440" alt="Screenshot 2021-03-19 at 15 12 59" src="https://user-images.githubusercontent.com/59654112/111793471-98e4d300-88c5-11eb-9724-3ba334455dbd.png">

- [x] Add total time next to bar (text doesn't change, only bar changes)

<img width="1440" alt="Screenshot 2021-03-19 at 15 14 28" src="https://user-images.githubusercontent.com/59654112/111793698-cd588f00-88c5-11eb-8414-e14195e9dee2.png">

- [x] Provisional Score

<img width="1439" alt="Screenshot 2021-03-19 at 15 14 52" src="https://user-images.githubusercontent.com/59654112/111793759-dba6ab00-88c5-11eb-97f4-a07ee67ae0f8.png">

- [x] Pre-synthesis (static bar)

<img width="721" alt="Screenshot 2021-03-19 at 15 15 21" src="https://user-images.githubusercontent.com/59654112/111793823-ed884e00-88c5-11eb-97c0-fee7969df82e.png">

- [x] SYNTHESIS: bar on top, new margins and bottom bar

<img width="722" alt="Screenshot 2021-03-19 at 15 15 57" src="https://user-images.githubusercontent.com/59654112/111793895-02fd7800-88c6-11eb-9e06-a75a97f533d6.png">

- [x] PREREVIEW: static bar

<img width="1439" alt="Screenshot 2021-03-19 at 15 16 19" src="https://user-images.githubusercontent.com/59654112/111793976-101a6700-88c6-11eb-817b-90d3a2b1393c.png">

- [x] REVIEW COUNTDOWN

<img width="1439" alt="Screenshot 2021-03-19 at 15 17 32" src="https://user-images.githubusercontent.com/59654112/111794166-3b9d5180-88c6-11eb-9d50-c178f49bd1d6.png">

- [x] Review add review length text (static text, moving bar like investigation)

<img width="1439" alt="Screenshot 2021-03-19 at 15 18 53" src="https://user-images.githubusercontent.com/59654112/111794348-6be4f000-88c6-11eb-9224-df74031d392d.png">

- [x] Final score: bottom bar, text, range in center

**Comment by ivanromakh** [comment]
@SashaScholar6 arrows aren`t good. they move to left and right sides.
![image](https://user-images.githubusercontent.com/18567511/112129851-81149400-8bd0-11eb-8eb7-659087a50f65.png)

**Comment by ivanromakh** [comment]
@SashaScholar6 its better to use some library to make those arrows like this one.https://github.com/sasza2/react-arrows#readmehttps://codesandbox.io/s/stoic-perlman-6php9
