### ISSUE TITLE
Bricks build page should only be visible/editable by author, invited editor (s),publisher, admin

### ISSUE THREAD

**Issue by scholar6admin** [Scholar-6/brillder#3015]
![image](https://user-images.githubusercontent.com/58778078/111828384-1f5bdd80-88e3-11eb-9337-2df432771e92.png)

Should not be editable or viewable

**Comment by william-gooch** [comment]
It shouldn't be visible? What should it do instead, just redirect to the home page?

I've fixed it so it's not editable, but I'm not sure about a redirect - it's still *visible* even on mobile so it's not a quill thing.

**Comment by william-gooch** [comment]
@SashaScholar6 bump

**Comment by william-gooch** [comment]
@SashaScholar6 please respond to the comment above.
