### ISSUE TITLE
Plan Tab, then remove plan book

### ISSUE THREAD

**Issue by SashaScholar6** [Scholar-6/brillder#3020]
<img width="1371" alt="Screenshot 2021-03-19 at 20 37 22" src="https://user-images.githubusercontent.com/59654112/111833834-022f0b00-88f3-11eb-8af7-35a68b350721.png">

**Comment by ivanromakh** [comment]
@SashaScholar6 what about tutorial?

**Comment by SashaScholar6** [comment]
<img width="1440" alt="Screenshot 2021-03-29 at 11 46 42" src="https://user-images.githubusercontent.com/59654112/112826168-89634800-9084-11eb-87ae-d4e2be1b1b4c.png">

@ivanromakh can we hide grey add comment circle first time builder sees screen? (could be confusing as also has a plus icon in it)

**Comment by ivanromakh** [comment]
@SashaScholar6 what is that icon in plan tab?

**Comment by SashaScholar6** [comment]
Feather-map
