### ISSUE TITLE
Refactor dialog system so there aren't as many hidden components being rendered.

### ISSUE THREAD

**Issue by william-gooch** [Scholar-6/brillder#3022]
Currently we render lots of separate dialog components, each of them totally different and for different purposes.
Building a new component for every dialog we create is quite inefficient in terms of development time, so I think it's a good idea to create a more general dialog API.
Possible idea: root dialog that takes props from context.
![image](https://user-images.githubusercontent.com/40644139/111970174-eabe7080-8af2-11eb-988e-578dc7693e6d.png)

**Comment by ivanromakh** [comment]
@william-gooch Yep. I have BaseDialogWrapper component for this. but there is a lot of different buttons in dialogs. like text and styles so I give up on it. it will take 50props to make this wrapper work.

**Comment by ivanromakh** [comment]
@william-gooch maybe we can create few dialog providers for different dialogs maybe.

**Comment by william-gooch** [comment]
@ivanromakh My thought was for unique dialog components we can have an InnerComponent prop like some material-ui components do.

I know we have BaseDialogWrapper but it's not widely used, and it still requires rendering a separate component for each dialog - my thought was, we could have a single root dialog component whose props are changed based on context, and then have a function which shows that dialog.

**Comment by ivanromakh** [comment]
@william-gooch Ok I will group simillar popups then.
