### ISSUE TITLE
Refactor investigationBuildPage

### ISSUE THREAD

**Issue by william-gooch** [Scholar-6/brillder#3029]
Currently this file is quite bloated and overcomplicated, with many properties being recalculated every render.
I think it would be beneficial to wrap a lot of these properties in memos, and extract some of these functions to a separate service, and so on.

**Comment by ivanromakh** [comment]
@william-gooch is it in development or mobile branch?

**Comment by william-gooch** [comment]
I'd say in development because Quill did change a lot of the code there.
