### ISSUE TITLE
Cover page: Mobile version and UI improvements

### ISSUE THREAD

**Issue by SashaScholar6** [Scholar-6/brillder#3036]
**Mobile**
https://xd.adobe.com/view/15199ba2-ed28-409c-a0d1-3c4932c0ef51-404a/

- [x] <img width="374" alt="Screenshot 2021-03-09 at 17 19 03" src="https://user-images.githubusercontent.com/59654112/110502527-8f0be480-80fb-11eb-8632-46ca4914a8ef.png">

**not seeing this on mobile?**<img width="1001" alt="Screenshot 2021-03-23 at 13 26 01" src="https://user-images.githubusercontent.com/59654112/112145988-53811800-8bdb-11eb-8d6f-932ca7f6dd00.png">

POPUP TEXT (hovering over red question marks)
**On hover, in 193366 blue (white text)**

What is a brick?

- [x] For below, place numbers in white circles, font Brandon Bold dark blue

TEXT IN POPUP
- [x] **A brick is a learning unit that should take either 20, 40, or 60 minutes to complete.** 

Bricks follow a cognitively optimised sequence:

1 **Preparation:** stimulus content gets you in the zone.
2 **Investigation:** challenging interactive questions make you think.
3 **A preliminary score**
4 **Synthesis:** explanation.
5 **Review:** hints help you correct your answers.
6 **A final score**

7 If you are signed up, your brick will transform into a book in your personal library.  Bricks can be replayed from start to finish, so you can revise what you've learned and improve your score. 

**On hover, in 193366 blue (white text)**

LEVELS

- [x] As above, place numbers in white circles, font Brandon Bold dark blue

TEXT in popup
- [x] **Brillder focusses on universal concepts and topics, not specific exam courses.** 

**LEVELS**
**I      Foundation**  
For 15-16 yr-olds, equivalent to GCSE / IB Middle Years / High School Diploma

**II & III      Core**
For 17-18 yr-olds, equivalent to A-level / IB / High School Honors 

**IV      Extension**
College / Undergraduate level, to challenge Oxbridge (UK) or Advanced Placement (US) students

IMAGE
- [x] height should be fixed so not scrollable

- [ ] have a preview like linkedin

**Comment by ivanromakh** [comment]
@SashaScholar6 I don`t get it. I don`t see white circles?

**Comment by ivanromakh** [comment]
@SashaScholar6 this is hard to understand. first you tell text is white in blue box then you tell text is dark blue in blue box?
![Uploading image.png…]()

**Comment by ivanromakh** [comment]
@SashaScholar6 mobile cover page restored.
![image](https://user-images.githubusercontent.com/18567511/113308939-57194b00-930f-11eb-844d-48119a44f7ce.png)

**Comment by SashaScholar6** [comment]
> @SashaScholar6 this is hard to understand. first you tell text is white in blue box then you tell text is dark blue in blue box?
> ![image](https://user-images.githubusercontent.com/18567511/113297823-c8eb9780-9303-11eb-83d3-c03bc454fbc1.png)
> 
> if popup background is light blue and text is blue. isn`t it hard to read?

That was about circles, hopefully clearer now.
