### ISSUE TITLE
When student plays assignment, I cannot see results as a teacher - student status [ ]

### ISSUE THREAD

**Issue by SashaScholar6** [Scholar-6/brillder#3037]
<img width="1741" alt="Screenshot 2021-03-22 at 17 26 12" src="https://user-images.githubusercontent.com/59654112/112125520-cf6f6600-8bc3-11eb-90be-ad40ac187e7b.png">

**Comment by william-gooch** [comment]
studentStatus should be blank if no-one has played the brick yet

**Comment by SashaScholar6** [comment]
@william-gooch this was after assigned brick was played by student unfortunately,

**Comment by aromakh** [comment]
@ivanromakh  please makesure assignmentId is properly passed to the API.
"/play/attempt"

**Comment by ivanromakh** [comment]
@aromakh done but student status still empty.
![image](https://user-images.githubusercontent.com/18567511/112168716-360f7680-8bfa-11eb-87ca-bb57617fce19.png)

**Comment by aromakh** [comment]
@SashaScholar6 
Fixed.
Scoring will appear only for new brick attemps.
