### ISSUE TITLE
When pending invite accepted, refresh student screen automatically

### ISSUE THREAD

**Issue by SashaScholar6** [Scholar-6/brillder#3038]

**Comment by william-gooch** [comment]
@SashaScholar6 I don't think this is a Quill task???

**Comment by SashaScholar6** [comment]
@william-gooch No, but part of Teacher Optimisation which is also a priority

**Comment by william-gooch** [comment]
@SashaScholar6 I don't understand why you keep moving this into the Quill queue, this isn't a Quill task?

**Comment by SashaScholar6** [comment]
@william-gooch you'll notice the column says 'William / Quill', and that it doesn't have a quill label.  Makes it easier for me to see what Ivan has going on when you've clocked off.
