### ISSUE TITLE
Popup Logic

### ISSUE THREAD

**Issue by SashaScholar6** [Scholar-6/brillder#3041]
**From brick / view all**
**ASSIGN**

<img width="1554" alt="Screenshot 2021-03-23 at 11 15 17" src="https://user-images.githubusercontent.com/59654112/112130715-0dbb5400-8bc9-11eb-9923-bdfc7afc3c3b.png">

- [x] 'Assign Brick' button blue by default, text in 193366

- [x] Select 'no deadline' by default

- [x] **Date of deadline should be from today's date, not before**

<img width="823" alt="Screenshot 2021-04-07 at 13 50 37" src="https://user-images.githubusercontent.com/59654112/113869132-469e2000-97a8-11eb-8b0b-ee0dd4d2e329.png">

- [x] fix dropdown width

**CREATE CLASS**

- [x] Subject field should be filled with first subject in profile by default

**Comment by ivanromakh** [comment]
@SashaScholar6 this was generalized...

**Comment by ivanromakh** [comment]
in mine it looks better and different? ...
![image](https://user-images.githubusercontent.com/18567511/114048983-b6d5a000-9893-11eb-8a3a-a51fa7c32f57.png)

**Comment by ivanromakh** [comment]
Did you ask Farman to fix this too?

**Comment by SashaScholar6** [comment]
@ivanromakh no, but day month and year should all be on the same line, and the width of each value (much narrower - only two characters for date and month and four for year
