### ISSUE TITLE
Assignments tab and reminder button

### ISSUE THREAD

**Issue by SashaScholar6** [Scholar-6/brillder#3043]
Waiting on #3261 

<img width="1917" alt="Screenshot 2021-03-23 at 11 30 14" src="https://user-images.githubusercontent.com/59654112/112132756-3a706b00-8bcb-11eb-9b0b-a3c21f0f1663.png">

- [x] Show pending users in expanded assignment view in alternating yellow bar underneath students who have accepted invitation

- [x] Make font of Question Number bigger and dark blue

- [x] Make font of Student Name much bigger

- [x] font of score in circle should be much bigger

- [x] cross should be a bit smaller and thicker
- [x] tick should be thicker

<img width="1513" alt="Screenshot 2021-03-23 at 12 06 19" src="https://user-images.githubusercontent.com/59654112/112137143-3004a000-8bd0-11eb-9379-dd1be6265bba.png">

**REMINDERS**

- [x] @william-gooch reminder notification should say 'You have been reminded to play BRICK TITLE by TEACHER NAME (not author name)

- [x] @ivanromakh notification circle should be yellow if not passed deadline

**Comment by ivanromakh** [comment]
@SashaScholar6 this one is for backend
![image](https://user-images.githubusercontent.com/18567511/114170797-17b8b300-993c-11eb-854b-bb97867e42fb.png)

**Comment by SashaScholar6** [comment]
@ivanromakh ok, feel free to assign @aromakh when done

**Comment by ivanromakh** [comment]
@aromakh In this request I need score in each assignment https://dev-api.brillder.com/bricks/byStatus/4

**Comment by ivanromakh** [comment]
@aromakh In this request I need number of assignments in each student https://dev-api.brillder.com/classrooms
