### ISSUE TITLE
iPad: remove all hovers

### ISSUE THREAD

**Issue by SashaScholar6** [Scholar-6/brillder#3046]
Ipad 8th generation with iOS 14
- [x] Home icon from all-subjects page
- [x] View & Play icon as student

### End
- [x] should only ned to click home button once

Test here 
https://live.browserstack.com/dashboard#os=iOS&os_version=14.0&device_browser=safari&zoom_to_fit=true&full_screen=true&url=https%3A%2F%2Flocal-brillder.brillder.com%3A3000%2Fhome&speed=1

**Comment by scholar6admin** [comment]
Still seems to be happening on an ipad air 4 running ios14

![image](https://user-images.githubusercontent.com/58778078/115417167-4f531500-a1f0-11eb-9a73-6a2ba915cf80.png)

**Comment by ivanromakh** [comment]
@scholar6admin I removed all hovers in css files which support tablets.
