### ISSUE TITLE
Play Fixes

### ISSUE THREAD

**Issue by SashaScholar6** [Scholar-6/brillder#3058]
- [x] Students and builders shouldn't have adapt and assign brick options in brief

- [x] update circles with slack svgs

- [x] 2.5 vw for back next, chevron 3vw

- [x] Click to expand next to brief should be dark blue and smaller font

- [x] **Remove old intro page, instead go back to new Prep and keep Resume logic (removing coutdown if resuming**

- [x] Cascade effect for sections, pre-investigation, pre-synthesis, pre-review.  And remove typewriter

- [x] cascade for circles and tooltips in brief 

- [x] fade into red from grey, like in choose one answer preview

- [x] if user tries to click red button, same as if clicking next

- [x] smooth opacity from 0-100, 100-0 for 3,2,1, GO! countdown

**Comment by SashaScholar6** [comment]
Play preview should show new Prep page, withe Brief expanded perhaps

**Comment by ivanromakh** [comment]
@SashaScholar6 this task could produce a lot of bugs. Lest do it after quill merge into production. This will take few days or more.
