### ISSUE TITLE
No in app notification when invited to class (had to go out to home screen)

### ISSUE THREAD

**Issue by scholar6admin** [Scholar-6/brillder#3064]
- [x] add to dashboard
- [x] add to library
- [x] add to back-to-work public and personal

**Comment by ivanromakh** [comment]
you mean reject button?
![image](https://user-images.githubusercontent.com/18567511/128138085-7892a646-0c10-4cc5-9ea5-398fc50e1e68.png)

**Comment by ivanromakh** [comment]
this is problem as there could be few invitations. what is there is another after you rejected one?
