### ISSUE TITLE
Phone Preview issues

### ISSUE THREAD

**Issue by SashaScholar6** [Scholar-6/brillder#3067]
<img width="1008" alt="Screenshot 2021-03-29 at 13 28 04" src="https://user-images.githubusercontent.com/59654112/112836965-2dec8680-9093-11eb-963f-0dff53d30fa6.png">

- [x] Latex doesn't render
- [x] Image doesn't render
- [ ] can we autoscroll phone with focus events (can be new task)?

**Comment by ivanromakh** [comment]
@SashaScholar6 I don`t see this problem. Is it fixed?
![image](https://user-images.githubusercontent.com/18567511/113127723-bef16800-9221-11eb-856c-abeeb70f9786.png)

**Comment by ivanromakh** [comment]
@SashaScholar6 about auto scroll lets do it later. build is already very slow. it will make it slower even more.

**Comment by ivanromakh** [comment]
@SashaScholar6 latex not working when copy pasting existing stuff. you need to type it every time.

**Comment by SashaScholar6** [comment]
I see, so maybe one for @william-gooch ? It will be handy for builders - we'll need to let them know if we release without that capability.

**Comment by SashaScholar6** [comment]
Ok we can look into speeding up build before autoscroll.  Anything you can do on that or is it mostly @william-gooch and @aromakh ?

**Comment by ivanromakh** [comment]
@SashaScholar6 I will check it.

**Comment by ivanromakh** [comment]
@SashaScholar6 I probably could fix it.
