### ISSUE TITLE
Add register interest white popup with mailchimp to website

### ISSUE THREAD

**Issue by SashaScholar6** [Scholar-6/brillder#3075]
This is so that we can launch our campaign for teachers, providing them a pathway to click and get their emails to then get in touch personally (after they have seen and been intrigued by our video, for instance)

<img width="1910" alt="Screenshot 2021-03-31 at 11 45 12" src="https://user-images.githubusercontent.com/59654112/113132584-8f892e00-9216-11eb-9cff-b364a9ba0c97.png">

- [x] in landing page, directly from Say Hello (replace mailto link)

![Uploading Screenshot 2021-03-31 at 11.45.25.png…]()

- [x] In teachers page, where button was, with text on button 'Register my interest'

- [x] add arrow and animate it so it floates like icons in login page

<img width="650" alt="Screenshot 2021-04-01 at 10 11 30" src="https://user-images.githubusercontent.com/59654112/113271738-be64da00-92d2-11eb-80c5-90324dfa9888.png">

MOBILE
- [x] http://swagger.scholar6.org/docs/#!/marketing/addEmailToMailchimp

- [x] fix small popup in phone

- [ ] when typing, leave 'Register my interest' button at the bottom - **see mobile view**

**Comment by ivanromakh** [comment]
@aromakh switched it to you. link in email is not good.

**Comment by aromakh** [comment]
@ivanromakh 
not sure about link in email.
We should use API ""/marketing/mailchimp/addEmail/:email"" to add user to Mailchimp

**Comment by aromakh** [comment]
@ivanromakh 
Now it works fine, your email is added to Mailchimp

**Comment by aromakh** [comment]
![image](https://user-images.githubusercontent.com/7169477/113276301-620cb500-92e8-11eb-9542-2f7719b3442c.png)

**Comment by ivanromakh** [comment]
@SashaScholar6 new design
![image](https://user-images.githubusercontent.com/18567511/113283771-62f61480-92f1-11eb-813a-a0e43dec3f05.png)

**Comment by ivanromakh** [comment]
@SashaScholar6 I am not sure what is this about.
![image](https://user-images.githubusercontent.com/18567511/113284104-d13ad700-92f1-11eb-989c-31abe8733322.png)
