### ISSUE TITLE
Quill styling

### ISSUE THREAD

**Issue by SashaScholar6** [Scholar-6/brillder#3085]
PLAN TAB

- [x] make font is plan preview phone much bigger

- [x] one line beneath keywords in phone

- [x] remove outline in keywords dropdown

- [x] more space between icons in toolbar

- [x] include italics for title

- [x] put clock into plan tab

- [x] Add Open Question top bar like for Brief and Prep

- [x] make youtube videos full width in plan tab with same margin as text

- [x] hover colour of toolbar icons 50%
- [ ] copy and pasting text shows grey background in phonee (Ivan can`t do anything about this one)

**Comment by ivanromakh** [comment]
@SashaScholar6 Last one was impossible for ckeditor. Maybe @william-gooch have some way.
