### ISSUE TITLE
Fix Build height/grid issue

### ISSUE THREAD

**Issue by SashaScholar6** [Scholar-6/brillder#3094]
<img width="1118" alt="Screenshot 2021-04-05 at 12 11 53" src="https://user-images.githubusercontent.com/59654112/113568295-32232180-9608-11eb-9d34-9382a96c244c.png">

**Comment by farmanahmed2007** [comment]
please do show URL in schreenshots

**Comment by farmanahmed2007** [comment]
cannot see the issue as it is in the screenshot on the tablet or desktop

**Comment by ivanromakh** [comment]
its happen in specific condition.

**Comment by farmanahmed2007** [comment]
The only issue is the page content is extending due to headers and giving scroll

**Comment by ivanromakh** [comment]
grid is expanding in wrong way.
![image](https://user-images.githubusercontent.com/18567511/113577915-b4bcd880-962a-11eb-8aad-16194db70119.png)

**Comment by farmanahmed2007** [comment]
Either we should limit the content according to page or arrange the view of the page so scroll wont appear

**Comment by ivanromakh** [comment]
fist column height should not be related to second and third one.

**Comment by ivanromakh** [comment]
draft bricks height is expending recording to big thing in second column.

**Comment by farmanahmed2007** [comment]
how many brick rows to show max in the bottom? after first column

**Comment by ivanromakh** [comment]
we don`t need rows only columns in each column probably should have 6 items

**Comment by farmanahmed2007** [comment]
but items are distributed with HTML vertically generally they would have to show after one another
I cannot control the amount of items with CSS, it can only be done with the amount of dynamic content that is being called

**Comment by farmanahmed2007** [comment]
![image](https://user-images.githubusercontent.com/36436724/113582029-4e8f8000-9641-11eb-82da-1e2c9a9c6b22.png)

**Comment by farmanahmed2007** [comment]
here you can see the issue, the content is coming dynamically vertical

**Comment by ivanromakh** [comment]
I see we need to change grid into columns to fix this.

**Comment by ivanromakh** [comment]
@farmanahmed2007 forget about this just make yellow and green container absolute position so they not affecting the image.

**Comment by ivanromakh** [comment]
If you make them absoute their height should not damage other stuff.
![image](https://user-images.githubusercontent.com/18567511/113582531-2a2ba780-9631-11eb-8c95-ea81d2f9072a.png)

**Comment by farmanahmed2007** [comment]
Done
