### ISSUE TITLE
Image in answer type fixes

### ISSUE THREAD

**Issue by SashaScholar6** [Scholar-6/brillder#3098]
TO DEPLOY TO MOBILE BRANCH so it can go to production

- [x] **Vertical shuffle 10vh fix and reduce padding between image and caption so image can be a bit bigger within height**

- [x] **Choose one 20 vh, image centred and caption underneath**

- [x] when adding an image into an answer type, only option I should have is to delete it (placeholder should not appear)

- [x] when image added, I should be able to click and see interface

- [x] If I add a caption, this caption should appear in work area below image (and image should appear too!)

- [x] If adding caption in image component, should it to me in work area also

- [x] Image in horizontal shuffle should not overflow

<img width="857" alt="Screenshot 2021-04-06 at 16 04 47" src="https://user-images.githubusercontent.com/59654112/113733980-d7b2bf80-96f2-11eb-8dab-56ba3f4876f8.png">

- [x] upload icon should be underneath caption - not overlaying (can make modal window bigger to allow this)

**Comment by ivanromakh** [comment]
@SashaScholar6 there is problem there is already delete button which appear when there is more than 4 questions. Where I should put delete image button?
![image](https://user-images.githubusercontent.com/18567511/113695114-2eab9b00-96d9-11eb-837d-00892aabd54f.png)
