### ISSUE TITLE
PLAN Fixes

### ISSUE THREAD

**Issue by SashaScholar6** [Scholar-6/brillder#3101]
CHOOSE SUBJECT

PLAN TAB

- [x] **space between icons should be regular**

- [x] image icon thicker

- [X] subject dropdown remove blue line and round bottom edges

- [x] Add Placeholders: TITLE: What is your brick about? / OPEN Q: Ideally, every brick should point to a bigger question. / BRIEF: Outline the purpose of this brick / PREP: Add engaging and relevant preparatory material

- [x] keywords in mobile should break lines rather than overflow and scroll right

<img width="841" alt="Screenshot 2021-04-06 at 12 23 54" src="https://user-images.githubusercontent.com/59654112/113703627-fdc86780-96d2-11eb-9511-31b840527103.png">

- [x] space between title and keywords should be same as elsewhere (less)

- [x] Pre-select first subject by default

- [ ] Next button higher

- [x] 'Next' text clickable

**Comment by ivanromakh** [comment]
@SashaScholar6 If I make few lines for keywords play button will not be visible. so should I do it? it is the only place where we show keywords for phones.
![image](https://user-images.githubusercontent.com/18567511/113865088-5f143780-97b4-11eb-9ad5-fd8d1ad07469.png)
![image](https://user-images.githubusercontent.com/18567511/113864998-4146d280-97b4-11eb-8d0b-9d8ee37a1827.png)

**Comment by ivanromakh** [comment]
@SashaScholar6 not sure about next button higher. There is no place for it.
![image](https://user-images.githubusercontent.com/18567511/113868479-63425400-97b8-11eb-8324-fd11c81fdc62.png)

**Comment by scholar6admin** [comment]
I am happy with this. Not sure what @SashaScholar6 wanted with the next button being higher but we can create another task for that.
