### ISSUE TITLE
Popup Styling Fixes

### ISSUE THREAD

**Issue by SashaScholar6** [Scholar-6/brillder#3104]
<img width="321" alt="Screenshot 2021-04-06 at 12 27 17" src="https://user-images.githubusercontent.com/59654112/113704014-80512700-96d3-11eb-9cf4-7b32b80c793a.png">

- [x] restore to previous styling, with title in one line, smaller red circle and icon 

<img width="628" alt="Screenshot 2021-04-07 at 15 00 15" src="https://user-images.githubusercontent.com/59654112/113878986-004dbe80-97b2-11eb-9739-8f8facdce60f.png">

- [x] check all of the above and restore

**Comment by farmanahmed2007** [comment]
do you have a design for this?

**Comment by farmanahmed2007** [comment]
and how are they going to appear on mobile

**Comment by ivanromakh** [comment]
@farmanahmed2007 this one is only for phones
![image](https://user-images.githubusercontent.com/18567511/114047388-542fd480-9892-11eb-9c91-f86a30ba72d9.png)

**Comment by ivanromakh** [comment]
this one don`t appear in phones at all.
![image](https://user-images.githubusercontent.com/18567511/114047500-64e04a80-9892-11eb-877f-0d306b188141.png)

**Comment by ivanromakh** [comment]
every popup in build page only for tablet and desktop.
