### ISSUE TITLE
First time builder create a brick - blue screen looping

### ISSUE THREAD

**Issue by scholar6admin** [Scholar-6/brillder#3114]
![image](https://user-images.githubusercontent.com/58778078/113763368-88c85280-9711-11eb-9768-e186d6b26c92.png)

Register as a new builder
Create a new brick
There should not be a blue screen

**Comment by ivanromakh** [comment]
@william-gooch this task was assigned on me....

**Comment by ivanromakh** [comment]
@william-gooch reasign to your self next time please.

**Comment by william-gooch** [comment]
@ivanromakh Ah! My bad, apologies. I was kind of just assuming that everything in the Quill queue was assigned to me without checking. Won't happen again.

**Comment by scholar6admin** [comment]
Excellent. Works on dev-app
