### ISSUE TITLE
Block image pasting using ctrl+v on open question and brief

### ISSUE THREAD

**Issue by scholar6admin** [Scholar-6/brillder#3121]
Still an issue on 9.10.0 
![image](https://user-images.githubusercontent.com/58778078/117671570-d74d8e80-b1a0-11eb-83f3-ed2120558488.png)

**Comment by ivanromakh** [comment]
this works for answers and any quill as well.

**Comment by ivanromakh** [comment]
for titles as well.
![image](https://user-images.githubusercontent.com/18567511/128167260-dfab9755-8efe-43d1-b84f-911b15d42d3f.png)
