### ISSUE TITLE
Can't intuitively delete an image added into plan

### ISSUE THREAD

**Issue by SashaScholar6** [Scholar-6/brillder#3130]
<img width="674" alt="Screenshot 2021-04-07 at 13 54 12" src="https://user-images.githubusercontent.com/59654112/113869626-d348de00-97a8-11eb-80ee-19396d36064e.png">

**Comment by ivanromakh** [comment]
@william-gooch I will try this one.

**Comment by william-gooch** [comment]
@SashaScholar6  what's the status of this one? Did you manage it @ivanromakh, or is it assigned to me now?

**Comment by ivanromakh** [comment]
@william-gooch Sasha wanna you to add trash button to delete images in quill.
