### ISSUE TITLE
Super slow investigation - rerendering issue

### ISSUE THREAD

**Issue by SashaScholar6** [Scholar-6/brillder#3132]
https://dev-app.brillder.com/build/brick/518/plan

**Comment by william-gooch** [comment]
@SashaScholar6 Not currently slow for me. Any specific question or was this already fixed?

**Comment by ivanromakh** [comment]
@william-gooch try ported bricks from production

**Comment by ivanromakh** [comment]
@william-gooch there is 20 000 of events sometimes you need to wait few seconds when you switch pages.

**Comment by ivanromakh** [comment]
@william-gooch try this brick https://dev-app.brillder.com/build/brick/513/investigation/question-component/202346

**Comment by SashaScholar6** [comment]
@william-gooch try this one for instance: https://dev-app.brillder.com/build/brick/518/investigation/question-component/207056
