### ISSUE TITLE
Build: Add Grey bars with titles for each component

### ISSUE THREAD

**Issue by SashaScholar6** [Scholar-6/brillder#3133]
<img width="425" alt="Screenshot 2021-04-07 at 15 28 41" src="https://user-images.githubusercontent.com/59654112/113883316-f1690b00-97b5-11eb-916b-e104ca719951.png">

- [x] 'Question Text' (top fixed component) - rounded panel and grey bar

- [x] 'Text' - round panel

- [x] 'Image' - grey bar and rest should be in lighter grey colour

- [x] 'Sound' - grey bar and rest should be in lighter grey colour

- [x] 'Graph' text should be same as rest (bigger and dark blue)

<img width="411" alt="Screenshot 2021-04-07 at 15 37 18" src="https://user-images.githubusercontent.com/59654112/113884771-2cb80980-97b7-11eb-9a73-2e7cb6b0f0a8.png">

- [x] graph should fit aligned with edges, not overflow

<img width="633" alt="Screenshot 2021-04-08 at 13 34 04" src="https://user-images.githubusercontent.com/59654112/114027318-25543700-986f-11eb-9aad-c51ec633a053.png">

- [x] Add Red Answers bar above all answer panels

- [ ] If only one short answer, then 'Answer' instead of 'Answers'

**Comment by ivanromakh** [comment]
@SashaScholar6 this one could will slow down this. Will do it later. 
![image](https://user-images.githubusercontent.com/18567511/114040485-542cd600-988c-11eb-9ef4-0a1537fa27c1.png)

**Comment by SashaScholar6** [comment]
Ok no problem
