### ISSUE TITLE
New student user cannot access library

### ISSUE THREAD

**Issue by scholar6admin** [Scholar-6/brillder#3134]
We need to send private bricks to anonymous users. 
When those users play and signup using the anonymous bricks they need to access the library and see the anonymous brick in the library. 

I have signed up as a new user
lindsaymacvean+student9@scholar6.org
password: password

When I click on my library to see the anonymous brick I just played it has a BSOD

![image](https://user-images.githubusercontent.com/58778078/114000178-a9e48c80-9852-11eb-9d96-1394dd3d321d.png)

![image](https://user-images.githubusercontent.com/58778078/114000217-b4068b00-9852-11eb-85d9-772136bbafdd.png)

**Comment by ivanromakh** [comment]
@scholar6admin I tried it but I didn`t get any problem with it.

**Comment by ivanromakh** [comment]
@scholar6admin from the image you send me there was problem in backend side.
![image](https://user-images.githubusercontent.com/18567511/114002099-3c8e2700-9865-11eb-8ec0-410e70262e48.png)

**Comment by ivanromakh** [comment]
@aromakh take a look at this 
![image](https://user-images.githubusercontent.com/18567511/114002532-a0185480-9865-11eb-9713-f4578530ff73.png)
