### ISSUE TITLE
White screen when clicking between question tabs

### ISSUE THREAD

**Issue by scholar6admin** [Scholar-6/brillder#3136]
https://dev-app.brillder.com/build/brick/334/investigation/question-component/37113

![image](https://user-images.githubusercontent.com/58778078/114019078-e5d51d00-9865-11eb-9824-9cae1cd6a924.png)

**Comment by ivanromakh** [comment]
this was related to image caption.

**Comment by ivanromakh** [comment]
Hm. image caption is also html?
it is now Y.Text. its good that I moved this in separated component. ease fix.
![image](https://user-images.githubusercontent.com/18567511/114023454-90a40600-987b-11eb-836b-97078abe6cad.png)
