### ISSUE TITLE
Set image height in Choose One/Several and Horizontal shuffle to 20vh

### ISSUE THREAD

**Issue by SashaScholar6** [Scholar-6/brillder#3137]
<img width="1203" alt="Screenshot 2021-04-08 at 13 13 10" src="https://user-images.githubusercontent.com/59654112/114024930-7f073200-986c-11eb-884d-7ceaf9946d32.png">
<img width="1197" alt="Screenshot 2021-04-08 at 13 13 17" src="https://user-images.githubusercontent.com/59654112/114024936-80385f00-986c-11eb-9c32-56b50bbcbabc.png">

- [x] ensure height does not cause image to stretch - keep padding on top and bottom

- [x] for horizontal shuffle, padding on left and right should be the same as on top and bottom

<img width="395" alt="Screenshot 2021-04-08 at 13 15 05" src="https://user-images.githubusercontent.com/59654112/114024942-80d0f580-986c-11eb-8d62-0a3476af04b4.png">

- [x] ideally 'x' should not overlap image: instead place in top right of answer panel, with image below

**Comment by ivanromakh** [comment]
@SashaScholar6 x button is generalized.
