### ISSUE TITLE
Blue screen when trying to get into build

### ISSUE THREAD

**Issue by SashaScholar6** [Scholar-6/brillder#3141]
See any of the bricks in red on this spreadsheet
https://docs.google.com/spreadsheets/d/1XujeK46859frVX001IiAAEDHkYE8sGCKUCE-u1TshgM/edit#gid=1236276701

They just show a BSOD with the loader
![image](https://user-images.githubusercontent.com/58778078/114320094-3d94b200-9b0c-11eb-947d-6bfde957a575.png)

**Comment by william-gooch** [comment]
@scholar6admin was this not fixed by https://github.com/Scholar-6/brillder/commit/b0897da1cb4b4cbedb96bedb3724385528ebdaa3 ?
I understand the wait is a bit long here - it's possibly to do with the fact that bricks on production *tend* to be longer, so they take longer to convert to yjs' format
