### ISSUE TITLE
Move Image interface fixes

### ISSUE THREAD

**Issue by SashaScholar6** [Scholar-6/brillder#3147]
IMAGE COMPONENT

<img width="704" alt="Screenshot 2021-04-09 at 15 20 05" src="https://user-images.githubusercontent.com/59654112/114194115-12ad3100-9947-11eb-8ab6-026c460dfa17.png">

- [x] add padding for left-align
- [ ] add image name in grey bar 
- [ ] hide strange dots

- [ ] remove proceed return popup and just have red 'x' in top right

IMAGES IN ANSWERS
<img width="856" alt="Screenshot 2021-04-09 at 15 23 38" src="https://user-images.githubusercontent.com/59654112/114194589-91a26980-9947-11eb-80b5-34312a96517a.png">

- [ ] add grey bar with filename and smaller button like bigger innterface

**Comment by ivanromakh** [comment]
it was hard to find it someone deleted it from commits. https://github.com/Scholar-6/brillder/blob/aa6923b141f908293a8b51b9def350e1ff1793db/src/components/build/buildQuestions/components/Image/ImageDialog.tsx
![image](https://user-images.githubusercontent.com/18567511/114703895-993e8580-9d2e-11eb-9bc6-5e6ae3d4b894.png)
somehow it got reverted?
https://github.com/Scholar-6/brillder/commit/a5fa8fbe37468f2cf6db69777921c46c5bb53e02

**Comment by SashaScholar6** [comment]
Oh oops, that was me being daft and not knowing what I was doing, sorry!
