### ISSUE TITLE
Set up source maps on datadog

### ISSUE THREAD

**Issue by scholar6admin** [Scholar-6/brillder#3154]
https://docs.datadoghq.com/real_user_monitoring/guide/upload-javascript-source-maps/?tab=webpackjs

This is needed so that we can diagnose errors without having a random chunk.js line

**Comment by ivanromakh** [comment]
I tried but failed. node_modules causing me errors. I will try again later.

**Comment by ivanromakh** [comment]
@scholar6admin I cleared project. Created branch according to instructions but its not working.
There is some errors. probably instruction is old.
After I removed all errors in project it show some error where I can`t fix it.
https://github.com/Scholar-6/brillder/tree/3154_empty_project
![image](https://user-images.githubusercontent.com/18567511/116400795-1f7cc080-a833-11eb-9885-24b645902d3d.png)

**Comment by ivanromakh** [comment]
https://docs.sentry.io/platforms/javascript/guides/react/sourcemaps/

**Comment by ivanromakh** [comment]
unminifying react. https://docs.sentry.io/platforms/javascript/guides/react/sourcemaps/
