### ISSUE TITLE
Fixes on plan

### ISSUE THREAD

**Issue by scholar6admin** [Scholar-6/brillder#3158]
- [x] Icons at top should be on left
- [x] No preview button

It looks right when you go back to it after getting 
![image](https://user-images.githubusercontent.com/58778078/114376978-0fe85100-9b7e-11eb-8e2c-aa10fdc54162.png)

- [x] when prep invalid rediect to the plan tab (not the plan panels)

<img width="264" alt="Screenshot 2021-04-14 at 15 12 48" src="https://user-images.githubusercontent.com/59654112/114724847-e2450880-9d33-11eb-8487-ec44eb6487ce.png">

- [x] remove 'your plan' button

**Comment by ivanromakh** [comment]
@SashaScholar6 I am not sure about this one until plan tab is restored.

**Comment by SashaScholar6** [comment]
yes, only after @william-gooch has re-implemented quill on plan tab.

**Comment by ivanromakh** [comment]
@SashaScholar6 there is no validation for plan right now.
![image](https://user-images.githubusercontent.com/18567511/114838500-6f906780-9ddd-11eb-97e7-202e187b8b69.png)

**Comment by SashaScholar6** [comment]
There should be, so please add
