### ISSUE TITLE
Text component repeating

### ISSUE THREAD

**Issue by scholar6admin** [Scholar-6/brillder#3162]
- [x] See 'les jeux sont fait'  - brick 461 - second component text component repeating from question 1 to all the other questions. 

https://dev-app.brillder.com/build/brick/461/investigation/question-component

![image](https://user-images.githubusercontent.com/58778078/114381405-fe557800-9b82-11eb-9754-f89522846ad3.png)

![image](https://user-images.githubusercontent.com/58778078/114381450-0b726700-9b83-11eb-89b9-49e34d213524.png)

**Comment by ivanromakh** [comment]
Solution is simple.
First when page loading it goes to 2 question and render 'Suppose 150' component.
then it goes back to first question but 'Suppose 150' component stays probably becouse of key error. I fixed this by chaning key to index which is generated by array instead of id.

**Comment by ivanromakh** [comment]
We probably will need to fix this later. it was implemented before questions where sorted by order parameter. And now first question is not actually first. first one is the question with the lowest order field.

**Comment by ivanromakh** [comment]
hm. this is still happening in this brick I will check this issue too.

**Comment by ivanromakh** [comment]
here text is replacing. number of components stays the same.

**Comment by ivanromakh** [comment]
@SashaScholar6 @lindsaymacvean I added delay when components are switching so deconstructor should start and restart quill components and all data related to quill. Added some components to make it look good. this is how it look when switching.
![image](https://user-images.githubusercontent.com/18567511/114423645-0da6e680-9bc0-11eb-90e2-e7cc1dde60a6.png)

**Comment by ivanromakh** [comment]
can be customized but can`t show any data related to question as it is refreshing.
