### ISSUE TITLE
S9+ has big eyes

### ISSUE THREAD

**Issue by scholar6admin** [Scholar-6/brillder#3169]
![image](https://user-images.githubusercontent.com/58778078/114795018-97ec7780-9d85-11eb-8e34-a7f4c7c2f699.png)
https://live.browserstack.com/dashboard#os=android&os_version=9.0&device=Samsung+Galaxy+S9+Plus&device_browser=chrome&zoom_to_fit=true&full_screen=true&url=https%3A%2F%2Fdev-app.brillder.com%2Fplay%2Fbrick%2F464%2Fpre-synthesis&speed=1

**Comment by ivanromakh** [comment]
@SashaScholar6 I don`t know how it should look...
