### ISSUE TITLE
For ios without flexbox show warning screen (<iOS11 I think)

### ISSUE THREAD

**Issue by scholar6admin** [Scholar-6/brillder#3170]
Can we wrap the whole react code in a feature detection script?

https://developer.mozilla.org/en-US/docs/Learn/Tools_and_testing/Cross_browser_testing/Feature_detection

And if no flexbox etc then just show an error screen.

![image](https://user-images.githubusercontent.com/58778078/114795290-1ea15480-9d86-11eb-91fe-67527e2d1fb0.png)
https://live.browserstack.com/dashboard#os=iOS&os_version=8.0&device_browser=safari&zoom_to_fit=true&full_screen=true&url=https%3A%2F%2Fdev-app.brillder.com%2Fplay%2Fbrick%2F464%2Fpre-synthesis&speed=1

**Comment by ivanromakh** [comment]
@scholar6admin I tried to show this warning in that iPad Air 2, but even css is not working there. it is probably very very old iPad.

**Comment by ivanromakh** [comment]
@scholar6admin Are you sure about OS 14 IPhone 11 also have IO 13.
![image](https://user-images.githubusercontent.com/18567511/116438431-1b629a00-a857-11eb-9480-ae502910fe5e.png)

**Comment by ivanromakh** [comment]
![image](https://user-images.githubusercontent.com/18567511/117127692-18aafc00-ada5-11eb-99dd-232af3972c5a.png)
