### ISSUE TITLE
ipad 2019 sidebar issue

### ISSUE THREAD

**Issue by scholar6admin** [Scholar-6/brillder#3171]
![image](https://user-images.githubusercontent.com/58778078/114837800-ffc5b100-9dcb-11eb-9a20-48fd223750e8.png)
https://live.browserstack.com/dashboard#os=iOS&os_version=12.0&device_browser=safari&zoom_to_fit=true&full_screen=true&speed=1

**Comment by ivanromakh** [comment]
Fixed
![image](https://user-images.githubusercontent.com/18567511/115710441-07acc480-a37b-11eb-981b-abff18ebd435.png)

**Comment by scholar6admin** [comment]
@ivanromakh when subject is selected it is not visible in sidebar
Make sure that ipad css uses --theme-dark-blue when selected.
