### ISSUE TITLE
New assign popup

### ISSUE THREAD

**Issue by scholar6admin** [Scholar-6/brillder#3179]
Please don't commit this until we release 9.1.0
<img width="1440" alt="Screenshot 2021-04-15 at 10 27 35" src="https://user-images.githubusercontent.com/58778078/114848922-24735600-9dd7-11eb-80ff-cb136adbf5f7.png">

This popup should create a class and invite students all in one go.
 

 
<img width="1440" alt="Screenshot 2021-04-16 at 12 07 36" src="https://user-images.githubusercontent.com/59654112/115015994-64583d00-9eac-11eb-85df-35c6e4f2e02a.png">

- [x] 'No Deadline' preselected as an option
- [x] If fields are empty when 'assign' clicked, then mark as red and 'alert' popup (same as validation on brick) with text 'Please fill in the fields in red'

- [x] when 'Assign' clicked, take new teacher to manage classes, assignments tab, expanded assignment view
- [x] add intro js and grey text:

Invited students will remain amber until they accept to join your class 

Once students start joining your class, they will be shown here.

GREY 
When they have completed the assignment, you will be able to see how they have done on the brick as a whole and on each individual question.

You will also be able to send them reminders to complete the assignment at any time.

**Comment by ivanromakh** [comment]
@SashaScholar6 why it tells `create your first class` teacher probably already have few classes no?

**Comment by SashaScholar6** [comment]
The point is this is for teachers that have just entered the system (hence intro.js before). The second popup #3186 is for existing teachers

**Comment by ivanromakh** [comment]
@SashaScholar6 that popup doesn`t look like introjs at all. intro js have at least one button.
