### ISSUE TITLE
First time teachers experience

### ISSUE THREAD

**Issue by scholar6admin** [Scholar-6/brillder#3180]
As a new teacher (who does not have a class with assigned bricks)
When I arrive at the home screen I should see this
<img width="1440" alt="Screenshot 2021-04-15 at 10 27 01" src="https://user-images.githubusercontent.com/58778078/114856847-8041dd00-9ddf-11eb-8fed-79b3a4505dc8.png">

- [x] And I click 'next' it should take me to the subject category page

- [x] When I arrive at a brick I should see this

<img width="1440" alt="Screenshot 2021-04-15 at 10 27 16" src="https://user-images.githubusercontent.com/58778078/114856843-7f10b000-9ddf-11eb-98d7-fb5cb71a36dd.png">

When I click to assign a brick I should be redirected

**Comment by ivanromakh** [comment]
@scholar6admin I am not sure what do you mean by switching to another brick.

**Comment by ivanromakh** [comment]
https://github.com/Scholar-6/brillder-backend/issues/473

**Comment by scholar6admin** [comment]
@ivanromakh I dont think you need to worry about this, Ill take it out. We meant that you should be able to click off the popup and back to the list of bricks and select a different brick
