### ISSUE TITLE
Connection lost on new brick

### ISSUE THREAD

**Issue by scholar6admin** [Scholar-6/brillder#3181]
![image](https://user-images.githubusercontent.com/58778078/114855369-cd24b400-9ddd-11eb-88a2-51b9653bb8a5.png)

As editor@scholar6.org
When I click on a brick that has been sent to me to edit
And I click to the first question panel
Then I should not see connection lost.

https://dev-app.brillder.com/build/brick/567/plan

editor can`t edit brick.
![image](https://user-images.githubusercontent.com/18567511/114857076-88564880-9df0-11eb-8283-bd7d7aa8aff1.png)

Happens on production as well
![image](https://user-images.githubusercontent.com/58778078/114858734-c435e180-9de1-11eb-8b3b-05c43e67341d.png)
https://app.brillder.com/build/brick/530/investigation/question-component/224838

**Comment by ivanromakh** [comment]
@scholar6admin Ok I will have a look
