### ISSUE TITLE
Public tab needs 'create brick'

### ISSUE THREAD

**Issue by scholar6admin** [Scholar-6/brillder#3182]
![image](https://user-images.githubusercontent.com/58778078/114856781-6dc7a380-9ddf-11eb-9400-1f71a146fcb1.png)

If no bricks in public tab it should look like this
![image](https://user-images.githubusercontent.com/58778078/114858886-f1828f80-9de1-11eb-8662-6cf818bc1eab.png)

If there are bricks then show the smaller icon
![image](https://user-images.githubusercontent.com/58778078/114859004-14ad3f00-9de2-11eb-92ea-cb5a6bb66bd4.png)

**Comment by ivanromakh** [comment]
I fixed this. When actual view have no bricks you will have create brick button in sidebar.

**Comment by ivanromakh** [comment]
I will be fixing second point then

**Comment by ivanromakh** [comment]
I added it here 
![image](https://user-images.githubusercontent.com/18567511/114862868-b8551a00-9df7-11eb-9d0b-60305c7b774b.png)
