### ISSUE TITLE
Fixes to build public tab sidebar

### ISSUE THREAD

**Issue by scholar6admin** [Scholar-6/brillder#3183]
- [x] If I select status that has no bricks (but there are some bricks in another status).
Then I should still see the sidebar 
![image](https://user-images.githubusercontent.com/58778078/114863526-be42ff00-9de7-11eb-837f-fa17d85a007b.png)

If no bricks at all then just show 
![image](https://user-images.githubusercontent.com/58778078/114863377-905dba80-9de7-11eb-9ab5-a1ece2bac2e2.png)

If there are some bricks then show sidebar
![image](https://user-images.githubusercontent.com/58778078/114863449-a3708a80-9de7-11eb-8d63-62aba408d82d.png)

**Comment by ivanromakh** [comment]
@SashaScholar6 where should be create brick link here?
![image](https://user-images.githubusercontent.com/18567511/114867500-9363a580-9dfd-11eb-99db-e1b42427e65f.png)
