### ISSUE TITLE
Cover Page functional fixes

### ISSUE THREAD

**Issue by SashaScholar6** [Scholar-6/brillder#3185]
<img width="1437" alt="Screenshot 2021-04-15 at 14 04 11" src="https://user-images.githubusercontent.com/59654112/114876150-f2252100-9df5-11eb-9ce0-098968ae3788.png">

- [x] fix text cutoff ellipsis

<img width="1440" alt="Screenshot 2021-04-15 at 14 04 43" src="https://user-images.githubusercontent.com/59654112/114876153-f3564e00-9df5-11eb-85af-0a007f0031fa.png">

- [x] move keywords down 

- [x] Add Sponsored by and image input (default image is Scholar 6 logo)

- [x] Add 'see bio' button and popup

<img width="621" alt="Screenshot 2021-04-15 at 14 25 25" src="https://user-images.githubusercontent.com/59654112/114876659-7081c300-9df6-11eb-96e9-e77f94fa049b.png">

- [x] 'see bio' button blue on hover, white text, add 50% outline

- [x] By Name Surname of author

- [x] Private bricks that are not General and Topical should not have this (sponsor text and image) on cover page

- [x] Min and max arrows in sidebar should remain so we can switch between them

- [x] Level popup fix cutoff

**Comment by ivanromakh** [comment]
@SashaScholar6 which ellipsis you mean?
![image](https://user-images.githubusercontent.com/18567511/115262528-4ead7680-a13d-11eb-8353-26df7be9cf13.png)

**Comment by SashaScholar6** [comment]
'Equati...'

**Comment by ivanromakh** [comment]
@SashaScholar6 so I should make font size smaller?

**Comment by SashaScholar6** [comment]
you showed me some rule to make text fit on one line

**Comment by ivanromakh** [comment]
@aromakh we need global object for sponsors. sponsor should have field like imageUrl as string for images and probably id.
![image](https://user-images.githubusercontent.com/18567511/115851127-4b610600-a42f-11eb-8666-839ab8fe0f07.png)
