### ISSUE TITLE
Existing teachers assign popup

### ISSUE THREAD

**Issue by SashaScholar6** [Scholar-6/brillder#3186]
<img width="1438" alt="Screenshot 2021-04-15 at 13 49 08" src="https://user-images.githubusercontent.com/59654112/114876844-a2932500-9df6-11eb-9821-c9a9de732d4a.png">

- [x] dropdown with existing classes selected by default

- [x] If 'Create New Class selected, then same blue fields as in popup for new teacher

**Comment by ivanromakh** [comment]
@SashaScholar6 what level mean? brick has his own level.
