### ISSUE TITLE
Play order and usability fixes

### ISSUE THREAD

**Issue by SashaScholar6** [Scholar-6/brillder#3190]
Unauthenticated user (stays the same)
cover -> brief -> sections ->  pre-prep -> new-prep -> pre-investigation -> live

Play preview it should follow the unauthenticated flow

Authenticated Users (it changes)

- [x] brief -> pre-prep -> new-prep -> live

- [x] student goes straight to Brief page from Play now

<img width="1305" alt="Screenshot 2021-04-15 at 16 25 04" src="https://user-images.githubusercontent.com/59654112/114895152-27863a80-9e07-11eb-87db-75104b6adaa2.png">

- [x] change text in sections  to be just: 

The Preparation phase presents some tasks to get you thinking.

<img width="1181" alt="Screenshot 2021-04-15 at 16 24 11" src="https://user-images.githubusercontent.com/59654112/114895194-353bc000-9e07-11eb-815d-03b9d5b32468.png">

- [x] add small progress indication on timer

<img width="173" alt="Screenshot 2021-04-20 at 14 52 39" src="https://user-images.githubusercontent.com/59654112/115407586-10b95c80-a1e8-11eb-8cee-f3eb24e048f1.png">

- [x] Brief: fix dashed circle placement

- [x] Brief: restore animation for items in sidebar

- [x] PREP: fix circle placement

**Comment by ivanromakh** [comment]
@SashaScholar6 So student go to brief page but teacher to cover page right?

**Comment by ivanromakh** [comment]
@SashaScholar6 prep don`t have circle anymore. 
![image](https://user-images.githubusercontent.com/18567511/115410684-824ed600-a1fb-11eb-8f8f-3a4e8f3928cd.png)

**Comment by ivanromakh** [comment]
@SashaScholar6 there is some bug in review page. timer is reseting there.
