### ISSUE TITLE
Add last-saved to plan screen.

### ISSUE THREAD

**Issue by scholar6admin** [Scholar-6/brillder#3195]
- [x] move icons to the left so there is space 
![image](https://user-images.githubusercontent.com/58778078/116017157-b6c8f480-a636-11eb-9677-72d4d0f84eee.png)

Add Last Saved indicator to plan screen

- [x] Add ID to plan screens
This url should have the id of the brick not 'new-brick'

![image](https://user-images.githubusercontent.com/58778078/115418659-9261b800-a1f1-11eb-88a7-ebd6816f4c33.png)

Also test to check that there are no /brick/NaN in network tab
![image](https://user-images.githubusercontent.com/58778078/115418797-ac9b9600-a1f1-11eb-9f59-b93fa743eaf4.png)

- [x] last saved should be above phone in blue

**Comment by ivanromakh** [comment]
@scholar6admin this is a big update.

**Comment by ivanromakh** [comment]
@scholar6admin this was @william-gooch task maybe he can move it from yjs branch faster.

**Comment by scholar6admin** [comment]
@ivanromakh Im still seeing the icons on the right

![image](https://user-images.githubusercontent.com/58778078/116426243-d9c3f600-a83a-11eb-9488-6e867fd2e4cf.png)
