### ISSUE TITLE
Short answer - multiple entries shortens and pushes to the left

### ISSUE THREAD

**Issue by scholar6admin** [Scholar-6/brillder#3198]
- [ ] @SashaScholar6 please confirm you are happy with UI/UX specification

![image](https://user-images.githubusercontent.com/58778078/116124406-2c2ad880-a6bc-11eb-8688-2aa5a1763217.png)

![image](https://user-images.githubusercontent.com/58778078/116124430-31882300-a6bc-11eb-945e-d89aa6995032.png)

**Comment by ivanromakh** [comment]
![image](https://user-images.githubusercontent.com/18567511/117128953-c10d9000-ada6-11eb-8993-f8c90a24e358.png)
