### ISSUE TITLE
Intercept 403 on all /build/ and show popup to login again

### ISSUE THREAD

**Issue by scholar6admin** [Scholar-6/brillder#3202]
As a builder
If I have a permission issue
And I get a 403 response from the backend
Then I should see a popup that says

"We just need to check your id again."
Button: "Reload"

To test
Login as a builder and open a public draft brick
In a separate tab log out and login as a student
Go back to the first tab and try to edit the brick
You should see a 'we need to check your id' popup that redirects you to login

**Comment by ivanromakh** [comment]
![image](https://user-images.githubusercontent.com/18567511/115026952-c07e8980-9ecb-11eb-8b58-9072686994ff.png)

**Comment by scholar6admin** [comment]
@ivanromakh I tried deleting my redis cookie, I also tried going in as an editor who is making 403 requests

but this popup does not seem to trigger??

![image](https://user-images.githubusercontent.com/58778078/115428985-dc02d080-a1fa-11eb-9408-c659619e4fff.png)

![image](https://user-images.githubusercontent.com/58778078/115429003-e1f8b180-a1fa-11eb-90db-9e199df8b7a3.png)

**Comment by scholar6admin** [comment]
@ivanromakh we are almost there. I think the cache is not clearing so the tab that reloads still thinks it is logged in as the builder and has all his details. 

We should either force a full page refresh or clear the cache. 


https://user-images.githubusercontent.com/58778078/115934358-c4407c00-a488-11eb-8269-eb185d096ce7.mp4

**Comment by ivanromakh** [comment]
@scholar6admin this task was in deployed column. need more description about this.

**Comment by scholar6admin** [comment]
@ivanromakh I just need test steps because I cant trigger this reload box. What should I do to trigger it.

**Comment by ivanromakh** [comment]
@scholar6admin I think we fixed this by locking brick so we don`t send put request when role is invalid.
