### ISSUE TITLE
Easy upload of cover images

### ISSUE THREAD

**Issue by scholar6admin** [Scholar-6/brillder#3205]
As a publisher or admin
When I publish a brick
Then I should be taken to the cover page of the brick.

**Comment by scholar6admin** [comment]
@SashaScholar6 Im undecided about what to do here. 

1. We add the cover screen into play preview
2. We make publishers have to go and view it in the library before adding a cover.

**Comment by SashaScholar6** [comment]
Probably 1?

**Comment by SashaScholar6** [comment]
Play Preview still needs some of the routing/caching fixed for back and forth clicking other than that
