### ISSUE TITLE
Lock brick for author when sent to editor

### ISSUE THREAD

**Issue by scholar6admin** [Scholar-6/brillder#3218]
As a builder
When I create a brick
And add an editor
Then I should no longer be able to edit it
And it should be locked
Until it is sent back to me.

**Comment by ivanromakh** [comment]
@lindsaymacvean Right now authors can only edit bricks in draft status.
![image](https://user-images.githubusercontent.com/18567511/115555510-44fc4e00-a2b8-11eb-8249-3eba27027555.png)

**Comment by ivanromakh** [comment]
@scholar6admin for me brick is locked.
