### ISSUE TITLE
Clicking on image in synthesis is opening next image (instead of current)

### ISSUE THREAD

**Issue by scholar6admin** [Scholar-6/brillder#3223]
![image](https://user-images.githubusercontent.com/58778078/115527310-d8b62600-a288-11eb-9550-cb022f0df29c.png)

**Comment by william-gooch** [comment]
Image dialog no longer appears. However for the blockquote including the image there is a workaround:
Click on the image, press enter, un-blockquote the text after it and then select and un-blockquote the image itself.
