### ISSUE TITLE
Remove invite editor from private bricks

### ISSUE THREAD

**Issue by aromakh** [Scholar-6/brillder#3226]
UPDATE TO THIS TASK
Remove the option to invite an editor if you have selected 'keep control'

Steps:
1. Create brick.
2. Chose "keep private"
3. Assign editor.
4. Back to work

Actual:
 brick is locked and not editable for the autor. Otherwise editor can edit brick.

Expected:
 @scholar6admin please describe desired result.

**Comment by scholar6admin** [comment]
@aromakh not sure what you mean here

![image](https://user-images.githubusercontent.com/58778078/115540121-a6f78c00-a295-11eb-8656-f51c4ce25276.png)

I don't think that we can invite an editor on a isCore=0 
![image](https://user-images.githubusercontent.com/58778078/115540217-c55d8780-a295-11eb-9aee-892f72d958fe.png)

**Comment by aromakh** [comment]
@lindsaymacvean actualy we can..
Just click "share"

**Comment by scholar6admin** [comment]
You are correct. I had forgotten we had that option in there. 
![image](https://user-images.githubusercontent.com/58778078/115562816-c5b64c80-a2ae-11eb-88be-036c05f05c10.png)
![image](https://user-images.githubusercontent.com/58778078/115562834-cb139700-a2ae-11eb-968c-38c9331ce294.png)

I will bring this up with @josephelvet and @SashaScholar6 later on
