### ISSUE TITLE
Image spacing and blockquote

### ISSUE THREAD

**Issue by SashaScholar6** [Scholar-6/brillder#3229]
<img width="820" alt="Screenshot 2021-04-21 at 12 04 14" src="https://user-images.githubusercontent.com/59654112/115543890-cf818500-a299-11eb-915e-424bc04cd466.png">

- [ ] when I click on another tab from synthesis, spaces I have added are removed (For example, if I add two spaces after a full stop before the next sentence, or if I add a line space underneath an image)

- [x] Following this, if I play preview and then go back to build, the images are subsumed into blockquotes, like in screenshot above: https://dev-app.brillder.com/build/brick/357/synthesis

- [x] Blockquote also breaks
<img width="835" alt="Screenshot 2021-04-21 at 12 07 47" src="https://user-images.githubusercontent.com/59654112/115544238-4028a180-a29a-11eb-88e1-168f76675f82.png">

**Comment by ivanromakh** [comment]
probably related to counting words.

**Comment by ivanromakh** [comment]
this is something related to quill.

**Comment by ivanromakh** [comment]
@SashaScholar6 bug happen only when quill receive data so as long as you don`t go back to synthesis page it will look like this.
![image](https://user-images.githubusercontent.com/18567511/115560620-71669900-a2bd-11eb-9d3f-061190722566.png)
once you go back to synthesis it quill will auto update text and add that qoutes to images so you will just need to remove quotes from image and save again.
![image](https://user-images.githubusercontent.com/18567511/115560731-893e1d00-a2bd-11eb-9922-f2344bca0518.png)

**Comment by ivanromakh** [comment]
Quill is trimming spaces by default. I can`t do anything about it.
![image](https://user-images.githubusercontent.com/18567511/115569198-aa0a7080-a2c5-11eb-99d8-d59b51b4c148.png)
![image](https://user-images.githubusercontent.com/18567511/115569158-a0810880-a2c5-11eb-9c0d-1ae9c0259f27.png)

**Comment by ivanromakh** [comment]
this is somewhere here. It producing during convering html to quill and it setting attributes as blockqoute.
https://github.com/quilljs/quill/blob/develop/core/editor.js#L20

**Comment by ivanromakh** [comment]
That is the place that apply delta to html. but it apply it wrong.
![image](https://user-images.githubusercontent.com/18567511/115588147-1f327180-a2d7-11eb-9626-be0788d4828b.png)
First image is loading good.
then comes blockqoute
![image](https://user-images.githubusercontent.com/18567511/115588793-c9aa9480-a2d7-11eb-80e8-77a31435356e.png)

Then insert text
![image](https://user-images.githubusercontent.com/18567511/115588908-e9da5380-a2d7-11eb-92b0-3d333d5929a8.png)

Then blockqoutes.
![image](https://user-images.githubusercontent.com/18567511/115589269-52c1cb80-a2d8-11eb-806b-5c296c27addf.png)
Then it remove all.
![image](https://user-images.githubusercontent.com/18567511/115590656-e47e0880-a2d9-11eb-9235-30942fe9b5fb.png)
And finally insert it with black qoute.
![image](https://user-images.githubusercontent.com/18567511/115590847-1b541e80-a2da-11eb-9288-6b4d7d6ee107.png)

**Comment by ivanromakh** [comment]
its impossible to fix it if we don`t make local version of quill.

**Comment by ivanromakh** [comment]
Fixed probably.
