### ISSUE TITLE
Move intro box down so we can see the invited users

### ISSUE THREAD

**Issue by scholar6admin** [Scholar-6/brillder#3230]
![image](https://user-images.githubusercontent.com/58778078/115544314-59315280-a29a-11eb-91c6-56e8e88d04fa.png)

**Comment by ivanromakh** [comment]
@SashaScholar6 I will try but probably impossible.

**Comment by ivanromakh** [comment]
like this?
![image](https://user-images.githubusercontent.com/18567511/116377991-614d3d00-a81a-11eb-8f58-7e72939f1b3d.png)
