### ISSUE TITLE
alignment in synthesis

### ISSUE THREAD

**Issue by scholar6admin** [Scholar-6/brillder#3240]
- [x] fix left align
- [x] justified and center align are the wrong way around (see video below)
- [x] Make sure that extra white spaces are rendered in phone preview

https://user-images.githubusercontent.com/58778078/116723568-98b51880-a9d7-11eb-96da-9d0620458c1a.mp4

<img width="130" alt="Screenshot 2021-04-29 at 12 14 48" src="https://user-images.githubusercontent.com/59654112/116542427-8b6b3180-a8e4-11eb-98a6-41726b8aae0c.png">

- [x] fix dropdown overflow

- [x] replace with quill icons:

<img width="865" alt="Screenshot 2021-04-29 at 15 43 22" src="https://user-images.githubusercontent.com/59654112/116569857-b1eb9580-a901-11eb-8abf-505aed19fd12.png">

- [x] reposition between numbering and blockquotes

**Comment by ivanromakh** [comment]
@SashaScholar6 for me left align not working.
![image](https://user-images.githubusercontent.com/18567511/117006844-96153480-acf1-11eb-9384-36ccd019d846.png)

**Comment by ivanromakh** [comment]
@SashaScholar6 I count words by white spaces can`t do it.
![image](https://user-images.githubusercontent.com/18567511/117007159-fb692580-acf1-11eb-8606-4e4d0402ff49.png)
