### ISSUE TITLE
Highlight Qs in phone preview should be smaller

### ISSUE THREAD

**Issue by SashaScholar6** [Scholar-6/brillder#3245]
- [x] font smaller

<img width="1047" alt="Screenshot 2021-04-23 at 15 18 26" src="https://user-images.githubusercontent.com/59654112/115884930-532ca480-a447-11eb-8f59-ddb8268bfe06.png">

**Comment by ivanromakh** [comment]
@SashaScholar6 is it tablet. in mine pc it looks smaller.

**Comment by ivanromakh** [comment]
@scholar6admin this task is too old it looks smaller in mine.
