### ISSUE TITLE
Image and Captions fixes

### ISSUE THREAD

**Issue by SashaScholar6** [Scholar-6/brillder#3246]
When caption is a certain length, images revert to left instead of centre align

<img width="644" alt="Screenshot 2021-04-23 at 15 28 01" src="https://user-images.githubusercontent.com/59654112/115886101-815eb400-a448-11eb-879d-a436c9b93738.png">

- [x] image should remain in the centre

- [ ] text should be centre aligned with image and move onto next line if necessary

Images in Answers
<img width="229" alt="Screenshot 2021-04-29 at 13 44 40" src="https://user-images.githubusercontent.com/59654112/116552540-0df9ee00-a8f1-11eb-90c8-dcb45b7dbaca.png">

- [x] hide placeholder when image added

- [x] trash icons should be far right

- [x] images should not overflow

- [x] should be able to click and get to image interface

**Comment by ivanromakh** [comment]
@SashaScholar6 if this is in dev I need brick id.
