### ISSUE TITLE
Archive Early

### ISSUE THREAD

**Issue by scholar6admin** [Scholar-6/brillder#3254]
- [ ] @SashaScholar6 please confirm you are happy with UI/UX specification

As a teacher
I should be able to archive a brick at any time.

If I click on the archive button before the brick is cooked (i.e. all users have completed or it is past deadline)
then there should be a popup to confirm archiving:
"There are students who have not yet completed it. Are you sure you want to archive it."

**Comment by ivanromakh** [comment]
![image](https://user-images.githubusercontent.com/18567511/116382092-3c5ac900-a81e-11eb-9dad-eafc32f682fb.png)

**Comment by scholar6admin** [comment]
@ivanromakh  Excellent work here. 

However backend seems to be throwing a 500
![image](https://user-images.githubusercontent.com/58778078/116450704-84481300-a853-11eb-896f-03ac31c590cc.png)


Any ideas. Is it to do with this brick assignment being very old before we implemented deadlines or something?

**Comment by ivanromakh** [comment]
@scholar6admin I need brick id.

**Comment by scholar6admin** [comment]
@ivanromakh 457
