### ISSUE TITLE
Cannot type links in prep

### ISSUE THREAD

**Issue by scholar6admin** [Scholar-6/brillder#3258]
If I type https://google.com and enter a space
then this should convert to a link

![image](https://user-images.githubusercontent.com/58778078/116120740-c89eac00-a6b7-11eb-940f-1329ef758b7d.png)

https://user-images.githubusercontent.com/58778078/116252753-c562f900-a767-11eb-933e-304325e7e6ba.mp4

**Comment by ivanromakh** [comment]
https://github.com/quilljs/quill/issues/109

**Comment by ivanromakh** [comment]
@scholar6admin as I see there is autolink which will transfrom links after page is refreshed not typing.
