### ISSUE TITLE
Assignment fixes

### ISSUE THREAD

**Issue by scholar6admin** [Scholar-6/brillder#3261]
These tasks came from #3043
- [x] @ivanromakh Create class from assignments tab should redirect me to student tab

- [x] ~~@aromakh api return number of bricks assigned to each student in class~~ unnecessary right now
- [ ]  ~~@ivanromakh Show number of bricks assigned to each student in class~~  (need backend)

- [x] @aromakh In this request I need score in each assignment https://dev-api.brillder.com/bricks/byStatus/4

- [x] @aromakh In this request I need max score in each assignment https://dev-api.brillder.com/bricks/byStatus/4

- [ ] @ivanromakh In Student, when complete show **Final Score:** X

- [x] @ivanromakh notification circle should be yellow if not passed deadline

- [x] @ivanromakh Invited should be total number of students invited to assignment (not only those pending, also those who have accepted)
![image](https://user-images.githubusercontent.com/58778078/116455239-be67e380-a858-11eb-9c9e-9a515b8a01c7.png)

**Comment by scholar6admin** [comment]
@william-gooch go with that for the moment. I think @SashaScholar6 may have had thoughts about number of bricks being different for a student depending on whether they were added to the class later etc. But lets cross that bridge when we come to it.

**Comment by ivanromakh** [comment]
@aromakh there is something wrong. I have 22% here.
![image](https://user-images.githubusercontent.com/18567511/116996350-f309ee00-ace3-11eb-80d7-19077b1d17f5.png)
but in response I have 19 here.
![image](https://user-images.githubusercontent.com/18567511/116996401-02893700-ace4-11eb-9867-01e61874d854.png)

**Comment by ivanromakh** [comment]
@aromakh we need percentages now. not points.  You could you calculate it on backend or add max score filed there.
