### ISSUE TITLE
Resend invitation

### ISSUE THREAD

**Issue by scholar6admin** [Scholar-6/brillder#3262]
- [x] @william-gooch or @aromakh need capability to resend invitation
- [x] Add a simple blue button 'Resend' on each yellow pending user in the students tab.
![image](https://user-images.githubusercontent.com/58778078/116224400-83768a80-a748-11eb-84f7-1a005053657f.png)

**Comment by william-gooch** [comment]
@scholar6admin is that first part definitely done already? I can't find the endpoint anywhere...
