### ISSUE TITLE
Urgent Phone Fixes

### ISSUE THREAD

**Issue by scholar6admin** [Scholar-6/brillder#3273]
- [x] White screen when accessing activation link from phone (s9+ chrome)
![image](https://user-images.githubusercontent.com/58778078/116251288-71a3e000-a766-11eb-9e3e-8a8ce8931842.png)

- [x] Terms page needs to be a scrollable window in phone (s9+ chrome)
![image](https://user-images.githubusercontent.com/58778078/116251641-c47d9780-a766-11eb-91f4-977a3caa6189.png)

**Comment by ivanromakh** [comment]
for me popup is a little messed too.
![image](https://user-images.githubusercontent.com/18567511/116252640-6eb1eb00-a778-11eb-99ce-4aea7d913452.png)
