### ISSUE TITLE
Stop bold when latex selected

### ISSUE THREAD

**Issue by scholar6admin** [Scholar-6/brillder#3276]
As a builder
When I select latex on some latex
Then it should remove bold/italic from the text
So that the latex renders correctly in the phone

![image](https://user-images.githubusercontent.com/58778078/116384119-7375ae00-a80f-11eb-9611-1e409608bce5.png)

https://dev-app.brillder.com/build/brick/208/investigation/question-component/28887

**Comment by william-gooch** [comment]
The reason is that part of the LaTeX environment is bolded, meaning the LaTeX parser interprets it as an error.
I'll see if I can make it so that LaTeX environments can't be formatted by other features.
