### ISSUE TITLE
Add tables to quill toolbar

### ISSUE THREAD

**Issue by SashaScholar6** [Scholar-6/brillder#3277]
- [ ] this is preventing me from publishing a Spanish brick

Lets try forking and updating (make sure to create a pull request back to the original repo)

**Comment by ivanromakh** [comment]
@SashaScholar6 I need icon for this.

**Comment by SashaScholar6** [comment]
Icon: https://heroicons.com/

Implementation:
https://github.com/quilljs/quill/issues/117

https://github.com/volser/quill-table-ui
