### ISSUE TITLE
Fix punctuation on word highlight phone preview

### ISSUE THREAD

**Issue by scholar6admin** [Scholar-6/brillder#3286]
![image](https://user-images.githubusercontent.com/58778078/116449153-c708eb80-a851-11eb-9465-acb9ef4902ce.png)

It seems to have double spaces between words and before punctuation marks. 

Test , . ' ! ?

<img width="548" alt="Screenshot 2021-04-29 at 17 16 28" src="https://user-images.githubusercontent.com/59654112/116583865-b10d3080-a90e-11eb-84f0-3fb01cd3b572.png">

- [x] also fix spacing between words (so more like line highlighting)

**Comment by ivanromakh** [comment]
@SashaScholar6 there is no double spacing its margin between words.
