### ISSUE TITLE
Add public personal dropdown to plan tab

### ISSUE THREAD

**Issue by SashaScholar6** [Scholar-6/brillder#3288]
To change brick status quickly

<img width="715" alt="Screenshot 2021-04-29 at 10 38 20" src="https://user-images.githubusercontent.com/59654112/116531525-2eb54a00-a8d7-11eb-9710-5cdad8f8640f.png">

- [x] globe icon for Public

- [x] key icon for personal

**Comment by ivanromakh** [comment]
@SashaScholar6 public is by default?

**Comment by SashaScholar6** [comment]
@ivanromakh Not necessarily, will depend on whether user has clicked from public or personal tab (therefore no placeholder needed)
