### ISSUE TITLE
Immediately show teachers best score on assigned brick

### ISSUE THREAD

**Issue by scholar6admin** [Scholar-6/brillder#3289]
Needs merging.

- [x] @SashaScholar6 please confirm you are happy with UI/UX specification

As a student I do not want to have to play a brick again when it is assigned to me if I have already played it. 

When a teacher assigns me a brick I have already played
Then the teacher should immediately see my best score on that brick

When two teachers assign me the same brick
Then I should only have to play the brick once for both teachers to see my score.

When I play a brick and get a better score
Then all teachers who have assigned me the brick will see my best score (not my last score)

As a student
When I click on assignments
Then I should see bricks have been assigned to be and I have played
And bricks that have been assigned to me and not played.
And there should only be two filters played/not played (no submitted to teacher)

**Comment by aromakh** [comment]
@scholar6admin 
Which changes to backeng should be done?
