### ISSUE TITLE
Library should show best score not last score

### ISSUE THREAD

**Issue by scholar6admin** [Scholar-6/brillder#3290]
- [x] @SashaScholar6 please confirm you are happy with UI/UX specification
- [x] @william-gooch  check that the max score stays the same when multiple play attempts

**Comment by ivanromakh** [comment]
something is wrong with this. After I checked maxScore should be max score of brick. but it changed after I attempted again.
![image](https://user-images.githubusercontent.com/18567511/116694068-74e9d680-a9c7-11eb-814d-07b257d5b252.png)

**Comment by aromakh** [comment]
@ivanromakh  maybe brick was edited? eg, question was added, edited?
