### ISSUE TITLE
Help button cut off in Firefox

### ISSUE THREAD

**Issue by SashaScholar6** [Scholar-6/brillder#3291]
<img width="1440" alt="Screenshot 2021-04-29 at 12 23 50" src="https://user-images.githubusercontent.com/59654112/116543489-d6397900-a8e5-11eb-9db4-776878f2f5b9.png">

- [x] big sidebar

<img width="877" alt="Screenshot 2021-04-29 at 12 25 23" src="https://user-images.githubusercontent.com/59654112/116543616-fbc68280-a8e5-11eb-86f9-d5c30fd362f7.png">

- [ ] small sidebar (should be small circle with question mark)

**Comment by ivanromakh** [comment]
@SashaScholar6 In mine help button is good. need more details.
![image](https://user-images.githubusercontent.com/18567511/117151029-5b7acd00-adc1-11eb-918b-92811f8f05e8.png)
