### ISSUE TITLE
Build Fixes

### ISSUE THREAD

**Issue by SashaScholar6** [Scholar-6/brillder#3292]
<img width="408" alt="Screenshot 2021-04-29 at 13 28 51" src="https://user-images.githubusercontent.com/59654112/116550555-d7bb6f00-a8ee-11eb-8eb3-0fa0a8455891.png">

- [x] add white line between each answer hint

- [x] Placeholders: Global Hint / Answer 1 Hint

<img width="445" alt="Screenshot 2021-04-29 at 13 32 34" src="https://user-images.githubusercontent.com/59654112/116551010-5ca68880-a8ef-11eb-9d05-fecf0a89e549.png">

- [x] move up red answers bar

<img width="190" alt="Screenshot 2021-04-29 at 13 39 12" src="https://user-images.githubusercontent.com/59654112/116551905-51a02800-a8f0-11eb-93b7-92014b3b06ed.png">

- [x] fix height of dropdown
- [x] text should be brandon reg

**Synthesis** 

<img width="1298" alt="Screenshot 2021-04-29 at 14 02 15" src="https://user-images.githubusercontent.com/59654112/116554840-8feb1680-a8f3-11eb-9d99-0919b99bc709.png">

- [x] when synthesis is empty, phone should show default screen with brick length selection and recommended lengths

- [x] Change lengths to 600-800 words for 20 minute, 1200-1600 words for 40 minutes and 1800-2000 words for 60 minutes

**Comment by ivanromakh** [comment]
![image](https://user-images.githubusercontent.com/18567511/116563104-638fc400-a90c-11eb-8fc5-79a4a12a2398.png)

**Comment by ivanromakh** [comment]
@SashaScholar6 synthesis is empty only when you created brick. and I see it.
![image](https://user-images.githubusercontent.com/18567511/116564872-0563e080-a90e-11eb-8ef6-33f0c39120dc.png)

**Comment by SashaScholar6** [comment]
I should see that every time I have no characters in it

**Comment by ivanromakh** [comment]
For published I will create separate route and component so other filters wont have any influence on it

**Comment by SashaScholar6** [comment]
Found the trigger by the way:

1. Start in a brick (build interface)
2. Exit brick
3. Click build bricks and published
