### ISSUE TITLE
LateX swallowing up regular prose and removing spaces

### ISSUE THREAD

**Issue by SashaScholar6** [Scholar-6/brillder#3295]
<img width="1022" alt="Screenshot 2021-04-29 at 13 53 03" src="https://user-images.githubusercontent.com/59654112/116553603-39310d00-a8f2-11eb-8d60-938799277dd8.png">

- [x] Restore grey background for LateX so it's more clear where it starts and ends

<img width="1157" alt="Screenshot 2021-04-29 at 15 38 34" src="https://user-images.githubusercontent.com/59654112/116569098-fb87b080-a900-11eb-8176-48886d41be6f.png">

- [x] work area not displaying TeX deselect

**Comment by ivanromakh** [comment]
@SashaScholar6 I need color which one is it?

**Comment by ivanromakh** [comment]
@william-gooch second point of task.
This is something with latex plugin I leave it to you. unselecting work in preview but in workarea it look the same
![image](https://user-images.githubusercontent.com/18567511/116675446-81ae0080-a9ae-11eb-9e7b-72f49be85847.png)
