### ISSUE TITLE
Make notification bell white with red number circle

### ISSUE THREAD

**Issue by SashaScholar6** [Scholar-6/brillder#3297]
<img width="336" alt="Screenshot 2021-04-29 at 15 40 48" src="https://user-images.githubusercontent.com/59654112/116569421-46a1c380-a901-11eb-887b-df51a5b3aed0.png">

- [x] for mobile, only show red dot (no numbers, will be too small) if new notifcations

**Comment by ivanromakh** [comment]
@SashaScholar6 need design for 2digits. like 23 it wont not fit in circle

**Comment by ivanromakh** [comment]
@SashaScholar6 we could live it for mobile as it is. it is looking good there no? or it is too small?
![image](https://user-images.githubusercontent.com/18567511/117012402-93b5d900-acf7-11eb-9301-8fd70f5ebb05.png)

**Comment by SashaScholar6** [comment]
styled like above please (white outline) - image numbers will be too small - if so no need to show, red circle will be enough

**Comment by ivanromakh** [comment]
ok
