### ISSUE TITLE
Published Bricks Section Updates

### ISSUE THREAD

**Issue by SashaScholar6** [Scholar-6/brillder#3298]
**Published bricks section**

- [x] @SashaScholar6 confirm Ivans question.

<img width="1077" alt="Screenshot 2021-04-29 at 17 02 37" src="https://user-images.githubusercontent.com/59654112/116581891-b49fb800-a90c-11eb-8308-cfff1fd4a990.png">

- [x] this view should not happeen (exit brick building, home screen, click “build bricks” then published quickly)

<img width="1435" alt="Screenshot 2021-04-29 at 17 01 42" src="https://user-images.githubusercontent.com/59654112/116581790-9934ad00-a90c-11eb-88bd-181772affb0a.png">

- [x] remove create a new brick button and add row above of published bricks

<img width="422" alt="Screenshot 2021-04-29 at 13 41 11" src="https://user-images.githubusercontent.com/59654112/116552097-91670f80-a8f0-11eb-8724-20ba44eba6fd.png">

- [x] add brick id on hover bottom right

- [x] replace hashtags with ‘|’

**Comment by ivanromakh** [comment]
@SashaScholar6 I need design or more details about level filter. is it one of 3.  or many or 3.
