### ISSUE TITLE
Manage Classes Search

### ISSUE THREAD

**Issue by SashaScholar6** [Scholar-6/brillder#3302]
Assignments Tab

- [x] @ivanromakh Placeholder is: Search by Brick Title, Student Name, or Subject
- [x] @aromakh make the above possible

Students Tab

- [ ] make email and subject searchable (only name works for now)

**Comment by aromakh** [comment]
@ivanromakh  just use POST Instead of GET for search.
http://swagger.scholar6.org/docs/#!/classroom/searchClassrooms
