### ISSUE TITLE
Vertical Shuffle updated design

### ISSUE THREAD

**Issue by SashaScholar6** [Scholar-6/brillder#3304]
- [x] Desktop
- [x] Mobile

<img width="1310" alt="Screenshot 2021-04-30 at 11 34 22" src="https://user-images.githubusercontent.com/59654112/116683895-224cf200-a9a8-11eb-844a-90ea775bb50d.png">

- [x] Click on two answers at a time to reorder.
- [x] number circles
- [x] when clicked, feather-refresh rotates

**Comment by ivanromakh** [comment]
@SashaScholar6 this is only for phones?

**Comment by ivanromakh** [comment]
![image](https://user-images.githubusercontent.com/18567511/117288751-81ad7500-ae74-11eb-892a-443f0702b3c0.png)
![image](https://user-images.githubusercontent.com/18567511/117288793-8eca6400-ae74-11eb-9167-05abee777e5e.png)
