### ISSUE TITLE
Ipad 2019 brick IDs showing up in catalogue

### ISSUE THREAD

**Issue by scholar6admin** [Scholar-6/brillder#3306]
![image](https://user-images.githubusercontent.com/58778078/116724417-8a1b3100-a9d8-11eb-874f-21469bf5556a.png)

**Comment by ivanromakh** [comment]
is it better?
![image](https://user-images.githubusercontent.com/18567511/117133163-8dcdff80-adac-11eb-9ab1-09164b84fe3c.png)

**Comment by scholar6admin** [comment]
Excellent
