### ISSUE TITLE
Iphone optimisation

### ISSUE THREAD

**Issue by scholar6admin** [Scholar-6/brillder#3308]
- [x] Add padding at bottom on iphone play so that student can see the bottom of the question panels without scrolling.
![image](https://user-images.githubusercontent.com/58778078/117013641-f4d5b080-ace7-11eb-8f9e-0ee2e625d6f0.png)

- [ ]  Stop menu opening as default
![image](https://user-images.githubusercontent.com/58778078/117013502-d96aa580-ace7-11eb-98ec-5e7487120b5f.png)

**Comment by ivanromakh** [comment]
there is padding it problem with height. need some css magic.

**Comment by ivanromakh** [comment]
@scholar6admin Are you sure about hiding menu. There was task to show it in mobile to make it more vissible.
