### ISSUE TITLE
Validation on Missing word

### ISSUE THREAD

**Issue by scholar6admin** [Scholar-6/brillder#3309]
![image](https://user-images.githubusercontent.com/58778078/117016906-14baa380-aceb-11eb-9395-0cf5579b944b.png)

The first three are wrong so it is good they have a hint

The last one should actually be correct so the hint should not be in orange. 

In general the hints always show up in orange on this question type.

**Comment by ivanromakh** [comment]
@scholar6admin they are correct I just checked in build.

**Comment by ivanromakh** [comment]
@scholar6admin they are always orange in missing words. I think all hints are always orange.

**Comment by ivanromakh** [comment]
@scholar6admin I see this is old question. new missing words don`t have multiple hints.
