### ISSUE TITLE
Grey copy pasting issue

### ISSUE THREAD

**Issue by SashaScholar6** [Scholar-6/brillder#3312]
- [x]  title
![image](https://user-images.githubusercontent.com/58778078/117181509-38561a80-adcd-11eb-8233-701c62b07cba.png)

When I copy and paste text into work area,background appears

<img width="760" alt="Screenshot 2021-05-05 at 10 18 03" src="https://user-images.githubusercontent.com/59654112/117120523-56029000-ad8b-11eb-8035-d6d184b684b5.png">

<img width="1637" alt="Screenshot 2021-05-05 at 10 19 25" src="https://user-images.githubusercontent.com/59654112/117120555-60248e80-ad8b-11eb-8cca-437a46eb3d77.png">

**Comment by ivanromakh** [comment]
@SashaScholar6 title also has color if you copy pasting. what should I do with that? no color?
![image](https://user-images.githubusercontent.com/18567511/117271994-68e89380-ae63-11eb-9092-85db2fadd418.png)
