### ISSUE TITLE
Cannot upload images on questions

### ISSUE THREAD

**Issue by scholar6admin** [Scholar-6/brillder#3316]
- [x] popup should match the popup on image component (except for adjusting size of image) and should open file browser before popup.
![image](https://user-images.githubusercontent.com/58778078/117342970-bbde3d00-ae9b-11eb-8d2c-f7190d0a0bef.png)

- [x] On both popups remove the 'proceed popup'
![image](https://user-images.githubusercontent.com/58778078/117344716-9b16e700-ae9d-11eb-9973-6b1c73e23f4c.png)

On vertical shuffle, horizontal shuffle, pair match etc cannot click on '+JPG' to add an image

https://user-images.githubusercontent.com/58778078/117177072-83b9fa00-adc8-11eb-9b9e-95ebe848939b.mp4

**Comment by scholar6admin** [comment]
@ivanromakh I am pretty sure this is a front end issue. Can you still work on this today?

**Comment by ivanromakh** [comment]
we need to strip html in image path probably

**Comment by ivanromakh** [comment]
something is weird going on here. it should work now.

**Comment by ivanromakh** [comment]
and someone removed trash button here. is it ghost
![image](https://user-images.githubusercontent.com/18567511/117333125-4b3a1f00-aea1-11eb-9748-4ca881077dd3.png)

**Comment by scholar6admin** [comment]
@ivanromakh great work. That will do for this evening. I am moving this task back to general queue just to tweak two things. See in description above.
