### ISSUE TITLE
Duplicating components on 604

### ISSUE THREAD

**Issue by scholar6admin** [Scholar-6/brillder#3317]
https://dev-app.brillder.com/build/brick/604/investigation/

Repeating components on question 3

**Comment by ivanromakh** [comment]
@william-gooch probably because of this key. use index instead of id.
![image](https://user-images.githubusercontent.com/18567511/117633883-2090e480-b187-11eb-8431-40081ce2084c.png)

**Comment by william-gooch** [comment]
True, but that was causing the issue with being unable to swap components because the index stayed the same.

**Comment by ivanromakh** [comment]
ok I will check

**Comment by william-gooch** [comment]
@ivanromakh That's for choose several, not for duplicating components.
Not to mention, I know there's an error somewhere, the issue is fixing it. For some reason react-sortablejs doesn't reflect the current state of the data, which causes duplicate components with the same keys.

**Comment by ivanromakh** [comment]
@william-gooch they are not duplicating for me. there are all different.

**Comment by william-gooch** [comment]
@ivanromakh Ah, you're right. I remember it only does it when you load the brick for the first time after dumping it from a backup.
My bad - since I'm the one with a local version of the backend it's only easy for me to fix anyway.
Still not sure exactly why it's happening but I'll see what I can do.

**Comment by ivanromakh** [comment]
@william-gooch  It could be because id is the same of some components. when brick is old with components without ids. maybe something is with id generator or time when id is generated. But not sure.

**Comment by scholar6admin** [comment]
Closing this as it appears to be only a problem the first time an old brick is loaded (and does not actually permanently affect the brick) and any potential fix would require a data migration across all components which is much riskier than just telling people to refresh if they see this bug.
