### ISSUE TITLE
MANAGE CLASSES & ASSIGNMENT FIXES

### ISSUE THREAD

**Issue by SashaScholar6** [Scholar-6/brillder#3318]
**MAJOR**

- [x] assignments tab, text changes as discussed and in screenshot
<img width="524" alt="Screenshot 2021-05-06 at 12 57 54" src="https://user-images.githubusercontent.com/59654112/117294551-adc3f880-ae6a-11eb-8b11-469835b554a2.png">

- [x] create class button, add grey tooltip 'Create Class'
- [x] remove add student button from assignments tab, and remove assign brick button from students tab
- [x] In students tab, add 'Add a new student' text to button
- [x] Backend - View All in students tab, showing all users that are pending, and which classed they have been invited to (keep resend button, no need for pending text)

ASSIGNMENTS

<img width="390" alt="Screenshot 2021-05-06 at 13 01 10" src="https://user-images.githubusercontent.com/59654112/117294927-22973280-ae6b-11eb-92ce-1f034cbdb993.png">

- [x] Icons in circles: if assigned, incomplete then show file-plus (not in any other case) - if I have played the brick, show check-square

- [x] Show red circle next to assignments or shared with me, showing number of incomplete assignments/bricks shared

MINOR

<img width="381" alt="Screenshot 2021-05-06 at 14 14 40" src="https://user-images.githubusercontent.com/59654112/117304222-6abb5280-ae75-11eb-9748-0458650811aa.png">

- [x] change shape in Manage Classes so like below:

<img width="301" alt="Screenshot 2021-05-06 at 14 13 10" src="https://user-images.githubusercontent.com/59654112/117304101-495a6680-ae75-11eb-9fac-d36631052499.png">

- [x] chevron should rotate 90 degrees on hover, with 50% background on hover.  When clicked, chevron should point downwards to show expanded view.

- [x] make user and brick icons thinner so that they match text

<img width="268" alt="Screenshot 2021-05-06 at 13 00 05" src="https://user-images.githubusercontent.com/59654112/117294809-fc719280-ae6a-11eb-89d1-c6d247c5a235.png">

<img width="658" alt="Screenshot 2021-05-06 at 12 59 29" src="https://user-images.githubusercontent.com/59654112/117294736-e5cb3b80-ae6a-11eb-921b-5975653bfe7f.png">

- [x] students text should be same size ass class text

- [x] add resend button here too

**Comment by ivanromakh** [comment]
@SashaScholar6 move pending users out of this. this needed backend help.

**Comment by ivanromakh** [comment]
@SashaScholar6 resend button will not be visible when overflow.
![image](https://user-images.githubusercontent.com/18567511/117461371-25228680-af56-11eb-87f7-2c4d152d23d5.png)
![image](https://user-images.githubusercontent.com/18567511/117461402-2c499480-af56-11eb-9c23-3423c4490106.png)

**Comment by scholar6admin** [comment]
Acceptable I feel as the alternative is to go to student tab.

**Comment by ivanromakh** [comment]
@SashaScholar6 this is assignment page right? if yes then they all are assigned.
![image](https://user-images.githubusercontent.com/18567511/118819222-cd710d00-b8bd-11eb-9556-c67719e91055.png)

**Comment by ivanromakh** [comment]
@SashaScholar6 need more details about this one
![image](https://user-images.githubusercontent.com/18567511/118820400-e7f7b600-b8be-11eb-865b-409641632e1b.png)

**Comment by ivanromakh** [comment]
@aromakh there is some error in backend side. 
![image](https://user-images.githubusercontent.com/18567511/118823726-debc1880-b8c1-11eb-8472-aad9fce39b41.png)

**Comment by ivanromakh** [comment]
@lindsaymacvean we can`t expand bricks  in manage classes page right now in dev.

**Comment by SashaScholar6** [comment]
@ivanromakh like this

<img width="101" alt="Screenshot 2021-05-19 at 14 53 16" src="https://user-images.githubusercontent.com/59654112/118824780-060ae980-b8b2-11eb-801d-93d73c0f1baa.png">

**Comment by ivanromakh** [comment]
@aromakh I need hasPlayedBrick and isAssigned here.
![image](https://user-images.githubusercontent.com/18567511/119504548-bd04da80-bd74-11eb-9d5b-bad2de6d93df.png)

**Comment by SashaScholar6** [comment]
@ivanromakh @william-gooch No, play dashboard, subject circles on cover images
