### ISSUE TITLE
PLAY FIXES

### ISSUE THREAD

**Issue by SashaScholar6** [Scholar-6/brillder#3321]
**CRITICAL/MAJOR**

- [x] E**veryone should see a cover page**

- [x] remove 'by' Author name, change 'see bio' to Author Profile'

- [x] 'Commissioned by' **(lowercase 'b')**

<img width="375" alt="Screenshot 2021-05-06 at 14 05 34" src="https://user-images.githubusercontent.com/59654112/117302994-21b6ce80-ae74-11eb-8a85-0f8b55ab5005.png">

- [x] 'Scroll down' in bold, centred in bottom of bar - grey by default, blue if scrolling necessary

<img width="448" alt="Screenshot 2021-05-06 at 15 05 11" src="https://user-images.githubusercontent.com/59654112/117311849-7fe7af80-ae7c-11eb-873a-6bd8399a1737.png">

- [x] remove last character (')
<img width="120" alt="Screenshot 2021-05-06 at 16 35 09" src="https://user-images.githubusercontent.com/59654112/117325977-220d9480-ae89-11eb-80e4-b5bcac037353.png">

**Comment by ivanromakh** [comment]
@SashaScholar6 I can`t reproduce this. what is big?
![image](https://user-images.githubusercontent.com/18567511/117301068-ea9be980-ae82-11eb-9fd8-d51cb4b34f48.png)

**Comment by ivanromakh** [comment]
@SashaScholar6 it will be in few lines in  phones. should I make font smaller?
![image](https://user-images.githubusercontent.com/18567511/117301653-82013c80-ae83-11eb-97e0-6d9866d9201a.png)
![image](https://user-images.githubusercontent.com/18567511/117301616-7ada2e80-ae83-11eb-8f77-a8679a97ada1.png)
