### ISSUE TITLE
IMAGE & CAPTION FIXES

### ISSUE THREAD

**Issue by SashaScholar6** [Scholar-6/brillder#3323]
MAJOR

- [x] ** Image should remain in centre if centre align radio checked** (work area, image interface and **desktop play**)

- [x] centre radio button by default (not Left)

- [x] add file name in grey bar with red x

- [x] Add 'x' in top right of image interface - blue default, red hover

- [x] When I add an image into an answer, placeholders should disappear, and only reappear when I delete the image

- [x] fix hint image stretching
<img width="1016" alt="Screenshot 2021-05-07 at 10 25 59" src="https://user-images.githubusercontent.com/59654112/117429165-abbb7180-af1e-11eb-8d42-3f9653358060.png">

**Comment by ivanromakh** [comment]
@SashaScholar6 I tried but I have it centered.
![image](https://user-images.githubusercontent.com/18567511/117310235-c0025e80-ae8b-11eb-8d14-bfde8f3696b8.png)

**Comment by SashaScholar6** [comment]
is it also ok in work area?

What shouldn't happen is like screenshots here:
<img width="603" alt="Screenshot 2021-05-06 at 15 09 35" src="https://user-images.githubusercontent.com/59654112/117312612-13b97b80-ae7d-11eb-81ed-3f556fbd186e.png">
<img width="1185" alt="Screenshot 2021-05-06 at 15 10 10" src="https://user-images.githubusercontent.com/59654112/117312701-28960f00-ae7d-11eb-8d99-1922ae91a33f.png">

**Comment by ivanromakh** [comment]
this is synthesis I was doing image component in question.

**Comment by SashaScholar6** [comment]
my fault for not specifying - it is/has been an issue in synthesis

**Comment by ivanromakh** [comment]
@SashaScholar6 I can`t add image to answer at all.
![image](https://user-images.githubusercontent.com/18567511/117313631-be866580-ae8e-11eb-8367-fe424de7e791.png)

**Comment by SashaScholar6** [comment]
yeah guess we need to wait for william fix #3316

**Comment by ivanromakh** [comment]
@SashaScholar6 I can add fix for new images not existing ones. that is quill stuff.
![image](https://user-images.githubusercontent.com/18567511/117315397-546ec000-ae90-11eb-990a-971691cbc51e.png)
