### ISSUE TITLE
Add zoom function for answers with images

### ISSUE THREAD

**Issue by SashaScholar6** [Scholar-6/brillder#3325]
- [x] **Add text** (only when images are in answers)

- [x] DESKTOP
“Hover over images to zoom” (text and functionality)

- [x] MOBILE
 “Double tap images to zoom” (text and functionality)

- [x] fix styling/size issue with @SashaScholar6 

<img width="1285" alt="Screenshot 2021-05-12 at 10 03 57" src="https://user-images.githubusercontent.com/59654112/117948845-6ecdf100-b309-11eb-8f0e-85b8cf54c838.png">

- [x] Instruction Text should be on same line in pair match, with full stops.
- [x] Image should be centred heightwise when no caption.  

- [x] Make background for images on left column e5e8ed, right column lighter grey (like normal pair match)

- [x] reduce hover blue border-width on desktop so more like mobile

**Comment by ivanromakh** [comment]
there is no double click in phones. can use time comparison and regular click (touch).
https://stackoverflow.com/questions/61350154/ondoubleclick-dont-work-on-phone-react-js-app

**Comment by ivanromakh** [comment]
@SashaScholar6 pair match captions aren`t working propertly.

**Comment by ivanromakh** [comment]
we have only one caption probably for options.

**Comment by ivanromakh** [comment]
@SashaScholar6 where is white line?
![image](https://user-images.githubusercontent.com/18567511/118634026-c4f3d600-b7da-11eb-962d-2d7536962215.png)

**Comment by ivanromakh** [comment]
@SashaScholar6 I am not sure about this one.
![image](https://user-images.githubusercontent.com/18567511/118788125-216afa00-b89c-11eb-9b6f-7d3e930171e5.png)
