### ISSUE TITLE
Add each hints to missing word

### ISSUE THREAD

**Issue by scholar6admin** [Scholar-6/brillder#3327]
We cant remember exactly why we removed this from missing word but lets try adding it back.

If more than one missing word per line
Then stack up the hints one under another.

**Comment by ivanromakh** [comment]
@scholar6admin I had task to remove hints. @SashaScholar6 could you confirm that we need to add it again?

**Comment by ivanromakh** [comment]
@scholar6admin it was an issue when text was very long and hints very under few lines of text.
