### ISSUE TITLE
Get rid of username on signup process

### ISSUE THREAD

**Issue by scholar6admin** [Scholar-6/brillder#3331]
- [x] Should not have to click twice. It should just progress without waiting for the username to be generated in the background.

![image](https://user-images.githubusercontent.com/58778078/125057970-b1117580-e0a1-11eb-97dd-be95c21efc72.png)

Change 'generate username' to 'Please enter your full name'
Dont show the generated username on the right, but still generate it on the backend. 

Add 'This is your username that others see, it's only useful if your name is very common like John, or Smith.' to the tutorial on the profile page.
Last thing before highlighting the green save button
![image](https://user-images.githubusercontent.com/58778078/124449760-ac844e80-dd7b-11eb-8d00-2f733fd1e11f.png)

**Comment by ivanromakh** [comment]
@scholar6admin where I should add 'This is your username that others see, it's only useful if your name is very common like John, or Smith.' to the tutorial on the profile page.' ??
