### ISSUE TITLE
Latex has weird spacing and sizing

### ISSUE THREAD

**Issue by scholar6admin** [Scholar-6/brillder#3333]
<img width="400" alt="Screenshot 2021-05-06 at 13 00 44 (1)" src="https://user-images.githubusercontent.com/58778078/117351796-0a90d480-aea6-11eb-8569-98b3edf11b21.png">

- [x] Make all characters evenly spaced. Particularly the 'i'
- [x] Stop the extra space after tex.
- [x] Make text roughly the same size as the normal text around it.

- [x] This brick has latex that is not rendering in phone preview
https://app.brillder.com/build/brick/599/investigation/question-component/235807
![image](https://user-images.githubusercontent.com/58778078/117378803-0d9fbb00-aece-11eb-89e5-01ba0c313c86.png)
It works on other panels if you copy paste this text. Can we fix this issue so the author does not have to redo his questions. The author of this brick is the lead partnership manager with our main partner Gooroo.

**Comment by ivanromakh** [comment]
@scholar6admin there was margin. but other related to font. this is some font.
![image](https://user-images.githubusercontent.com/18567511/117438965-eb905200-af3a-11eb-9710-7ad549c29a10.png)
