### ISSUE TITLE
Non-breaking spaces act strange when in blockquotes

### ISSUE THREAD

**Issue by scholar6admin** [Scholar-6/brillder#3335]
Lets discuss together on Friday

Enter all three lines of the following text
```
 
this line is surrounded by characters &#x00A0;
 
```
Make it a quote. 
enter some non-quoted text after this quote

You will see it copies part of the text in the phone preview like this:
![image](https://user-images.githubusercontent.com/58778078/121376606-92e91600-c939-11eb-8154-8c2f99743244.png)

https://github.com/Scholar-6/brillder/blob/9fba47bdb47e0a8f50cf7f2156cdd6840a200d16/src/components/services/mathJaxService.ts#L14-L41

![image](https://user-images.githubusercontent.com/58778078/117380309-4e4d0380-aed1-11eb-859b-a5cceab7f82c.png)
https://dev-app.brillder.com/build/brick/304/plan

https://scholar6.zendesk.com/agent/tickets/355

**Comment by ivanromakh** [comment]
@scholar6admin this is a problem with quill probably.

**Comment by william-gooch** [comment]
It's an issue with the `parseDataToArrayQuote` function in mathjaxService.ts
https://github.com/Scholar-6/brillder/blob/9fba47bdb47e0a8f50cf7f2156cdd6840a200d16/src/components/services/mathJaxService.ts#L14-L41
It's causing lines from quill to be parsed out of order. However since I have no clue how this function is supposed to work can I leave it to you?

**Comment by ivanromakh** [comment]
it can`t be related to that as it is only used in play to render existed data but not in build.
Problem was with quill parsing that data. maybe it was prep created by ck-editor.

**Comment by ivanromakh** [comment]
its ck-editor content probably. so just need to rewrite it if it can`t be parsed.

**Comment by william-gooch** [comment]
> it can`t be related to that as it is only used in play to render existed data but not in build.
> Problem was with quill parsing that data. maybe it was prep created by ck-editor.

@ivanromakh I'm 99% certain it's that function.
Apparently the bug also happens in play. That function is definitely used for the plan in build - but not for the synthesis (where this bug doesn't happen)
Any chance you can take a look at why a space in a blockquote would have some weird behaviour with that function?
Thanks in advance :)
