### ISSUE TITLE
Categorise: If I don't drag anything into Categories during Investigation, nothing shows and I am unable to amend answer in review

### ISSUE THREAD

**Issue by SashaScholar6** [Scholar-6/brillder#3338]
- [x] Needs small white margin at top of first uncategorised answer in review
![image](https://user-images.githubusercontent.com/58778078/117700279-b5aed000-b1bd-11eb-9283-24ba817adc1c.png)

<img width="1367" alt="Screenshot 2021-05-07 at 10 17 19" src="https://user-images.githubusercontent.com/59654112/117428109-a873b600-af1d-11eb-860e-10d55ae06d0a.png">

- [x] If I am moving on from question while some answers are unsorted, make popup that says: You haven't categorised all answers. Are you sure you want to move on?

**Comment by ivanromakh** [comment]
@SashaScholar6 I see them in review. need brickId. 
![image](https://user-images.githubusercontent.com/18567511/117429152-6c495100-af2f-11eb-8e03-51ab3a28ce2c.png)

**Comment by ivanromakh** [comment]
@SashaScholar6 I see them there. need all steps to reproduce it.
![image](https://user-images.githubusercontent.com/18567511/117429415-b599a080-af2f-11eb-9292-d803030bd104.png)
