### ISSUE TITLE
Warning screen on safari less than 13

### ISSUE THREAD

**Issue by scholar6admin** [Scholar-6/brillder#3341]
Warning screen on safari version 12 and older 

"Brillder is not yet fully optimised for this old thing." Same error screen as ipad

In the UK.
It looks like version 14 accounts for 70% of safari users and version 13 accounts for 10% with the rest of the versions accounting for 10% together. 
![image](https://user-images.githubusercontent.com/58778078/117650781-0b1cba00-b189-11eb-8528-e083ff4449f2.png)

**Comment by ivanromakh** [comment]
@scholar6admin I don`t have this version. There is only some old 10.1 version which is not working propertly.
![image](https://user-images.githubusercontent.com/18567511/117445018-e0d9bb00-af42-11eb-95aa-797baf37ee65.png)

**Comment by ivanromakh** [comment]
I tried to create new brick. there is cursor but you can`t type. no support...
![image](https://user-images.githubusercontent.com/18567511/117446382-ad982b80-af44-11eb-9a70-d9c466ca45e7.png)

in version 14 there is at least cursor and different errors.

**Comment by ivanromakh** [comment]
@scholar6admin matchAll is not supported by broswer. safari is old.
![image](https://user-images.githubusercontent.com/18567511/117447071-ae7d8d00-af45-11eb-91c8-8ad651ed61ed.png)

**Comment by ivanromakh** [comment]
@scholar6admin do we really need support for safari 10.1? if so we also will need to support all from 14 to 10.1 right?

**Comment by scholar6admin** [comment]
Ok I just need to understand how far back our support will extend with safari >13

**Comment by william-gooch** [comment]
Quill has recently been updated to v2 if that helps this task at all.

**Comment by ivanromakh** [comment]
@scholar6admin actually quill now is working in sierra 10.1 too now.  Images aren`t working in version 11.1.

**Comment by scholar6admin** [comment]
@ivanromakh But we still need to consider matchAll does not work on safari <12. Unless we can change how that matchAll to something else. I think there is only one case in the code.
