### ISSUE TITLE
Vertical Shuffle Fixes

### ISSUE THREAD

**Issue by scholar6admin** [Scholar-6/brillder#3346]
- [x] Phone preview vertical shuffle decrease padding

![image](https://user-images.githubusercontent.com/58778078/117639079-719adb80-b17b-11eb-8bad-ee4200231f87.png)

- [x] Restore dragging on desktop versions but keep switching version on mobile

**Comment by ivanromakh** [comment]
@SashaScholar6 what about tablets (IPads) ?

**Comment by scholar6admin** [comment]
@ivanromakh  Go for dragging version on ipad.
