### ISSUE TITLE
Copy/Paste Fixes

### ISSUE THREAD

**Issue by scholar6admin** [Scholar-6/brillder#3347]
- [x] Turn black text to blue
Still happening on 9.12.0 (try from here https://www.lipsum.com/feed/html )
![image](https://user-images.githubusercontent.com/58778078/118509914-64a45c00-b728-11eb-8d2e-04a1b15d4a64.png)

- [x] Remove background colour from copy pasted text in phone preview and in synthesis body
![image](https://user-images.githubusercontent.com/58778078/117655259-bda34b80-b18e-11eb-9625-9ed57bbf13bd.png)
![image](https://user-images.githubusercontent.com/58778078/117655275-c1cf6900-b18e-11eb-8b8d-330a0ad51430.png)

**Comment by scholar6admin** [comment]
@SashaScholar6  could not find an example of copy pasted text with grey background in preprod (even if text is bold or italic). Going to mark that as complete, let me know if there is a specific scenario where that is still happening.

**Comment by william-gooch** [comment]
@scholar6admin can't find example of black text, copying from lipsum no longer triggers it, and brick 731 in the screenshot was deleted, presumably because you restored the database from production. If you can trigger this again, please let me know :)

**Comment by ivanromakh** [comment]
@scholar6admin need brick id.

**Comment by ivanromakh** [comment]
@william-gooch do you have any idea how we can intercept copypasted text. is it posible with clipboard plugin? we only need to remove color of incoming text.

**Comment by william-gooch** [comment]
Yeah, that's definitely possible with the Clipboard plugin. We already have a custom version of the Clipboard plugin for pasting images and such. I can have a go of this if I can get a definite way to paste coloured text into Quill.

**Comment by ivanromakh** [comment]
@scholar6admin  @william-gooch if I make text blue we wont be able to copy tables or other plugin content only raw text. we will need some transformer for those plugins. leave it to William.

**Comment by scholar6admin** [comment]
@ivanromakh seen and understood.
