### ISSUE TITLE
Images in questions fixes

### ISSUE THREAD

**Issue by scholar6admin** [Scholar-6/brillder#3351]
- [x] Cannot press green button on image upload on vertical shuffle. If this is an image size thing then show a warning "This image is too large, try shrinking it."
![image](https://user-images.githubusercontent.com/58778078/119408049-fdb11500-bcdc-11eb-8798-3cac862730fe.png)

https://dev-app.brillder.com/build/brick/731/investigation/question-component

Using this image:
![20210524_104858](https://user-images.githubusercontent.com/58778078/119409521-55e91680-bcdf-11eb-8f2a-de4151bd3d8c.jpg)

- [x] Vertical shuffle Image not resizing on phone preview
![image](https://user-images.githubusercontent.com/58778078/117668912-4a093a80-b19e-11eb-9b3c-cc15b607694d.png)

- [x] Horizontal Shuffle not resizing on phone 
![image](https://user-images.githubusercontent.com/58778078/117671930-3ad7bc00-b1a1-11eb-98d5-0362e31fac59.png)

- [ ] How to save when deleting image in popup on verticalshuffle, choose several, pair match

**Comment by ivanromakh** [comment]
@scholar6admin brick is deleted. I will try to reproduce.

**Comment by ivanromakh** [comment]
@scholar6admin which browser is it? Can`t reproduce it.
![image](https://user-images.githubusercontent.com/18567511/119350106-9af15680-bca7-11eb-9f26-64e2706bb268.png)

**Comment by ivanromakh** [comment]
@scholar6admin this task is old horizontal shuffle don`t have images anymore.

**Comment by ivanromakh** [comment]
@william-gooch you need to add popup in quill as well. there was error I added check for null but it will need second warning probably.

**Comment by ivanromakh** [comment]
@scholar6admin what do you mean by save when delete?
![image](https://user-images.githubusercontent.com/18567511/119462934-ebb98b80-bd49-11eb-98b3-409f1b80d90f.png)

**Comment by scholar6admin** [comment]
Good work
