### ISSUE TITLE
Capture email from cover page

### ISSUE THREAD

**Issue by scholar6admin** [Scholar-6/brillder#3359]
- [x] Popup should also open when user clicks 'play now' from cover page (not just on timer)
- [x] Should also happen on mobile cover page

- [x] Also check synthesis, it should progress to review when email is submitted on popup. (the user should not have to click again to start the review).

We have discovered that of the 16-20 people clicking the link in the email from Gooroo only 2-4 actually play the brick. 

As a prospective user
I would like to give my email early
So that I can be reminded to come back

When I click 'play brick' on the cover page
Then I should see a popup that says
"Great that you've clicked a Brick. To play this amazing, authored resource for free can we have your email?"
Text field "Enter a valid email"
Buttons "Not yet." and "Sure"
When I click immediately navigate to next page
If 'sure' then Store this email in the local cache
When I click to the synthesis
Then I should not have to enter an email a second time to start creating an account.
If 'not yet' then ask for the email when creating an account in the synthesis.

- [x] Both popups should look good on mobile
- [x] Both popups should have small font link under the text field that says 'Already a member? Sign in here.'
- [x] If server responds with 400 error that user already exists show red on text box and message 'You might already have an account, try signing in.'
- [x] 10 seconds after the finish of loading the cover page show same popup.

**Comment by ivanromakh** [comment]
@scholar6admin need to fix play for anonymous users first. can`t get to synthesis.

**Comment by ivanromakh** [comment]
matomo is not working?

**Comment by ivanromakh** [comment]
not working only in localhost.
