### ISSUE TITLE
Youtube video scaling on mobile

### ISSUE THREAD

**Issue by scholar6admin** [Scholar-6/brillder#3360]
![image](https://user-images.githubusercontent.com/58778078/117945479-4690c300-b306-11eb-964f-0d3b2124c9bc.png)

As a mobile user
I dont want to have the video cut off the side of the portrait view.

- [x] When I click to play Youtube video I should see it in fullscreen landscape with x to go back to portrait

**Comment by ivanromakh** [comment]
video overflow fixed.
![image](https://user-images.githubusercontent.com/18567511/118289298-e0f72f00-b4dd-11eb-81b6-5255dea0a982.png)

**Comment by ivanromakh** [comment]
@lindsaymacvean  I disabled full screen mode for phones. rotating will produce bugs.

**Comment by ivanromakh** [comment]
@lindsaymacvean we can cofigure youutbe videos by those parameters. https://developers.google.com/youtube/player_parameters
