### ISSUE TITLE
Hide zendesk fields

### ISSUE THREAD

**Issue by scholar6admin** [Scholar-6/brillder#3365]
![image](https://user-images.githubusercontent.com/58778078/117994922-cd5e9380-b338-11eb-88f4-64aaa835b39a.png)

**Comment by ivanromakh** [comment]
@scholar6admin which fields I should hide?

**Comment by scholar6admin** [comment]
@ivanromakh  Just the OS/agent/screensize prefilled fields. It would be great if these were still sent with the ticket.
