### ISSUE TITLE
Updated view of Published bricks

### ISSUE THREAD

**Issue by SashaScholar6** [Scholar-6/brillder#3367]
<img width="1141" alt="Screenshot 2021-05-13 at 11 13 59" src="https://user-images.githubusercontent.com/59654112/118111998-537fe600-b3dc-11eb-8b05-2bc666f812e0.png">

- [x] 3x2 grid for each page of public catalogue

- [x] so that images don't stretch, force resize during cover page upload (see linkedin cover upload)

<img width="748" alt="Screenshot 2021-05-13 at 11 16 21" src="https://user-images.githubusercontent.com/59654112/118112252-a9548e00-b3dc-11eb-91f3-ebf8d176786f.png">

- [x] scroll for now

**Comment by ivanromakh** [comment]
@SashaScholar6 crop isn`t working with alpha channel. It is replaced with black color in the library we use.

**Comment by ivanromakh** [comment]
@SashaScholar6  you need to click inside to crop.
![image](https://user-images.githubusercontent.com/18567511/118654518-52422500-b7f1-11eb-848f-9da6fa6d28be.png)

**Comment by SashaScholar6** [comment]
@ivanromakh if no cover image, grey background with feather-image icon as default.  Now we can make background of the main area where bricks are listed pure white
