### ISSUE TITLE
Build and Validation Fixes

### ISSUE THREAD

**Issue by SashaScholar6** [Scholar-6/brillder#3369]
- [x] Add images to Question Text component

VALIDATION

- [x] should not be able to progress from empty plan tab to play preview

- [x] should not be able to progress from empty synthesis to play preview

- [x] all empty fields should go red in plan tab (none are)

- [x] empty synthesis whole panel should go red

- [x] Question text, text, image, graph and sound should go red if empty and play preview button clicked

- [x] Empty All Answer Hint should go red on validation

- [x] choose answer if ticked but no answer should not be valid and should go red

**Comment by ivanromakh** [comment]
@SashaScholar6 this is only for fixed one or to all text components?
![image](https://user-images.githubusercontent.com/18567511/118469881-d374bb80-b70e-11eb-85c6-12aa9bbb288a.png)

**Comment by SashaScholar6** [comment]
@ivanromakh only fixed question text component

**Comment by ivanromakh** [comment]
@SashaScholar6 I think those two were fixed by @william-gooch when he was doing some stuff.
![image](https://user-images.githubusercontent.com/18567511/118473414-9c080e00-b712-11eb-86e8-8511b69f9b8f.png)

**Comment by ivanromakh** [comment]
@SashaScholar6 which fields we should validate? I validated quills. 
![image](https://user-images.githubusercontent.com/18567511/118476578-5a796200-b716-11eb-8dc7-ed301e1bc5b6.png)

**Comment by ivanromakh** [comment]
> @SashaScholar6 I think those two were fixed by @william-gooch when he was doing some stuff.
> ![image](https://user-images.githubusercontent.com/18567511/118473414-9c080e00-b712-11eb-86e8-8511b69f9b8f.png)

only working for new bricks and only once. then its not working...

**Comment by ivanromakh** [comment]
@SashaScholar6 categorise is looking like this when invalid. should I add some margin from top?
![image](https://user-images.githubusercontent.com/18567511/118480950-9bc04080-b71b-11eb-88f6-930d9df59e29.png)

**Comment by ivanromakh** [comment]
@SashaScholar6 what should I show in this popup when synthesis is empty?
![image](https://user-images.githubusercontent.com/18567511/118485047-94e7fc80-b720-11eb-901b-2a145a1bb63f.png)

**Comment by ivanromakh** [comment]
@SashaScholar6 for graphs only button should go red right?
![image](https://user-images.githubusercontent.com/18567511/118488383-59e7c800-b724-11eb-86d5-c3068da2412a.png)

**Comment by SashaScholar6** [comment]
maybe it would actually be clearer if the whole bottom bar went red

**Comment by ivanromakh** [comment]
@SashaScholar6 graphs aren`t working propertly for me. I can`t edit second time.
