### ISSUE TITLE
Student should not be able to access build screen on public published brick

### ISSUE THREAD

**Issue by scholar6admin** [Scholar-6/brillder#3374]
As student@scholar6.org (or any user who is not an admin)
I should not be able to access links such as https://app.brillder.com/build/brick/303/plan
Which is isCore=1 and status=4 (public and published)
As I should not be able to easily cheat at public published bricks. 
When I enter this url directly then I should be redirected to the bricks play cover.

**Comment by ivanromakh** [comment]
@scholar6admin where is such link?

**Comment by scholar6admin** [comment]
@ivanromakh see updated description above.

**Comment by ivanromakh** [comment]
@scholar6admin what about reviewers and publishers?
