### ISSUE TITLE
Update Image popup checkbox for copyright protection

### ISSUE THREAD

**Issue by scholar6admin** [Scholar-6/brillder#3378]
![image](https://user-images.githubusercontent.com/58778078/118489254-885da700-b714-11eb-9a87-fa6596f71ad1.png)

Change this to two radio buttons that say: 

“I am aware of licence restrictions around the publication of images online. I have checked this image is available for use without such restriction or within Creative Commons criteria which allow commercial use.”

OR

“I am creating a brick for educational use with my own students and can therefore use licensed images consistent with the exemptions for education in the Copyright Designs and Patents Act, 1988.”

- [x] smaller font and Brandon Light

**Comment by ivanromakh** [comment]
@scholar6admin so this is not OR but `and` right?
![image](https://user-images.githubusercontent.com/18567511/118654759-8e758580-b7f1-11eb-8d81-093822285074.png)

**Comment by ivanromakh** [comment]
@scholar6admin they are all required or you you can choose one of them?

**Comment by ivanromakh** [comment]
@SashaScholar6 should I make font smaller?
![image](https://user-images.githubusercontent.com/18567511/118655501-486cf180-b7f2-11eb-855d-ef1b197ca32d.png)
