### ISSUE TITLE
image attribution

### ISSUE THREAD

**Issue by scholar6admin** [Scholar-6/brillder#3379]
- [x] @ivanromakh not working on images on the left side of pair match and in vertical shuffle.
![image](https://user-images.githubusercontent.com/58778078/122420214-69586c00-cf83-11eb-83b9-0c5a42d70967.png)

- [x] @ivanromakh this still doesnt look right in some cases such as this

https://dev-app.brillder.com/play-preview/brick/667/live

![image](https://user-images.githubusercontent.com/58778078/122257812-45842000-cec8-11eb-8fe9-84f9227bb56a.png)

This needs to be running vertically in even smaller text on the right of images from the bottom to top.

- [x] Image component
- [x] Synthesis
- [x] Prep

- [x] nice :), should also show when image inserted from toolbar

**Comment by ivanromakh** [comment]
@SashaScholar6 where it isn`t working which component?

**Comment by ivanromakh** [comment]
@SashaScholar6 this is working for me even in text component.
![image](https://user-images.githubusercontent.com/18567511/122226459-ae669a80-cebe-11eb-9eab-ffca76722281.png)

**Comment by ivanromakh** [comment]
desktop fix
![image](https://user-images.githubusercontent.com/18567511/122375132-a0bb1e80-cf6b-11eb-9e54-a1fd88c00123.png)

**Comment by ivanromakh** [comment]
phone
![image](https://user-images.githubusercontent.com/18567511/122376104-85044800-cf6c-11eb-88ae-301332dc3afb.png)
