### ISSUE TITLE
Clicking completed assignment notification bsod

### ISSUE THREAD

**Issue by scholar6admin** [Scholar-6/brillder#3380]
- [x] As teacher@scholar6.org when I click on a completed assignment notification I get a BSOD
https://dev-app.brillder.com/post-play/brick/577/20
![image](https://user-images.githubusercontent.com/58778078/119407149-bc6c3580-bcdb-11eb-91c9-6d32927c5681.png)

![image](https://user-images.githubusercontent.com/58778078/119407160-c130e980-bcdb-11eb-9a36-ca04e6988402.png)

- [x] Make brick assignment notification clickable
https://user-images.githubusercontent.com/58778078/118520966-70951b80-b732-11eb-8e18-1619129a324c.mp4

- [x] Clicking student completed assignment goes to blue screen of death
![image](https://user-images.githubusercontent.com/58778078/118682372-4b6ae080-b7f8-11eb-963b-f6e30bf4e195.png)

https://user-images.githubusercontent.com/58778078/118682389-4efe6780-b7f8-11eb-9d3f-d0403b88f7a1.mp4

![image](https://user-images.githubusercontent.com/58778078/118682218-26766d80-b7f8-11eb-811a-2ce048ba560b.png)

Compeleted brick as new lindsaymacvean+secondstudent@scholar6.org
https://dev-app.brillder.com/post-play/brick/304/431
Got BSOD

**Comment by ivanromakh** [comment]
@william-gooch seems like sender id is not student id in notification. attempt not found.
![image](https://user-images.githubusercontent.com/18567511/119353379-79926980-bcab-11eb-99e8-e3304af69abd.png)

**Comment by ivanromakh** [comment]
@william-gooch  I created new assignment and it is working in it. maybe attempt was deleted somehow.

**Comment by ivanromakh** [comment]
@scholar6admin those attempts are removed. I gives me 404 error. I can do nothing about this. I created new attempts and it works fine for them. you can switch this task to @aromakh. Maybe he can check in database why it is removed.
