### ISSUE TITLE
8 areas instead of 20 subjects

### ISSUE THREAD

**Issue by SashaScholar6** [Scholar-6/brillder#3395]
URL should be
https://app.brillder.com/play/dashboard/subject-categories

- [x] As an unauthenticated user I should see the category page
- [x] As an authenticated user I should go straight to 'my subjects' tab
- [x]  On the 'my subjects' tab underneath the subjects there should be an option to add another subject to profile

- [x] add levels filters as in design

<img width="1440" alt="Screenshot 2021-06-14 at 12 17 12" src="https://user-images.githubusercontent.com/59654112/121886168-0198eb80-cd0d-11eb-8543-46d5cbd456ee.png">

As an unauthenticated user, when I get to the categories page. And I click a category (i.e. humanities) 
- [x] then I should only see the humanities subjects in the side bar and I should not see other subjects in the sidebar 
- [x] and the category name should be the h1 header on the page
- [x] and the humanities subjects should not be selected/highlighted (in white), they should all be blue instead
- [x] when I click one of the subjects in the left bar then it will filter/highlight by the subject but will still not show subjects outside the category in the left side bar
- [x] There will be a button underneath the subjects on the left to return to all subjects in the left sidebar

<img width="1440" alt="Screenshot 2021-06-14 at 12 34 39" src="https://user-images.githubusercontent.com/59654112/121886199-0c538080-cd0d-11eb-8ddb-30a46c59e2ac.png">

- [x] all subjects goes white on hover, blue text. add levels filter as in design.

<img width="1440" alt="Screenshot 2021-06-10 at 11 04 59" src="https://user-images.githubusercontent.com/59654112/121507074-37bc2f80-c9dc-11eb-8e4a-836adca8c29e.png">

- [x]   Arts, to include Art, History of Art, Design & Technology, Music, Drama & Theatre

- [x] Languages, to include French, Spanish and Classics, English Language

- [x] Humanities and Social Sciences, to include Economics, English Literature, Geography, History, Politics, Psychology, Religion and Philosophy,   Sociology

- [x] General & Topical, as a separate category

- [x] Science, to include Biology Chemistry and Physics

- [x] Maths and Computing, to include Maths and Computer Science

MOBILE

- [x] text at top in blue

- [x] last two are School Client and Corporate

**Comment by ivanromakh** [comment]
@SashaScholar6 what about phones?

**Comment by ivanromakh** [comment]
@SashaScholar6 I need those circle groups as svgs. good to have them with same size.
![image](https://user-images.githubusercontent.com/18567511/121325371-36c2c980-c91a-11eb-87f6-28e825e1bd85.png)

**Comment by ivanromakh** [comment]
I am not good with this geomentric. good to have some svgs.
![image](https://user-images.githubusercontent.com/18567511/121349407-24548a00-c932-11eb-9fa8-ceb4b9a21d6f.png)

**Comment by ivanromakh** [comment]
@SashaScholar6 what do you mean by this?
![image](https://user-images.githubusercontent.com/18567511/121680119-d66e8c00-cac1-11eb-8625-a4c5432452f7.png)

**Comment by ivanromakh** [comment]
@SashaScholar6 what is the point of groups if he moves for my subjects where he has all his subjects...

**Comment by ivanromakh** [comment]
@SashaScholar6 what is this for?
![image](https://user-images.githubusercontent.com/18567511/122224005-5d55a700-cebc-11eb-8e2b-37bde166ca58.png)

**Comment by SashaScholar6** [comment]
@ivanromakh should be same text as for levels in build onboarding/plan
