### ISSUE TITLE
Publishing Fixes

### ISSUE THREAD

**Issue by SashaScholar6** [Scholar-6/brillder#3397]
- [x] Publish button should be greyed out if brick is not in pending publication column (so publisher/admin has to click to send to publisher in order to publish

- [x] When editor clicks to send brick to publisher, they should see the following popup:

<img width="745" alt="Screenshot 2021-05-20 at 12 06 14" src="https://user-images.githubusercontent.com/59654112/118968397-cac8f300-b963-11eb-9453-24e999fcab21.png">

Before submitting this brick for publication, please confirm the following:

The images used are of a reasonable quality and have neither stretched nor pixelated.  They are available for use without commercial restrictions. 

The Prep material for this brick should not take significantly longer or shorter to consider than the recommended guideline (5, 10, and 15 minutes for 20, 40, and 60 minute bricks respectively). 

The Synthesis for this brick should not take significantly longer or shorter to read than the recommended guideline 
(4, 8, and 16 minutes @ 150-200 words/min. for 20, 40, and 60 minute bricks respectively).   

I have clicked through the mobile previews on the right of the screen while building, and have pressed the green button in the top right to play preview a version of this brick on a desktop.  In both cases, I have either flagged technical issues where they have arisen, or made fixes to improve the play experience myself.

- [x] If Send to Publisher clicked before all boxes are checked, popup wiith red circle and white alert triangle says: We want to make sure each brick is as enjoyable and fair as it can possibly be. (Brandon bold, larger text)
Please check all boxes before submitting this brick for publication (Brandon Reg Italic, smaller text)

- [x] it's not ready yet red default, blue hover

- [x] when all boxes checked, 'Send to Publisher goes green with white text

<img width="1243" alt="Screenshot 2021-05-20 at 16 08 34" src="https://user-images.githubusercontent.com/59654112/119003472-a8e06800-b985-11eb-9255-44c4a0e958c7.png">

- [x] centre title 'Before submitting...

- [x] first line of text should be level with checkboxes

- [x] Increase space between each cheboxes (height of panel can increase)

**Comment by ivanromakh** [comment]
@SashaScholar6 I don`t understand first point. What is pending publication column?
![image](https://user-images.githubusercontent.com/18567511/118979235-edb5d000-b980-11eb-8d1b-5782a90c43d5.png)

**Comment by ivanromakh** [comment]
@SashaScholar6 so you can click grey button?
![image](https://user-images.githubusercontent.com/18567511/118979558-42594b00-b981-11eb-915b-05f6e4431648.png)

![image](https://user-images.githubusercontent.com/18567511/118979528-3b323d00-b981-11eb-94c2-c7ee64b71690.png)

**Comment by ivanromakh** [comment]
@SashaScholar6 Publish button is grey for publisher when it is not in status review. Admin can publish anytime.
![image](https://user-images.githubusercontent.com/18567511/118982940-944fa000-b984-11eb-9a79-43df35d2286e.png)
