### ISSUE TITLE
Onboarding and help circles

### ISSUE THREAD

**Issue by SashaScholar6** [Scholar-6/brillder#3398]
<img width="1804" alt="Screenshot 2021-05-20 at 15 26 38" src="https://user-images.githubusercontent.com/59654112/118996470-d9bd9e80-b97f-11eb-9cd3-973f13f53335.png">
<img width="1805" alt="Screenshot 2021-05-20 at 15 26 52" src="https://user-images.githubusercontent.com/59654112/118996499-df1ae900-b97f-11eb-93b0-e155a31c0fe2.png">

- [x] Title: Be punchy and succinct. This ought to be written in Camel or Sentence Case, and give a reasonable indication of the content of the brick.  If you would like to use a more playful title, remember to add relevant keywords in the section below, so that your brick is more likely to appear to interested learners.

- [x] Keywords: Keywords are best thought of as likely search terms, and are ultimately curated by Publishers for each subject.  For multi-word keywords, separate words with a hyphen, eg. ‘19th-Century’.

- [x] Levels: same text and styling as on cover page

- [x] Open Question: We see education as being a mix of open questions and closed questions.  A lot of emphasis is placed on the latter in traditional schooling.  While it is undoubtedly necessary to build on fundamentals, it can be stifling for both teachers and learners not to go any further and engage in more holistic discussion.  A good open question may be the title for an essay or seminar, and should invite a broader dialogue or appreciation of the subject at hand.

<img width="1807" alt="Screenshot 2021-05-20 at 15 25 35" src="https://user-images.githubusercontent.com/59654112/118996636-f4901300-b97f-11eb-8b44-70834e9b38b5.png">

- [x] start-building page (both buttons red with white text) on hover

<img width="1803" alt="Screenshot 2021-05-20 at 15 26 08" src="https://user-images.githubusercontent.com/59654112/118996650-f5c14000-b97f-11eb-93df-cbe1747ae045.png">

- [x] Author Profile: This is taken from the information you provide in your profile page, and should reflect your academic interests and credentials.
- [x] play now green on hover

- [x] @aromakh  latest published brick in author selected subject. If no published brick in that subject, latest general & topical brick

<img width="1805" alt="Screenshot 2021-05-20 at 15 26 22" src="https://user-images.githubusercontent.com/59654112/118996655-f6f26d00-b97f-11eb-8447-b0c7dcb1b744.png">

- [x] Brief: Two or three sentences is often enough.  This is the first page learners will see (after the cover), so aim to hook them -   interesting anecdotes, problem statements and paradoxes are most welcome!

- [x] Prep: This is a timed section, and though learners will not be moved on to the next section automatically, we recommend that you try to be fair with your estimation of how long this section will take.  This will help learners apportion 20, 40, or 60 minutes to a brick and have the satisfaction of completing them within that timeframe.  Within these lengths, it should be possible to allocate 5, 10, or 15 minutes respectively to complete the prep section.

<img width="1239" alt="Screenshot 2021-05-21 at 13 43 56" src="https://user-images.githubusercontent.com/59654112/119139194-a25ff800-ba3a-11eb-8381-a80a13ea3819.png">

- [ ] single keywords default to lowercase and do not capitalise?

**Comment by ivanromakh** [comment]
@SashaScholar6 can`t do anything there until proposal page is fixed.

**Comment by SashaScholar6** [comment]
@ivanromakh what's up with it? which page exactly?

**Comment by ivanromakh** [comment]
@SashaScholar6 something is wrong with routing. we probably need another url for proposal pages.

**Comment by ivanromakh** [comment]
@carloscholar6 @SashaScholar6  could we use another route for proposal pages which is not related to investigation?

**Comment by SashaScholar6** [comment]
odd, doesn't really have anything to do with investigation

**Comment by ivanromakh** [comment]
@SashaScholar6  They have same url. Router don`t know what to do with it and is refreshing page in infinity loop

**Comment by SashaScholar6** [comment]
https://dev-app.brillder.com/build/brick/304/brick-title

that doesn't have investigation in it? I'm confused

**Comment by ivanromakh** [comment]
@SashaScholar6 it has. router for investigation use /build/brick/304 part. which is the same as proposal part. it don`t care what is after it.

**Comment by ivanromakh** [comment]
@SashaScholar6 it works fine id dev. interesting.

**Comment by ivanromakh** [comment]
@SashaScholar6 I see it works fine for bricks which are already finished not for new ones.

**Comment by SashaScholar6** [comment]
when you say proposal part, do you mean plan tab or brick-title, open-question, length etc.?

**Comment by ivanromakh** [comment]
![image](https://user-images.githubusercontent.com/18567511/119142393-1e643b00-ba4f-11eb-90a4-802c3a98a46a.png)

**Comment by ivanromakh** [comment]
@SashaScholar6 the open question in design is wrong. it is quill. need update.

**Comment by aromakh** [comment]
@ivanromakh  
Here is api to get lastest public brick withing users subject, or general subject in case of no bricks for user subjects.
http://swagger.scholar6.org/docs/#!/brick/getLastest

**Comment by ivanromakh** [comment]
@SashaScholar6 this is question. I don`t know what I should do.
![image](https://user-images.githubusercontent.com/18567511/120333359-49287c00-c2f8-11eb-8a5f-44c1517b4026.png)
