### ISSUE TITLE
BUILD & PLAY FIXES

### ISSUE THREAD

**Issue by SashaScholar6** [Scholar-6/brillder#3399]
- [x] PLAY: On vertical shuffle, 'Hover images to zoom' should be on same line as 'Drag to rearrange'

- [X] PLAY: Choose One and Several Height Fix

- [x] BUILD/PLAY Bullet points rendering as numbers, and too small in PLAY

- [x] BUILD PREVIEW: font should be left align not justify

- [x] BUILD: Colour panel not working in Plan tab and stays fixed

**Comment by ivanromakh** [comment]
@william-gooch did you fix alignment. seems fixed for me.
