### ISSUE TITLE
Text component

### ISSUE THREAD

**Issue by scholar6admin** [Scholar-6/brillder#34]
Insert CKeditor Wysiwyg into text component. 

Review documentation and see if it supports Latex.

We want it look something like this
![image](https://user-images.githubusercontent.com/58778078/73649366-8682e800-4677-11ea-84f5-81c1c75ebdec.png)

But we only want Bold and Underline as options. (no other options)

Character limit on the text component should be 500 Characters.

**Comment by ivanromakh** [comment]
https://github.com/Scholar-6/brillder/pull/39

**Comment by ivanromakh** [comment]
![image](https://user-images.githubusercontent.com/18567511/73936148-d9180a80-48ea-11ea-986e-bd4eff874fe0.png)
