### ISSUE TITLE
Categorise: each answer hints appearing in wrong order because of randomising display

### ISSUE THREAD

**Issue by SashaScholar6** [Scholar-6/brillder#3402]
<img width="408" alt="Screenshot 2021-05-20 at 16 36 41" src="https://user-images.githubusercontent.com/59654112/119007899-90724c80-b989-11eb-8dfb-db2c9de6d94c.png">

- [x] in phone show answers underneath correct headings, with hints attached to them

- [x] In the Play, have a light grey box under each heading with dashed lines and 'Drag Answers Here' until all answers have been categorised
<img width="1385" alt="Screenshot 2021-05-20 at 16 38 58" src="https://user-images.githubusercontent.com/59654112/119008216-e1824080-b989-11eb-8b95-a4fb21dff451.png">

- [x] answers should not disappear if question not attempted

- [x] fix duplication bug

**Comment by ivanromakh** [comment]
@SashaScholar6 but categorise don`t have each answer hints.

**Comment by ivanromakh** [comment]
@SashaScholar6 should I add each answer hints in categorise?
