### ISSUE TITLE
Matomo signup event triggers twice

### ISSUE THREAD

**Issue by scholar6admin** [Scholar-6/brillder#3409]
@ivanromakh seems to trigger twice
![image](https://user-images.githubusercontent.com/58778078/122419076-93f5f500-cf82-11eb-9baf-b4f3b21400be.png)

Expecting a synthesis-signup event to matomo as an unauthenticated user entering email on the synthesis page.

![image](https://user-images.githubusercontent.com/58778078/119353977-6a0b2480-bc9b-11eb-8913-1dd5e3680474.png)

This is to track advertising conversions.

**Comment by ivanromakh** [comment]
@scholar6admin this event is used to track logged in users in login page as well.
