### ISSUE TITLE
Pair match deleting wrong answer

### ISSUE THREAD

**Issue by scholar6admin** [Scholar-6/brillder#3417]
Delete first answer actually deletes last answer

https://user-images.githubusercontent.com/58778078/119645416-e9bcfe80-be15-11eb-82e4-e916c91400aa.mp4

**Comment by ivanromakh** [comment]
@scholar6admin can`t reproduce it in new brick. is it old brick?

**Comment by ivanromakh** [comment]
@scholar6admin brick 663 isn`t working for me. maybe it is broken.

**Comment by ivanromakh** [comment]
@scholar6admin I see this is happen when you remove answer in the middle. it is something related to quill.

**Comment by ivanromakh** [comment]
@scholar6admin this is not only in pair match it is in every question where answers are lists.

**Comment by ivanromakh** [comment]
this is not needed for missing word as it is just input there.
