### ISSUE TITLE
Get rid of ckeditor code including highlighter

### ISSUE THREAD

**Issue by scholar6admin** [Scholar-6/brillder#3430]
Few lines still outstanding
![image](https://user-images.githubusercontent.com/58778078/121576192-10875180-ca20-11eb-8757-1198e1bc87c4.png)

- [x] Hide the highlighter using a js variable that can be turned on for testing using the dev console. Lets make a global Brillder object and have booleans under its Brillder.testing property for displaying or hiding new features.
- [x] Generally fix it. Seems to be a memory leak at the moment.
- [x] Highlight between lines when dragging down
- [ ] Selecting a highlighted text a second time will unhighlight the text
- [ ] Clicking the highlight option on the left again will leave the text highlighted but 'put the cap back on the highlighter'

https://user-images.githubusercontent.com/58778078/120458747-707e5800-c38f-11eb-88c1-fee9dbe13e43.mp4

**Comment by ivanromakh** [comment]
not working probably because it is ck-editor but content generated by quill.

**Comment by ivanromakh** [comment]
need to replace ck-editor with quill to make it work for prep. prep and synthesis fields are using many quill plugins which aren`t suported by ck-editor. 


Need to read about quill to add highlighting on select.

**Comment by ivanromakh** [comment]
ckeditor removed.

**Comment by ivanromakh** [comment]
I managed to highlight text in quill. not sure about unhighlighting.

it works only on raw text.
![image](https://user-images.githubusercontent.com/18567511/121508738-9c808580-c9ee-11eb-962c-8e53d890f1d5.png)

**Comment by ivanromakh** [comment]
removing specific formats
https://github.com/quilljs/quill/issues/2807
