### ISSUE TITLE
Adapt book to phone

### ISSUE THREAD

**Issue by scholar6admin** [Scholar-6/brillder#3431]
- [x] the route is redirecting me back to home page on iphone 11 on browserstack

<img width="388" alt="Screenshot 2021-06-11 at 10 45 01" src="https://user-images.githubusercontent.com/59654112/121667380-1e7db680-caa2-11eb-8fa6-42d4e8aca6a5.png">

- [x] cover

<img width="388" alt="Screenshot 2021-06-10 at 16 16 42" src="https://user-images.githubusercontent.com/59654112/121551096-3f44fe00-ca07-11eb-92db-4a7052236e1a.png">

- [x] inner page

- [x] corner-up-left button goes to book cover

<img width="387" alt="Screenshot 2021-06-10 at 16 17 05" src="https://user-images.githubusercontent.com/59654112/121551147-4d931a00-ca07-11eb-9f05-3ba95f31ca5a.png">

- [x] Brief

<img width="385" alt="Screenshot 2021-06-10 at 16 17 25" src="https://user-images.githubusercontent.com/59654112/121551204-597edc00-ca07-11eb-968b-f33f1846e267.png">

- [x] Prep

<img width="387" alt="Screenshot 2021-06-10 at 16 17 56" src="https://user-images.githubusercontent.com/59654112/121551303-6d2a4280-ca07-11eb-9b4d-01571155d862.png">

- [x] Questions 

<img width="388" alt="Screenshot 2021-06-10 at 16 18 53" src="https://user-images.githubusercontent.com/59654112/121551437-8d5a0180-ca07-11eb-8fe7-c40d5ff13b3f.png">

- [x] Synthesis

- [x] add bottom menu bar
- [x] adjust top bar to be full width, numbers in Brandon bold

- [x] animate swipe icon on first page
- [x] fix height issue in inner panels
- [x] numbers should be clickable

**Comment by ivanromakh** [comment]
@scholar6admin there is no zendesk button in design. should I hide it?

**Comment by ivanromakh** [comment]
this is what I have made so far.
![image](https://user-images.githubusercontent.com/18567511/121690449-8a761400-cace-11eb-8eb3-b8152bc31cab.png)

**Comment by scholar6admin** [comment]
> @scholar6admin there is no zendesk button in design. should I hide it? and beta text

@ivanromakh no dont hide. I think what you have is good

**Comment by ivanromakh** [comment]
ok then I will be adjusting book and other pages.

**Comment by ivanromakh** [comment]
@SashaScholar6 need link for this icon 
![image](https://user-images.githubusercontent.com/18567511/121701224-594f1100-cad9-11eb-9555-4031dddaf22e.png)

**Comment by ivanromakh** [comment]
questions are for monday.

**Comment by ivanromakh** [comment]
there is some errors related to quill in some books. but most should work.
![image](https://user-images.githubusercontent.com/18567511/122244768-cd205d80-cecd-11eb-8bd5-64196287920e.png)
![image](https://user-images.githubusercontent.com/18567511/122244789-d3163e80-cecd-11eb-823f-5986a9c32db1.png)

**Comment by ivanromakh** [comment]
maybe attempts are too old

**Comment by ivanromakh** [comment]
but it works fine for my new attempts.

**Comment by ivanromakh** [comment]
iphone version
![image](https://user-images.githubusercontent.com/18567511/123255858-f9089800-d4f8-11eb-8c65-ea7692db19c2.png)

**Comment by ivanromakh** [comment]
iphone book.
![image](https://user-images.githubusercontent.com/18567511/123257245-931d1000-d4fa-11eb-9754-86ff94810164.png)
