### ISSUE TITLE
Library on phone

### ISSUE THREAD

**Issue by scholar6admin** [Scholar-6/brillder#3432]
<img width="391" alt="Screenshot 2021-06-11 at 14 54 52" src="https://user-images.githubusercontent.com/59654112/121697590-1b47f200-cac5-11eb-8067-b2bab9d02543.png">

- [x] Make sure 20 min books are not super slim
- [x] stop weird scrolling thing, if it doesnt fit it should go to next line
- [x] One subject per row with subject title

- [x] enable My library in main page

- [x] show View it in my Library button again on results book page

**Comment by ivanromakh** [comment]
@SashaScholar6 it will scroll for now.
![image](https://user-images.githubusercontent.com/18567511/123265455-bf895a00-d503-11eb-808f-6080d7069ffe.png)
