### ISSUE TITLE
Joe #383: Green ticks become amber 

### ISSUE THREAD

**Issue by SashaScholar6** [Scholar-6/brillder#3439]
https://app.brillder.com/play-preview/brick/140/ending 

First screen shot shows that apparently I got question 6 right.

Second screen shot shows that - though I did nothing - number 6 is now ticked orange.

<img width="1133" alt="Screenshot 2021-06-03 at 15 45 36" src="https://user-images.githubusercontent.com/59654112/120664313-bec05380-c482-11eb-8e8a-964073a6129e.png">

<img width="1155" alt="Screenshot 2021-06-03 at 15 48 12" src="https://user-images.githubusercontent.com/59654112/120664772-1eb6fa00-c483-11eb-8e55-4bdfe246f4a1.png">

**Comment by ivanromakh** [comment]
@scholar6admin it is amber if you don`t visit that question tab during review.
