### ISSUE TITLE
Joe #371: Brick 529 scoring issue with Q3

### ISSUE THREAD

**Issue by SashaScholar6** [Scholar-6/brillder#3440]
I did my Blake Tyger brick and got 99%. I had put in the wrong answer on Question 3.

In the final marks it showed I had orange ticks not just for 3, which I corrected, but for 7/8/9/10/11/12/1/14/15.

------------------
Submitted from: https://app.brillder.com/play-preview/brick/529/ending

**Comment by ivanromakh** [comment]
@SashaScholar6 probably fixed by #3439
