### ISSUE TITLE
Tom #366: Phone play should not refresh on rotation

### ISSUE THREAD

**Issue by SashaScholar6** [Scholar-6/brillder#3441]
- [x] Should not reset timer on prep

- [x] Should not reset to question 1
- [x] Not working at least for choose one and categorise

https://user-images.githubusercontent.com/58778078/121551764-d1e59d00-ca07-11eb-8b59-98d53e1f27e6.mp4

We need to store the question answers given so that rotation does not cause play attempt to be reset.

Test on iphone 11 in browserstack

**Comment by ivanromakh** [comment]
@SashaScholar6  done till synthesis. should I fix header height?
![image](https://user-images.githubusercontent.com/18567511/121033762-2218f100-c7b5-11eb-8057-425a9e52d5a1.png)

**Comment by ivanromakh** [comment]
attempt is cashing you can try refreshing page even in desktop.

**Comment by ivanromakh** [comment]
hm. stepping is inside of child component. I could try cashing that separatly too.

**Comment by ivanromakh** [comment]
@SashaScholar6 it will cash data only after you go to next question.
