### ISSUE TITLE
White screen on end of play preview

### ISSUE THREAD

**Issue by scholar6admin** [Scholar-6/brillder#3442]
Create a brick and then quickly click through the play preview.
It goes to a whitescreen
![image](https://user-images.githubusercontent.com/58778078/120720483-0e733f00-c4c4-11eb-8999-176b01c046a8.png)

![image](https://user-images.githubusercontent.com/58778078/120720474-0c10e500-c4c4-11eb-9658-265112c9fdaa.png)

Tried fixing it here
https://github.com/Scholar-6/brillder/commit/9465144a7d3b1809125abf8003e51f25d9e7356b

But still seeing same symptom slightly different line item
![image](https://user-images.githubusercontent.com/58778078/120727750-403fd200-c4d3-11eb-8544-6eb5d91f79a0.png)

**Comment by william-gooch** [comment]
@scholar6admin I can't reproduce this.
It's entirely possible it was related to #3443 if it only happened in play preview - it was possibly getting the brick from redux after the PUT request returned no questions or something like that.
If you can give me a video of it happening again I'll take another look.
