### ISSUE TITLE
Create a brick, exit then return, shows empty brick

### ISSUE THREAD

**Issue by scholar6admin** [Scholar-6/brillder#3443]
Easiest way to reproduce is just to play preview and then return to the investigation build screen. 

![image](https://user-images.githubusercontent.com/58778078/120720828-ac670980-c4c4-11eb-9c70-3351eba5dd09.png)

https://user-images.githubusercontent.com/58778078/120720945-d91b2100-c4c4-11eb-8388-258835db5a74.mp4

**Comment by william-gooch** [comment]
@ivanromakh this is a backend issue, if you're alright with me taking it over?
