### ISSUE TITLE
isCore is not set by default

### ISSUE THREAD

**Issue by scholar6admin** [Scholar-6/brillder#3444]
Also test from the menu. 

If user clicks create brick from public tab then set brick as public
If user clicks create brick from personal tab then set brick as personal.

![image](https://user-images.githubusercontent.com/58778078/120721000-edf7b480-c4c4-11eb-960f-bafcf9c5cb7a.png)

**Comment by ivanromakh** [comment]
yep it was removed as I added example page. which is page before proposal. I will restore it.

**Comment by ivanromakh** [comment]
it wasn`t working propertly probably before but now it should in back to work page.
