### ISSUE TITLE
Clicking assignment notification takes me to ugly intro page

### ISSUE THREAD

**Issue by scholar6admin** [Scholar-6/brillder#3449]
![image](https://user-images.githubusercontent.com/58778078/120725535-12a45a00-c4ce-11eb-82fe-a2816a3d93d1.png)
As a student@scholar6.org
When I click on the assignment notification
![image](https://user-images.githubusercontent.com/58778078/120725576-2cde3800-c4ce-11eb-84bd-b3c918c56eb4.png)

It goes to 
https://dev-app.brillder.com/play/brick/674/intro
which is ugly

**Comment by ivanromakh** [comment]
move to cover page.
