### ISSUE TITLE
Book looks weird

### ISSUE THREAD

**Issue by scholar6admin** [Scholar-6/brillder#3452]
Still happening on dev 10/06/21

I think this might be when only the investigation was completed.

https://app.brillder.com/post-play/brick/576/115

https://user-images.githubusercontent.com/58778078/120728633-45058580-c4d5-11eb-90f8-f05c91ec3920.mp4

**Comment by ivanromakh** [comment]
@scholar6admin that person didn`t play brick to the end. only saved live probably.

**Comment by ivanromakh** [comment]
attempt was removed. don`t see that anymore.
