### ISSUE TITLE
Mobile Play

### ISSUE THREAD

**Issue by SashaScholar6** [Scholar-6/brillder#3459]
https://xd.adobe.com/view/a28eecdc-b8fe-4c23-bc93-209ee85f31f2-f7dd/ 

BRIEF
<img width="387" alt="Screenshot 2021-06-22 at 15 46 01" src="https://user-images.githubusercontent.com/59654112/122946643-71445180-d371-11eb-8b07-e193b0fad86c.png">

- [x] update top and bottom bars
- [x] fix assign popup style on a call with me

PRE-PREP
<img width="386" alt="Screenshot 2021-06-22 at 15 46 15" src="https://user-images.githubusercontent.com/59654112/122946897-a6e93a80-d371-11eb-8b8c-fb80dbfbf22a.png">

- [x] get arrow from me

PREP
<img width="387" alt="Screenshot 2021-06-22 at 15 46 24" src="https://user-images.githubusercontent.com/59654112/122947069-c84a2680-d371-11eb-944c-560f787404c4.png">

- [x] update design

PRE-INVESTIGATION
<img width="387" alt="Screenshot 2021-06-22 at 15 46 34" src="https://user-images.githubusercontent.com/59654112/122948384-c896f180-d372-11eb-8442-bb92cb0c746c.png">

- [x] add page

COUNTDOWN
<img width="386" alt="Screenshot 2021-06-22 at 15 46 43" src="https://user-images.githubusercontent.com/59654112/122948528-e19fa280-d372-11eb-87ac-c354f9a364b8.png">

- [x] update bars (text tbd)

INVESTIGATION
<img width="386" alt="Screenshot 2021-06-22 at 15 46 53" src="https://user-images.githubusercontent.com/59654112/122948686-009e3480-d373-11eb-926d-df121c852695.png">

- [x] solid white circle and blue text for answered questions; current question has ring and small triangle

PROVISIONAL SCORE
<img width="387" alt="Screenshot 2021-06-22 at 15 47 04" src="https://user-images.githubusercontent.com/59654112/122949236-668abc00-d373-11eb-89c1-e84152dad942.png">

- [x] show number of correct and incorrect questions, number of questions attempted and time spent on investigation

PRE-SYNTHESIS
<img width="388" alt="Screenshot 2021-06-22 at 15 47 11" src="https://user-images.githubusercontent.com/59654112/122949498-9cc83b80-d373-11eb-9490-640f55a41cea.png">

- [x] add page

SYNTHESIS

<img width="386" alt="Screenshot 2021-06-22 at 15 47 20" src="https://user-images.githubusercontent.com/59654112/122949566-ac478480-d373-11eb-97cf-6fe890d08984.png">

- [x] update bars

REVIEW

<img width="386" alt="Screenshot 2021-06-22 at 15 47 41" src="https://user-images.githubusercontent.com/59654112/122949799-dac55f80-d373-11eb-9f6b-b014ee2fbb31.png">

- [x] update design with ticks, crosses and triangle pointer
- [x] next to 'Correct!', green circle with white tiick; next to 'Not quite - try again', red circle with white cross

<img width="385" alt="Screenshot 2021-06-22 at 15 47 52" src="https://user-images.githubusercontent.com/59654112/122950027-0ba59480-d374-11eb-8285-501e582ec209.png">

- [x] add number of yellow ticks and review time

**Comment by ivanromakh** [comment]
@SashaScholar6  there is no subject here.

**Comment by ivanromakh** [comment]
@SashaScholar6 need this arrow.
![image](https://user-images.githubusercontent.com/18567511/123424597-bbc00b00-d5c9-11eb-9460-18a072fb313b.png)

**Comment by ivanromakh** [comment]
@SashaScholar6 it will be hard to add triangle in live. that area is scrollable. You can create separate task for it.

**Comment by ivanromakh** [comment]
@SashaScholar6 provisional score page. maybe we should make answers scrollable like in live and review.
some data isn`t visible in provisional score page.
![image](https://user-images.githubusercontent.com/18567511/123926939-0dcfaa80-d995-11eb-82fe-227af9f531bd.png)

**Comment by ivanromakh** [comment]
Score pages iphone.
![image](https://user-images.githubusercontent.com/18567511/123928711-d2ce7680-d996-11eb-8336-e51c47d43e2f.png)
![image](https://user-images.githubusercontent.com/18567511/123928819-ea0d6400-d996-11eb-8081-c8e463472746.png)


Score pages android
![image](https://user-images.githubusercontent.com/18567511/123929027-1a550280-d997-11eb-8383-73c214bf7dd2.png)
![image](https://user-images.githubusercontent.com/18567511/123929065-250f9780-d997-11eb-944c-c1a55cc7fa4c.png)
