### ISSUE TITLE
Incorrect attempts get 0 not free marks

### ISSUE THREAD

**Issue by SashaScholar6** [Scholar-6/brillder#3460]

**Comment by ivanromakh** [comment]
I am not sure about short answer. if there is 6 answers each wrong answer gives you 0.5points.
maximum points is always 6.
![image](https://user-images.githubusercontent.com/18567511/121318778-3d4e4280-c914-11eb-92df-f5ba2fde3d45.png)
![image](https://user-images.githubusercontent.com/18567511/121318707-2ad40900-c914-11eb-95e1-6920e7b9700c.png)

**Comment by ivanromakh** [comment]
@SashaScholar6 can`t reproduce it. if you select wrong answer it will give you 1. 0.5 or 0.75 pointes depend on question type. it gives you 0 if you just skip question.
