### ISSUE TITLE
Attribution text on images - Smaller font and vertical on right of images

### ISSUE THREAD

**Issue by scholar6admin** [Scholar-6/brillder#3466]
- [ ] @ivanromakh We need it on images in synthesis and prep

Font should be vertical going up the bottom right hand side of images. 

Size equivalent to 6px or smaller. Use vh or whatever is best.

This might be needed for chrome
https://www.programmersought.com/article/9833824333/

**Comment by ivanromakh** [comment]
@scholar6admin where is vertical on right here?
![image](https://user-images.githubusercontent.com/18567511/121162334-82ac3a80-c856-11eb-9628-db15c97a55ac.png)
