### ISSUE TITLE
Authors can upload cover images on personal bricks

### ISSUE THREAD

**Issue by scholar6admin** [Scholar-6/brillder#3476]
This is still not working for student@scholar6.org on dev-app 15/06/21
![image](https://user-images.githubusercontent.com/58778078/122106781-3cd11280-ce12-11eb-9d06-922fd6b3ca44.png)

<img width="789" alt="Screenshot 2021-06-21 at 10 10 01" src="https://user-images.githubusercontent.com/59654112/122737389-e54efe80-d278-11eb-93c1-ba28dd8d717d.png">

- [x] text higher, bigger, and dark blue

This is just on personal bricks, not on public bricks.

- [x] add text which says 'Click to add a cover image’

**Comment by william-gooch** [comment]
@scholar6admin Is this not supposed to be possible?
