### ISSUE TITLE
Play - Show the maximum achievable mark on every question panel

### ISSUE THREAD

**Issue by scholar6admin** [Scholar-6/brillder#3477]
- [x] All answers in play-preview are showing out of 5
![image](https://user-images.githubusercontent.com/58778078/125268847-02b73b80-e300-11eb-987a-1fd44e87bb4e.png)

Also need to show how the score has changed on the review panels.

<img width="386" alt="Screenshot 2021-06-22 at 17 12 28" src="https://user-images.githubusercontent.com/59654112/122962188-1284d500-d37d-11eb-8ead-ba7985ba016a.png">

- [x] Mobile
- [x] Desktop
- [x] show tick in review
- [x] fix spacing below triangle

**Comment by ivanromakh** [comment]
@scholar6admin why this is moved back?
