### ISSUE TITLE
Book - hide quick access numbers

### ISSUE THREAD

**Issue by SashaScholar6** [Scholar-6/brillder#3480]
This is just on desktop

Just hide numbers for moment.

**Comment by ivanromakh** [comment]
@SashaScholar6 this is problematic as there is multiple attempts to which attempt it should navigate?

**Comment by ivanromakh** [comment]
@SashaScholar6 there is a problem with moving. right now book is opening when you hover. so it wiill not open unsless you hoveer over book. and when you go outside the book it will close. so it will not open on click unless we change rules for the book.
