### ISSUE TITLE
BUILD fixes

### ISSUE THREAD

**Issue by SashaScholar6** [Scholar-6/brillder#3482]
<img width="278" alt="Screenshot 2021-06-10 at 12 45 44" src="https://user-images.githubusercontent.com/59654112/121519610-d26f3b00-c9e9-11eb-8f13-fae9baa6a320.png">

- [x] line height with latex input should remain constant compared to other lines.
- [x] nice :), but now lines are a bit too close together - please add a bit more space between them

<img width="252" alt="Screenshot 2021-06-10 at 12 47 29" src="https://user-images.githubusercontent.com/59654112/121519779-06e2f700-c9ea-11eb-8980-ea17afb5d5c8.png">

- [x] only show tooltip for current state of brick
- [x] make circles a smaller
- [x] also show status circles on plan tab and synthesis

<img width="388" alt="Screenshot 2021-06-10 at 12 49 11" src="https://user-images.githubusercontent.com/59654112/121519973-43aeee00-c9ea-11eb-9bfb-47ba6065be99.png">

<img width="398" alt="Screenshot 2021-06-10 at 12 48 59" src="https://user-images.githubusercontent.com/59654112/121520005-4c9fbf80-c9ea-11eb-9a93-64eb1542de53.png">

- [x] Vertical shuffle answer panel should have sound option and be arranged like choose one/several

- [x] Also add sound to horizontal shuffle

<img width="413" alt="Screenshot 2021-06-10 at 12 50 46" src="https://user-images.githubusercontent.com/59654112/121520141-7bb63100-c9ea-11eb-8091-b154c8fa68e9.png">

- [x] also add sound and styling like choose one/several for Categorise

<img width="290" alt="Screenshot 2021-06-10 at 12 56 08" src="https://user-images.githubusercontent.com/59654112/121520876-583fb600-c9eb-11eb-9364-80c15097d311.png">
<img width="761" alt="Screenshot 2021-06-10 at 12 56 40" src="https://user-images.githubusercontent.com/59654112/121520878-58d84c80-c9eb-11eb-9f4b-dd62aed13049.png">

- [x] blockquote should be same size as reg text in phone (smaller)
- [x] blockquote should be same size as reg text in desktop (bigger)

<img width="265" alt="Screenshot 2021-06-10 at 12 58 09" src="https://user-images.githubusercontent.com/59654112/121521047-832a0a00-c9eb-11eb-992a-5d8b82fb2e82.png">

- [x] remove extra font-weight on Question Text component

<img width="578" alt="Screenshot 2021-06-10 at 13 10 14" src="https://user-images.githubusercontent.com/59654112/121522666-3fd09b00-c9ed-11eb-8e4c-d945760afe0d.png">

- [x] change to normal Yes/No button, grey and red backgrounds

**Comment by ivanromakh** [comment]
https://stackoverflow.com/questions/58943180/adding-a-custom-drop-down-tool-to-the-quill-editor-with-javascript

**Comment by ivanromakh** [comment]
@SashaScholar6 audio component in phone doesn`t look good. Should it look the same as in desktop?
![image](https://user-images.githubusercontent.com/18567511/121666029-838cd880-cab1-11eb-818c-da92ceb94b42.png)

**Comment by SashaScholar6** [comment]
yep, much too small - is that a caption underneath?  what's happening at the bottom?

**Comment by ivanromakh** [comment]
@SashaScholar6 what about tutorials?
