### ISSUE TITLE
Improve Hints and colour coding in review

### ISSUE THREAD

**Issue by SashaScholar6** [Scholar-6/brillder#3484]
- [x] These should all be the same for desktop and mobile

<img width="677" alt="Screenshot 2021-07-13 at 13 11 54" src="https://user-images.githubusercontent.com/59654112/125452278-7f123fc5-ba6e-4cfd-ac37-8f5a834a2067.png">

- [x] add red circle with cross and green circle with check next to 'Not quite..' and 'Correct!' like in mobile 

GLOBAL HINTS STYLING - apply to all answer types: 

- [x] Add 'Hint:' in Brandon bold to all hints
- [x] Add more padding in desktop (same on left, right, top and bottom)

<img width="650" alt="Screenshot 2021-07-13 at 13 28 25" src="https://user-images.githubusercontent.com/59654112/125451598-326aa2ef-747e-4552-991c-c81f1737a6c2.png">

- [x] for correct answers, add green circle, f5f6f7 check and 'NB:' in Brandon bold
- [x] same padding everywhere on left, right, top and bottom
- [x] text of all hints should be left-aligned

- [x] apply to Short Answer, Choose One & Several, Pair Match, Missing Word, Categorise, Vertical and Horizontal Shuffle, Word and Line Highlighting

SHORT ANSWER
<img width="990" alt="Screenshot 2021-07-13 at 13 12 15" src="https://user-images.githubusercontent.com/59654112/125449530-110ca79a-5f8b-4ab7-b16c-31ca79319de5.png">

- [x] PLACEHOLDERS: 'Type your answer here' (one short answer) / 'Type Answer 1', 'Type Answer 2' etc.

<img width="371" alt="Screenshot 2021-07-13 at 13 52 34" src="https://user-images.githubusercontent.com/59654112/125454826-35ca71fc-f0a6-44f0-aee7-1b1bcb0163d2.png">

- [x] 50% green if answer correct, red background white text if incorrect

EACH ANSWER HINTS
CHOOSE ONE & SEVERAL
<img width="850" alt="Screenshot 2021-07-13 at 13 45 56" src="https://user-images.githubusercontent.com/59654112/125453914-a7b32fe8-4368-44ee-8413-97c3e2cace66.png">

- [x] each answer - correct (50% green)
- [x] hints should be left aligned

<img width="856" alt="Screenshot 2021-07-13 at 14 01 53" src="https://user-images.githubusercontent.com/59654112/125456103-96e8c4bc-bef2-4e6f-b99f-04af392369f7.png">

- [x] each answer - incorrect

PAIR MATCH each answer hints
- [x] same idea and colours as choose one and several - 50% green if correct
- [x] show as grey if incorrect
- [x] hints should be left aligned

VERTICAL AND HORIZONTAL SHUFFLE
- [x] 50% green if correct

MISSING WORD EACH ANSWER
- [x] same idea and colours as choose one and several
- [x] add padding above hints and round all corners

**Comment by ivanromakh** [comment]
@SashaScholar6 there is no quill toolbar here.
![image](https://user-images.githubusercontent.com/18567511/125606750-327f2389-911f-455b-b95d-66106392c721.png)

this one is real.
![image](https://user-images.githubusercontent.com/18567511/125606788-2d0b3861-3b13-41b8-9527-7d1fc79315dd.png)

**Comment by ivanromakh** [comment]
missing word hints.
![image](https://user-images.githubusercontent.com/18567511/125609791-faa54194-8b1d-4239-80fa-ecbcc7483d37.png)

**Comment by ivanromakh** [comment]
@SashaScholar6 I can`t do it.
![image](https://user-images.githubusercontent.com/18567511/125791048-d1f0d088-bfc3-4d10-b08c-d1182d3e393a.png)

**Comment by ivanromakh** [comment]
this is how pair match hint are now. I don`t know what I need to fix.
