### ISSUE TITLE
Cant send back to publisher from editor

### ISSUE THREAD

**Issue by scholar6admin** [Scholar-6/brillder#3488]
Author sends to editor
editor sends to publisher
publisher sends back to editor
Then editor should still see button to send back to publisher 

https://user-images.githubusercontent.com/58778078/121531452-516a7080-c9f6-11eb-9133-bf55bb30dc22.mp4

**Comment by ivanromakh** [comment]
@scholar6admin that brick is cashed. And status of that cashed brick is sendedToPublisher.
![image](https://user-images.githubusercontent.com/18567511/126667085-f26b5a88-06b9-4353-9c10-0579c288d7ad.png)
