### ISSUE TITLE
Hints on choose one / choose several should be grey if not selected correctly

### ISSUE THREAD

**Issue by scholar6admin** [Scholar-6/brillder#3490]
![image](https://user-images.githubusercontent.com/58778078/121540569-7d89ef80-c9fe-11eb-8aac-2fa6b0fe99f5.png)

<img width="1098" alt="Screenshot 2021-07-16 at 09 58 05" src="https://user-images.githubusercontent.com/59654112/125921994-fd4bc254-e708-48bf-99d6-8f6f14d81c38.png">

- [x] only hint of selected incorrect answer should be yellow, others light grey

It is misleading if I see a hint in orange under a question that should not be selected (it makes me think I should have selected it). It should be grey instead.

**Comment by ivanromakh** [comment]
I detected some bug.
Choose several is correct if I select all answers with wrong ones. and result is 3/4.
![image](https://user-images.githubusercontent.com/18567511/125927011-c0e308f3-34c9-4183-b66b-48fdcd32b294.png)
