### ISSUE TITLE
Mobile Onboarding up to select-subjects

### ISSUE THREAD

**Issue by SashaScholar6** [Scholar-6/brillder#3492]
We need to have the updated onboarding

<img width="387" alt="Screenshot 2021-06-16 at 14 09 10" src="https://user-images.githubusercontent.com/59654112/122224852-6d658a80-ceac-11eb-8817-051365560650.png">

- [x] update design, login colours and buttons, with join now option like in desktop

<img width="387" alt="Screenshot 2021-06-16 at 14 10 17" src="https://user-images.githubusercontent.com/59654112/122225013-9554ee00-ceac-11eb-8d19-24ea270fde8e.png">

- [x] update email entry design

<img width="387" alt="Screenshot 2021-06-16 at 14 11 36" src="https://user-images.githubusercontent.com/59654112/122225197-c3d2c900-ceac-11eb-9be8-d1ec376719aa.png">

- [x] Join the revolution page

<img width="385" alt="Screenshot 2021-06-16 at 14 11 57" src="https://user-images.githubusercontent.com/59654112/122225266-d1884e80-ceac-11eb-8041-d4688c7f663b.png">

- [x] update User Agreement page size and design.  When checked, box turns green and panel animates by fading away

<img width="387" alt="Screenshot 2021-06-16 at 14 13 24" src="https://user-images.githubusercontent.com/59654112/122225478-04cadd80-cead-11eb-967c-784b3f158cb1.png">

- [x] Thank you for signing up page

<img width="388" alt="Screenshot 2021-06-16 at 14 13 48" src="https://user-images.githubusercontent.com/59654112/122225551-1318f980-cead-11eb-9acf-3bc66090baca.png">

- [x] User Preference updated

<img width="389" alt="Screenshot 2021-06-16 at 14 14 11" src="https://user-images.githubusercontent.com/59654112/122225614-2035e880-cead-11eb-9aca-a958694f528f.png">

- [x] Select subjects (grey background when subject selected)

**Comment by ivanromakh** [comment]
@SashaScholar6 what about forgot password link?

**Comment by ivanromakh** [comment]
@SashaScholar6 we probably don`t have join now page for phones.

**Comment by SashaScholar6** [comment]
@ivanromakh yes we do, new design 3rd screenshot on this task

**Comment by ivanromakh** [comment]
@SashaScholar6 there is no option to join with google as in desktop. This one look like register page.
![image](https://user-images.githubusercontent.com/18567511/122903038-afcd1280-d357-11eb-876a-59854ff42be4.png)

**Comment by ivanromakh** [comment]
Join page design is too big for iphones. they are not that long as in design. they are shorter with top and bottom menu.
![image](https://user-images.githubusercontent.com/18567511/122903707-574a4500-d358-11eb-9460-ef5066bb0cf1.png)
![image](https://user-images.githubusercontent.com/18567511/122903799-6af5ab80-d358-11eb-8a63-fbe685986051.png)
