### ISSUE TITLE
Image is stretched on iphone 11

### ISSUE THREAD

**Issue by scholar6admin** [Scholar-6/brillder#3494]
Possibly only after rotating.

See 'Othellos Hankerchief' question 4

Seems to be on the image component but not on the image insert button on quill.

**Comment by ivanromakh** [comment]
@scholar6admin I have no problem there.
![image](https://user-images.githubusercontent.com/18567511/124245345-96328480-db28-11eb-8386-e992c555fee8.png)

**Comment by ivanromakh** [comment]
@scholar6admin I can`t fix height in iphone (easy in android). Height is hardcoded in quill.  We need to fix it in quill. but if we fix it will need to remove something and it will look worse in desktop.

**Comment by ivanromakh** [comment]
We need to remove this slider to fix this.
![image](https://user-images.githubusercontent.com/18567511/124789566-1440c200-df53-11eb-9f38-97a656e1ce24.png)
