### ISSUE TITLE
Capitalisation option

### ISSUE THREAD

**Issue by scholar6admin** [Scholar-6/brillder#3495]
Transform the text and make sure the ctrl+z can undo it.

<img width="110" alt="Screenshot 2021-06-10 at 12 52 23" src="https://user-images.githubusercontent.com/59654112/121520377-c0da6300-c9ea-11eb-9ea3-16e432253908.png">

- [x] Add ability to change capitalisation on Synthesis toolbar

**Comment by william-gooch** [comment]
@scholar6admin @SashaScholar6 need icons for this.

**Comment by william-gooch** [comment]
@SashaScholar6 currently on synthesis. Where else should it be?
