### ISSUE TITLE
Order of questions changes

### ISSUE THREAD

**Issue by scholar6admin** [Scholar-6/brillder#3497]
- [x] When you click to a brick from back to work that it orders by 'order' on questions and not the order of the array.

When I change order of questions 
**Then exit and return to brick from back to work**
Then the order of questions is same as array 
It should use the order property of the questions

https://user-images.githubusercontent.com/58778078/122108498-2af06f00-ce14-11eb-84d6-6908bb4f0c59.mp4

**Comment by ivanromakh** [comment]
@scholar6admin I don`t see brick with id 704. can`t reproduce this in other bricks.

**Comment by ivanromakh** [comment]
I fixed this before.

**Comment by scholar6admin** [comment]
@ivanromakh I can see this right now on dev. Can I show you.

**Comment by ivanromakh** [comment]
@scholar6admin sure when you are free.

**Comment by ivanromakh** [comment]
@scholar6admin this is backend issue. we don`t need to save questions in brick anywore.

**Comment by ivanromakh** [comment]
@aromakh put /brick should not care about questions.
Please remove saving order of questions there. and questions at all.
