### ISSUE TITLE
Add a preview phone window on right hand side

### ISSUE THREAD

**Issue by scholar6admin** [Scholar-6/brillder#35]
We want a preview window on the right hand side of the Brick Build screen. 

![image](https://user-images.githubusercontent.com/58778078/73649642-23de1c00-4678-11ea-8544-29ea166953ea.png)

Ignore the rest of the screen we just want a phone outline on the right hand side. On smaller screens this preview should disappear. 

This phone outline will be empty and show message "Preview not available"

When we rebuild the play interface we will be bringing these components in as the preview but until then it will remain empty.

Please use a phone outline similar to Lucid chart. (Feint grey)

**Comment by ivanromakh** [comment]
@scholar6admin I will check this library for preview
https://github.com/kimolalekan/react-device-frame#readme

**Comment by ivanromakh** [comment]
https://github.com/Hermanya/react-device-frames

**Comment by ivanromakh** [comment]
Made for Iphone5s. The pre-login page for now which don`t need authorization.
![image](https://user-images.githubusercontent.com/18567511/74253915-64810980-4cf8-11ea-8b9d-6a0b2088af9c.png)

**Comment by ivanromakh** [comment]
![image](https://user-images.githubusercontent.com/18567511/74440631-ff075700-4e76-11ea-8d89-ae5950721f86.png)
