### ISSUE TITLE
Update bricks on brillder.com to be last 8 published.

### ISSUE THREAD

**Issue by scholar6admin** [Scholar-6/brillder#3500]

**Comment by ivanromakh** [comment]
@scholar6admin why is it assigned to Sasha?

**Comment by ivanromakh** [comment]
@scholar6admin we don`t have publish date. just get first 8 in the list. they should be the most recent updated.

**Comment by scholar6admin** [comment]
Ok sounds good. The reason I assigned to @SashaScholar6 is because I wanted him to sign off on it and make sure there was not another option he had thought of.
