### ISSUE TITLE
Fix Short Answer in phone

### ISSUE THREAD

**Issue by SashaScholar6** [Scholar-6/brillder#3501]
- [ ] It seems very large on iphone 11 on browser stack

https://user-images.githubusercontent.com/58778078/122194429-58c5ca00-ce8d-11eb-84d9-7cd293037200.mp4

<img width="273" alt="Screenshot 2021-06-15 at 12 32 09" src="https://user-images.githubusercontent.com/59654112/122045562-d1694f80-cdd5-11eb-9771-be3039858a25.png">

- [x] placeholder should be a readable size - as large as possible

**Comment by ivanromakh** [comment]
![image](https://user-images.githubusercontent.com/18567511/122058182-097f8b00-cdf4-11eb-94a9-71bb182ff19c.png)

**Comment by ivanromakh** [comment]
@scholar6admin don`t know how to fix it. I make font size bigger it shouldn`t zoom but it is still zooming probably related to quill.
