### ISSUE TITLE
No text in plan tab

### ISSUE THREAD

**Issue by scholar6admin** [Scholar-6/brillder#3502]
![image](https://user-images.githubusercontent.com/58778078/122099362-d47e3300-ce09-11eb-8182-cb7acaab063f.png)

Use student@scholar6.org
I tested multiple times and went very slowly through the plan pages to check it wasnt a speed thing.

**Comment by scholar6admin** [comment]
@ivanromakh Still seems to be an issue just for Prep

**Comment by ivanromakh** [comment]
its just quill is slow you need to wait when you creating brick.

**Comment by ivanromakh** [comment]
also quill sometimes throws errors and data could not be saved.

**Comment by ivanromakh** [comment]
you need to see preview if it is working or not.
