### ISSUE TITLE
Sound on vertical/horizontal shuffle is wonky

### ISSUE THREAD

**Issue by scholar6admin** [Scholar-6/brillder#3504]
- [x] Not recording?
This might just be my chrome.

- [x] Check sound component
- [x] And horizontal shuffle
- [x] And vertical shuffle
- [x] Choose one
- [x] Choose several
- [x] Also add to pair match

**Comment by ivanromakh** [comment]
there is some bug that you need to delete first before recording. but recording is working for me.
