### ISSUE TITLE
colour on synthesis doesn't stick

### ISSUE THREAD

**Issue by scholar6admin** [Scholar-6/brillder#3522]
Apply colour to text synthesis
Click to question
click back to synthesis and the colour should still be applied.

Also check Tessa's ticket https://scholar6.zendesk.com/agent/tickets/417 

- [x] For some reason the italicised word in the title here (Titanic) keeps reverting to being navy, even though I've turned it red multiple times. Is this because it's italicised?

------------------
Submitted from: https://app.brillder.com/build/brick/701/synthesis

**Comment by william-gooch** [comment]
Need more information on this

**Comment by william-gooch** [comment]
@scholar6admin can't seem to reproduce the issue on synthesis.
The title should not be able to be coloured, how is Tessa doing that? Also what brick is this, I can't access Zendesk?

**Comment by SashaScholar6** [comment]
701
