### ISSUE TITLE
Time out not progressing at end of review

### ISSUE THREAD

**Issue by scholar6admin** [Scholar-6/brillder#3529]
- [x] The review stage is not progressing at end of time out
https://dev-app.brillder.com/play/brick/683/review
![image](https://user-images.githubusercontent.com/58778078/123082591-16fdcc00-d417-11eb-88fb-0a87505d2418.png)

Go to play
wait for investigation timer to time out
Now leave the brick and come back to play again
The investigation skips because the timer is maxed out

if refreshing the timing should be cached
If you click to play from the cover then it should clear any timing cache and start a new play attempt.

**Comment by ivanromakh** [comment]
@scholar6admin play is cashed. if you use the same brick it will get brick from local storage probably. It will restore attempt from cash.

**Comment by ivanromakh** [comment]
@scholar6admin it will move you to provisonal score if time for investigation run out.

**Comment by scholar6admin** [comment]
@ivanromakh right but if you finish the brick all the way to the end then the timer should reset. Currently if you go back to the brick after finishing it and the timer had run out then it will still skip the investigation.
