### ISSUE TITLE
Change text in wiris to blue #01C58 and classic serif font default

### ISSUE THREAD

**Issue by SashaScholar6** [Scholar-6/brillder#353]
- [ ] default font in work area and phone preview

- [ ] matching dark blue colour

<img width="831" alt="Screenshot 2020-10-07 at 16 20 21" src="https://user-images.githubusercontent.com/59654112/95343611-09b8a580-08b9-11eb-8229-dfe8b29ea25b.png">

**Comment by ivanromakh** [comment]
@SashaScholar6  This is imposible. We need to change library for this.

**Comment by ivanromakh** [comment]
@SashaScholar6  I can`t change image
![image](https://user-images.githubusercontent.com/18567511/82995039-be89ae80-a00b-11ea-8f31-ea7be619451c.png)

**Comment by ivanromakh** [comment]
its already was blue in phone preview before
