### ISSUE TITLE
Just get titles instead of 3mb all public bricks

### ISSUE THREAD

**Issue by scholar6admin** [Scholar-6/brillder#3534]
To decrease data transported for initial queries. 

GET /bricks/byStatus/{status}

Restrict to the following:
Image, title, level, author,

Assigned Status
Whether completed or not (see #3332)

Dont send questions, synthesis etc.

**Comment by william-gooch** [comment]
Realizing now that (without the sitemap) this task is actually kind of useless, since there's no way to get to the catalogue page from the index page if you're not logged in!
I'm still doing it but we might want to consider adding in a button like "explore our catalogue" from the login page.
