### ISSUE TITLE
Mobile Student Onboarding Intro.js

### ISSUE THREAD

**Issue by SashaScholar6** [Scholar-6/brillder#3541]
- [x] hide zendesk and 'Terms' on signup (join the revolution) page

<img width="384" alt="Screenshot 2021-06-22 at 16 12 51" src="https://user-images.githubusercontent.com/59654112/122951125-f3824500-d374-11eb-88df-13454b36638a.png">

After select-subjects for Student, onboarding includes the following intro js:

- [x] As above for View & Play (wider so 'view & play' on one line)

- [x] Same idea for My Assignments icon, text is: Find and Play your assigned ‘bricks’ here

- [x] Around Zendesk Icon: 'If you spot anything that doesn't look right, or experience a technical issue, click here to create a help ticket'.

- [x] for last one, have 'Explore Brillder' button which takes user to view all home page

**Comment by ivanromakh** [comment]
@SashaScholar6 intro js isn`t working there. I can do something else.

**Comment by ivanromakh** [comment]
@SashaScholar6 it will be hard to do it is swiping.

**Comment by ivanromakh** [comment]
![image](https://user-images.githubusercontent.com/18567511/126465733-ea0e0202-1159-4b8b-8507-019d7cddc099.png)
