### ISSUE TITLE
Mobile View All new design flow

### ISSUE THREAD

**Issue by SashaScholar6** [Scholar-6/brillder#3544]
https://xd.adobe.com/view/a28eecdc-b8fe-4c23-bc93-209ee85f31f2-f7dd/

<img width="387" alt="Screenshot 2021-06-22 at 16 32 45" src="https://user-images.githubusercontent.com/59654112/122955814-5b865a80-d378-11eb-8404-5b52075134c2.png">

- [x] grey shape and text if no results

<img width="387" alt="Screenshot 2021-06-22 at 16 32 59" src="https://user-images.githubusercontent.com/59654112/122955847-650fc280-d378-11eb-9997-89617fdb7162.png">

- [x] clicking cover shows and hides expanded grey shape (text from Brief with ellipsis if overflowing)

- [x] hide 'Save Brick' option and heart until backend is ready

<img width="386" alt="Screenshot 2021-06-22 at 16 33 08" src="https://user-images.githubusercontent.com/59654112/122955880-6ccf6700-d378-11eb-9e43-f459559f0f34.png">

- [x] expanded view of subject when red chevron clicked.  Number next to level is number of bricks in that level for that subject (in this case English Levels I & II)

**Comment by ivanromakh** [comment]
@SashaScholar6 its not very visible in white images.
should I add some shadow?
![image](https://user-images.githubusercontent.com/18567511/123400163-1f3c3f80-d5ae-11eb-916e-9d9f83510951.png)

![image](https://user-images.githubusercontent.com/18567511/123400128-177c9b00-d5ae-11eb-9dbe-5c4989a9d56b.png)

**Comment by aromakh** [comment]
@SashaScholar6 this is Ivan. Need design for unauthorized user as well.
