### ISSUE TITLE
Loop on post /brick without subject

### ISSUE THREAD

**Issue by scholar6admin** [Scholar-6/brillder#3562]
The frontend is currently looping request to post /brick on the choose subject page when the subject has not yet been selected. (This is because the backend expects a subject)

We either need to accept post /brick with subject null, or we need to wait to post the brick and get a brick id until the subject has been selected.

**Comment by william-gooch** [comment]
@scholar6admin Not getting this issue. Was it fixed at some point?

**Comment by ivanromakh** [comment]
@william-gooch here is loop when there is error during creating brick.
![image](https://user-images.githubusercontent.com/18567511/123778991-5fffc580-d8da-11eb-9d08-8b69f938a555.png)

**Comment by william-gooch** [comment]
@ivanromakh the surrounding if statement checks if the subject has been selected yet. So that shouldn't execute if there's no subject selected.
@scholar6admin I still can't reproduce this?

**Comment by ivanromakh** [comment]
@william-gooch you are right it happen after you selected subject.
Loop was happening in proposal /brick-title page not in /subject. after subject was selected.

**Comment by william-gooch** [comment]
@ivanromakh still not getting a loop on /brick-title

**Comment by ivanromakh** [comment]
@william-gooch yep you can`t reproduce it now. as it was fixed. but loop can happen if backend will throw 400 error again in the future.

**Comment by ivanromakh** [comment]
@william-gooch it is better to move this out from render function as it could cause infinity loops.

**Comment by william-gooch** [comment]
@ivanromakh got it. I'm not sure where it should be moved out to, though? I'm not super great with class components.

**Comment by ivanromakh** [comment]
this is not urgent now we can fix it later when we will be refactoring some proposal.
