### ISSUE TITLE
Brick 491 Q3 has undefined prefilled

### ISSUE THREAD

**Issue by scholar6admin** [Scholar-6/brillder#3569]
https://dev-app.brillder.com/play/brick/491/cover

**Comment by william-gooch** [comment]
@scholar6admin not happening for me. Is it still happening for you?

**Comment by ivanromakh** [comment]
I was happening when brick was failed to save.

**Comment by ivanromakh** [comment]
@william-gooch  there is actually bug with selection subjects in proposal. you can fix that. it is when you have 2 or more subjects or when you have 1 subject don`t remember.
