### ISSUE TITLE
Mark bricks with an attempt in the catalogue

### ISSUE THREAD

**Issue by scholar6admin** [Scholar-6/brillder#3584]
- [x] Use this checkmark (feather check-circle) but in white with background circle to be colour of subject
![image](https://user-images.githubusercontent.com/58778078/127366081-f3b2bac0-7449-4d24-a766-973379835901.png)

- [x] Go direct to attempts page
![image](https://user-images.githubusercontent.com/58778078/127366244-7b7e505a-ae0b-4561-8665-b473240832e6.png)

- [x] add book icon to bricks
- [x] Clicking bricks that have been played should go to the book of attempts.
<img width="471" alt="Screenshot 2021-06-09 at 16 37 49" src="https://user-images.githubusercontent.com/59654112/121385504-13f7db80-c941-11eb-8fd6-84e3bd2db64e.png">

**Comment by ivanromakh** [comment]
@scholar6admin from where I should go to attempts page?
![image](https://user-images.githubusercontent.com/18567511/127462314-909283f3-5764-4f86-a6f5-14e59b099a75.png)
