### ISSUE TITLE
'General & Topical' should only be selected by default if user does not select any other subjects at signup

### ISSUE THREAD

**Issue by scholar6admin** [Scholar-6/brillder#3585]

**Comment by ivanromakh** [comment]
@scholar6admin when user is created he was granted with general and topical subject after he register before terms page. 

I am not preselecting it it is already there from the start.
![image](https://user-images.githubusercontent.com/18567511/124291747-8ed99e00-db5d-11eb-88ca-8731f70992d5.png)
