### ISSUE TITLE
Word Highlighting Fixes

### ISSUE THREAD

**Issue by scholar6admin** [Scholar-6/brillder#3591]
- [x] Word highlight in book preview has no spaces when clicking on one of the eyes
![image](https://user-images.githubusercontent.com/58778078/124267426-23c5a280-db30-11eb-827b-5fec48f21f3f.png)

- [x] punctuation is missing on phone preview in build
https://scholar6.zendesk.com/agent/tickets/348
![image](https://user-images.githubusercontent.com/58778078/124280114-33e57e00-db40-11eb-8aca-141ca0cbe01f.png)
![image](https://user-images.githubusercontent.com/58778078/124280150-3ea01300-db40-11eb-87cb-24ad8bd3627b.png)

- [x] Play - full stops and commas are breaking to new lines
![image](https://user-images.githubusercontent.com/58778078/124280408-90489d80-db40-11eb-8ab4-a4fb705a69dc.png)
https://app.brillder.com/play/brick/683/live

<img width="389" alt="Screenshot 2021-07-14 at 13 44 52" src="https://user-images.githubusercontent.com/59654112/125624345-dbc5f9b9-d608-4ff1-893f-a3c4ff3ab978.png">

- [x] spaces between words don't appear in mobile book (check linehighlight also)

**Comment by ivanromakh** [comment]
@scholar6admin I can only apply general rule by css. to make break line of not. this can`t be fixed with css.

Should I include commas in green area to prevent this? Currently it is divided and coma is not part of the word. so if there is no space for sign it will move to next line.
