### ISSUE TITLE
scroll bar on question text in play

### ISSUE THREAD

**Issue by scholar6admin** [Scholar-6/brillder#3594]
Very. hard to play long bricks (like Lear 523) without a sense of how long prep and synthesis is

<img width="1364" alt="Screenshot 2021-07-14 at 13 52 59" src="https://user-images.githubusercontent.com/59654112/125625305-fee250cd-8cc5-4fa4-a01f-de80dceedef1.png">

- [x] show during investigation, synthesis and review

- [x] update style in prep
- [x] is it in brief?

- [x] block horizontal scrollbar from appearing

- [x] remove 'Scroll down' text in bottom bar

- [x] on mobile, thin transparent scroll bar on right hand side

<img width="1607" alt="Screenshot 2021-07-20 at 14 06 26" src="https://user-images.githubusercontent.com/59654112/126329283-9f18b9a2-3055-4056-b82d-c43470517f93.png">

- [x] fix width

- [x] remove /fixscrollbars in brief

**Comment by ivanromakh** [comment]
@SashaScholar6 I can`t do it in prep as prep has round corner. scroll can only be used in rectangle area.
