### ISSUE TITLE
Personal published bricks should not get an error when loading the cover

### ISSUE THREAD

**Issue by scholar6admin** [Scholar-6/brillder#3597]
![image](https://user-images.githubusercontent.com/58778078/124287119-8e360d00-db47-11eb-987f-1004fbb94b6e.png)

https://app.brillder.com/play/brick/215/cover

This is because the lambda og server side rendering cannot pull the brick from the API. 

We probably need to change the route of published personal bricks so that they bypass the lambda script but are still accessible. But if we do that then make sure to fix the sharing button so that personal bricks can still be shared properly.

**Comment by ivanromakh** [comment]
@scholar6admin I need url.

**Comment by ivanromakh** [comment]
user have no access to some request in cover page backend task. @aromakh this should work for unauthorized users https://dev-api.brillder.com/brick/public/215
