### ISSUE TITLE
Black screen of death on mobile for submitted to publisher notification

### ISSUE THREAD

**Issue by SashaScholar6** [Scholar-6/brillder#3608]
- [x] As a publisher, when I receive a notification that a brick is 'Submitted for Publication' and I click on it, then it should not go to a black screen of death. The notification should show bigger boat popup
<img width="375" alt="Screenshot 2021-07-08 at 10 32 39" src="https://user-images.githubusercontent.com/59654112/124899499-19942000-dfd8-11eb-90da-b21797149816.png">

<img width="385" alt="Screenshot 2021-07-06 at 13 17 06" src="https://user-images.githubusercontent.com/59654112/124598407-78348f00-de5c-11eb-99a9-5f4633dd51b6.png">

- [x] fix styles and height
- [x] expand and swipe interactions
- [x] animate on clear all
- [x] go to brick cover for published brick notification
- [x] bigger boat popup for all build notifications (invited to edit, submitted for publication)

- [x] published a brick notification should take me to brick cover page

<img width="379" alt="Screenshot 2021-07-08 at 10 42 43" src="https://user-images.githubusercontent.com/59654112/124901141-a55a7c00-dfd9-11eb-8077-6fdd03fb03de.png">

- [x] brick assigned to me should not have ugly popup notification (remove and instead only show in notification panel)
- [x] assigned notification should take me to brick cover page

- [x] remove rounding from top left corner

**Comment by ivanromakh** [comment]
@SashaScholar6 i don`t receive submitted for publication notification.

**Comment by ivanromakh** [comment]
@SashaScholar6 I recive only publish notifications and for some reason there are two for each brick.
![image](https://user-images.githubusercontent.com/18567511/124909943-b1ebce00-dff3-11eb-837c-f3e2c4a844a6.png)

**Comment by ivanromakh** [comment]
From the moment I created brick untill publish I get only 2 publish notifications.
