### ISSUE TITLE
Library Fixes

### ISSUE THREAD

**Issue by SashaScholar6** [Scholar-6/brillder#3610]
<img width="458" alt="Screenshot 2021-07-06 at 18 02 09" src="https://user-images.githubusercontent.com/59654112/124639623-49caaa00-de84-11eb-83a4-cd9f736c7138.png">

- [x] make books wider so more space when initials added
- [x] initials should only show on adapted bricks
- [x] assigned but incomplete bricks should stay as before (grey text, no padlock and colour or 0%)

- [x] do the same as above for mobile library

<img width="355" alt="Screenshot 2021-07-08 at 10 24 35" src="https://user-images.githubusercontent.com/59654112/124898272-f026c480-dfd6-11eb-8b71-d9d8ddbcc384.png">

- [x] fix first cut off of tooltip
- [x] order in zommed out library should be same as subject shelf (latest brick shows first)

<img width="377" alt="Screenshot 2021-07-08 at 10 29 42" src="https://user-images.githubusercontent.com/59654112/124898865-7ba05580-dfd7-11eb-8092-e5b2166d21d9.png">

- [x] book title should be capitals in mobile like in desktop

<img width="310" alt="Screenshot 2021-07-09 at 14 22 49" src="https://user-images.githubusercontent.com/59654112/125084268-3c4e3380-e0c1-11eb-80e2-25b8081962fd.png">

- [x] should only have to click once (not twice) to see book contents
- [x] replace search icon with book icon which takes me to my library

**Comment by ivanromakh** [comment]
@SashaScholar6 seems like this is not working. should I hide it?
![image](https://user-images.githubusercontent.com/18567511/125046885-174cc700-e0a7-11eb-8277-201f164f92b2.png)

**Comment by ivanromakh** [comment]
@william-gooch check if they are sorted by attempt date in backend side or add attempt date as I don`t have any date related to it.
![image](https://user-images.githubusercontent.com/18567511/125049705-ea4de380-e0a9-11eb-80dd-1a0562177233.png)

**Comment by william-gooch** [comment]
@ivanromakh should this be sorted from earliest to latest or the other way around?

**Comment by ivanromakh** [comment]
@SashaScholar6 you need to click only once after all data is loaded. time of loading depends on server.
