### ISSUE TITLE
Blockquotes and font sizing in mobile

### ISSUE THREAD

**Issue by SashaScholar6** [Scholar-6/brillder#3634]
<img width="533" alt="Screenshot 2021-07-09 at 14 01 47" src="https://user-images.githubusercontent.com/59654112/125081706-360a8800-e0be-11eb-94de-7dc894284562.png">

<img width="398" alt="Screenshot 2021-07-09 at 14 02 25" src="https://user-images.githubusercontent.com/59654112/125081800-533f5680-e0be-11eb-9376-b09f2e1909fe.png">

- [x] should be 4.5vw in Brief/Prep (smaller) and investigation (bigger)

- [x] Investigation good, but Brief, Prep and Synthesis still too big (Maybe just my phone?)

- [x] Book font still too big, should be same as investigation

**Comment by ivanromakh** [comment]
synthesis don`t have other font-size except 5vw.
![image](https://user-images.githubusercontent.com/18567511/125091613-3e23f100-e0d9-11eb-987b-d89ec2da51f3.png)
same for brief.
![image](https://user-images.githubusercontent.com/18567511/125091739-5a279280-e0d9-11eb-8c82-3ae2e813198a.png)

only investigation could have other font size which is 1rem which default material and can`t be removed.
![image](https://user-images.githubusercontent.com/18567511/125092057-9bb83d80-e0d9-11eb-9d76-e44e4a9dc15c.png)

**Comment by ivanromakh** [comment]
@SashaScholar6 if font is really wrong try zooming. if font gets bigger during zoom it is not 5vw but 1rem. and we will need to remove material somehow troblesome.

**Comment by ivanromakh** [comment]
@SashaScholar6 font in book is only 5vw there is no other font size.
