### ISSUE TITLE
If I replace an uploaded image with a different one, it duplicates and jumps to the top of the Question text area

### ISSUE THREAD

**Issue by SashaScholar6** [Scholar-6/brillder#3643]
<img width="1085" alt="Screenshot 2021-07-12 at 15 13 28" src="https://user-images.githubusercontent.com/59654112/125302452-dd3c2900-e323-11eb-9041-47dce60be17d.png">

**Comment by ivanromakh** [comment]
@SashaScholar6 this is related to quill.
