### ISSUE TITLE
For. partially correct answers, add yellow crosses in score screens and review

### ISSUE THREAD

**Issue by SashaScholar6** [Scholar-6/brillder#3656]
<img width="1158" alt="Screenshot 2021-07-14 at 13 15 08" src="https://user-images.githubusercontent.com/59654112/125621882-82d2bcd7-069a-4ffe-8c55-15d15fcaf7f1.png">
<img width="1208" alt="Screenshot 2021-07-14 at 13 19 21" src="https://user-images.githubusercontent.com/59654112/125621891-2b5179c1-1b88-4502-9d45-53bc8f9096b7.png">

- [x] for partially correct answers, yellow crosses on provisional and final score pages (desktop and. mobile)

<img width="1074" alt="Screenshot 2021-07-14 at 13 26 21" src="https://user-images.githubusercontent.com/59654112/125621894-c54dae86-c84e-4b2e-962b-32742b139f55.png">

- [x] yellow circle with cross during review
- [x] for incorrect answers, change text to 'Incorrect - try again!

<img width="317" alt="Screenshot 2021-07-14 at 13 27 46" src="https://user-images.githubusercontent.com/59654112/125622762-4a318730-1dc2-4808-b5ce-bda724288ed2.png">

- [x] also yellow number circle in mobile

<img width="369" alt="Screenshot 2021-07-14 at 13 35 41" src="https://user-images.githubusercontent.com/59654112/125622968-4fed59ce-204f-4a01-9864-442b5240a530.png">

- [x] more padding after answer and svgs slightly thicker

<img width="389" alt="Screenshot 2021-07-15 at 10 32 06" src="https://user-images.githubusercontent.com/59654112/125767006-14ef0f85-2fb8-4488-afd4-683f50b5ed98.png">

<img width="386" alt="Screenshot 2021-07-15 at 10 32 24" src="https://user-images.githubusercontent.com/59654112/125767012-fe700a4c-4ddb-42f2-92ee-95604f7b5b39.png">

- [x] show yellow crosses and marks on mobile

<img width="1439" alt="Screenshot 2021-07-15 at 10 40 21" src="https://user-images.githubusercontent.com/59654112/125767091-f8b7e416-b88d-415a-942c-06eeb1a01f7e.png">

- [x] update desktop score pages to show same info as mobile

<img width="1439" alt="Screenshot 2021-07-15 at 10 40 21" src="https://user-images.githubusercontent.com/59654112/125767239-9489aa9a-86d3-4d65-a2aa-46bea5788bd6.png">
<img width="1439" alt="Screenshot 2021-07-15 at 10 40 55" src="https://user-images.githubusercontent.com/59654112/125767256-b2b31b8d-66ad-4d1c-b60d-9c57071e94df.png">

- [x] Correct answers showing as 'Not quite...' instead of 'Correct!'

- [x] PROVISIONAL SCORE

You can improve this when reviewing your answers (desktop and mobile) - exception: don't show if user has scored 100% in investigation
FINAL SCORE
This is an average of your provisional score and your review score (desktop only) (edited)

**Comment by ivanromakh** [comment]
@SashaScholar6 what is  partially correct answers?

**Comment by SashaScholar6** [comment]
eg. 3 marks out of, 2 marks out 6etc.
<img width="423" alt="Screenshot 2021-07-14 at 14 14 17" src="https://user-images.githubusercontent.com/59654112/125628158-fd9d6b68-bf45-44f2-8491-5b3b9234d85e.png">
