### ISSUE TITLE
Categorise: if left unanswered in investigation, I cannot answer it in review

### ISSUE THREAD

**Issue by SashaScholar6** [Scholar-6/brillder#3663]
<img width="1020" alt="Screenshot 2021-07-15 at 14 56 59" src="https://user-images.githubusercontent.com/59654112/125800430-29b950b2-a252-4ef7-a8d5-53d810549413.png">

- [ ] caused by switching tabs?

**Comment by ivanromakh** [comment]
can`t reproduce it.
