### ISSUE TITLE
Desktop. countdown

### ISSUE THREAD

**Issue by SashaScholar6** [Scholar-6/brillder#3665]
<img width="1440" alt="Screenshot 2021-07-16 at 11 02 30" src="https://user-images.githubusercontent.com/59654112/125931342-10131fe6-8f2f-451d-bc5f-05aa544eaa90.png">

- [x] BEFORE INVESTIGATIOM

You have 8 minutes to have a first crack at the questions.

Don’t worry if you are unable to answer everything in time - you can 
have another go after reading the Synthesis of this brick.

<img width="1440" alt="Screenshot 2021-07-16 at 11 04 59" src="https://user-images.githubusercontent.com/59654112/125931352-a5783cad-5d5a-4846-b30b-2f6579ea5883.png">

- [x] BEFORE REVIEW:
You have 3 minutes to review your answers and improve your score.

Your final score will be an average of your provisional and review scores.  You can replay this brick as many times as you like after this.

- [x] Animate. hourglass

**Comment by ivanromakh** [comment]
@SashaScholar6 this is this page before investigation. I should replace it?
![image](https://user-images.githubusercontent.com/18567511/125935921-643d3e01-4008-45f0-9769-44538965c283.png)

**Comment by ivanromakh** [comment]
I need link for glasses
