### ISSUE TITLE
Pair Match right hand side not showing in play preview

### ISSUE THREAD

**Issue by SashaScholar6** [Scholar-6/brillder#3682]
<img width="1282" alt="Screenshot 2021-07-20 at 12 16 52" src="https://user-images.githubusercontent.com/59654112/126315242-b6c48069-c807-4011-806b-9f9829f59a57.png">

- [x] pair match fix

- [x] Also categorise in review (brick 581): https://scholar6.zendesk.com/agent/tickets/425

<img width="1412" alt="Screenshot 2021-07-20 at 18 51 32" src="https://user-images.githubusercontent.com/59654112/126371922-8fb48076-529d-44cd-b239-fbce976afb9a.png">

<img width="1046" alt="Screenshot 2021-07-21 at 10 43 16" src="https://user-images.githubusercontent.com/59654112/126468865-37ea711b-9e2e-4f12-be87-5c46d9a97289.png">

- [x] pair match left column should be centre aligned

<img width="978" alt="Screenshot 2021-07-21 at 10 43 39" src="https://user-images.githubusercontent.com/59654112/126469016-3df9bba0-edee-46bc-87e4-e15396dbd148.png">

- [x] centre align categorise answers

**Comment by ivanromakh** [comment]
@SashaScholar6 I need brick id.
![image](https://user-images.githubusercontent.com/18567511/126320284-cadf246d-f4ee-46ac-a769-e8456d9984f5.png)

**Comment by ivanromakh** [comment]
@SashaScholar6 I don`t have this problem. which browser is it?
![image](https://user-images.githubusercontent.com/18567511/126320574-e944682f-8dba-4952-8f4f-68b2b723958c.png)

**Comment by ivanromakh** [comment]
@SashaScholar6 pair match should be center aligned.
