### ISSUE TITLE
Phone book contents page and updates

### ISSUE THREAD

**Issue by SashaScholar6** [Scholar-6/brillder#3692]
<img width="390" alt="Screenshot 2021-07-21 at 14 12 11" src="https://user-images.githubusercontent.com/59654112/126494327-20ee45bf-8c0a-49bb-af5d-48dd427b920b.png">

- [x] contents white circle and icon always visible when sidescrolling (numbers go behind)
- [x] add brief icon
- [x] show first few words of brief, prep and questions
- [x] clicking on any row takes you to that page in book

<img width="292" alt="Screenshot 2021-07-22 at 11 04 01" src="https://user-images.githubusercontent.com/59654112/126622486-7166d1fc-058c-4313-be9b-009e991e3cf6.png">

- [x] simplify showing investigation and review

**Comment by ivanromakh** [comment]
@SashaScholar6 no bottom menu or zendesk?

**Comment by SashaScholar6** [comment]
@ivanromakh we can keep bottom menu

**Comment by ivanromakh** [comment]
@SashaScholar6 why we show it in brick title?
![image](https://user-images.githubusercontent.com/18567511/126640943-71cbe499-6e39-4f93-a599-a59143d9acb5.png)

**Comment by SashaScholar6** [comment]
<img width="372" alt="Screenshot 2021-07-22 at 14 20 33" src="https://user-images.githubusercontent.com/59654112/126645693-2e6fa9ed-ad12-4570-8af3-5507e40174cd.png">

yes it replaces current question pages (hence number 1 top left)

**Comment by SashaScholar6** [comment]
like clicking on eyes currently
