### ISSUE TITLE
Desktop book new design

### ISSUE THREAD

**Issue by SashaScholar6** [Scholar-6/brillder#3693]
<img width="1440" alt="Screenshot 2021-07-21 at 15 19 59" src="https://user-images.githubusercontent.com/59654112/126504452-eb90685e-5364-4807-ac5a-b48572a7164f.png">

- [x] contents sidebar - hover selector and click
- [x] contents and brief icons in header
- [x] add ticks and crosses
- [x] chevrons for question overflow

<img width="1440" alt="Screenshot 2021-07-26 at 10 23 51" src="https://user-images.githubusercontent.com/59654112/126966118-f2b989f8-9bd1-4646-b22e-12bd825c1725.png">

- [x] add 'Contents' fixed to top of sidebar like original design

- [x] add fixed line at bottom above help (like for all subjects sidebar)

- [x] text from brick should be bigger in sidebar (2vh rather than 1.5)
- [x] 'Brief' and 'Prep' should be 3vh not 2.5

<img width="1440" alt="Screenshot 2021-07-26 at 10 27 27" src="https://user-images.githubusercontent.com/59654112/126966591-51b266f1-55d8-40c9-b88f-4f987755f48a.png">

- [x] add grey area on right for brief, prep and synthesis

- [x] when a something is selected in sidebar, it should turn white with dark blue text

- [x] restore book cover
- [x] restore inner page with just play again on left and attempts on right. clicking attempt goes to current view with contents sidebar on left

**Comment by ivanromakh** [comment]
@SashaScholar6 there is attempts page before this page. need that one too.

**Comment by ivanromakh** [comment]
![image](https://user-images.githubusercontent.com/18567511/126669284-b85f6f0c-9644-4049-bbbd-c3af0ed97cf2.png)

**Comment by ivanromakh** [comment]
@SashaScholar6 what about beta text or zendesk button?

**Comment by ivanromakh** [comment]
@SashaScholar6 what is this big text?
![image](https://user-images.githubusercontent.com/18567511/126782708-20b4e7f1-99fa-46d3-9418-e11a8cb6c85f.png)

**Comment by ivanromakh** [comment]
@SashaScholar6 what is the point of this icon if there is sidebar? there is no content page.
![image](https://user-images.githubusercontent.com/18567511/126784497-1156a95c-8568-43f8-b273-616797f47733.png)

**Comment by ivanromakh** [comment]
Latest book.
![image](https://user-images.githubusercontent.com/18567511/126804746-25661bd0-6180-4f4f-9126-5aaa8f607530.png)
