### ISSUE TITLE
Reminder button and archiving

### ISSUE THREAD

**Issue by SashaScholar6** [Scholar-6/brillder#3695]
<img width="1109" alt="Screenshot 2021-07-22 at 10 00 29" src="https://user-images.githubusercontent.com/59654112/126614249-e583d0ff-d9b1-402d-bc19-526a3d8d65a8.png">

- [x] archive button should be grey by default and only go green if deadline has passed or all students have completed brick
- [x] red reminder button should only send reminder and NOT archive assignment
- [x] intro.js when brick has been archived for the first time: 'Find your archived assignments here'.

<img width="1086" alt="Screenshot 2021-07-22 at 09 57 25" src="https://user-images.githubusercontent.com/59654112/126613806-b5695207-4b82-41c1-939d-6b1024852bda.png">

- [x] In archived, only show classes with archived bricks
- [x] add Unarchive button in circle with feather arrow-up-circle icon
- [x] Andriy create request for unarchive

**Comment by ivanromakh** [comment]
@aromakh I need unarchive assignment request. analog to POST: /brick/assignment/{assignmentId}/archive

**Comment by aromakh** [comment]
@ivanromakh  api is done
