### ISSUE TITLE
Ipad 11 IOS 14 fixes

### ISSUE THREAD

**Issue by scholar6admin** [Scholar-6/brillder#3700]
PLAY
- [x] Initial timer screen text out of alignment
![image](https://user-images.githubusercontent.com/58778078/126805847-2ed46062-8399-4d82-ac92-b68e1e5ec82c.png)

- [ ] Numbers are too high and there is a weird white border at the bottom
![image](https://user-images.githubusercontent.com/58778078/126807936-bad86a13-2469-4d62-a3b0-3953f771181a.png)

- [x] Large icons on pair match
![image](https://user-images.githubusercontent.com/58778078/126806459-1343b000-a3cb-4a8c-a888-d81280d8ec07.png)

- [x] Images in questions in investigation are all small and left aligned
![image](https://user-images.githubusercontent.com/58778078/126806622-617ec3eb-3022-46c4-a04c-8ae31038091f.png)

- [x] short answer has empty grey square on right

- [x] Investigation score looks weird (see chemistry brick as unauthenticated user)
![image](https://user-images.githubusercontent.com/58778078/126805241-e4d616b9-8193-437b-be5e-6f5a6b427f23.png)

- [x] review looks weird with big red cross at top
![image](https://user-images.githubusercontent.com/58778078/126805364-d18dcbca-8a13-4a04-96f4-dd75d8523ed3.png)

- [x] Cant seem to see keyboard on screen for setting password
![image](https://user-images.githubusercontent.com/58778078/126806965-71916a4c-431c-49c0-82f4-1bbe131c744d.png)

- [x] Terms and conditions has white background
![image](https://user-images.githubusercontent.com/58778078/126807020-e9dedcc9-6dcf-4d27-8f2d-2deae438fcf8.png)

- [x] Choose user screen doesnt look right
![image](https://user-images.githubusercontent.com/58778078/126807274-c9b44c38-5655-43cd-a7b2-4359af7a3bb5.png)

- [x] My assignments icon missing from homepage for student (needs to display even if no assignments yet)
![image](https://user-images.githubusercontent.com/58778078/126807378-dcd78df2-2fc5-459c-9141-d2b035bd7430.png)

- [x] My library doesnt seem to display (I had definitely played bricks)
![image](https://user-images.githubusercontent.com/58778078/126807660-f111224e-73f3-4679-9ce3-288904e6813e.png)

- [x] Build is not clickable which is fine on mobile but there is no popup. Popup should say "This feature is not available on this device, try a desktop browser."

**Comment by ivanromakh** [comment]
@SashaScholar6 ipads not working for me in browser stack.
