### ISSUE TITLE
Invite existing user to class doesn't show popup

### ISSUE THREAD

**Issue by scholar6admin** [Scholar-6/brillder#3703]
As an existing student on Brillder
When I am added to a new class
And I get the notification email
And I click the link 
And I log in
Then I see the assignments page
But I do not see a pop up to accept the class notification.

When I click accept then I should see all the assignments immediately load.

**Comment by ivanromakh** [comment]
Added popup to accept invitation in that page.
![image](https://user-images.githubusercontent.com/18567511/127152489-668a2d40-e8c2-4402-b6e8-9e2f40a5a5c7.png)
