### ISSUE TITLE
No notification when publisher sends back to editor

### ISSUE THREAD

**Issue by scholar6admin** [Scholar-6/brillder#3704]
![image](https://user-images.githubusercontent.com/58778078/126824355-60883065-d7b7-43f7-aef9-747bece7242f.png)

**Comment by ivanromakh** [comment]
@aromakh there is something wrong with return to editor request. what is publisher? 
it is probably throwing error because there is no publisher in brick.
![image](https://user-images.githubusercontent.com/18567511/128318467-be906e67-ef47-40f3-b685-6e1bf90571a3.png)

**Comment by ivanromakh** [comment]
we don`t use publisher in brick anywhere this prop should be removed. brick.publisher.
![image](https://user-images.githubusercontent.com/18567511/128320969-08c105ce-b89e-4df0-b057-ebbfd394fe93.png)
