### ISSUE TITLE
Teacher commenting on books

### ISSUE THREAD

**Issue by SashaScholar6** [Scholar-6/brillder#3711]
- [x] annotation for students to themselves (feather pen icon)

<img width="470" alt="Screenshot 2021-07-27 at 10 26 52" src="https://user-images.githubusercontent.com/59654112/127130735-0fa94b26-2d0d-4da2-a3d5-b275f02402b9.png">

- [x] comments like in build between teacher and students
- [x] holistic comment from manage classes goes to Brief comment section (doesn't appear to work yet)

<img width="1080" alt="Screenshot 2021-07-28 at 10 44 48" src="https://user-images.githubusercontent.com/59654112/127301386-131f0f83-e5fe-40b8-9694-85be662bdba0.png">

<img width="433" alt="Screenshot 2021-08-25 at 16 53 41" src="https://user-images.githubusercontent.com/59654112/130813806-e978dbec-345e-478e-a31b-94175ddd9edd.png">

- [x] really cool, but no send/submit button?

<img width="86" alt="Screenshot 2021-08-31 at 15 47 53" src="https://user-images.githubusercontent.com/59654112/131514119-c8295a19-e0c7-40b3-96f1-7850885fbb10.png">

- [x] make full height, not circle and replace save icon with send icon
- [x] when clicked, popup should go away
<img width="440" alt="Screenshot 2021-08-31 at 15 48 02" src="https://user-images.githubusercontent.com/59654112/131514156-293b39c8-72b5-4f6f-9e56-e80e49577b2f.png">

- [x] show number of comments (yellow if my comment, red if from someone else) in circles on right

- [x] individual student view also

**Comment by ivanromakh** [comment]
@william-gooch there is error while trying to make comment.
![image](https://user-images.githubusercontent.com/18567511/131645894-9b2e5a01-da6e-4747-ab06-e1b7faffe7ea.png)

**Comment by ivanromakh** [comment]
@scholar6admin this is backend problem. teacher can`t updated attempt.
![image](https://user-images.githubusercontent.com/18567511/133602477-52c130e1-5ef5-4c30-8018-7719dbeefa62.png)
