### ISSUE TITLE
If student is deleted and then added again to a class then they cannot see the assignments.

### ISSUE THREAD

**Issue by scholar6admin** [Scholar-6/brillder#3715]
And there is a weird 0 after the classname
![image](https://user-images.githubusercontent.com/58778078/127288332-51097497-f952-4cb6-8509-8eabed4c0feb.png)

**Comment by ivanromakh** [comment]
@scholar6admin assignments are completed. you need to switch tab to completed one.

**Comment by ivanromakh** [comment]
@scholar6admin anyone with role admin can edit classes someone probably added that zero.
