### ISSUE TITLE
Iphone 8 Cover page issues

### ISSUE THREAD

**Issue by scholar6admin** [Scholar-6/brillder#3719]
- [x] "Sign in here >" on phone, tablet and desktop

![image](https://user-images.githubusercontent.com/58778078/127299149-f4b37b10-9152-4239-a334-bb062ce6f5f6.png)

- [x] Buttons on popup are too close together
- [x] Input text is slightly hidden?

![image](https://user-images.githubusercontent.com/58778078/127299704-ce555c8f-44ae-41f7-93fd-2537db69e9b8.png)

- [x] question mark is overlapping cover image.

**Comment by ivanromakh** [comment]
I didn`t detect overlap in cover image in Iphone8.
![image](https://user-images.githubusercontent.com/18567511/127341107-45580e3d-9f57-45d7-9eaa-f9c8cad51259.png)
