### ISSUE TITLE
Book fixes

### ISSUE THREAD

**Issue by SashaScholar6** [Scholar-6/brillder#3729]
- [ ] default view should be like investigation. with no selected answers (neither investigation nor review selected

<img width="1230" alt="Screenshot 2021-07-28 at 15 49 04" src="https://user-images.githubusercontent.com/59654112/127343920-73d1d0d3-4769-49f0-9d21-27bcd59ee881.png">

- [x] showing. as correct with two. wrong answers?

https://dev-app.brillder.com/post-play/brick/529/13

<img width="801" alt="Screenshot 2021-07-28 at 15 50 40" src="https://user-images.githubusercontent.com/59654112/127344039-f0c24655-b76c-4bf3-9c46-9258c0bd3310.png">

- [x] top of. book should show correct, incorrect. and not quite coloured circles with ticks/crosses and text
- [x] show. marks in top right of white area

**Comment by ivanromakh** [comment]
@SashaScholar6 what do you mean by this? it is unselected by default.
![image](https://user-images.githubusercontent.com/18567511/127448412-31cd1af1-e049-4667-91b5-c91cdd7b0ffa.png)
