### ISSUE TITLE
Should see lozenge with editor name after clicking to 'send invite'

### ISSUE THREAD

**Issue by scholar6admin** [Scholar-6/brillder#3730]
![image](https://user-images.githubusercontent.com/58778078/127361469-877cfcf5-7c9f-48e0-8749-c17ec7beb29d.png)

**Comment by ivanromakh** [comment]
@aromakh  this is backend problem. first time when I assign editor it return me empty list.
it should return error if it failed.
![image](https://user-images.githubusercontent.com/18567511/127469269-22049b13-5b1c-4048-ac4a-cdd7d08bc91f.png)
![image](https://user-images.githubusercontent.com/18567511/127469313-e7ce634b-87d8-4567-9435-78526e96ec08.png)

**Comment by aromakh** [comment]
@ivanromakh  for it works fine.
Please add more detalis for case when Editor is not returned.
Maybe there are some additional steps.
