### ISSUE TITLE
The same brick can be assigned twice to the same class

### ISSUE THREAD

**Issue by scholar6admin** [Scholar-6/brillder#3731]
- [x] on the class management page if you try to assign brick twice you should see the same popup as below "That Brick has already been assigned to this class."
![image](https://user-images.githubusercontent.com/58778078/131680433-82e72f77-cdd5-4d8a-8f43-4d1e63cec8d3.png)

- [x] If brick already an active assignment (i.e. not archived) then do not assign a second time. 

@ivanromakh 
- [x] If the user tries to assign it a second time show a popup that says "This Brick has already been assigned to that class."
 
- [x] If assignment has been archived then allow a second assignment

**Comment by ivanromakh** [comment]
@aromakh its hard for me if it is already archived it return me a list of alll bricks. better something else.
![image](https://user-images.githubusercontent.com/18567511/131817123-b23e3f3e-1bd1-40fb-a5d9-4b1e379e8cda.png)
