### ISSUE TITLE
Two play attempts 100% and 50% creates an oversized book in library

### ISSUE THREAD

**Issue by scholar6admin** [Scholar-6/brillder#3732]
![image](https://user-images.githubusercontent.com/58778078/127365123-8258e326-8446-40fa-a717-d74852f495d3.png)

**Comment by ivanromakh** [comment]
@scholar6admin this is something related scoring to that brick. Probably that brick is broken. Can`t play that brick. Max score is 2 and score is 6. its 300%.
I can only limit height.
![image](https://user-images.githubusercontent.com/18567511/127444267-d6747e61-a25c-46a3-a51e-ddfb2826377b.png)

**Comment by ivanromakh** [comment]
@scholar6admin this is backend issue. Score in book attempts is fine 2 of 2.

**Comment by ivanromakh** [comment]
@aromakh check /play/library request. max score or last attempt score is wrong it should not be more than max score.
![image](https://user-images.githubusercontent.com/18567511/127446129-9692256d-d494-4d21-a96f-e0ed79d3e104.png)
