### ISSUE TITLE
Class Invitation popup on assignments page

### ISSUE THREAD

**Issue by scholar6admin** [Scholar-6/brillder#3745]
As a student
When I receive an invitation to a class
And I click the link
Then I go to the assignments page
And I should see the class invitation popup

However at the moment I have to click the home button to trigger this popup

**Comment by ivanromakh** [comment]
I have no problem with it. I see popup after I clicked link.
![image](https://user-images.githubusercontent.com/18567511/128011245-43ed249a-5ae7-4f4c-ae19-2a3946ba2cd3.png)
