### ISSUE TITLE
Remove extra space before comma , and stop . in play word highlight questions

### ISSUE THREAD

**Issue by scholar6admin** [Scholar-6/brillder#3748]
<img width="951" alt="Screenshot 2021-08-04 at 18 32 44" src="https://user-images.githubusercontent.com/59654112/128219215-61fcf95d-ef6a-457e-8b84-74f7122b078e.png">

**Comment by ivanromakh** [comment]
@SashaScholar6  this is probably old component it will work only for new ones.
