### ISSUE TITLE
Search in Build Bricks

### ISSUE THREAD

**Issue by SashaScholar6** [Scholar-6/brillder#3756]
- [x] @ivanromakh  implement same search logic as for View All page. (delay before search and other things if any)
- [x] @ivanromakh highlight keywords.
- [x] @aromakh  search keywords, even if keyword is partially typed.
- [x] @aromakh  keywords are missing after search.
- [x] @aromakh index brickId  and make it searchable as well.

**Comment by ivanromakh** [comment]
@aromakh bricks don`t have keywords.
