### ISSUE TITLE
Fix: accents getting cut off from title (LES RÉFUGIÉS...)

### ISSUE THREAD

**Issue by SashaScholar6** [Scholar-6/brillder#376]
<img width="305" alt="Screenshot 2020-04-23 at 10 20 00" src="https://user-images.githubusercontent.com/59654112/80077500-df16a280-854d-11ea-9d8b-0d27366daa98.png">

**Comment by ivanromakh** [comment]
![image](https://user-images.githubusercontent.com/18567511/80379903-65f9b100-88a7-11ea-9504-1c04728dabe6.png)
