### ISSUE TITLE
short answer should limit to 3 words

### ISSUE THREAD

**Issue by SashaScholar6** [Scholar-6/brillder#3766]
<img width="849" alt="Screenshot 2021-08-03 at 11 56 12" src="https://user-images.githubusercontent.com/59654112/127996763-0fbc7ccd-017f-4289-8445-f753dc425651.png">

- [x] three word maximum
- [x] fix popup so not underlapping

**Comment by ivanromakh** [comment]
in looks good in mine.
![image](https://user-images.githubusercontent.com/18567511/128016798-908e72ca-c948-4018-819f-37772836376a.png)

**Comment by ivanromakh** [comment]
@william-gooch is there a way to limit quill by words?

**Comment by ivanromakh** [comment]
@SashaScholar6 I don`t know how to do this right now. this looks hard.

**Comment by SashaScholar6** [comment]
@ivanromakh ok. we'll see if @william-gooch can have a quick look
