### ISSUE TITLE
Sam Ticket #442: Sound not being validated in pair match

### ISSUE THREAD

**Issue by SashaScholar6** [Scholar-6/brillder#3769]
<img width="863" alt="Screenshot 2021-08-03 at 12 20 04" src="https://user-images.githubusercontent.com/59654112/128000108-31ae0dbb-c140-4b08-97a4-1f971a97587c.png">

Hi Sasha, Lindsay,

yesterday I wrote two pair match questions using sound files, but these caused errors when I tried to move on with the play button. Apologies if I've missed something, but this seems like it's not working.

Thanks,
Sam

------------------
Submitted from: https://app.brillder.com/build/brick/833/investigation/question-component/236957

**Comment by ivanromakh** [comment]
sound is playing everywhere in build for me.
