### ISSUE TITLE
Show 'created by 'Teacher name' in white area next to class name

### ISSUE THREAD

**Issue by SashaScholar6** [Scholar-6/brillder#3774]
<img width="1409" alt="Screenshot 2021-08-05 at 11 35 14" src="https://user-images.githubusercontent.com/59654112/128328208-d19477f2-102f-4df8-9c96-a1befcec2660.png">

- [x] @aromakh I need teacher for assignment. GET https://dev-api.brillder.com/bricks/assigned

- [x] hide for now

- [x] in white area, above assignments
- [ ] grey lozenge for teacher name
- [x] round brick cover in Safari

**Comment by aromakh** [comment]
@ivanromakh  teacher is added.

**Comment by ivanromakh** [comment]
@SashaScholar6 rounded in some safari. rounding isn`t working in many cases in safari.
![image](https://user-images.githubusercontent.com/18567511/131847987-b2032ae3-ad45-4e2d-8a7a-6d4218de83c8.png)
