### ISSUE TITLE
Placeholders and tooltips build

### ISSUE THREAD

**Issue by SashaScholar6** [Scholar-6/brillder#3788]
TOOLTIPS
- [x] plan tab: 'Plan'
- [x] '+'. tab: 'Add a new question panel'
- [x] synthesis tab: 'Synthesis'
- [x] styled in Brandon reg, light blue background, grey text

PLACEHOLDERS

<img width="474" alt="Screenshot 2021-08-11 at 20 54 51" src="https://user-images.githubusercontent.com/59654112/129086705-eabb86f9-930a-46b5-ad95-a4bbb60ded80.png">

- [x] 'Introduce your question'

<img width="779" alt="Screenshot 2021-08-09 at 12 09 11" src="https://user-images.githubusercontent.com/59654112/128690892-c3500697-0dcf-4f5c-a391-0f5ee18b860d.png">

SHORT ANSWER
- [x] 'Short Answer (max. 3 words)'

CHOOSE ONE AND SEVERAL

<img width="400" alt="Screenshot 2021-08-09 at 12 13 39" src="https://user-images.githubusercontent.com/59654112/128691389-d2bd092f-677d-4d8a-b8f7-727cb1f0e3a1.png">

- [x] Answer 1, Answer 2 etc. (like hints) - and remove ellipsis (and 'Enter')

VERTICAL SHUFFLE
<img width="1052" alt="Screenshot 2021-08-09 at 12 14 33" src="https://user-images.githubusercontent.com/59654112/128691493-0d657c34-cc4f-4be4-9baf-e12403937c7a.png">

- [x] Answer 1, Answer 2 etc. (like hints) - and remove ellipsis (and 'Enter')
- [x] in entry panel, in same grey as sound and image component, place a circle on left hand side with the number in it.  This should show in the work area after answer entered

HORIZONTAL SHUFFLE
- [x] Answer 1, Answer 2 etc. (like hints) - and remove ellipsis (and 'Enter')
- [ ] in entry panel, in same grey as sound and image component, place a circle on left hand side with the number in it.  This should show in the work area after answer entered

PAIR MATCH
<img width="542" alt="Screenshot 2021-08-09 at 13 07 50" src="https://user-images.githubusercontent.com/59654112/128697390-75bf90be-5ec0-445b-bef6-28917db5b2b2.png">

- [x] remove ellipsis from placeholder
- [x] each answer hints should be 'Option 1 Hint', etc. because hints show on left

**Comment by ivanromakh** [comment]
@SashaScholar6 can`t do this there is too much styles it just breaks.
![image](https://user-images.githubusercontent.com/18567511/128848177-972d8f5b-befe-4a2a-8e99-5f8397d09051.png)

**Comment by ivanromakh** [comment]
@SashaScholar6 there is no space for circles in horizontal shuffle
![image](https://user-images.githubusercontent.com/18567511/128879203-88a89316-e6d7-467a-a187-20f726710e49.png)
