### ISSUE TITLE
Ticket #412: Image sizing on zoom answers

### ISSUE THREAD

**Issue by SashaScholar6** [Scholar-6/brillder#3795]
The original image is large 
https://api.brillder.com/files/114ad559-8a9b-4967-853a-60d56c668a54.png

But the quill question input makes the image small? @william-gooch 

Toby Peres  Jun 20 11:26
Is there a way to make pictures in the question box bigger? Sometimes even the zoom in thing doesn't make it big enough

------------------
Submitted from: https://app.brillder.com/build/brick/551/investigation/question-component/229213

<img width="1151" alt="Screenshot 2021-08-09 at 12 24 16" src="https://user-images.githubusercontent.com/59654112/128692855-7deb93e3-7991-4723-b999-003cf6b9ba58.png">

**Comment by ivanromakh** [comment]
@SashaScholar6 zoom image could be small if resolution of that image is small. it depends on image size. if I make it bigger it will just blurs.

**Comment by ivanromakh** [comment]
@SashaScholar6 it depends on monitor resolution. if it is monitor with high resolution it could look smaller as resolution of image isn`t that big.

**Comment by SashaScholar6** [comment]
551 question 6 like in task

**Comment by ivanromakh** [comment]
I can`t zoom it in prep. Maybe William could make it zoom
