### ISSUE TITLE
When brick adapted, show it more clearly

### ISSUE THREAD

**Issue by SashaScholar6** [Scholar-6/brillder#3797]
- [x] show adapt icon in build back to work and play dashboard in subject circle
- [x] show adapted icon on brick cover page
- [x] write 'ADAPTED' in small text above title in brick cover page
- [x] in build, show icon next to brick title above tabs

**Comment by ivanromakh** [comment]
@SashaScholar6 I am not sure which one is adopted icon.

**Comment by ivanromakh** [comment]
@SashaScholar6 too much styles can change hover there.
