### ISSUE TITLE
Build Bricks:  Show level 

### ISSUE THREAD

**Issue by SashaScholar6** [Scholar-6/brillder#3800]
- [x] For adapted bricks

- [x] for bricks with edit icon on them

- [x] For returned bricks
- [x] show as green for pending publication column
<img width="322" alt="Screenshot 2021-08-16 at 12 43 53" src="https://user-images.githubusercontent.com/59654112/129551803-1e16333b-1088-4d51-9670-0fee20a2fe4b.png">

**Comment by ivanromakh** [comment]
@SashaScholar6 what is dit icon?

**Comment by ivanromakh** [comment]
@SashaScholar6 which page is it?

**Comment by ivanromakh** [comment]
I see build page

**Comment by SashaScholar6** [comment]
oops - 'Edit' icon
