### ISSUE TITLE
Icons in build

### ISSUE THREAD

**Issue by SashaScholar6** [Scholar-6/brillder#3803]
<img width="317" alt="Screenshot 2021-08-11 at 20 32 08" src="https://user-images.githubusercontent.com/59654112/129083838-88ac5dda-6c06-4f57-97ab-2767df7f0a8d.png">

- [x] add feather-watch on left of in progress. and feather-award on left of published

<img width="190" alt="Screenshot 2021-08-11 at 20 33 05" src="https://user-images.githubusercontent.com/59654112/129083971-8e83fb81-eee6-4d7b-931e-ac2f74136629.png">

- [x] style the same as Levels in View All

<img width="450" alt="Screenshot 2021-08-11 at 20 36 09" src="https://user-images.githubusercontent.com/59654112/129084344-ee218aa4-ced9-49f4-8816-715294390ba7.png">

- [x] add alert-triangle on left of 'Take care...
- [x] move placeholder to centre

<img width="246" alt="Screenshot 2021-08-11 at 20 39 13" src="https://user-images.githubusercontent.com/59654112/129084730-42b21223-6a41-483b-b594-083ac5729dc2.png">

- [x] add refresh-cw icon left of 'Change Answer..

<img width="625" alt="Screenshot 2021-08-11 at 20 40 52" src="https://user-images.githubusercontent.com/59654112/129084948-6b021fe0-b116-4dfe-b039-8fe022a8ba94.png">

- [x] add check-square to left of text for choose one and several

- [x] Vertical Shuffle: add sort (same as in manage classes) icon on left of 'Enter Answers...'
- [x] Horizontal Shuffle: add chevrons-right left of 'Enter Answers...'
- [x] add space in placeholder 'Answer 1' etc.

- [x]  add check-square to left of text for missing word
- [x] remove ellipsis in answer entry panels

- [x] remove ellipses for word and line highlighing

**Comment by ivanromakh** [comment]
@SashaScholar6 space sign or something? there is space between Answer and 1 right?
![image](https://user-images.githubusercontent.com/18567511/129321518-0bb819f0-2014-43d6-8c3b-713e43c0b545.png)
