### ISSUE TITLE
Fix icons and text on iPad Home screen

### ISSUE THREAD

**Issue by SashaScholar6** [Scholar-6/brillder#3806]
- [x] make icons and text bigger, like on desktop
- [x] remove/reduce letter spacing so like desktop
- [x] make left text bigger by about 20%
- [x] icons and text nice styles, but a bit too big now - could be 10 % smaller
- [x] brick stats icon should be thicker - like my library

**Comment by ivanromakh** [comment]
![image](https://user-images.githubusercontent.com/18567511/129368519-7f23c21a-8a32-4502-87ce-4b3f12ed7eee.png)

**Comment by SashaScholar6** [comment]
better :) - see tweaks in task above

**Comment by ivanromakh** [comment]
![image](https://user-images.githubusercontent.com/18567511/129372295-8cee8323-17f3-4471-a79f-db60ae6788d8.png)

**Comment by SashaScholar6** [comment]
nice :)
