### ISSUE TITLE
Pair Match height issue

### ISSUE THREAD

**Issue by SashaScholar6** [Scholar-6/brillder#3818]
<img width="1198" alt="Screenshot 2021-08-16 at 17 41 37" src="https://user-images.githubusercontent.com/59654112/129590873-dea15c42-7cea-4e10-86dd-d9c1647cd724.png">

**Comment by ivanromakh** [comment]
@SashaScholar6 need brick id can`t reproduce it.
![image](https://user-images.githubusercontent.com/18567511/129710590-cac93ff3-e36a-4bc3-827b-a0bace341061.png)

**Comment by SashaScholar6** [comment]
weird seems fine now, was 697
