### ISSUE TITLE
Manage Classes Brick Wall

### ISSUE THREAD

**Issue by aromakh** [Scholar-6/brillder#3819]
Since now /classrooms return just classroms with students and assignments.

to get all or selected classroom page data, please use follwoing url. If classroomId is set to 0 or null, it means all classes. 

http://swagger.scholar6.org/docs/#!/classroom/getClassroomAssignments

**Comment by ivanromakh** [comment]
@aromakh it is still the same. not loading.

**Comment by ivanromakh** [comment]
it is waiting 10sec and return nothing.
![image](https://user-images.githubusercontent.com/18567511/129685086-d0a96d05-cadf-4dcc-9cab-5a87fc9ebe1e.png)

**Comment by ivanromakh** [comment]
and remove pagination as I don`t know how many assignments are in page.
