### ISSUE TITLE
Manage Users updates

### ISSUE THREAD

**Issue by SashaScholar6** [Scholar-6/brillder#3821]
<img width="721" alt="Screenshot 2021-08-17 at 12 23 13" src="https://user-images.githubusercontent.com/59654112/129709691-eafc51b8-cc06-4464-8ce1-19eef6d69752.png">

- [x] show most recently joined by default
- [x] remove letter spacing on 'All Users'
- [x] Remove capitalisation from All Users and make smaller
- [x] Add New User also remove caps
- [x] style subjects in sidebar like in View All
- [x] remove chevron and hiding code from sidebar

- [x] date joined has disappeared?
- [x] styles on call w me
<img width="1049" alt="Screenshot 2021-08-18 at 17 13 03" src="https://user-images.githubusercontent.com/59654112/129924062-2b6695b7-10af-4983-b0b7-e7a7c5460887.png">

- [x] inactive users make circle red and text 'Inactive underneath picture
- [x] 2 or 3 more rows

**Comment by ivanromakh** [comment]
@SashaScholar6 not every one have role preference.

**Comment by scholar6admin** [comment]
@aromakh Everyone should have a role preference set on the backend.

**Comment by ivanromakh** [comment]
that is probably new user and didn`t set it yet.

**Comment by ivanromakh** [comment]
his status is 0

**Comment by scholar6admin** [comment]
Ahh got it ok no worries.

**Comment by ivanromakh** [comment]
there are a lot such users.
![image](https://user-images.githubusercontent.com/18567511/129891794-da418167-034f-4ab1-960e-a72296d5f8db.png)

**Comment by ivanromakh** [comment]
@SashaScholar6 this one is for backend.
![image](https://user-images.githubusercontent.com/18567511/129892131-67bd9ca9-6634-44e6-a9f5-8bd5b79f36f6.png)
