### ISSUE TITLE
Toby & Sam Ticket #452: Timer should not reset

### ISSUE THREAD

**Issue by SashaScholar6** [Scholar-6/brillder#3826]
Hi all,

two quick issues I've found recently, here's the first (second to come).

If I click on Brief when reading through the preview, the timer at the bottom resets.

Thanks,
Sam

Submitted from: https://app.brillder.com/play-preview/brick/838/prep

Screenshot 2021-08-17 at 18.03.24.png
Screenshot 2021-08-17 at 18.03.24
PNG

Toby Peres  Yesterday 20:05
Hiding the timer and showing it again resets the clock on the prep and synthesis. Works fine for investigation stage.

------------------
Submitted from: https://app.brillder.com/play-preview/brick/646/synthesis

- [x] fix prep timer
- [x] fix synthesis timer

**Comment by ivanromakh** [comment]
@SashaScholar6 its play preview.
