### ISSUE TITLE
Sam #451: Colour not showing up in profile panels

### ISSUE THREAD

**Issue by SashaScholar6** [Scholar-6/brillder#3827]
Hi again,

I'm also having the issue we'd had previously, with text colour/not showing up, on my profile page.

Sam

------------------
Submitted from: https://app.brillder.com/onboarding/profile-page

<img width="896" alt="Screenshot 2021-08-18 at 12 07 40" src="https://user-images.githubusercontent.com/59654112/129880172-8e026c0d-af40-4e71-a62b-40a9c3b3e2d1.png">

**Comment by ivanromakh** [comment]
probably firefox
