### ISSUE TITLE
Pair Match in Play Preview before refresh

### ISSUE THREAD

**Issue by SashaScholar6** [Scholar-6/brillder#3834]
<img width="1252" alt="Screenshot 2021-08-19 at 10 32 19" src="https://user-images.githubusercontent.com/59654112/130036228-867b46e9-b905-4f25-89a0-bf860db55c4d.png">

https://app.brillder.com/play-preview/brick/697/live

**Comment by ivanromakh** [comment]
@SashaScholar6 what is wrong?
