### ISSUE TITLE
NO need for Brick Status changed email

### ISSUE THREAD

**Issue by SashaScholar6** [Scholar-6/brillder#3835]
<img width="662" alt="Screenshot 2021-08-19 at 11 42 34" src="https://user-images.githubusercontent.com/59654112/130046920-9282a5b1-144f-4218-ba47-55812af0aafe.png">

**Comment by ivanromakh** [comment]
https://github.com/Scholar-6/brillder-backend/commit/2c2fa78dde02f0bb33f3917221853e6e634747ea
