### ISSUE TITLE
Fix 4/1 Manage Classes bug

### ISSUE THREAD

**Issue by SashaScholar6** [Scholar-6/brillder#3841]
<img width="1019" alt="Screenshot 2021-08-20 at 14 17 43" src="https://user-images.githubusercontent.com/59654112/130231831-eff3c285-16b4-476a-a7db-c836f79cdcdd.png">

- [ ] Fix count of users @aromakh

**Comment by ivanromakh** [comment]
@SashaScholar6 this is coming from database.

**Comment by ivanromakh** [comment]
@aromakh  we have one user but it gives me 4 + 1. Did I miss some users?
![image](https://user-images.githubusercontent.com/18567511/130233394-396b906f-ee27-46f6-ac28-7a1f5c10d2c4.png)

**Comment by ivanromakh** [comment]
but that class has only one student...
![image](https://user-images.githubusercontent.com/18567511/130233684-0a3b0c8e-9ab2-42ab-ae75-785171f31c34.png)

**Comment by ivanromakh** [comment]
@SashaScholar6 that is probably very old class. when we had personal assignments.
