### ISSUE TITLE
Builder user preference should have adapt button

### ISSUE THREAD

**Issue by scholar6admin** [Scholar-6/brillder#3847]
![image](https://user-images.githubusercontent.com/58778078/130424153-96f7e704-f225-49c9-a4bd-883e60777aa9.png)

- [x] show same popup as when admin clicking adapt

**Comment by ivanromakh** [comment]
@SashaScholar6 I see same popup for admins and builders.
![image](https://user-images.githubusercontent.com/18567511/135079354-6a4a1405-2979-4364-a865-2f08761f847a.png)
