### ISSUE TITLE
Carlo cannot access scores of users through brilliantminds@brillder.com

### ISSUE THREAD

**Issue by scholar6admin** [Scholar-6/brillder#3858]
login as brilliantminds@brillder.com

And check the latest scores for the classes. Carlo thinks he should be seeing more scores on the latest bricks. 

- [ ] 0 students showing as completed on previous assignments - /classroom/assignments showing byStatus:{count:0} completed 
![image](https://user-images.githubusercontent.com/58778078/131478091-d7935729-188d-41a3-b4f4-15f2ad840836.png)

- [ ] if it makes it faster - Remove studentStatus array from /classroom/assignments

- [x] Cannot see score beside student when opening the assigned brick. Get it from /stats/assignment when opening the assignment byStudent field
![image](https://user-images.githubusercontent.com/58778078/131478794-6353aa07-ef02-4731-aff5-bf9594b1509e.png)

**Comment by ivanromakh** [comment]
@scholar6admin what do you mean by access to scores?

**Comment by ivanromakh** [comment]
@scholar6admin which classes should I check?

**Comment by scholar6admin** [comment]
@ivanromakh it is as user brilliantminds@brillder.com and it is class 450 the all rounder one

**Comment by ivanromakh** [comment]
@scholar6admin All I see is this number is wrong. it sometimes 0 when there is some attempts.
![image](https://user-images.githubusercontent.com/18567511/131330727-297415e5-216c-457e-b386-bc8e44bd0d5c.png)

**Comment by ivanromakh** [comment]
There should be at least 10 in status 2 here.
![image](https://user-images.githubusercontent.com/18567511/131331262-b813df12-1722-4d5c-8568-b11c4131aa59.png)

**Comment by ivanromakh** [comment]
@aromakh There should be at least 10 in status 2 here.
![image](https://user-images.githubusercontent.com/18567511/131331262-b813df12-1722-4d5c-8568-b11c4131aa59.png)

**Comment by ivanromakh** [comment]
@aromakh there is something wrong with this. currently I am getting results from two end points for students
here are some results.
https://dev-api.brillder.com/classroom/assignments/0/10/450
and here are some another results.
https://dev-api.brillder.com/stats/assignment/136

**Comment by ivanromakh** [comment]
I can probably do it by myself as all data seems present. no database update needed or editional data.

**Comment by ivanromakh** [comment]
@aromakh there are no students in this list. couldn`t figure out why.
https://github.com/Scholar-6/brillder-backend/blob/master/src/controllers/classroomController.ts#L264

there is some filter maybe it is removing them.
https://github.com/Scholar-6/brillder-backend/blob/master/src/controllers/classroomController.ts#L213
