### ISSUE TITLE
James #464: Safari issues

### ISSUE THREAD

**Issue by SashaScholar6** [Scholar-6/brillder#3860]
- [x] can't type into question panels
- [x] can't upload images

**Comment by ivanromakh** [comment]
@SashaScholar6 I don`t have mac. can`t check if uploading works on safari.

**Comment by ivanromakh** [comment]
safari can`t load files?
![image](https://user-images.githubusercontent.com/18567511/131653215-617c5f2c-6bb9-4ca1-802e-5840b5503bb3.png)

**Comment by ivanromakh** [comment]
uploading sounds works good for me so it should be the same for images. problem is getting files.

**Comment by ivanromakh** [comment]
for images I need access to Mac which have at least one image.

**Comment by ivanromakh** [comment]
found image. its quill error for images.
![image](https://user-images.githubusercontent.com/18567511/131653746-ebcbb748-26e1-4cb8-8c7d-ef4b9e361dcd.png)
