### ISSUE TITLE
Plan tab fixes

### ISSUE THREAD

**Issue by SashaScholar6** [Scholar-6/brillder#3864]
<img width="868" alt="Screenshot 2021-09-01 at 13 02 24" src="https://user-images.githubusercontent.com/59654112/131660640-cc8718c7-99c3-4cb0-b73f-6826cde6dfd0.png">

- [x] pending publication tooltip should be on one line
- [x] write 'Brick Status' in bold above 4 circles

**Comment by ivanromakh** [comment]
@SashaScholar6 which browser is it?
