### ISSUE TITLE
When I play through a brick as unauth user then get to synthesis and sign in, I am not able to continue my play attempt

### ISSUE THREAD

**Issue by SashaScholar6** [Scholar-6/brillder#3865]
- [x] Logging in from synthesis popup I Should be taken to review now synthesis
- [x] I should be able to complete the review (the popup just doesn't do anything when click 'submit')
![image](https://user-images.githubusercontent.com/58778078/133628751-d9ace381-8d5d-4167-8f2f-f0228d29c493.png)

Instead I am taken to home screen.

- [x] When I get redirected back to the review I should see the same play attempt I left (not a white screen)
![image](https://user-images.githubusercontent.com/58778078/133598455-5c72e9b6-c679-471c-9b23-ccf6004fe1c6.png)

- [x] sign in from cover page pop up should also redirect

- [x] I would like to go back to where I was in my play attempt

- [x] desktop
- [x] mobile

**Comment by ivanromakh** [comment]
@SashaScholar6 @scholar6admin I will need to work in separate brick. For this we will need to move everything to local storage it will take few days or more.
