### ISSUE TITLE
Sam Table fixes #465

### ISSUE THREAD

**Issue by SashaScholar6** [Scholar-6/brillder#3867]
Using a table in a question seems not to look as nice as in the synthesis section. Also, I notice I'm missing the options for alignment here too.

------------------
Submitted from: https://app.brillder.com/build/brick/838/investigation/question-component/236990

- [x] style like in synthesis with grey backgrounds
- [x] include alignment option

- [ ] the tables still seem to be a little buggy. I had a lot of di­f­fi­­­culty work­ing with the sub­­­­di­vided cells in the second half, and I've just no­ticed that whenev­er I log back in the column widths are re­­­set, al­though I think this comes out ok when the Brick is played.

Submitted from: https://app.brillder.com/build/brick/838/synthesis

**Comment by ivanromakh** [comment]
@SashaScholar6 I can`t reproduce it.

**Comment by william-gooch** [comment]
I've enabled alignment option but I also can't reproduce the issue with tables. I'd need more than 'had a lot of difficulty'.
