### ISSUE TITLE
Toolbar, tab and Safari fixes

### ISSUE THREAD

**Issue by SashaScholar6** [Scholar-6/brillder#3869]
<img width="713" alt="Screenshot 2021-09-01 at 15 21 58" src="https://user-images.githubusercontent.com/59654112/131678804-1ae5ba83-22f6-4365-add5-dd0897540f68.png">

- [x] fix overflow safari

- [x] make Tt etc. regular not bold

- [x] 'Text Case' tooltip

<img width="340" alt="Screenshot 2021-09-01 at 15 22 27" src="https://user-images.githubusercontent.com/59654112/131678873-8c261db1-47be-4356-972a-d5b99d859192.png">

- [x] fix tab width to 2px

- [x] synthesis grey bar should have shadow
<img width="1379" alt="Screenshot 2021-09-01 at 15 24 31" src="https://user-images.githubusercontent.com/59654112/131679305-6855cb76-4476-4bc0-8352-de836d97086c.png">

Safari FIXES
- [x] fix Back to build text in sidebar
- [x] bottom grey bar should be round
- [x] progress bar should be rounded on left hand

<img width="1144" alt="Screenshot 2021-09-01 at 15 27 02" src="https://user-images.githubusercontent.com/59654112/131679618-e7e10e1a-ae7f-4a0e-b178-37e0eacc277b.png">

- [x] round grey edges

<img width="1244" alt="Screenshot 2021-09-01 at 15 27 56" src="https://user-images.githubusercontent.com/59654112/131679772-6b358559-d86e-46ca-8c47-1f42e859cd47.png">

- [x] remove square shadow on bottom bar

iPHONE

- [ ] progress bar should be rounded on left hand side during play

**Comment by ivanromakh** [comment]
@SashaScholar6 I don`t know how to do it.
![image](https://user-images.githubusercontent.com/18567511/131813399-8429e7b6-152c-4af1-85c3-2d0f440a2590.png)
