### ISSUE TITLE
Sidebar and number bar fixes

### ISSUE THREAD

**Issue by SashaScholar6** [Scholar-6/brillder#3871]
<img width="433" alt="Screenshot 2021-09-01 at 15 43 09" src="https://user-images.githubusercontent.com/59654112/131682225-81dd1430-dffa-4360-9f2b-9b42281d5035.png">

- [x] move prep icon button into number bar, before numbers on left
- [x] also in play preview
- [x] moved dashed circle also into number bar here, so that prep icon is in the middle (no longer show 'Prep' underneath
- [ ] move 'Click here...' text up so next to new position
- [x] remove line and move sidebar buttons up

- [ ] instead of line underneath selected number, just show a ring around number like on phone

**Comment by ivanromakh** [comment]
@SashaScholar6 I can`t do half of it.
