### ISSUE TITLE
should be multiples lozenges if multiple editors invited

### ISSUE THREAD

**Issue by SashaScholar6** [Scholar-6/brillder#3875]
- [x] only adds last editor
- [x] can't delete editors
- [x] show still have invite an editor button even after inviting an editor

**Comment by ivanromakh** [comment]
@SashaScholar6 this one works good for me. assigned two editors and see them.
![image](https://user-images.githubusercontent.com/18567511/131819923-d4f7eeb7-d59c-423c-bcf3-69148982810b.png)

**Comment by ivanromakh** [comment]
@SashaScholar6 you can delete editors if there are more than two.

**Comment by ivanromakh** [comment]
@aromakh editors aren`t asigned sometimes it could skip few.
I sent  5 people.
![image](https://user-images.githubusercontent.com/18567511/131842576-f31a87a9-c06e-4a9c-a795-693e8ad2df59.png)
but in response got only 4.
![image](https://user-images.githubusercontent.com/18567511/131842442-08d850bf-b8fa-4616-8e48-5a2b48bcb1f5.png)

**Comment by ivanromakh** [comment]
@SashaScholar6 you can`t invite because you are admin. builder can only invite editors. There is a rule that only 3 buttons can be present.

**Comment by ivanromakh** [comment]
@SashaScholar6 as admin you will be able to invite editors again after you move it to publication status. as there are aleady 3 buttons.
