### ISSUE TITLE
Admin should be able to delete editors of any brick (not just ones authored by them)

### ISSUE THREAD

**Issue by SashaScholar6** [Scholar-6/brillder#3879]

**Comment by ivanromakh** [comment]
@SashaScholar6 I see. you can`t remove editor if there is only one editor.

**Comment by scholar6admin** [comment]
You cant remove the last editor when the brick is returned to author.

https://dev-app.brillder.com/play-preview/brick/881/submit

**Comment by ivanromakh** [comment]
@scholar6admin author can`t return brick to editors. its forbidden.
![image](https://user-images.githubusercontent.com/18567511/133598537-c983b969-5a75-47ce-8db9-53db942717db.png)
![image](https://user-images.githubusercontent.com/18567511/133598400-4b92ef52-dbd6-436f-91b1-ba2e102ca069.png)

**Comment by ivanromakh** [comment]
@scholar6admin some users can`t be added as editors. not sure why (backend thing).

**Comment by aromakh** [comment]
@ivanromakh @lindsaymacvean 
current rules:

1. brick author can not be editor of own brick
2. current logged in user cannot be assigned as editor to the brick.

3. If user was alredy editor, he will be set as editor, but notification will not be sent.


No any other restrictions.

**Comment by ivanromakh** [comment]
@aromakh error can be just ENUM as Sasha will probablly will give text later.
