### ISSUE TITLE
Categorise image input

### ISSUE THREAD

**Issue by SashaScholar6** [Scholar-6/brillder#3883]
- [x] Images too big - should be same as vertical shuffle, with zoom capability

<img width="1070" alt="Screenshot 2021-09-11 at 19 17 21" src="https://user-images.githubusercontent.com/59654112/132955908-03ec7fd9-58db-49ae-9db2-ea1c9a25534c.png">

- [ ] why is this happening?

**Comment by ivanromakh** [comment]
@SashaScholar6 Image is too big. That is backend issue
