### ISSUE TITLE
Tessa Ticket #405 lineation (poem popup) on missing word

### ISSUE THREAD

**Issue by scholar6admin** [Scholar-6/brillder#3887]
https://scholar6.zendesk.com/agent/tickets/405

**Comment by ivanromakh** [comment]
@scholar6admin added button 
![image](https://user-images.githubusercontent.com/18567511/144604263-80b9c6f3-7dfb-4b6f-97b3-b1ac98d0ed28.png)

**Comment by ivanromakh** [comment]
@SashaScholar6 why did you moved it to back I don`t see any problem with this and in ticket there is no update about this task. moving to testing.
