### ISSUE TITLE
Landscape youtube in prep on safari

### ISSUE THREAD

**Issue by scholar6admin** [Scholar-6/brillder#3894]
- [x] When rotating the phone in prep it should show warning screen on landscape mode (but it should not interrupt any youtube video that is playing in the foreground) so that the user sees a warning when they close the video.
![image](https://user-images.githubusercontent.com/58778078/133760122-a2ef3911-7dac-46ed-b448-ca4fb787f0ac.png)

The test to satisfy Kate is Iphone 12 Safari

Full screen video in prep and then turn horizontal. 

Please see if we can set a condition (if prep and youtube mode is activated then ignore rotation warning screen)

Note for Lindsay
Also test on all other devices

**Comment by ivanromakh** [comment]
@scholar6admin I unable rotation in prep but I am unable to do anything in safari. there is no function to rotate or make it full screen.

**Comment by ivanromakh** [comment]
there is titles for rotation but thouse functions are undefined in real device. they only present in google chrome.
https://usefulangle.com/post/105/javascript-change-screen-orientation

**Comment by scholar6admin** [comment]
@ivanromakh I dont know if we need to worry. We just need to unblock it and let the browser do the rest when the user rotates their phone whilst watching a youtube video. 

I will test on dev using browserstack now.
