### ISSUE TITLE
OG preview needs to have 240 character limit

### ISSUE THREAD

**Issue by scholar6admin** [Scholar-6/brillder#3895]
- [x] character limit

- [x] If nothing returns after 30 seconds then remove 'Loading' 

see
https://app.brillder.com/build/brick/520/plan

![image](https://user-images.githubusercontent.com/58778078/131981107-63fc2c73-3398-4bdf-93f8-145adcd69f1a.png)

http://www.mathsbox.org.uk/revisionnotes/AQA%20Core%203%20Revision%20Notes.pdf

- [x] links in brief should be lozenges with red B logo and brick title

**Comment by ivanromakh** [comment]
@scholar6admin where is this need screenshot, brick or link.

**Comment by ivanromakh** [comment]
@SashaScholar6 I can`t limit by number of words I can limit by number of lines in build.

**Comment by SashaScholar6** [comment]
ok, how about 5 lines?

**Comment by ivanromakh** [comment]
@SashaScholar6 
![image](https://user-images.githubusercontent.com/18567511/134191974-c88fde8c-eae2-45e5-818d-c1719edec525.png)

**Comment by ivanromakh** [comment]
@SashaScholar6 where I can find that Loading... which is still after 30sec?

**Comment by ivanromakh** [comment]
@SashaScholar6 I need link as example to for creation of OG tags. Which I can paste in quill to create that tag.

**Comment by SashaScholar6** [comment]
Hi Ivan, it's for brick covers linking to other bricks
