### ISSUE TITLE
introjs off side of screen

### ISSUE THREAD

**Issue by scholar6admin** [Scholar-6/brillder#3896]
![image](https://user-images.githubusercontent.com/58778078/133593372-92bd1148-7d93-4f65-ab7e-530b8ce56da7.png)

Archive a brick shows an introjs
This should not be off the side of the screen.

- [x] green button should say 'View' (not 'Next' and take me to Archived screen

**Comment by ivanromakh** [comment]
@scholar6admin this is problem related to intro js maybe it is not supported by Safari. I can`t change where that popup will apper.

**Comment by ivanromakh** [comment]
I removed min-width and it isn`t overflowing but squished.
![image](https://user-images.githubusercontent.com/18567511/133989919-5c02cb68-2aa6-450b-8e1b-68bc79c785f0.png)
