### ISSUE TITLE
brief and prep button fixes

### ISSUE THREAD

**Issue by SashaScholar6** [Scholar-6/brillder#3898]
<img width="84" alt="Screenshot 2021-09-16 at 17 24 36" src="https://user-images.githubusercontent.com/59654112/133640176-90bc3d7e-82fb-40d8-927f-860be433ae9e.png">

- [x] fix cutoff
- [x] show hand rather than pointer when mous above it

**Comment by ivanromakh** [comment]
@SashaScholar6 Can`t reproduce cut off
