### ISSUE TITLE
When Adapted brick is published to public catalogue, don't show adapted icon on cover page anymore

### ISSUE THREAD

**Issue by SashaScholar6** [Scholar-6/brillder#3899]
<img width="802" alt="Screenshot 2021-09-16 at 17 36 29" src="https://user-images.githubusercontent.com/59654112/133642179-10990874-2800-46d7-87d7-7873e5b2a1db.png">

- [x] remove adapted text and icon from cover page when published isCore

- [x] and fix ellipsis issue

**Comment by ivanromakh** [comment]
@SashaScholar6 in which browser ellipsis occur?
