### ISSUE TITLE
Library should show best attempt

### ISSUE THREAD

**Issue by scholar6admin** [Scholar-6/brillder#3903]
![image](https://user-images.githubusercontent.com/58778078/133781265-7ff74ae9-9aff-4fe8-b09d-61e475b907c2.png)

<img width="1120" alt="Screenshot 2021-09-22 at 14 18 37" src="https://user-images.githubusercontent.com/59654112/134342309-fb748be5-eae4-47dc-bd07-516c824f9a08.png">
<img width="913" alt="Screenshot 2021-09-22 at 14 19 25" src="https://user-images.githubusercontent.com/59654112/134342321-0fd0ec6c-5954-42e7-b240-374e610eb559.png">

- [ ] now all are the same height!

<img width="1230" alt="Screenshot 2021-09-22 at 14 19 31" src="https://user-images.githubusercontent.com/59654112/134342327-5e8edf2e-641c-4797-8961-e9aff45dbf6b.png">

- [ ] contents sidebar, title should be on one line always (so ellipsis if necessary)

**Comment by ivanromakh** [comment]
@SashaScholar6 library shows the best attempt for me.
