### ISSUE TITLE
White screen on provisional score of published brick

### ISSUE THREAD

**Issue by SashaScholar6** [Scholar-6/brillder#3907]
https://app.brillder.com/play-preview/brick/348/provisionalScore

**Comment by ivanromakh** [comment]
@SashaScholar6 I don`t see white screen.
![image](https://user-images.githubusercontent.com/18567511/133990263-f85525a4-25e2-4882-9b7b-d817bdf90663.png)

**Comment by ivanromakh** [comment]
@SashaScholar6 you could see white screen on build if you don`t have access to brick.
