### ISSUE TITLE
Remove ckeditor4 directory 

### ISSUE THREAD

**Issue by scholar6admin** [Scholar-6/brillder#391]
https://github.com/Scholar-6/brillder/tree/development/public/ckeditor

I originally asked to remove references to CDNs in case they are blocked in China. However CKeditor 4 may be available there. 

We added ckeditor to the frontend public directory but we included a lot of useless files. These could be removed. e.g. the sample directory

**Comment by ivanromakh** [comment]
@scholar6admin  during removing old Equations this folder no longer needed. Removed

**Comment by ivanromakh** [comment]
https://github.com/Scholar-6/brillder/issues/602
