### ISSUE TITLE
Teacher Commenting UX

### ISSUE THREAD

**Issue by SashaScholar6** [Scholar-6/brillder#3915]
<img width="410" alt="Screenshot 2021-09-21 at 12 25 59" src="https://user-images.githubusercontent.com/59654112/134155119-ba3da938-7c11-4da4-9bed-5e0b70613e30.png">

- [x] when clicked, should not go yellow and create blank comment - only after green button is pushed
- [x] previous comment should not remain cached, and new comment should refresh number automatically

<img width="127" alt="Screenshot 2021-09-21 at 12 30 22" src="https://user-images.githubusercontent.com/59654112/134155615-1a82b9de-ef31-414e-919a-378b435c5db7.png">
- [ ] center circle with brick shapes (more right)

<img width="110" alt="Screenshot 2021-09-21 at 12 35 46" src="https://user-images.githubusercontent.com/59654112/134156274-123a8520-8352-44e4-98e0-930183c4f1cc.png">

- [x] 50% circle on hover, tooltip in bold saying 'View Book Summary'
- [x] make send reminder buttons and icons on left smaller, so same size as other circles

<img width="66" alt="Screenshot 2021-09-21 at 12 37 02" src="https://user-images.githubusercontent.com/59654112/134156436-a774c657-50af-4f4d-bad3-4768141b7f61.png">

- [x] when 1 or more comments present, take me to last comment when clicking
- [x] tooltip is 'View Comments' in bold, with 50% circle in red or yellow

<img width="60" alt="Screenshot 2021-09-21 at 12 38 08" src="https://user-images.githubusercontent.com/59654112/134156571-8c9211f3-1276-4ca1-a7b2-01ecb3d6a471.png">
- [ ] for empty comment, tooltip is 'Add comment', with 50% grey circle on hover

<img width="526" alt="Screenshot 2021-09-21 at 12 45 42" src="https://user-images.githubusercontent.com/59654112/134157533-bfcfcb38-7932-4b92-b0f0-45aadeeb9de6.png">

- [x] more padding at the bottom here

<img width="873" alt="Screenshot 2021-09-21 at 12 46 10" src="https://user-images.githubusercontent.com/59654112/134157602-d7fcb528-55a9-4d03-a37d-b9e2fb19ec65.png">

- [x] when I have opened the minipreview, make other students names dark GREY, and selected student bold - other eyes also GREY

- [x] 'View Brick Summary' bold tooltip for book and 50% green circle

<img width="424" alt="Screenshot 2021-09-21 at 12 50 22" src="https://user-images.githubusercontent.com/59654112/134158149-a16b7501-5964-44c8-88eb-3f4fa6b8118e.png">

- [x] instead mimic build system for commenting, with entry panel and send button on top
- [x] should not be able to keep replying empty comments
- [x] Reply/ies font should be sentence case not all caps (only capital 'R')

**Comment by ivanromakh** [comment]
blocked by https://github.com/Scholar-6/brillder-backend/issues/538
