### ISSUE TITLE
Teacher commenting fixes

### ISSUE THREAD

**Issue by SashaScholar6** [Scholar-6/brillder#3925]
- [x] Add loader after clicking manage classes
- [x] before student name and q1 on top left, add user icon with chevron up and down on top and bottom

<img width="394" alt="Screenshot 2021-09-24 at 15 22 50" src="https://user-images.githubusercontent.com/59654112/134681512-3af7b6e3-072a-4ad0-bae7-697f5e73819d.png">

- [x] all tooltips on this page light blue with tab grey BOLD text
- [x] tooltip for eye: 'View Answers'

- [x] view comments should take me to brief
- [x] Add 'Comments and Annotations' heading in bold in book above comment entry panel
- [x] add post cancel to replies like in build
- [x] font in replies ansd suggestions should be dark blue (also in build)

**Comment by ivanromakh** [comment]
@SashaScholar6 there is loader there.
![image](https://user-images.githubusercontent.com/18567511/134879999-d1cef7d5-ae3a-4e78-a21f-7f5441b7af2d.png)
![image](https://user-images.githubusercontent.com/18567511/134880045-09eeec25-b8ef-4f78-99e8-f3c0dc48df7e.png)

**Comment by ivanromakh** [comment]
@SashaScholar6 what about single user?

**Comment by ivanromakh** [comment]
when you click on user in class sidebar

**Comment by ivanromakh** [comment]
@SashaScholar6 it will take a lot of time to do other 2 points. need confirmation.
