### ISSUE TITLE
Lambda script to forward emails and redirect

### ISSUE THREAD

**Issue by scholar6admin** [Scholar-6/brillder#3937]
https://console.aws.amazon.com/lambda/home?region=us-east-1#/functions/Brillder_Marketing_Referral?tab=code

- [x] Script should accept a json object that has the following properties
```
{
    "referrerEmail":"string",
    "referredEmails:["string"...]
}
```
- [x] Send this object in an email to admin@scholar6.org

- [x] Let me know an endpoint where this script can be triggered (API gateway or cloudfront etc)

@lindsaymacvean 
Endpoint is:
https://3mjhia3qn5.execute-api.us-east-1.amazonaws.com/default/Brillder_Marketing_Referral

curl example:
`curl --location --request POST 'https://3mjhia3qn5.execute-api.us-east-1.amazonaws.com/default/Brillder_Marketing_Referral' \
--header 'Content-Type: application/json' \
--data-raw '{
    "referrerEmail": "string",
    "referredEmails": [
        "string",
        "email2"
    ]
}'`

**Comment by ivanromakh** [comment]
@aromakh CORS error. could you add brillder.com in white list or allow request from there.https://brillder.com/referral/?
