### ISSUE TITLE
Paywall V2 Account page

### ISSUE THREAD

**Issue by scholar6admin** [Scholar-6/brillder#3970]
https://lucid.app/lucidchart/1d236855-2f92-4293-bba9-ae167638f797/edit?invitationId=inv_051c1d35-070f-43bf-b226-89fe12df7de0&page=0_0#

- [x] Go Premium Buttons (at least one)
- [x] Choose the plan (with pricing) (double as a pricing page on the marketing site?)
- [x] Credit Card Form (stripe)
- [x] Warning countdown to limit on each of the buttons (assign on brick and assign in manage classes). 
- [x] Hard limit popup 

I want the checkout to look like this so people can discount to 0%
- [x] I want the checkout page to be something like this https://liveyourmessage.xperiencify.io/sales-for-superheroes/order/

**Comment by aromakh** [comment]
@ivanromakh 
I added coupon code to the payment intent, 
mobile branch is already updated.

For a moment price is not dynamic, as we will need to build voucher API, which will get coupon details and prices.
