### ISSUE TITLE
Create 4 starting pages

### ISSUE THREAD

**Issue by scholar6admin** [Scholar-6/brillder#4]
First page has the following options. 

1. Create a new brick
2. View Existing Bricks

The poster had these options but ignore them for the moment we can come back to them later. 
![image](https://user-images.githubusercontent.com/58778078/72424471-f9d2c180-377d-11ea-94ee-e90e92932886.png)

Second Page is a meta data form to create a new brick
![image](https://user-images.githubusercontent.com/58778078/72424711-52a25a00-377e-11ea-83fe-fbc7b8831715.png)

Third page will be similar to SurveyJS, it will be a content building page using blocks.
![image](https://user-images.githubusercontent.com/58778078/72424766-69e14780-377e-11ea-92de-9c8337ad689c.png)

Fourth Page will be a list of bricks
[There is not really an image for this on the poster]

**Comment by ivanromakh** [comment]
@lindsaymacvean Second page for small devices.
![image](https://user-images.githubusercontent.com/18567511/72629794-b03ece00-3959-11ea-8052-d258c1bcd027.png)

**Comment by ivanromakh** [comment]
Raw version of page 3
![image](https://user-images.githubusercontent.com/18567511/72742376-410fe680-3bb2-11ea-92da-dd3cc4d538e6.png)

**Comment by scholar6admin** [comment]
Brilliant thankyou. 

@ivanromakh 
Can we set the break points to 
max-width: 599px
min-width: 600px
min-width: 900px
min-width: 1200px
min-width: 1800px

As per this article. 
https://www.freecodecamp.org/news/the-100-correct-way-to-do-css-breakpoints-88d6a5ba1862/

Have the PRs been issued?

**Comment by scholar6admin** [comment]
Closing this task and splitting into:

#15 
#12 
#11 
#10
