### ISSUE TITLE
Change the maths colour to #FF6200 (too similar to 'in review' atm)

### ISSUE THREAD

**Issue by scholar6admin** [Scholar-6/brillder#401]
As a builder
when I go to view all
And I see maths bricks 
I should not confuse this with an in review brick

change the orange?

- [x] sidebar 

- [x] published brick colour

**Comment by aromakh** [comment]
@SashaScholar6  done

**Comment by SashaScholar6** [comment]
Cool thx :)

Some similar tasks on github to do w drama and alphabetising
