### ISSUE TITLE
Intro.js and self-published assignment for Educators

### ISSUE THREAD

**Issue by SashaScholar6** [Scholar-6/brillder#4131]
- [x] Add step to intro js around toggle: “Click on the key icon to view your personal catalogue and assign a brick you have published yourself”
- [x] Clicking on empty assignments should see intro.js in subsequent screens
<img width="1033" alt="Screenshot 2021-12-14 at 11 21 11" src="https://user-images.githubusercontent.com/59654112/145989018-841fe8d8-8e4a-48cb-a468-5fd2ff581fc4.png">

- [x] Add self-published bricks **by author** to assignment dropdown from manage classes

**Comment by ivanromakh** [comment]
@SashaScholar6 I don`t understand the first two points in this task.
