### ISSUE TITLE
Should not be able to assign unpublished bricks

### ISSUE THREAD

**Issue by scholar6admin** [Scholar-6/brillder#4161]
https://scholar6.zendesk.com/agent/tickets/553
As a teacher 
I should not be able to assign an unpublished brick to a class
in order to stop students seeing a hanging timer when clicking to a brick from the assignment email

- [x] stop displaying unpublished bricks in this drop down
![image](https://user-images.githubusercontent.com/58778078/149063605-5a7ddc14-1274-4475-b467-64229faa3cf4.png)

- [x] stop displaying unpublished bricks in the catalogue 'personal' tab and search (should only be visible in back to work until it is published)
![image](https://user-images.githubusercontent.com/58778078/149063775-6240983a-e9f9-4449-8d05-f8424c786697.png)

- [x] /bricks/byStatus/4 should not return status 1 bricks

**Comment by aromakh** [comment]
@scholar6admin it`s not possible.

**Comment by ivanromakh** [comment]
@aromakh this is a problem for personal bricks. byStatus/4 returns me status 1 brick.
![image](https://user-images.githubusercontent.com/18567511/149159454-5e10e280-241e-4db5-ae24-c04c77bde288.png)

**Comment by ivanromakh** [comment]
I added filter in front. last point for backend but not sure if needed.
