### ISSUE TITLE
Add Filter by Length

### ISSUE THREAD

**Issue by SashaScholar6** [Scholar-6/brillder#4162]
<img width="315" alt="Screenshot 2021-12-22 at 16 16 27" src="https://user-images.githubusercontent.com/59654112/147114433-4688e2b5-0b06-444d-a91c-7de5acc5dff4.png">

- [x] play dashboard (underneath Levels) : 20 mins, 40 mins, 60 mins
- [x] reduce margin under Sort by so the same as margin below Filter
- [x] filters are additive
- [x] reduce 'Sort By', 'Filter' and 'Subjects' to 1.5vw (not 1.8)

<img width="353" alt="Screenshot 2021-12-22 at 16 20 49" src="https://user-images.githubusercontent.com/59654112/147115013-8241deee-c847-4fb4-8ed5-5dfd4b1b3175.png">

- [x] back to work public published

- [x] make back to work published filters work like in dashboard, ie. default unselected shows all bricks, so that filters are additive and unselecting does not take you back to blank screen

![Screenshot 2021-12-29 at 14 42 55](https://user-images.githubusercontent.com/59654112/147668325-11ebea53-22be-48ce-8226-c57c22ea396a.png)

**Comment by ivanromakh** [comment]
@SashaScholar6 filters are addictive in play dashboard
![image](https://user-images.githubusercontent.com/18567511/147467980-f39fe81b-0a16-4c06-ad22-6273e80dcc26.png)

**Comment by SashaScholar6** [comment]
Should be radio buttons too

**Comment by ivanromakh** [comment]
Ok
