### ISSUE TITLE
Phone Play Fixes

### ISSUE THREAD

**Issue by SashaScholar6** [Scholar-6/brillder#4167]
![Screenshot 2021-12-23 at 17 23 26](https://user-images.githubusercontent.com/59654112/147267214-4a916cb8-307f-4b37-ba1e-3e073c3f8bbf.png)

- [x] add same padding above synthesis text as in open question
- [x] also same padding below text

![Screenshot 2021-12-23 at 17 24 18](https://user-images.githubusercontent.com/59654112/147267299-39c4a31f-12be-462e-af93-3064438c8b6b.png)

- [x] image attribution text should be tab gray
- [x] Scroll on  right text and icon should be on line above if no images present

![Screenshot 2021-12-23 at 17 25 11](https://user-images.githubusercontent.com/59654112/147267395-c23f49de-0d01-4706-ac0e-06fafb490c64.png)

- [x] zoom icon missing here (vertical shuffle w images

![Screenshot 2021-12-23 at 17 26 18](https://user-images.githubusercontent.com/59654112/147267517-40822e41-2061-415d-b1dd-20eb7b525ea4.png)
)

- [x] space above and below book before top and bottom bars should be the same (move book up)

- [x] attribution should not be cut off on right in synthesis images
- [x] this may be causing sidescroll, which also should not happen

- [x] make missing word line and dropdown bigger

**Comment by ivanromakh** [comment]
@SashaScholar6 what is image attribution?

**Comment by SashaScholar6** [comment]
Image attribution text, displayed on side of images

**Comment by ivanromakh** [comment]
@SashaScholar6 its cutting off because it is overflowing.
![image](https://user-images.githubusercontent.com/18567511/147945738-c4f8a16b-fef5-48c7-8240-c981269e68f7.png)
![image](https://user-images.githubusercontent.com/18567511/147945788-4387a31e-2c53-4c9b-a177-44fdf1d5d2e6.png)
