### ISSUE TITLE
Suggest and Edit Keywords

### ISSUE THREAD

**Issue by SashaScholar6** [Scholar-6/brillder#4186]
- [x] suggest keywords in build from published 
<img width="563" alt="Screenshot 2021-12-30 at 11 52 08" src="https://user-images.githubusercontent.com/59654112/147745465-de0472ee-ef11-41a0-b142-3acb851c9001.png">

- [x] only show public published keywords in dropdown suggestions

- [x] dropdown font brandon and dark blue
- [x] should bee in alphabetical order by default (ie if I just click panel)
- [x] remove dropshadow

- [x] admins can edit keywords from cover page (white editon icon leads to plan page)
<img width="697" alt="Screenshot 2021-12-30 at 11 52 34" src="https://user-images.githubusercontent.com/59654112/147745505-b5101542-21a3-4074-924f-d354d90bfc03.png">

**Comment by ivanromakh** [comment]
there are around 1500 keywords in database.

**Comment by ivanromakh** [comment]
@SashaScholar6 it is not possible to edit keywords from cover page. it will brake layout.
