### ISSUE TITLE
Make Play colours match phone

### ISSUE THREAD

**Issue by SashaScholar6** [Scholar-6/brillder#4189]
MOBILE
![Screenshot 2021-12-23 at 17 26 40](https://user-images.githubusercontent.com/59654112/147267549-1bf73c65-f8e9-4e45-80c1-e9da90979908.png)

- [x] hints should not overflow under categorise questions

<img width="1078" alt="Screenshot 2021-12-31 at 13 52 26" src="https://user-images.githubusercontent.com/59654112/147824422-7c21ad7e-f60e-429f-b0cf-3fa007b3d266.png">

- [x] number colours and rings like on mobile play
- [x] top and bottom bars light blue, **remove shadows**
- [x] with triangle under question I am currently on
- [x] prep button, selected numbers, next text and icon in white
- [x] progress bar dark blue background

<img width="960" alt="Screenshot 2022-01-03 at 12 57 30" src="https://user-images.githubusercontent.com/59654112/147927788-777e1c24-af53-49de-b281-9968e5f35a71.png">

- [x] overflow issue
- [x] make. default background of Hide Timer button dark blue

- [ ]synthesis top bar should be blue
<img width="162" alt="Screenshot 2022-01-03 at 13 03 09" src="https://user-images.githubusercontent.com/59654112/147928258-0e0dd1df-785e-4947-943a-768f592ce119.png">
 
- [x] fix white edges on top and bottom corners

**Comment by ivanromakh** [comment]
@SashaScholar6 I don`t think I will be able to fix corners it will probably break everything.

**Comment by ivanromakh** [comment]
@SashaScholar6 we probably need to rewrite it in order to remove that.
