### ISSUE TITLE
Fix Bullet point display bug

### ISSUE THREAD

**Issue by SashaScholar6** [Scholar-6/brillder#4195]
<img width="306" alt="Screenshot 2022-01-04 at 12 39 30" src="https://user-images.githubusercontent.com/59654112/148053704-3b923eac-39a6-459f-a407-e49439ce77f7.png">

**Comment by ivanromakh** [comment]
@SashaScholar6 could you provide brick id or url?

**Comment by ivanromakh** [comment]
@SashaScholar6 don`t see problem with bullets.
![image](https://user-images.githubusercontent.com/18567511/148074494-b71d454d-246c-4b47-9af7-cc4ab131721a.png)

**Comment by SashaScholar6** [comment]
907. Bizarrely fixed in production. Is it also ok in dev? Maybe deploy thing
