### ISSUE TITLE
Connection lost popup Sam

### ISSUE THREAD

**Issue by SashaScholar6** [Scholar-6/brillder#4210]
Possibly connected to Open Question character limit?
<img width="872" alt="Screenshot 2022-01-09 at 21 52 24" src="https://user-images.githubusercontent.com/59654112/148702487-aef828d0-3dcb-40fa-ba10-1091737207c6.png">

**Comment by ivanromakh** [comment]
@aromakh what is the limit for open question in database?
![image](https://user-images.githubusercontent.com/18567511/148744734-b4b7ddf5-af5f-4428-b744-1eba5f15d598.png)

**Comment by ivanromakh** [comment]
@SashaScholar6 you are right there is a limit to open question. it is not saving brick if it is too big.

**Comment by ivanromakh** [comment]
@SashaScholar6 @aromakh limit is probably 258 characters. so what should I do?
