### ISSUE TITLE
Update Play Layout to avoid bottom bar and overflow issues

### ISSUE THREAD

**Issue by SashaScholar6** [Scholar-6/brillder#4212]
- [x] desktop
- [x] iPad
- [x] synthesis bar should be blue with white text (might just be an issue on iPad)
- [x] triangles under numbers in review (might just be an issue on iPad)
- [x] also on provisional and final score pages

FINAL STEP
- [x] on final step, move results to a blue bottom bar
- [x] remove light grey area
- [x] move all icons on 1 line across instead of 2

IPAD
- [x] add italics text for iPad next to “Drag to rearrange” - horizontal shuffle, pair match and categorise. Icon is heroicons cursor-clickhttps://heroicons.com/ ; text: “Click and hold to move if using an Apple Pencil”
- [x] iPad: missing word and word and line highlighting text should be the same size as reeg text (bigger)

**Comment by ivanromakh** [comment]
@SashaScholar6 I don`t understand what text should be? “Drag to rearrange” or “Click and hold to move if using an Apple Pencil”

**Comment by ivanromakh** [comment]
@SashaScholar6 what should I do in provisional score page?

**Comment by ivanromakh** [comment]
@SashaScholar6 there are already 3 parts in categorize. not sure where to put fourth one.
![image](https://user-images.githubusercontent.com/18567511/148801644-99a9a207-1eeb-4961-bcd1-d4573dade60d.png)

**Comment by SashaScholar6** [comment]
zoom is only if there are images. those three could fit on top line in iPad, Apple pencil text could be on a second line.

**Comment by SashaScholar6** [comment]
@ivanromakh provisional score: update layout so as to remove white overlaps on corners

**Comment by ivanromakh** [comment]
@SashaScholar6 I don`t understand how it should look.
![image](https://user-images.githubusercontent.com/18567511/148928935-5627261f-0425-4cc0-9afd-f6a505165aec.png)
it will look different from provisional score page.
