### ISSUE TITLE
Share Class with another teacher

### ISSUE THREAD

**Issue by SashaScholar6** [Scholar-6/brillder#4218]
https://scholar6.zendesk.com/agent/tickets/606
Ticket left open for #4243 

<img width="863" alt="Screenshot 2022-01-11 at 11 57 38" src="https://user-images.githubusercontent.com/59654112/148938667-133cdee3-18a3-4c46-9f6f-837089f22f11.png">

- [x] white share icon in subject
- [x] popup to enter username or email (same style as invite user/editor
- [x] accept/reject

**Comment by ivanromakh** [comment]
@aromakh I need to get list of invitations?

**Comment by ivanromakh** [comment]
@aromakh there is no invitation for teachers.

**Comment by aromakh** [comment]
@ivanromakh 
![image](https://user-images.githubusercontent.com/7169477/149524953-0617a1b3-046d-4718-b8f2-8c2d20c03dec.png)
