### ISSUE TITLE
Paywall UI - DEV-MOBILE ONLY

### ISSUE THREAD

**Issue by SashaScholar6** [Scholar-6/brillder#4220]
- [x] Check that premium goes away if paid 

- [x] PUSH TO DEV-MOBILE ONLY

https://xd.adobe.com/view/d250acd9-a16b-4788-9ed8-9deae528b01e-8703/

HOME

- [x] go premium on home page
- [x] text goes green on hover and goes to Choose Plan page

COVER
- [x] cover image update assign popup with counter
- [x] text goes green on hover and goes to Choose Plan page

ONE PLAY ATTEMPT LEFT
- [x] popup
- [x] text goes green on hover and goes to Choose Plan page

NO FREE ASSIGNMENTS LEFT
- [x] go premium educators popup
- [x] button goes dark-blue on hover

NO PLAY ATTEMPTS LEFT
- [x] go premium learners popup
- [x] button goes dark-blue on hover

MANAGE CLASSES
- [x] white on sidebar 10-1 free Assignments left
- [x] popup
<img width="404" alt="Screenshot 2022-01-11 at 14 59 37" src="https://user-images.githubusercontent.com/59654112/148966663-a4df221b-994d-4f42-b587-1baae330e4b8.png">

- [x] amber when no free assignment
<img width="396" alt="Screenshot 2022-01-11 at 14 59 49" src="https://user-images.githubusercontent.com/59654112/148966717-f0cdd9cc-6d3c-43f2-bf19-e73663b0d173.png">

- [x] go premium educators popup

CHOOSE PREMIUM PLAN

- [x] heroicons academic-cap: https://heroicons.com/

**Comment by SashaScholar6** [comment]
Nice. What about the create a new class option?

**Comment by ivanromakh** [comment]
@SashaScholar6 it should redirect to manage classes page?

**Comment by SashaScholar6** [comment]
No it should be the same as before when there were two radio buttons at the top of popup (see production if no longer on dev)

**Comment by ivanromakh** [comment]
@SashaScholar6 ok added.
![image](https://user-images.githubusercontent.com/18567511/149353352-5e4a566c-3d57-4142-967f-2f6a44d5ed59.png)

**Comment by ivanromakh** [comment]
![image](https://user-images.githubusercontent.com/18567511/149353436-f28c587e-2826-4a22-95b4-386714dd925a.png)

**Comment by ivanromakh** [comment]
Educators popup.
![image](https://user-images.githubusercontent.com/18567511/149506722-b6d3f07c-0052-40ce-b3f3-edaf7f40facd.png)

**Comment by SashaScholar6** [comment]
Nice :)
