### ISSUE TITLE
Cannot set a user as institution preference

### ISSUE THREAD

**Issue by scholar6admin** [Scholar-6/brillder#4232]
As an admin user 
When I try to set brilliantmindsprizes@scholar6.org to be an institution user
It does not update the profile

The dev tools says 501
![image](https://user-images.githubusercontent.com/58778078/149525110-5d46f46a-ed29-45f5-a6ec-030afa6c1b34.png)

The follow on task from this is to confirm whether there is a way to play a competition brick without taking part in the competition

**Comment by ivanromakh** [comment]
@scholar6admin institution preference was removed in backend side. https://github.com/Scholar-6/brillder-backend/blob/master/src/entity/UserPreference.ts
