### ISSUE TITLE
Automated email button when publishing brick

### ISSUE THREAD

**Issue by scholar6admin** [Scholar-6/brillder#4236]
As a publisher
When I publish a brick
Then I want to be able to choose whether to email users who have that subject in their profile

Interesting Idea
Subscribe to a tag
Add email notification settings to profile
Also consider in-app notification

<img width="463" alt="Screenshot 2022-02-01 at 10 32 46" src="https://user-images.githubusercontent.com/59654112/151952983-5e8429ba-cbb7-4595-ab74-4a8a70c209cd.png">

- [ ] currently showing author name instead of [First Name]

**Comment by william-gooch** [comment]
@SashaScholar6 I think I need to know what template this email should use. If it doesn't use any of the existing ones then I'll need to get a design for the new one.

**Comment by SashaScholar6** [comment]
@william-gooch template added. Cover image should be clickable

**Comment by scholar6admin** [comment]
This is done
