### ISSUE TITLE
Share Class: show who shared the class

### ISSUE THREAD

**Issue by SashaScholar6** [Scholar-6/brillder#4239]
- [x] I can still see surnames coming from the backend (testing as an educator) when searching for teachers to share classrooms with.
![image](https://user-images.githubusercontent.com/58778078/154339584-eb1996ca-9e53-49be-b6cf-f8b16ed867d1.png)
![image](https://user-images.githubusercontent.com/58778078/154339615-6e903e7b-4cc7-4ba1-bd1c-d14d1b43e2e6.png)

- [x] I did not tick the box to share photo when uploading profile image but still showing profile picture in another users search when they are looking for teachers to share classroom with
![image](https://user-images.githubusercontent.com/58778078/154341012-010f4e81-f893-48fb-b358-d718acb334f0.png)

<img width="535" alt="Screenshot 2022-01-18 at 12 23 14" src="https://user-images.githubusercontent.com/59654112/149936929-d4dbdf1f-6ed7-4089-8bee-968d912959b8.png">

- [x] so Ivan can show 'sent by Name Surname´ popup from the teacher sharing the class to the teacher accepting the shared class

request is GET /classrooms/teachInvitations
need firstName and lastName in resulting objects in array and probably profileImage.

https://scholar6.zendesk.com/agent/tickets/606

**Comment by ivanromakh** [comment]
Yep you will see more usernames coming from backend I am filtering them by teacher preference in front.

**Comment by ivanromakh** [comment]
seems like we need update our backend file controller to hide images which should be hidden.

**Comment by ivanromakh** [comment]
@SashaScholar6 second part of this task was already done by someone.
![image](https://user-images.githubusercontent.com/18567511/159450203-7559b9e5-68dd-4a49-81dd-8f021c1b3d26.png)
