### ISSUE TITLE
Share Class fixes

### ISSUE THREAD

**Issue by SashaScholar6** [Scholar-6/brillder#4243]
https://scholar6.zendesk.com/agent/tickets/606

- [x] remove surname - only show username
- [x] #4244
- [x] Picture upload popup/checkboxes (@aromakh need boolean variable in user for it. to switch public/private image) (database)

**Comment by ivanromakh** [comment]
@SashaScholar6 we have generalized element. It will remove surname everywhere in autocomplete popups.

**Comment by SashaScholar6** [comment]
@lindsaymacvean please advise. @ivanromakh I think we should probably separate the component as they serve different functions in Build vs Manage Classes. How hard would that be?

**Comment by ivanromakh** [comment]
@SashaScholar6 it should be like this or hide first name too?
![image](https://user-images.githubusercontent.com/18567511/150347634-93b85925-a467-4edc-93fa-2983593cb4f1.png)

**Comment by ivanromakh** [comment]
@SashaScholar6 can`t do second points don`t have that information.

**Comment by SashaScholar6** [comment]
You can't get it from manage users?

**Comment by ivanromakh** [comment]
@SashaScholar6 manage users is only for admins.
