### ISSUE TITLE
Mobile popup 1 attempt left

### ISSUE THREAD

**Issue by ivanromakh** [Scholar-6/brillder#4252]
![image](https://user-images.githubusercontent.com/18567511/150774063-b525589f-abf6-4e7a-b5d2-bdff7654afc5.png)
![image](https://user-images.githubusercontent.com/18567511/150775450-740cf86b-296b-4ff9-9a3c-d43446735262.png)
![image](https://user-images.githubusercontent.com/18567511/150778432-38896950-84ff-462b-b19a-33a23f2f1c06.png)
![image](https://user-images.githubusercontent.com/18567511/150783820-99a24b73-a8ca-4ce4-be29-1fcb906d0219.png)

**Comment by ivanromakh** [comment]
![image](https://user-images.githubusercontent.com/18567511/150775386-b1705b08-f0e4-40d3-9169-b92ad36c8dd0.png)

**Comment by ivanromakh** [comment]
scrollabel page.
![image](https://user-images.githubusercontent.com/18567511/150778198-85056f44-c263-4940-a3af-acfc30d44465.png)

**Comment by SashaScholar6** [comment]
Nice, much better

**Comment by ivanromakh** [comment]
![image](https://user-images.githubusercontent.com/18567511/150781460-2b1f8e35-9b69-4cd4-b91a-8141699e972c.png)

**Comment by SashaScholar6** [comment]
More padding around entry fields, and bigger font for agree and subscribe

**Comment by ivanromakh** [comment]
![image](https://user-images.githubusercontent.com/18567511/150788715-62f07232-5a2c-472f-9fc3-8323d9b63d14.png)
