### ISSUE TITLE
Vertical and Horizontal Shuffle Review Bug (Each answer hints)

### ISSUE THREAD

**Issue by SashaScholar6** [Scholar-6/brillder#4255]
Let's say answer is 

A 
B 
C 
D

Each answer has a hint.

I put down

A
B
D
C

Then I switch D and B in review, hint will show as grey with green tick for D now.

EG Question 7 from brick below:
I was trying out this vertical shuffle question and wondering if we could improve the use of green tick/orange hints on this type of question (it also goes for horizontal shuffle).

Currently you get a green tick next to the position (say, 3) that was correct the first time. But this gets confusing for the student when they reshuffle during the review process (which they inevitably will), as the tick remains in position 3 regardless of the item that is now there after reshuffling. Effectively you get a tick next to an incorrect answer.

I'm not sure if it would be better for the tick to just disappear when the student reshuffles. Or is there a better solution? I think ideally the correct answer would remain "stuck" in place, and the reshuffle would take place around it. Could this happen?

Feel free to ask me to explain if any of this didn't make sense.

------------------
Submitted from: https://app.brillder.com/play-preview/brick/1091/review

**Comment by ivanromakh** [comment]
@SashaScholar6 this is impossible if you answered A B C D then it is correct and you can`t switch them in review.

**Comment by ivanromakh** [comment]
@SashaScholar6 I can try to stack correct answers but it will make harder to shuffle wrong ones. so what I should do.
