### ISSUE TITLE
Fix number of assignments and classes in Manage Classes

### ISSUE THREAD

**Issue by SashaScholar6** [Scholar-6/brillder#4270]
<img width="504" alt="Screenshot 2022-01-28 at 12 41 44" src="https://user-images.githubusercontent.com/59654112/151548859-bdd9c0c8-6748-4d21-89d0-23f253f73ba4.png">

- [x] Add new Icon for number of classes, and show number of assignments on right

<img width="352" alt="Screenshot 2022-01-28 at 12 42 15" src="https://user-images.githubusercontent.com/59654112/151548927-41efd657-c628-4a1d-8569-977ce4589372.png">

- [x] add button to alphabetise classes - feather down and up for A-Z and Z-A (showing letters in brandon bold)
- [x] these white icons become blue on hover
- [x] tooltips: 'Sort Alphabetically: A-Z' 'Sort Alphabetically: Z-A', 'Sort by ascending number of assignments', 'Sort by descending number of assignments'
- [x] tab grey background for new view classes area

- [x] fix alphabetical case issue in sidebar

- [x] in class show students by alphabetical surname by default

<img width="359" alt="Screenshot 2022-02-03 at 12 47 28" src="https://user-images.githubusercontent.com/59654112/152345678-168da6b7-541d-412f-a0b7-cdf9078ea66f.png">

- [x] copy same view all classes info and styling from assignments tab
- [x] top show say [X] Learners in [Y] Classes

- [x] put number of classes icon on left with manage classes icon in white
- [x] tooltips should be bold and dark blue

- [x] CLASSES to Classes in Learner tab
- [x] 'View All Learners”

<img width="397" alt="Screenshot 2022-02-04 at 14 40 25" src="https://user-images.githubusercontent.com/59654112/152547872-a1a7c22a-12a6-4314-a499-9e8783929950.png">

- [x] classes icon should be blue with tab gray glasses when gray

<img width="371" alt="Screenshot 2022-02-04 at 14 40 18" src="https://user-images.githubusercontent.com/59654112/152547875-9cb5c995-f0b9-465f-8c8c-6f593fe1a1d2.png">

- [x] student number should be blu when background grey

**Comment by ivanromakh** [comment]
@SashaScholar6 its total number. archived included.

**Comment by ivanromakh** [comment]
@SashaScholar6 there is 255 assigned bricks not 95
