### ISSUE TITLE
Fix size and height of libraries in iPad overflow

### ISSUE THREAD

**Issue by SashaScholar6** [Scholar-6/brillder#4271]
Eg Florence Milner in Brilliant Minds prizes

- [x] shelves and books should be smaller, so 3 rows fit
- [x] font of subjects should be bigger
- [x] font of 'FILTER' in sidebar should be Cambel case, same size as 'Sort By'

- [x] include dark blue level strips in zoomed out library for general and topical bricks
- [x] fix competition star in expanded subject view
- [x] make sor by and filter font bigger

**Comment by ivanromakh** [comment]
@SashaScholar6 which user has 3 rows in my-library?
