### ISSUE TITLE
Teacher@scholar6 account inconsisent

### ISSUE THREAD

**Issue by SashaScholar6** [Scholar-6/brillder#4272]
- [x] In Profile, says I am on Free trial, but go premium options has disappeared from home screen

- [ ] When I try to assign, it says I have no free assignments left, but when I click assign nothing happens
- [x] if I am still a free user, I should see an upgrade popup 
- [ ] if I am paying, it should not show me number of free assignments left or option to go premium, and I should be able to assign to classes and see normal popup of 'Brick X has been assigned to Class Y'

**Comment by ivanromakh** [comment]
@SashaScholar6 after you try to subscribe twice payment system will be broken.
