### ISSUE TITLE
Student can't load assignment from teacher

### ISSUE THREAD

**Issue by SashaScholar6** [Scholar-6/brillder#4286]
paige  10 minutes ago
it isnt loading so cant get on the work my teachers sent me

------------------
Submitted from: https://app.brillder.com/play/brick/690/cover/english-literature/romeo-and-juliet-the-prologue

 17-startup-p@shireoakacademy.co.uk

**Comment by ivanromakh** [comment]
@SashaScholar6 this was fixed but not released yet.

**Comment by ivanromakh** [comment]
@SashaScholar6 cover page isn`t working on for unauthorized users.
