### ISSUE TITLE
Problem setting to students

### ISSUE THREAD

**Issue by SashaScholar6** [Scholar-6/brillder#4287]
Jo Turner  20 minutes ago
Do the people you share a brick with need to have an account with Brillder? Only, I shared a link and none of my learners could see the page properly on any browser. It only opened properly for me once I have signed in to my account and then used the link.

------------------
Submitted from: https://app.brillder.com/home

joanna.turner@nelsongroup.ac.uk

**Comment by ivanromakh** [comment]
let me check

**Comment by ivanromakh** [comment]
@SashaScholar6 it is fixed but not released yet to production.
