### ISSUE TITLE
referralId

### ISSUE THREAD

**Issue by scholar6admin** [Scholar-6/brillder#4295]
- [x] can we use the usernames as referralIds
- [x] Need to review with Lindsay

- [x] ReferralId is empty on this new student user
![image](https://user-images.githubusercontent.com/58778078/153432313-8f7ff333-228b-4d57-b477-a5c2c9e96c89.png)

As a user
I should be able to share any page on Brillder with my referralId on the end
And this will track any new user who signs up using the link I shared

When user a shares a link
And user b subscribes
Then user a will get £5 kickback

- [x] Frontend router should check params for referralId on first page loaded. Store this until they signup with a new email. If they login just discard.
- [x] Email registration should trigger a call to an api endpoint
- [x] new table on backend.
- [x] Table should store two states registered vs subscribed.
- [x] Add referral id to share link from all bricks for all users.

![image](https://user-images.githubusercontent.com/58778078/152776415-a6a4f3bb-c9a1-4c90-8151-16eb82ce9c54.png)

**Comment by william-gooch** [comment]
@lindsaymacvean should the referral ID persist between reloads? As in, if they begin to sign up with a referral ID and then their browser refreshes, should the referral ID still be present?
