### ISSUE TITLE
Apply Code button

### ISSUE THREAD

**Issue by scholar6admin** [Scholar-6/brillder#4311]
- [x] If any other voucher than 'WELCOM50' is applied then 'cross out' the price, leave the monthly annual checkboxes if you have to. Write in a grey panel underneath 'Custom Pricing Applies.' with small letters underneath 'Please check your original email offer.'
![image](https://user-images.githubusercontent.com/58778078/153429377-6d41ea79-185d-48f9-b49e-109bcb3ba200.png)

- [x] Should be able to apply CTG1 code to get 100% discount for 3 months

![image](https://user-images.githubusercontent.com/58778078/152988296-64cba45e-3305-480e-bb37-ccc74e5b2ca6.png)

**Comment by ivanromakh** [comment]
@scholar6admin I checked stripe there is no such coupon in dev.

**Comment by ivanromakh** [comment]
@SashaScholar6  @lindsaymacvean  this is weird. welcome50 is coupon for 50% but here it is 58%
![image](https://user-images.githubusercontent.com/18567511/153386959-2e06340f-45b6-4ac2-b090-aa7e37cd4028.png)

**Comment by SashaScholar6** [comment]
because there is a further saving if purchasing subscription annually (12 month for the price of 10 pretty much)

**Comment by ivanromakh** [comment]
@lindsaymacvean CTG1 will look like this. with 3 month 100% discount annual save is 25% right?
![image](https://user-images.githubusercontent.com/18567511/153423492-9a8a147f-5830-47f0-934a-b2e44b379862.png)
