### ISSUE TITLE
If voucher code is 100% off forever then do not ask for credit card

### ISSUE THREAD

**Issue by scholar6admin** [Scholar-6/brillder#4319]
This is specifically for SELMS because we are giving them 20 free accounts forever (because they could bring us 1000's of users)

Coupon code for testing is SELMS

**Comment by ivanromakh** [comment]
@scholar6admin stripe don`t support payments without credit cards we will need to do it ourselves. I can hardcode coupon in backend side. Or we can create table coupons with free coupons.

**Comment by ivanromakh** [comment]
@scholar6admin @SashaScholar6 is it good?
![image](https://user-images.githubusercontent.com/18567511/153566880-3712b983-befe-4909-ab6e-c6c4f153c281.png)
