### ISSUE TITLE
Sara Hussin profile not showing subscriber status

### ISSUE THREAD

**Issue by SashaScholar6** [Scholar-6/brillder#4326]
<img width="1223" alt="Screenshot 2022-02-14 at 12 24 49" src="https://user-images.githubusercontent.com/59654112/153863926-940800aa-7ada-4e44-b7fb-521dd003ead1.png">

- [x] she is already premium, should not have option to go premium again
- [x] should not say “Free trial” but Premium Learner or Premium Educator
- [x] should be a sparkle next to username on all premium users

<img width="317" alt="Screenshot 2022-02-15 at 18 18 53" src="https://user-images.githubusercontent.com/59654112/154124229-d8252922-b719-4165-8d14-e409e69ddb30.png">

- [x] grey label should say 'learner' not student
- [x] check for any other instances of student and convert to learner if displayed

**Comment by ivanromakh** [comment]
did you check that profile as admin?

**Comment by ivanromakh** [comment]
I works only for current logged in user profile.

**Comment by ivanromakh** [comment]
@SashaScholar6 there is plural form in few cases
![image](https://user-images.githubusercontent.com/18567511/154230613-190da392-3406-4d72-8828-ef3a5e4fd77f.png)

**Comment by ivanromakh** [comment]
@SashaScholar6 there is Student placeholders.
'Student Name or Subject'

**Comment by ivanromakh** [comment]
@SashaScholar6 In buttons. '+ Invite Students'

**Comment by SashaScholar6** [comment]
Yes "student" should be "learner" for all users
