### ISSUE TITLE
Intro.js is too small on profile page

### ISSUE THREAD

**Issue by scholar6admin** [Scholar-6/brillder#4335]
- [x] Profile image is not right
![image](https://user-images.githubusercontent.com/58778078/154267613-b5de867c-a1f2-46f0-930e-242b76daadd2.png)

- [x] Final step css is thrown off
![image](https://user-images.githubusercontent.com/58778078/154267817-6b13e253-7c05-4964-9758-8a1d1849340a.png)

<img width="725" alt="Screenshot 2022-02-22 at 15 24 43" src="https://user-images.githubusercontent.com/59654112/155163835-a49f81ca-0b13-440f-8244-4f85e94be8b2.png">

- [x] fix text:  Educators will never be able to view Learner profile pictures without their consent.

When a Builder invites an editor to peer review their work, or an Educator wants to share a class with a colleague, pictures (of users who have not selected the Learner preference) can help them choose the right user and make interactions feel more personal. Do you consent to your picture appearing in both of these scenarios? 

<img width="688" alt="Screenshot 2022-02-23 at 16 27 37" src="https://user-images.githubusercontent.com/59654112/155362562-3294805b-49ff-4784-9faa-93b00a4bb158.png">

- [x] username is not highlighted
- [x] update text: Your username will be visible to others in public leaderboards should you wish to compete, or in dropdowns should another user want to share a brick or class with you.

- [x] When I click through to end of intro js and try to close window, it takes me to homepage instead of letting me stay on profile page to make any more edit

<img width="764" alt="Screenshot 2022-03-14 at 11 14 50" src="https://user-images.githubusercontent.com/59654112/158161266-d030d4f8-20fd-41a6-bbf6-8513022220ca.png">

- [x] update text: remove text in brackets '(of users...preference)'

- [x] update text: change last sentence to 'Check the box to consent to your picture being visible to fellow Educators.'

**Comment by ivanromakh** [comment]
@SashaScholar6 what is wrong with final step?

**Comment by SashaScholar6** [comment]
Buttons are touching, username and save button cut off

**Comment by ivanromakh** [comment]
@SashaScholar6 what do you mean by fix text?
