### ISSUE TITLE
Adapt must be hidden on competition Bricks

### ISSUE THREAD

**Issue by scholar6admin** [Scholar-6/brillder#4343]
- [x] When existing educator arrives at a brick and then signs in they should not see the adapt button
![image](https://user-images.githubusercontent.com/58778078/165737664-6692fb30-7ef2-4560-bea4-701d38b57867.png)

this can just be a frontend thing for the moment.

- [x] fix on ipad and phone
- [x] don't show adapt button on competition brick

(when query string don`t have competitionId after login to continue play)

**Comment by ivanromakh** [comment]
@SashaScholar6 what do you mean by fix on phone and ipad?
