### ISSUE TITLE
General and Topical bugs weird display

### ISSUE THREAD

**Issue by SashaScholar6** [Scholar-6/brillder#4355]
<img width="280" alt="Screenshot 2022-02-17 at 15 31 22" src="https://user-images.githubusercontent.com/59654112/154514734-4ea68de4-7db7-47b4-b277-82f66e615495.png">

- [x] fix small view - light blue with white star

<img width="552" alt="Screenshot 2022-02-17 at 15 31 33" src="https://user-images.githubusercontent.com/59654112/154514774-47f2c9e9-9405-416a-a6bd-99be00b29bc6.png">

- [x] fix big view

- [x] can't read text on mobile (make dark blue probably)

- [ ] different svg for 40 and 60 min bricks

**Comment by ivanromakh** [comment]
@SashaScholar6 so what I should fix here? I need more details.

**Comment by SashaScholar6** [comment]
Competition star and mobile view
