### ISSUE TITLE
Different percentage score text

### ISSUE THREAD

**Issue by SashaScholar6** [Scholar-6/brillder#4363]
- [x] same text in provisional score page
- [x] text in provisional score page should be italic also
- [x] move percentage ring a little further from text
- [x] cleaner B logo in brill icon

- [x] 95+= Superlative !
- [x] 90+ = Most excellent !
- [x] 85+= Excellent!
- [x] 80+ = Admirable!
- [x] 75+= Commendable!
- [x] 70+ = Respectable!
- [x] 65+ = Decent!
- [x] 60+ = Half decent!
- [x] 55+ = Something to build on!
- [x] 50+ = Room for improvement!
- [x] 45+ = Just missing the pass mark!
- [x] 40+ = Tough going!
- [x] 35+ = Very tough going!
- [x] 30+ = Ouch!
- [x] 25+ = Yikes!
- [x] 20+ = Call a brain ambulance!
- [x] 15+ = You weren't even trying
- [x] 10+ = A monkey typing randomly would do better than that!
- [x] 5+ = Almost hard to do this badly - congratulations?
- [x] 0+ = You have a genius, but just not for this brick!

**Comment by ivanromakh** [comment]
@SashaScholar6 this is in the end of review. Right?
