### ISSUE TITLE
Brick Credit system

### ISSUE THREAD

**Issue by scholar6admin** [Scholar-6/brillder#4369]
- [x] Please refactor the SUBSCRIPTION_FREE_ATTEMPTS to become the number of brick play credits that a new user gets when they sign up. 

- [x] Alter the brickAttemptCount in the subscription table so that it is actually keeps track of the play credits. 

- [x] when investigation play attempt is submitted check if user has scored more than 50% in a previous play attempt otherwise subtracts 1 credit. Once you score 50% on a Brick it costs 0 credits to play (its free). If no credits return message 'NO CREDITS' 402

- [x] Every time Stripe charges the card with a subscription deposit more brick credits to subscription table (student/teacher monthly gets 5 credits, student/teacher yearly gets 60)

# Exceptions

- [x] If entering a competition play it costs 2 credits

- [x] If teacher assigns Brick then it does not cost a Credit to the student

- [x] If you are the author of the Brick then it does not cost a credit.

We will do the payment system to buy top up credits (without a subscription) in another task.

@SashaScholar6 
Credit notificaiton:
1. Credit used to play a brick
2. Buy credits
3. Credits given for monthly/yearly payment
4. Brills converted to credits

**Comment by aromakh** [comment]
@scholar6admin
What if user started attempt, but do not finish?
Credit is used, and lost?

There will not be any way to continue, and user will not get any brills, as brick attempt is not completed.

**Comment by aromakh** [comment]
@scholar6admin @SashaScholar6 
Do we need any notification?
