### ISSUE TITLE
Auth users: Show number of credits remaining on the brick cover page

### ISSUE THREAD

**Issue by SashaScholar6** [Scholar-6/brillder#4371]
<img width="523" alt="Screenshot 2022-02-22 at 12 47 35" src="https://user-images.githubusercontent.com/59654112/155135327-14c699d9-9824-47ee-91f5-389afc8cf52d.png">

- [x] on hover, number of credits (eg.3) becomes feather-play icon

**Comment by ivanromakh** [comment]
@SashaScholar6 you mean show number of brills?

**Comment by SashaScholar6** [comment]
No this is credits (which are worth 100 brills), but we'll clarify tomorrow with @aromakh and @lindsaymacvean
