### ISSUE TITLE
If I get a question completely correct, block ability to change answer in review

### ISSUE THREAD

**Issue by SashaScholar6** [Scholar-6/brillder#4372]
- [x] short answer
- [x] choose one
- [x] choose several
- [x] pair match
- [x] categorise
- [x] horizontal shuffle
- [x] vertical shuffle
- [x] missing woord
- [x] word highlighting
- [x] line highlighting

- [x] including when going back and forth between different questions - pair match and word and line highlighting should stay green if all correct

**Comment by ivanromakh** [comment]
@SashaScholar6 I tried its disabled if answer is correct in review.
