### ISSUE TITLE
A New High Score!

### ISSUE THREAD

**Issue by SashaScholar6** [Scholar-6/brillder#4381]
<img width="1582" alt="Screenshot 2022-02-23 at 13 46 19" src="https://user-images.githubusercontent.com/59654112/155331689-e2a475bf-ab72-4684-97da-3f0e31cf5706.png">
 
This is the second time I am playing this brick.

<img width="922" alt="Screenshot 2022-02-23 at 14 00 32" src="https://user-images.githubusercontent.com/59654112/155334164-9b640aa2-c785-4111-bea8-94c33e161aff.png">

For High Score, play 'School Pride' animation

- [x] https://www.kirilv.com/canvas-confetti/
colours: theme-green, blue (0681db), amber (ffd900)

For 100% in Investigation, play 'Fireworks' animation

- [x] colours: theme-green, blue (0681db)

- [x] brill earned difference waiting on @aromakh 

- [x]  only show 'A New High Score' text if over 50 (and therefore with confetti also)

**Comment by ivanromakh** [comment]
@SashaScholar6 unauthorized users will always see confetti.
