### ISSUE TITLE
Unauth should go back to review after signing up

### ISSUE THREAD

**Issue by SashaScholar6** [Scholar-6/brillder#4393]
<img width="1439" alt="Screenshot 2022-02-28 at 16 41 29" src="https://user-images.githubusercontent.com/59654112/156022458-df70fda6-db5f-4c97-a02e-346c4f03370a.png">

- [x] if I click exit from final score page, I get taken to login screen

<img width="1261" alt="Screenshot 2022-02-28 at 16 41 06" src="https://user-images.githubusercontent.com/59654112/156022396-70dd7501-e1b6-40b8-bf5b-67558ad813a7.png">

- [x] can't exit from more options page

**Comment by ivanromakh** [comment]
@SashaScholar6 there is exit button in the footer.

**Comment by SashaScholar6** [comment]
Yes, when I clicked yesterday it didn't go anywhere
