### ISSUE TITLE
Brill notifications

### ISSUE THREAD

**Issue by SashaScholar6** [Scholar-6/brillder#4394]
- [x] You earned [X] brills! (bold)
Well done on improving your score on ‘[Brick Title]’.

- [x] round number of brills

- [x] Brill icon in Notification

**Comment by ivanromakh** [comment]
@SashaScholar6 
![image](https://user-images.githubusercontent.com/18567511/156155593-a39b4132-191d-468e-b0e1-5bce24856b2c.png)
