### ISSUE TITLE
Score calculation bug

### ISSUE THREAD

**Issue by SashaScholar6** [Scholar-6/brillder#4396]
<img width="1425" alt="Screenshot 2022-03-01 at 11 04 02" src="https://user-images.githubusercontent.com/59654112/156157875-74d43afd-5e85-41cd-93c5-d31a8bbec7f3.png">

I got 93 previous high score then 100 in next attempt investigation

- [x] make sure previous high score is best final score not best review score @ivanromakh

**Comment by aromakh** [comment]
@ivanromakh 
Added rounding,
Let me know if it works after deploymet.
