### ISSUE TITLE
Play sounds

### ISSUE THREAD

**Issue by SashaScholar6** [Scholar-6/brillder#4401]
https://mixkit.co/free-sound-effects/drum/

- [x] normal click: Old camera shutter
- [x] pre-investiagtion timer: Ominous drums
- [x] pre-review timer: Ominous drums appear
- [x] Brills earned: Magical coin win

- [x] coin win on phone page with spinning coin

- [x] Final score: deep cinematic subtle drums
- [x] sci-fi sweep for sections, pre-investigation, pre-synthesis and pre-review

- [x] In Desktop dashboard: next to brills - dark blue circle with white volume icon
- [x] In Desktop Live brick: round button to turn off sounds in middle of dark blue side are, with feather volume and volume off icons
- [x] tooltips on both: Mute sounds / Enable sounds
- [x] shutter click for first few pages before investigation
<img width="772" alt="Screenshot 2022-03-02 at 16 51 34" src="https://user-images.githubusercontent.com/59654112/156408912-8f4742e5-c02e-4488-bdfe-c904a00f963d.png">

- [x] fix white line overflow in first few screens

- [x] enable or disable sounds via three dots menu in phone

UPDATES

- [x] remove shutter click everywhere
- [x] Investigation timer - replace ominous drums with Horror deep drum heartbeat https://mixkit.co/free-sound-effects/heartbeat/
- [x] Review timer - replace Ominous drums appear with Hard horror hit drum

**Comment by ivanromakh** [comment]
@SashaScholar6 last one is very quiet

**Comment by ivanromakh** [comment]
@SashaScholar6 it will only mute site sounds not youtube and play sound answers right?

**Comment by SashaScholar6** [comment]
Yes correct
