### ISSUE TITLE
Brill fixes frontend

### ISSUE THREAD

**Issue by SashaScholar6** [Scholar-6/brillder#4406]
- [x] @ivanromakh Home page did not update immediately with more brills
- [x] animation for new brills - numbers animation same as score, coin spins once
![image](https://user-images.githubusercontent.com/58778078/156229369-2a09ea03-6532-4448-a39e-b42b8107c941.png)

- [x] @ivanromakh publisher does not see brills?

**Comment by ivanromakh** [comment]
@SashaScholar6 my new publisher user can see brills.

**Comment by ivanromakh** [comment]
@SashaScholar6 what do you mean by this? 'cached questions and jumped straight'
