### ISSUE TITLE
Sign in with Google does not take me back to brick

### ISSUE THREAD

**Issue by SashaScholar6** [Scholar-6/brillder#4423]
<img width="453" alt="Screenshot 2022-03-08 at 08 29 15" src="https://user-images.githubusercontent.com/59654112/157197299-0b8ab397-fa51-4c99-aab1-a00326666d3c.png">

- [x] desktop
- [x] mobile

**Comment by ivanromakh** [comment]
@SashaScholar6 I tried it and it is resuming brick after filling name and some data

**Comment by ivanromakh** [comment]
not sure what the problem is?
