### ISSUE TITLE
Tessa #637: Ability to flip content in pair match?

### ISSUE THREAD

**Issue by SashaScholar6** [Scholar-6/brillder#4425]
Is there any way that we could create a function to be able to flip the images from one side of the pair match to the other? This could save quite a lot of time in some circumstances.

------------------
Submitted from: https://app.brillder.com/build/brick/1095/investigation/question-component/238954

- [x] move sound icon below jpeg icon, so pairs get taller
- [x] add button in bottom right of right column with 'move' icon (showing users they can drag)
- [x] between each pair, add a circle with switch-horizontal hero icon

**Comment by ivanromakh** [comment]
@SashaScholar6 What do you mean by flipping images?

**Comment by ivanromakh** [comment]
@SashaScholar6 sounds in build are overflowing.
