### ISSUE TITLE
Library overflowing

### ISSUE THREAD

**Issue by SashaScholar6** [Scholar-6/brillder#4435]
<img width="1150" alt="Screenshot 2022-03-15 at 09 30 44" src="https://user-images.githubusercontent.com/59654112/158348054-ce53f319-bdb0-4563-8497-7d6bbfd7ff5b.png">

- [x] add pagination after three rows

**Comment by ivanromakh** [comment]
@SashaScholar6 I need user credentials I don`t have user with so many attempts.

**Comment by ivanromakh** [comment]
@SashaScholar6 should I make it scrollable from top to bottom?
