### ISSUE TITLE
Toby #643 - Adapt bug

### ISSUE THREAD

**Issue by SashaScholar6** [Scholar-6/brillder#4451]
https://scholar6.zendesk.com/agent/tickets/643

I've adapted an old brick (258) and when I go to the synthesis on the build side, I get a white screen. All other panels worked fine. This adapted brick is 1194.

------------------
Submitted from: https://app.brillder.com/build/brick/1194/synthesis

**Comment by ivanromakh** [comment]
@SashaScholar6 that brick is probably too old. problem happening inside Quill.

**Comment by william-gooch** [comment]
This seems to not give me any problems now. Even adapting the original brick (258) worked fine for me.

**Comment by s-steddy** [comment]
Testing and looks like this was taken care of. Moving to deploy.
