### ISSUE TITLE
Toby #498: Choose Several caption issue

### ISSUE THREAD

**Issue by SashaScholar6** [Scholar-6/brillder#4458]
on choose several, if an image and too much text is used, it appears that the text cannot be edited

------------------
Submitted from: https://dev-app.brillder.com/build/brick/913/investigation/question-component/237542

- [x] panel shpuld extend to fit caption in work area

<img width="640" alt="Screenshot 2022-03-21 at 13 06 23" src="https://user-images.githubusercontent.com/59654112/159266968-3938f3e1-cc85-4d4d-b49e-84624495c342.png">

**Comment by ivanromakh** [comment]
I added overflow with three dots there.

**Comment by ivanromakh** [comment]
![image](https://user-images.githubusercontent.com/18567511/159748883-feef5a33-b31e-446a-95b5-a322fe745bb6.png)
