### ISSUE TITLE
book showing 0% if only investigation completed

### ISSUE THREAD

**Issue by scholar6admin** [Scholar-6/brillder#4469]
![image](https://user-images.githubusercontent.com/58778078/161531635-2ec812c1-d1ba-40e4-ad66-a4aa48d074ae.png)

- [x] In the all Book view it is showing 0% on the hover instead of the actual score (e.g. 30%)

![image](https://user-images.githubusercontent.com/58778078/161531646-0b8ca1f7-e1cf-4133-bd2a-91c0579a56f4.png)

- [x] In the specific subject area it shows 5% instead of the actual score (e.g. 30%)

**Comment by ivanromakh** [comment]
@scholar6admin I can`t reproduce it. need more details.

**Comment by ivanromakh** [comment]
I got 36% and 36% it is in that brick.
![image](https://user-images.githubusercontent.com/18567511/161535792-d0fdd63a-55f7-4734-ba97-fb566c1d1c86.png)

**Comment by ivanromakh** [comment]
@scholar6admin this is backend task trying to figure it out.
