### ISSUE TITLE
Play again from book is caching the starting question

### ISSUE THREAD

**Issue by scholar6admin** [Scholar-6/brillder#4473]
![image](https://user-images.githubusercontent.com/58778078/161538300-2d6d0d28-990b-4205-87c5-27ac8c87c005.png)

- [ ] When playing again from the book it takes me to the 4th/last question instead of the first one

**Comment by ivanromakh** [comment]
@scholar6admin I tried but it goes to cover page and on cover page cash is cleared. So you need to tell me where that play again button is so I can cash it on action.
