### ISSUE TITLE
Credits popup

### ISSUE THREAD

**Issue by SashaScholar6** [Scholar-6/brillder#4476]
<img width="1054" alt="Screenshot 2022-04-05 at 10 12 05" src="https://user-images.githubusercontent.com/59654112/161720867-ea328af5-f4bd-48d6-9176-c54114e9cbee.png">

- [x] If the user clicks off the popup and clicks play (without any credits) then the popup should open again

- [x] alert triangle should be white in red circle

- [x] this circle should be above message

- [x] Text smaller, and says 'Oh no! You are out of credits’

- [x] Add brill icon (high res) inside convert brills to credits button

- [x] convert button grey by default, blue text

- [x] double check mobile view

- [x] popup to confirm converting brills:

“To play this brick, you will need to convert 100 brills into 1 credit”

OR (in case of competition)

“To enter this competition, you will need to convert 200 brills into 2 credits”

Button: Convert and Start Playing

- [x] Popup should have an 'x' to exit, with same styling as on other popups

**Comment by ivanromakh** [comment]
@SashaScholar6 If I add icon in that button we will probably need to cut text.
![image](https://user-images.githubusercontent.com/18567511/161734056-e24b2785-935b-49e5-892d-3b8ea0d8e3fb.png)

**Comment by ivanromakh** [comment]
@SashaScholar6 
![image](https://user-images.githubusercontent.com/18567511/161735963-17c16301-0dbe-4be6-bdc9-b86c943a40df.png)
