### ISSUE TITLE
add credit total on desktop app home page

### ISSUE THREAD

**Issue by scholar6admin** [Scholar-6/brillder#4478]
![image](https://user-images.githubusercontent.com/58778078/161724385-ee9770b3-12dd-4dd1-9340-e459faa54ce2.png)

- [x] **also on view profile page, between brills and view library button**
HERE
<img width="1920" alt="Screenshot 2022-05-06 at 11 30 58" src="https://user-images.githubusercontent.com/59654112/167115365-4e68e96a-b4fe-4f13-9773-18d04e37dbe1.png">

- [x] double check mobile OK

<img width="394" alt="Screenshot 2022-04-06 at 11 33 38" src="https://user-images.githubusercontent.com/59654112/161956083-647f003c-81a1-4056-bf83-95683096b213.png">

<img width="408" alt="Screenshot 2022-04-06 at 11 34 38" src="https://user-images.githubusercontent.com/59654112/161956235-a29fe32f-4688-455c-afc4-b4b35079f361.png">

- [x] when I click to expand three dots, three dots disappear (because of width it seems)

**Comment by ivanromakh** [comment]
@SashaScholar6 like this?
![image](https://user-images.githubusercontent.com/18567511/161918067-d6b4fd3a-8caf-4c37-925d-639ece637df3.png)

**Comment by SashaScholar6** [comment]
Between brills and bell, extending light blue area.

**Comment by ivanromakh** [comment]
@SashaScholar6  Are you sure? Task says between between brills and view library button

**Comment by ivanromakh** [comment]
I see

**Comment by ivanromakh** [comment]
I don`t see view library button in profile page,

**Comment by ivanromakh** [comment]
@scholar6admin done. what should I do in profile page?
![image](https://user-images.githubusercontent.com/18567511/161935813-c3670cdc-0446-4eef-b01c-d0c67ae5c180.png)

**Comment by scholar6admin** [comment]
I just want the same on the profile page.

**Comment by ivanromakh** [comment]
@SashaScholar6 what is wrong?
