### ISSUE TITLE
Library Integration UI

### ISSUE THREAD

**Issue by scholar6admin** [Scholar-6/brillder#4485]
- [x] intro.js if url contains ?origin=library (see Sasha for exact details)

First panel (homepage): We offer free accounts to participating UK libraries.  Link your account at the end of this tutorial.

Last panel (manage account page): Link your library account by filling in your details below.

- [x] Better labelling to make sure autofill works properly
- [x] Add a help icon that reads 'If you belong to a participating Library.'
- [x] Button should say 'Link to Library'
- [x] If successful authentication then replace button with red button 'Unlink from Library'
- [x] Need to make it work on a mobile screen.
- [x] Library authority box 'placeholder' is 'Library Authority'
- [x] Pin 'placeholder' is 'Library Pin'
- [x] 'Current Plan' should say 'Library User'
- [x] Boxes should be prefilled if user already has a Library connection
- [x] If error from backend then popup 'Those details were not recognised, please contact support@scholar6.org for help.'
- [x] Library endpoint should be rechecked everytime new log in to check that their Library account hasnt gone out of date
- [x] Make sure UI is visible to all users (not just admins)
- [x] Design and text should be as follows
![image](https://user-images.githubusercontent.com/58778078/162407301-ecc14ac6-9141-47a4-ae73-61af8c205388.png)

- [x] If 'Other' selected as region then hide library card number and pin and instead show text input to send email to admin@brillder.com and sam@brillder.com with the library they are interested in.
- [x] If successful then popup says 'You successfully connected to your Library. You can now play for free. Competitions will still require paid credits.'
- [x] If not successful 'That did not work. Please try again, or select "other" and suggest a Library and we will check if they have a partnership scheme with Brillder.'

**Comment by ivanromakh** [comment]
@SashaScholar6 phone.
![image](https://user-images.githubusercontent.com/18567511/164416661-8c21a991-1169-4dae-a706-851ea79b3e34.png)
