### ISSUE TITLE
Notification: cancellation of subscription

### ISSUE THREAD

**Issue by scholar6admin** [Scholar-6/brillder#4488]
If subscription is cancelled in stripe then the user should receive a notification

"Your subscription has been cancelled. You will no longer receive monthly credits. Please use the help button on the bottom right if you have any questions."

- [ ] make sure to stop any scheduled depositing of credits see #4486

**Comment by ivanromakh** [comment]
![image](https://user-images.githubusercontent.com/18567511/166212938-0e35dbff-01ff-409f-ba68-19c460e118a3.png)
