### ISSUE TITLE
'Create competition popup' should have end time

### ISSUE THREAD

**Issue by scholar6admin** [Scholar-6/brillder#4493]
As an institution user I need to create competitions that are 24hrs long starting at 12pm. So add a start and end hour on the popup

- [x] When popup confirmed then add the competition id to the url immediately

Dont worry about the server having a different time. We will figure this out when we actually set the competitions.

![image](https://user-images.githubusercontent.com/58778078/162724763-032f1202-5dd4-4701-81ac-8102e2688732.png)

- [x] time should be separate from date
- [x] look into minutes - just 00, 15, 30 and 45 would be good
- [x] make time and date dropdowns as narrow as possible without overflows

**Comment by ivanromakh** [comment]
front data.
![image](https://user-images.githubusercontent.com/18567511/162932758-ec37c396-31ad-446d-8014-89644a125f41.png)
backend data after saving.
![image](https://user-images.githubusercontent.com/18567511/162932741-7d784f2a-a829-4694-8479-5654cbc3958a.png)
