### ISSUE TITLE
Library competition popup

### ISSUE THREAD

**Issue by SashaScholar6** [Scholar-6/brillder#4510]
- [x] If the user has already played in the competition then button should read 'OK' instead of 'Enter competition'

<img width="978" alt="Screenshot 2022-04-19 at 17 07 08" src="https://user-images.githubusercontent.com/59654112/164047490-5d972a99-f350-41cb-bbfb-8dafe97f14ec.png">

- [x] full stop at end of second sentence.
- [x] second sentence on second line (line break)
- [x] red circle with alert triangle above text
- [x] more padding above and below text

- [x] Instead of 'Ok' button says 'Enter Competition
- [x] when i click enter competition, I don't actually start playing brick!
- [x] 'x' in top right with hover effect to close window

**Comment by ivanromakh** [comment]
@SashaScholar6 as I see user can play competition brick only once by the logic we provided.

**Comment by ivanromakh** [comment]
https://github.com/Scholar-6/brillder/issues/4510#event-6547385689
