### ISSUE TITLE
Onboarding updates

### ISSUE THREAD

**Issue by SashaScholar6** [Scholar-6/brillder#4536]
<img width="1342" alt="Screenshot 2022-05-12 at 10 36 33" src="https://user-images.githubusercontent.com/59654112/168040694-c1b92db7-8cca-4ff9-a474-f3f85cdc15bf.png">

- [x] update learner text: “Which subjects are you interested in?”
- [x] update educator text: “Which subjects will you teach?”
- [x] update institution text: “Which subjects would you like to provide for?”
- [x] update builder text: “What kind of content will you create?”

<img width="1105" alt="Screenshot 2022-05-12 at 10 40 57" src="https://user-images.githubusercontent.com/59654112/168041635-8fe4a62e-37eb-45d8-82c7-4f1614713ab5.png">

- [x] hide bio field for users who select a Learner preference

LIBRARIES
<img width="1084" alt="Screenshot 2022-05-12 at 10 44 40" src="https://user-images.githubusercontent.com/59654112/168042368-2254fd96-5fca-4fa8-90c8-f6dc3939be9a.png">

- [x] updat text: “Get a free premium account through a participating UK library”
- [x] remove red question circle
- [x] add padding left so 'Southend' text iis not touching edge (same padding as in dropdown)
- [x] remove letter spacing in library card number and pin fields
- [x] update green button to to: “Link My Library”
- [x] plac link icon on right-hand side, make it go dark blue on hover

<img width="1009" alt="Screenshot 2022-05-12 at 10 49 10" src="https://user-images.githubusercontent.com/59654112/168043270-4df233a5-713b-4212-bfe4-54568dcf7cec.png">

- [x] remove letter spacing
- [x] Update placeholder text to “Suggest a Library”
- [x] add send icon on right of “Send” text, button should go dark blue on hover

**Comment by s-steddy** [comment]
Looks like this was all taken care of. Have found some bugs but will create a new issue. Moving to deploy for now.
