### ISSUE TITLE
Library Onboarding Screen

### ISSUE THREAD

**Issue by SashaScholar6** [Scholar-6/brillder#4538]
- [x] replace text above boxes "If you are a member of one of our partner libraries, enter your Library Region/Authority, barcode, and pin to unlock premium access for free" 
- [x] remove the library introjs (and make sure to not redirect to the account page)
- [x] Update the first field placeholder to 'Library Barcode Number'
- [x] Use same popups from profile screen (if success or error), if success then progress to next onboarding screen, otherwise stay on same screen
![image](https://user-images.githubusercontent.com/58778078/170028543-d175e10c-7c2f-4564-8003-aef85c98062f.png)

- [x] 'Unlink' button should be red (after the account has been linked)
- [x] 'Unlink' button should trigger a popup with text 'Are you sure you want to unlink your Library and pay to play bricks?'

Immediately after terms for library users

<img width="629" alt="Screenshot 2022-05-12 at 15 28 46" src="https://user-images.githubusercontent.com/59654112/168098901-424b6e18-84f2-422e-9ff8-d20f58f516b4.png">

- [x] This screen should only display if origin=library
- [x] Should work the same as in profile page. 
- [x] Link button becomes green when fields filled in.

**Comment by ivanromakh** [comment]
@SashaScholar6 what about mobile we have thank you page there logic is a little different there.

**Comment by ivanromakh** [comment]
@SashaScholar6 linking and unlinking works very slow in dev like 1 minute. maybe we need to add some loader spinner?

**Comment by ivanromakh** [comment]
@SashaScholar6 desktop only.

**Comment by ivanromakh** [comment]
I have hidden this popup.
![image](https://user-images.githubusercontent.com/18567511/170641451-14ac85df-b0e3-493c-8088-21386b616b49.png)
