### ISSUE TITLE
Ticket 688. When logged in as library user.

### ISSUE THREAD

**Issue by ivanromakh** [Scholar-6/brillder#4593]
https://scholar6.zendesk.com/agent/tickets/688

Sam says:
When logged in as library user, hover over brills and credits still not ideal.

Recommend:
i) replacing 'win cash prizes' with simply 'win prizes'.
ii) removing option to buy more credits, and revising explanation about credits to something more like in introjs: 'As a library user, you have free access to the Brillder catalogue, and so do not need to spend credits to play bricks. You can use credits to enter competitions, and can earn more by accumulating brills.'

**Comment by ivanromakh** [comment]
message updated.
![image](https://user-images.githubusercontent.com/18567511/172872783-006c9875-6ab3-49c9-809d-82abda41300f.png)

**Comment by s-steddy** [comment]
[x] For library user: hover-over brills now does not mention cash
[x] Error message has been corrected
Credit system needs a general re-think, so moving to deploy
