### ISSUE TITLE
Heart of Mercia login

### ISSUE THREAD

**Issue by scholar6admin** [Scholar-6/brillder#4608]
As a student from heart of mercia virtual college, I need to be able to access Brillder seamlessly
When I click on a Brick in Canvas
Then I should be immediately be authenticated using my Microsoft credentials. 
And I should arrive back at the Brick cover ready to play (without popups)
And at the end of the Brick I should be redirected back to Canvas (and not to the Brillder catalogue)

- [x] @ivanromakh we need to set up a Brillder [multi-tenant app in azure](https://docs.microsoft.com/en-us/azure/active-directory/develop/howto-convert-app-to-be-multi-tenant)
- [x] @ivanromakh try passport.js [openIdconnect plugin](http://www.passportjs.org/packages/passport-openidconnect/) to authenticate our own app **DONT WORRY ABOUT CONNECTING TO HEART OF MERCIA AT THE MOMENT**
- [x] Find the tenant id in the response and store that in the user record
- [x] Store in local storage that a user is from heart of mercia and do not show them options at the end of the Brick to go to the catalogue
- [x] Users validated from Heart of mercia tenants should be like 'Library users' and not have to use credits to play bricks
- [x] Sam is going to send us some example code and the tenantids for each of the colleges

**Comment by scholar6admin** [comment]
We are waiting on 
- [ ] DNS txt file from Dunstan
- [ ] SAML multitenant app on heart of mercia side
- [ ] Test users for authenticating against the heart of mercia app

**Comment by ivanromakh** [comment]
https://www.youtube.com/watch?v=P9-1zsJTEbA

**Comment by ivanromakh** [comment]
as I see azure portal don`t give us SAML option anymore. I will try other way.https://www.youtube.com/watch?v=VBovU1JucO0&t=317s

**Comment by scholar6admin** [comment]
Here is the App federation Data URI for the “Brillder” enterprise app I have created.

[See lastpass]

you should be able to retrieve the data required for SAML logins from there.

 

Basic SAML Configuration

Identifier (Entity ID) = http://app.brillder.com/login/saml

Reply URL (Assertion Consumer Service URL) = https://app.brillder.com/ @ivanromakh do we need to alter this to https://api.brillder.com?

Sign on URL = https://app.brillder.com/

 

Attributes & Claims

Givenname = user.givenname

Surname = user.surname

Emailaddress = user.mail

Name = user.userprincipalname

Unique User Identifier = user.userprincipalname

 

Set up Brillder

You'll need to configure the application to link with Azure AD.

[See lastpass]
 

 

Hopefully, this is enough info to start with the SAML login attempts

 [see lastpass]

 

We can investigate the Multi-Tenant app later.

 

Best regards

 

Dunstan

**Comment by ivanromakh** [comment]
OK I try to make it work

**Comment by ivanromakh** [comment]
![image](https://user-images.githubusercontent.com/18567511/175014434-40dbd0f8-a2dd-4b4e-84a9-911966f89ace.png)

**Comment by ivanromakh** [comment]
seemd like we can`t use default microsoft library as SAML is old we can use SAML library probably.
![image](https://user-images.githubusercontent.com/18567511/175017534-2ef220e8-fce9-4e9d-a8f9-de405e57787e.png)

**Comment by ivanromakh** [comment]
![image](https://user-images.githubusercontent.com/18567511/175025523-a86d3eb1-8654-4b2c-bd2e-efc06bd21683.png)

**Comment by ivanromakh** [comment]
need some certificate to make saml request.
![image](https://user-images.githubusercontent.com/18567511/175031051-a34cff0b-8fa8-442d-b5e5-803475ef039e.png)

**Comment by ivanromakh** [comment]
![image](https://user-images.githubusercontent.com/18567511/175491098-eb2fa3cd-4755-410c-83a4-739d4ef59a8a.png)

**Comment by mjridgway** [comment]
Domains for the three colleges:
kedst.ac.uk
hereford.ac.uk
wsfc.ac.uk

**Comment by sampayne** [comment]
This is in the `Startup.cs` file that runs when the app first launches:

```
services.AddAuthentication(OpenIdConnectDefaults.AuthenticationScheme).AddMicrosoftIdentityWebApp(options =>
 {
     options.Events.OnRemoteFailure = context =>
     {
         context.Response.Redirect("/");
         context.HandleResponse();
         return Task.CompletedTask;
     };

     options.ClientId = "<the client ID of your multi-tenant app>";
     options.TenantId = "common"; //Standard value for multi-tenant app
     options.Instance = "https://login.microsoftonline.com"; //Standard value for multi-tenant app
     options.Authority = "https://login.microsoftonline.com/common"; //Standard value for multi-tenant app
     options.RemoteAuthenticationTimeout = TimeSpan.FromMinutes(60);
     options.ResponseType = OpenIdConnectResponseType.IdToken;
     options.SignedOutRedirectUri = "<URL to send users to when they log out>";
     options.CorrelationCookie.SecurePolicy = CookieSecurePolicy.Always;
     options.CorrelationCookie.SameSite = Microsoft.AspNetCore.Http.SameSiteMode.None;
     options.TokenValidationParameters = new TokenValidationParameters
     {
         ValidateIssuer = true //As far as I know, if this is set to false, you can't rely on the tenant ID the user says they are from
     };

     options.MaxAge = TimeSpan.FromDays(1);
 }, cookieOptions =>
 {
     cookieOptions.Cookie.MaxAge = TimeSpan.FromDays(7);
     cookieOptions.ExpireTimeSpan = TimeSpan.FromDays(7);
     cookieOptions.SlidingExpiration = false;
 }, OpenIdConnectDefaults.AuthenticationScheme, CookieAuthenticationDefaults.AuthenticationScheme);
```

**Note: the various timeouts, cookie expiration times, and associated settings are for our environment. You should remove them to fallback on defaults, or set to appropriate values for Brillder**

In some middleware that runs for every request:

```
var emailAddress = filterContext.HttpContext.User.Identity.Name;

var tenantID = filterContext.HttpContext.User.Claims.ToList().Find(x => x.Type == "http://schemas.microsoft.com/identity/claims/tenantid");

if (tenantID == null || tenantID.Value == "" || tenantID.Value != institutionSettings.institution.microsoftTenantID.value)
{
    //You don't recognise the tenancy the user is from, redirect them somewhere
    return;
}

// You have the email address of the user above, now you should check they are a valid user already in your database and redirect/adjust UI as necessary 
```

This only checks against a single tenant ID, because for us this is a known value that has already been determined based on the URL the user used to hit the web app. The `if` statement could easily be adjusted to check the tenant ID against all valid values for all schools/colleges using Brillder with Microsoft authentication

**Comment by sampayne** [comment]
Three of our tenant IDs:
```
wsfcacuk.onmicrosoft.com
HerefordSixthFormColl549.onmicrosoft.com
heartofmercia.onmicrosoft.com
```

Also in addition to Mark's comment, some users might have an `@heartofmercia.org.uk` email address

**Comment by ivanromakh** [comment]
@sampayne  @lindsaymacvean I managed to login user. user profile has the data below.
![image](https://user-images.githubusercontent.com/18567511/176635145-b754230c-f365-4a7e-b535-b1c20ed4680e.png)

**Comment by ivanromakh** [comment]
backendBranch: miscrosoft-openId
fontendBranch: microsoft

**Comment by ivanromakh** [comment]
seems like there could be tenent id
![image](https://user-images.githubusercontent.com/18567511/176674311-94adcc49-f54a-44e9-a8bd-c2bd682e9cee.png)

**Comment by ivanromakh** [comment]
![image](https://user-images.githubusercontent.com/18567511/176678165-ff193d6f-a2b4-4728-9aee-f31ce1314545.png)

**Comment by ivanromakh** [comment]
Hi Sam.Our development front.https://dev-app.brillder.com/

**Comment by ivanromakh** [comment]
It seems like I need to add redirectUrl to user. we need to store actually only brickId user will be redirected to after successfull login with microsoft.

**Comment by ivanromakh** [comment]
They will have only exit button in the end.
![image](https://user-images.githubusercontent.com/18567511/178234826-55218718-fc4c-4ef5-b475-9f77d23605a4.png)

**Comment by ivanromakh** [comment]
need redirect url for heart of mercia users.

**Comment by ivanromakh** [comment]
Users by those domains no longer need to spend credits to play bricks.

**Comment by ivanromakh** [comment]
this task seems completed.
