### ISSUE TITLE
Institution role

### ISSUE THREAD

**Issue by scholar6admin** [Scholar-6/brillder#4609]
Phase 2 - Data Migration Synchronisation
Acceptance Criteria: Brillder should be able to differentiate between students and teachers and stay up to date with the teaching groups.
Target delivery: 1st August 2022

## Testing steps
1. Create institution user
2. Using postman As admin give that institution user domain privileges (in this case heart of mercia)
4. Using postman to reauthenticate as the institution user
5. Using postman try adding the heart of mercia test learner account details
6. Try authenticating with microsoft using the test learner credentials
7. Update personal details (try updating first name last name in particular) 
8. Using postman try reading the learner account details (check if can get any other user details)
9. Using postman try deleting the test learner account
10. Check what happens if learner tries to login again (does it create new account automatically)
11. Try adding the learner account again (can they access their old scores?)
12. Test if can still log in as a general microsoft user

## Technical requirements
Heart of Mercia MIS needs to be able to CRUD data for all their students/teachers/teaching groups.

- [x] @ivanromakh create an institution user role who can CRUD user accounts with emails in explicit domains (add a table for these?) (i.e. kedst.ac.uk, hereford.ac.uk, wsfc.ac.uk, heartofmercia.org.uk) 
- [x] Endpoint to bulk create users, request body should be json
- [x] Endpoint to read all users associated with institution (so filter by the associated domains)
- [x] Lets add a new user role '7' that is 'learner associated with an institution', this gets added to the profile either by Heart of Mercia when adding students, or when they authenticate with a tenantID from a known institution.

All student/teacher data will be transferred using a Brillder institution user to interact with the Brillder API. There will be an initial load of students, classes and teachers. Then a scheduled hourly job to read all users associated with the trust, detect differences using code in the HoM MIS and then push any differences in records back to Brillder.

**Comment by ivanromakh** [comment]
@scholar6admin I probable will need to add new enum to user. InstitutionType. based on institutionType they will be able to get users by tenantIds probably.

**Comment by ivanromakh** [comment]
Institution is not role but user preference.

**Comment by ivanromakh** [comment]
@scholar6admin I don`t have access to any database so I added it to env variable.

**Comment by ivanromakh** [comment]
@scholar6admin I need to know what is teaching groups?
