### ISSUE TITLE
Move phone up - should be fixed to the centre heightwise like the tab window is

### ISSUE THREAD

**Issue by SashaScholar6** [Scholar-6/brillder#461]
It is decentred on laptop, moves lower the larger the display is

<img width="903" alt="Screenshot 2020-05-25 at 20 11 30" src="https://user-images.githubusercontent.com/59654112/82835327-f71e7080-9ec3-11ea-912e-ed72b8bbe0b7.png">

**Comment by ivanromakh** [comment]
@SashaScholar6  Issue too old there is last update text now. It can`t be in the center anymore

**Comment by SashaScholar6** [comment]
The text can be moved up a little to accommodate the phone
