### ISSUE TITLE
Play free for the summer

### ISSUE THREAD

**Issue by GhadaShebl** [Scholar-6/brillder#4617]
- [x] First, we'll do some design changes to the Competitions page:
       https://www.figma.com/file/LMraQn88VxZ9cHt1CAiZXN/Brillder?node-id=20%3A707

- [x] Users who choose to register from the competitions page are considered learners and therefore they skip the page where they choose their account type

- [x] Users who choose to register from the competitions page will see the agreement section in the page where they enter their first and last name
https://www.figma.com/file/LMraQn88VxZ9cHt1CAiZXN/Brillder?node-id=773%3A5762

- [x] After selecting subjects, redirect back to the competitions page

**Comment by ivanromakh** [comment]
this makes hole registration process more complicated. hope it will work well.

**Comment by ivanromakh** [comment]
@GhadaShebl after checking code I have no idea how to do it. all process is based on user preference. it is impossible to skip that page.

**Comment by ivanromakh** [comment]
when user have his user preference set that user no longer need onboarding pages.

**Comment by ivanromakh** [comment]
![image](https://user-images.githubusercontent.com/18567511/176175684-5d757b5c-a169-4eb5-bc1e-21eef882bb2c.png)
