### ISSUE TITLE
BUG: Video outline in proposal extends video (see notes)

### ISSUE THREAD

**Issue by SashaScholar6** [Scholar-6/brillder#462]
<img width="988" alt="Screenshot 2020-04-30 at 16 45 31" src="https://user-images.githubusercontent.com/59654112/80724554-47432680-8b02-11ea-914b-a49a83095d23.png">

Toolbar to be momentarily disabled, clunky appearance.  

- [ ] If no text present, insert video below placeholder

**Comment by ivanromakh** [comment]
@SashaScholar6  So what I should do? You can`t use toolbar when you try to write a link
