### ISSUE TITLE
Hint hover should appear as an extension of the question mark (not above or below so that two are visible).  See notes

### ISSUE THREAD

**Issue by SashaScholar6** [Scholar-6/brillder#517]
<img width="518" alt="Screenshot 2020-05-06 at 20 20 11" src="https://user-images.githubusercontent.com/59654112/81273191-d2ff0a80-904e-11ea-8525-0a68a9738428.png">

**Comment by ivanromakh** [comment]
@SashaScholar6  It can`t be done in the scrolling work area.

**Comment by ivanromakh** [comment]
@SashaScholar6  It will the same as popups in the ck-editor toolbar they will be hidden. once they overflow the workarea

**Comment by SashaScholar6** [comment]
I see. Ok as is for now then.
