### ISSUE TITLE
Auto save brick on every event

### ISSUE THREAD

**Issue by scholar6admin** [Scholar-6/brillder#521]
When a builder makes a change
Then save and update latest save time

Use this during request
![image](https://user-images.githubusercontent.com/58778078/81307116-305b8180-9078-11ea-93d8-94d1ff10ea06.png)

Then return to the standard message (last saved etc)

**Comment by ivanromakh** [comment]
@SashaScholar6  I need design for this. Where I should place saving label?

**Comment by ivanromakh** [comment]
@scholar6admin  Could you specify which events. Like every character user type in ckeditor or something bigger? Like switching question or selection question types.
