### ISSUE TITLE
BUG: When I copy and paste text from elsewhere to Prep panel, this overrides the colour in the phone preview

### ISSUE THREAD

**Issue by SashaScholar6** [Scholar-6/brillder#530]
<img width="1676" alt="Screenshot 2020-05-08 at 17 57 59" src="https://user-images.githubusercontent.com/59654112/81424340-0ed0c780-9156-11ea-90e5-ae7ad53ba08a.png">

- [x] Should be the opposite - any text copied in Proposal becomes white

- [x] any black text copied elsewhere in build become dark blue

**Comment by ivanromakh** [comment]
@SashaScholar6  its not a bug its how this editor works

**Comment by ivanromakh** [comment]
@SashaScholar6  checked documentation didn`t find posibility to make it via configuration.

**Comment by SashaScholar6** [comment]
Hmm. No way to turn black to white? So for this panel only the colour in
the entry panel, ie. editor, must always match the colour in the preview? I
know it does normally, but there must be a way around this :/
