### ISSUE TITLE
Make Bold thicker in CK Editor (perhaps B goes to Brandon Black); alternatively, default text could be Brandon Light

### ISSUE THREAD

**Issue by SashaScholar6** [Scholar-6/brillder#531]
There is currently not much difference visually between bold and non-bold

<img width="282" alt="Screenshot 2020-05-08 at 20 43 34" src="https://user-images.githubusercontent.com/59654112/81438228-ae995000-916c-11ea-84b1-602629519edf.png">

**Comment by ivanromakh** [comment]
@SashaScholar6  This is svg images. can`t change them
