### ISSUE TITLE
Add Storybook to the front end https://storybook.js.org/

### ISSUE THREAD

**Issue by scholar6admin** [Scholar-6/brillder#54]
Give this a go

https://storybook.js.org/

Can we run this live at a sub domain storybook.scholar6.org

**Comment by ivanromakh** [comment]
@scholar6admin Storybook сan`t be part of this project. we need to create new repo for it.

**Comment by ivanromakh** [comment]
Its possible add storybook to existing project

**Comment by ivanromakh** [comment]
Added in branch https://github.com/Scholar-6/brillder/tree/storybook
With some button component as example.

**Comment by ivanromakh** [comment]
to run story book need to run

**Comment by ivanromakh** [comment]
![image](https://user-images.githubusercontent.com/18567511/74332733-16731100-4d9f-11ea-96ed-2ec8c0c628ca.png)

**Comment by ivanromakh** [comment]
@scholar6admin We can deploy storybook to github pages

**Comment by scholar6admin** [comment]
Closing because we can work on storybook if/when it becomes important to move towards end goal of making some money.
