### ISSUE TITLE
Swap alignment icon with 'A' and make 'Justify' default for Synthesis Text

### ISSUE THREAD

**Issue by SashaScholar6** [Scholar-6/brillder#561]
- [x] move icon over

- [x] 'Justify' default

**Comment by ivanromakh** [comment]
@SashaScholar6  I looked for justify but didn`t find such  solution for ckeditor5. There is rule for right and left language but nothing like this.

**Comment by ivanromakh** [comment]
https://ckeditor.com/docs/ckeditor5/latest/features/ui-language.html#setting-the-language-of-the-content

**Comment by ivanromakh** [comment]
It depends on language.
