### ISSUE TITLE
Add Beta Version to bottom right of screen

### ISSUE THREAD

**Issue by SashaScholar6** [Scholar-6/brillder#574]
- [ ] Text should be small

**Comment by ivanromakh** [comment]
@aromakh @lindsaymacvean  we need to setup need env variable for it. 
REACT_APP_VERSION - which will get release version from npm.
![image](https://user-images.githubusercontent.com/18567511/82907282-13c3b280-9f6f-11ea-808c-a4f4079d61ff.png)

**Comment by ivanromakh** [comment]
Development branch has 0.1.0 version
![image](https://user-images.githubusercontent.com/18567511/82907403-3e157000-9f6f-11ea-8942-dfb58d20a744.png)
