### ISSUE TITLE
Cache Play Preview Locally: route directly back between Question Panel in Build and Question in Play

### ISSUE THREAD

**Issue by SashaScholar6** [Scholar-6/brillder#595]
- [x] doesn't appear to work backwards from preview play to build.  Q1 and Q2 in preview have taken me to Q3 in build

- [x] how do I now get to the beginning of the play preview?

**Comment by ivanromakh** [comment]
@SashaScholar6 
How move to intruduction page?
1. From first page.
2. First time clicking play button or review button in synthesis
3.  From synthesis tab
