### ISSUE TITLE
PLAY: If no answer on question, score as 0 and show hint during review

### ISSUE THREAD

**Issue by SashaScholar6** [Scholar-6/brillder#599]
- [x] mark as 0

- [x] show hint in review

- [x] Short Answer
- [x] Chose One
- [x] Choose Several
- [x] Sort
- [x] Missing word
- [x] Word highlighting
- [x] Line highlighting

**Comment by ivanromakh** [comment]
- [ ]  Short Answer
- [] Chose One
- [] Choose Several
- [] Sort
- [] Missing word
