### ISSUE TITLE
Numbers next to subjects on View All and Play

### ISSUE THREAD

**Issue by SashaScholar6** [Scholar-6/brillder#622]
<img width="660" alt="Screenshot 2020-05-22 at 16 39 18" src="https://user-images.githubusercontent.com/59654112/82678961-cf70a380-9c4a-11ea-9147-61aca1283cd5.png">

- [ ] Align right and Brandon Light

**Comment by aromakh** [comment]
Added new field for published bricks count
http://swagger.scholar6.org/docs/#!/subject/subjectsGET
