### ISSUE TITLE
Move Drama between English and French: New subjects should be inserted alphabetically

### ISSUE THREAD

**Issue by SashaScholar6** [Scholar-6/brillder#624]
<img width="333" alt="Screenshot 2020-05-15 at 16 28 30" src="https://user-images.githubusercontent.com/59654112/82061648-477a1f00-96c9-11ea-9d27-da27c0d367af.png">

**Comment by ivanromakh** [comment]
dublicate https://github.com/Scholar-6/brillder/issues/767
