### ISSUE TITLE
Proposal phase: not every field porting to booklet consistently (eg. Titles in PP1, Brief disappeared for a betatesters, builder name does not always show)

### ISSUE THREAD

**Issue by SashaScholar6** [Scholar-6/brillder#634]
What I enter into entry fields is not saved consistently and does not appear in full in the animated booklet.  My name also does not consistently appear on the cover of said booklet.

**Comment by ivanromakh** [comment]
@scholar6admin  This can be related to refreshing page. I think we need to use local storage for proposal pages because this data saving only on the Brick Length page and Proposal page.
If user refresh the page data will be cleared.
