### ISSUE TITLE
ALL: add zendesk widget

### ISSUE THREAD

**Issue by scholar6admin** [Scholar-6/brillder#635]
On all pages have a bug report icon that allows user to report a bug

Automatically fill the email, url and screensize
https://developer.zendesk.com/embeddables/docs/widget/introduction

Auto fill any required fields in the widget so there is a minimum of entry for the user. 

If we can make it as simple as 
What happened?
What did you expect to happen?

**Comment by ivanromakh** [comment]
https://www.npmjs.com/package/@inlightmedia/react-zendesk-chat
