### ISSUE TITLE
Text Editor: Change 'Document colors' to 'Document colours' and Brandon Reg

### ISSUE THREAD

**Issue by SashaScholar6** [Scholar-6/brillder#650]
<img width="166" alt="Screenshot 2020-05-19 at 16 07 37" src="https://user-images.githubusercontent.com/59654112/82336556-0a749c00-99eb-11ea-836f-dc6ea613e91c.png">

**Comment by ivanromakh** [comment]
Its imposible. This text generating only after color is picked.

**Comment by ivanromakh** [comment]
At least it will take hour or few to figure out when and how. and catch some events not sure if it is worth it
