### ISSUE TITLE
Ticket #8 Build/Play: Check if youtube video is embeddable

### ISSUE THREAD

**Issue by scholar6admin** [Scholar-6/brillder#653]
https://stackoverflow.com/questions/37937597/how-can-i-check-if-a-youtube-video-allows-embedded-play

On both build and play if a youtube link is embeddable then show a preview of video else (i.e. error 101 or no response from server) display only a link to the Youtube video.

This video cannot be embedded so please try using that.
https://www.youtube.com/watch?v=baRbKxNGAoM

Cpmponent installed
- https://github.com/tjallingt/react-youtube

**Comment by ivanromakh** [comment]
@SashaScholar6  About link above I checked few times but it has some special restriction which is not showed. Now it checking if youtube link is embedable or not. But about restriction we will need to discuss it later

**Comment by scholar6admin** [comment]
We discussed using a plugin to complete this task instead of using the Youtube api.

**Comment by ivanromakh** [comment]
> We discussed using a plugin to complete this task instead of using the Youtube api.
@scholar6admin Yep I installed react-youtube component. It has 700 stars on github. and MIT licence
https://github.com/tjallingt/react-youtube

**Comment by ivanromakh** [comment]
@scholar6admin when error catched I replace youtube component with a link.

**Comment by ivanromakh** [comment]
task is done
