### ISSUE TITLE
Sign up wall Frontend

### ISSUE THREAD

**Issue by scholar6admin** [Scholar-6/brillder#654]
As an non-authenticated user
When I go to a play/brick url 
Then I should be able to play the brick up to and including the synthesis
And I should be able to see and search (only) the public bricks on the 'view all' page 

When I click to go to the review then I should see a popup...

We also need a design for the left hand side column when the user is not logged in. (explaining Brillder)
<img width="797" alt="Screenshot 2020-10-12 at 13 20 26" src="https://user-images.githubusercontent.com/59654112/95740960-b74b0080-0c8d-11eb-9253-f4ed3d060d0e.png">

<img width="1237" alt="Screenshot 2020-10-19 at 13 52 39" src="https://user-images.githubusercontent.com/59654112/96447585-68174980-1212-11eb-9b13-866e814c0ddd.png">

- [x] still stuck on loading

**Comment by ivanromakh** [comment]
@william-gooch can`t get brick for this page. This api call should not be protected by auth for this page.
![image](https://user-images.githubusercontent.com/18567511/95743641-bec4d680-0c9a-11eb-9a09-06c9979e346b.png)

**Comment by ivanromakh** [comment]
@scholar6admin currently view all page displays all bricks personal and core but anonimous user can access only isCore bricks
