### ISSUE TITLE
Table fixes

### ISSUE THREAD

**Issue by SashaScholar6** [Scholar-6/brillder#660]
![Kapture 2020-05-20 at 16 53 58](https://user-images.githubusercontent.com/59654112/82462048-61e23d00-9abb-11ea-90de-a8b72f36d2ea.gif)

- [x] Table seems only to appear when clicked a second time

- [x] Preview not working on text component

- [x] Hint table borders should be dark blue #01C58

- [x] Table popup from toolbar often hidden because too big - can we limit to 8x8?

**Comment by ivanromakh** [comment]
seems like we are losing focus of html element while clicking it or something. will be hard to fix.

**Comment by ivanromakh** [comment]
It is only happening when there is placeholder.

**Comment by ivanromakh** [comment]
will try to catch events but not sure if I will be able to fix it. Its just how this plugin works.

**Comment by ivanromakh** [comment]
Moved table in text becouse popup getting cut.
