### ISSUE TITLE
Please remove 6 dots in drag and drop and change number icons to plain text (Century Gothic if possible)

### ISSUE THREAD

**Issue by SashaScholar6** [Scholar-6/brillder#69]
<img width="656" alt="Screenshot 2020-02-14 at 13 08 04" src="https://user-images.githubusercontent.com/59654112/74535348-88796080-4f2d-11ea-8f8c-efdce521fcdc.png">

**Comment by ivanromakh** [comment]
![image](https://user-images.githubusercontent.com/18567511/74751742-63ab2300-5276-11ea-93e5-470186dfd76a.png)

**Comment by ivanromakh** [comment]
Numbers centered
![image](https://user-images.githubusercontent.com/18567511/74752164-f0ee7780-5276-11ea-87f8-4c00c8240048.png)
