### ISSUE TITLE
Short Answer Preview BUG: text gets cut off at the bottom

### ISSUE THREAD

**Issue by SashaScholar6** [Scholar-6/brillder#731]
<img width="880" alt="Screenshot 2020-05-28 at 15 33 24" src="https://user-images.githubusercontent.com/59654112/83147993-ae033200-a0f8-11ea-9a8a-4fe330e644c5.png">

**Comment by ivanromakh** [comment]
@SashaScholar6  It is fixed now? Can`t reproduce.
![image](https://user-images.githubusercontent.com/18567511/83616503-990f1e80-a590-11ea-83ca-3008d3906ae5.png)
