### ISSUE TITLE
Choose One Preview & Play: make font bigger, Brandon and move to the middle of the box (centre height)

### ISSUE THREAD

**Issue by SashaScholar6** [Scholar-6/brillder#732]
<img width="1039" alt="Screenshot 2020-05-28 at 15 36 23" src="https://user-images.githubusercontent.com/59654112/83148406-3681d280-a0f9-11ea-958d-a171fcd6e714.png">

- [x] Brandon

- [x] Font Height

- [x] Font Size (same size as in Short Answer)

**Comment by ivanromakh** [comment]
![image](https://user-images.githubusercontent.com/18567511/83510205-4b81ab80-a4d5-11ea-8e09-68ed7378a674.png)

**Comment by ivanromakh** [comment]
@SashaScholar6  Currently there is problem in ckeditor. Every enter key there mean new html element which making new lines
