### ISSUE TITLE
Clicking student leads to this (please fix, 'welcome Joe', no demo bricks, top left no longer leads to anything).  Seems to be the same with teacher and builder.

### ISSUE THREAD

**Issue by SashaScholar6** [Scholar-6/brillder#76]
<img width="1114" alt="Screenshot 2020-02-17 at 13 47 29" src="https://user-images.githubusercontent.com/59654112/74659351-0fc40f80-518c-11ea-98fe-046ac0a8f827.png">

**Comment by ivanromakh** [comment]
Hi @SashaScholar6 which brower did you use?

**Comment by ivanromakh** [comment]
@SashaScholar6 Need more information. What is top left?
