### ISSUE TITLE
Boxes very big in preview (production site, not sure if still issue on dev)

### ISSUE THREAD

**Issue by SashaScholar6** [Scholar-6/brillder#790]
<img width="1438" alt="Screenshot 2020-06-03 at 13 32 29" src="https://user-images.githubusercontent.com/59654112/83632023-ca8ee680-a59e-11ea-87bd-1d722ed98db4.png">

**Comment by ivanromakh** [comment]
@SashaScholar6  it was becouse of enter button
Now text  has multiple lines
![image](https://user-images.githubusercontent.com/18567511/83762350-1feef480-a680-11ea-84af-f5f8f5ea577a.png)
Can type whatever builder whant
