### ISSUE TITLE
Make Zendesk widget red instead of blue

### ISSUE THREAD

**Issue by SashaScholar6** [Scholar-6/brillder#835]

**Comment by ivanromakh** [comment]
@SashaScholar6  This can be set from zendesk account
![image](https://user-images.githubusercontent.com/18567511/84126752-fe5a8800-aa46-11ea-9d80-43da43d18fe1.png)
![image](https://user-images.githubusercontent.com/18567511/84126778-061a2c80-aa47-11ea-8db6-e41665b9dd6f.png)
![image](https://user-images.githubusercontent.com/18567511/84126794-0c100d80-aa47-11ea-9fd1-b27c769f32ca.png)
