### ISSUE TITLE
Ticket #24: Pair Match not working well on Safari (play preview dragging unresponsive)

### ISSUE THREAD

**Issue by SashaScholar6** [Scholar-6/brillder#848]
- [ ] cursor highlights rather than drags most of the time

**Comment by ivanromakh** [comment]
@SashaScholar6 dragging works for me but have color issue it is has white background.

**Comment by ivanromakh** [comment]
@AminHussaini we need to change color. in safari light-grey is white.
![image](https://user-images.githubusercontent.com/18567511/95191754-de12be00-07d9-11eb-8b3e-cbce17c7c755.png)
