### ISSUE TITLE
Sound: Record/Play/Delete

### ISSUE THREAD

**Issue by scholar6admin** [Scholar-6/brillder#86]
As a builder
I need to be able to insert an audio file
In order to enrich my questions, test comprehension and pronunciation

I also need to be able to record my own audio 
And input / remove directly
![Screenshot 2020-03-03 at 15 02 00](https://user-images.githubusercontent.com/59654112/75788445-28255400-5d60-11ea-8bca-57dc6008286e.png)

**Comment by ivanromakh** [comment]
@lindsaymacvean  For chrome we need https to record audio.

**Comment by ivanromakh** [comment]
The same for firefox also need https to record sounds
