### ISSUE TITLE
When I click arrow to sort user 'roles', I get the following error message

### ISSUE THREAD

**Issue by SashaScholar6** [Scholar-6/brillder#875]
Order from top to bottom should be
S+combinations
T+combinations
B+combinations
E+combinations
A+combinations

**Comment by ivanromakh** [comment]
![image](https://user-images.githubusercontent.com/18567511/102870969-766a2780-4446-11eb-83df-2a7e6da6a20d.png)
![image](https://user-images.githubusercontent.com/18567511/102871010-884bca80-4446-11eb-8246-d3129e378f38.png)
sorting not working in backend side maybe name changed.
