### ISSUE TITLE
Lock + icon on bricks not my own

### ISSUE THREAD

**Issue by scholar6admin** [Scholar-6/brillder#923]
As a builder
When I click on back to work
And I click on one of my own bricks
Then I can not add question components to any of the panels

I expect to not be able to click the + icon to add another panel unless I own that brick or I am editor for that brick.

**Comment by ivanromakh** [comment]
@aromakh api call PUT: https://dev-api.scholar6.org/brick need to return author.
![image](https://user-images.githubusercontent.com/18567511/85273561-6cab3b80-b486-11ea-86c7-e1812688d145.png)
